// Generated by scripts/import-library.py from the read-only archive.
export const importedSongs=[
  {
    "id": "hhc-1001",
    "title": "Come, Thou Fount of Every Blessing",
    "collection": "Hymns for Home and Church",
    "page": "1001",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1001.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1002",
    "title": "When the Savior Comes Again",
    "collection": "Hymns for Home and Church",
    "page": "1002",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1002.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1003",
    "title": "It Is Well with My Soul",
    "collection": "Hymns for Home and Church",
    "page": "1003",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1003.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1004",
    "title": "I Will Walk with Jesus",
    "collection": "Hymns for Home and Church",
    "page": "1004",
    "tonic": "B♭",
    "mode": "major",
    "fifths": -2,
    "asset": "./assets/scores/hhc-1004.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1005",
    "title": "His Eye Is on the Sparrow",
    "collection": "Hymns for Home and Church",
    "page": "1005",
    "tonic": "B♭",
    "mode": "major",
    "fifths": -2,
    "asset": "./assets/scores/hhc-1005.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1006",
    "title": "Think a Sacred Song",
    "collection": "Hymns for Home and Church",
    "page": "1006",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1006.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1007",
    "title": "As Bread Is Broken",
    "collection": "Hymns for Home and Church",
    "page": "1007",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1007.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1008",
    "title": "Bread of Life, Living Water",
    "collection": "Hymns for Home and Church",
    "page": "1008",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1008.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1009",
    "title": "Gethsemane",
    "collection": "Hymns for Home and Church",
    "page": "1009",
    "tonic": "D",
    "mode": "minor",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1009.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": [],
    "modeOverride": "minor",
    "evidence": "Opening/repeated D-minor harmony and D bass establish D minor; final D-major chord is a Picardy ending."
  },
  {
    "id": "hhc-1010",
    "title": "Amazing Grace",
    "collection": "Hymns for Home and Church",
    "page": "1010",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1010.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1011",
    "title": "Holding Hands Around the World",
    "collection": "Hymns for Home and Church",
    "page": "1011",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1011.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1012",
    "title": "Anytime, Anywhere",
    "collection": "Hymns for Home and Church",
    "page": "1012",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1012.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1013",
    "title": "God’s Gracious Love",
    "collection": "Hymns for Home and Church",
    "page": "1013",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1013.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1014",
    "title": "My Shepherd Will Supply My Need",
    "collection": "Hymns for Home and Church",
    "page": "1014",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1014.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1015",
    "title": "Oh, the Deep, Deep Love of Jesus",
    "collection": "Hymns for Home and Church",
    "page": "1015",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1015.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1016",
    "title": "Behold the Wounds in Jesus’ Hands",
    "collection": "Hymns for Home and Church",
    "page": "1016",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1016.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1018",
    "title": "Come, Lord Jesus",
    "collection": "Hymns for Home and Church",
    "page": "1018",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1018.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1019",
    "title": "To Love like Thee",
    "collection": "Hymns for Home and Church",
    "page": "1019",
    "tonic": "B♭",
    "mode": "major",
    "fifths": -2,
    "asset": "./assets/scores/hhc-1019.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1020",
    "title": "Softly and Tenderly Jesus Is Calling",
    "collection": "Hymns for Home and Church",
    "page": "1020",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/hhc-1020.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1021",
    "title": "I Know That My Savior Loves Me",
    "collection": "Hymns for Home and Church",
    "page": "1021",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1021.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1022",
    "title": "Faith in Every Footstep",
    "collection": "Hymns for Home and Church",
    "page": "1022",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/hhc-1022.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1023",
    "title": "Standing on the Promises",
    "collection": "Hymns for Home and Church",
    "page": "1023",
    "tonic": "B♭",
    "mode": "major",
    "fifths": -2,
    "asset": "./assets/scores/hhc-1023.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1024",
    "title": "I Have Faith in the Lord Jesus Christ",
    "collection": "Hymns for Home and Church",
    "page": "1024",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1024.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1025",
    "title": "Take My Heart and Let It Be Consecrated",
    "collection": "Hymns for Home and Church",
    "page": "1025",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1025.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1026",
    "title": "Holy Places",
    "collection": "Hymns for Home and Church",
    "page": "1026",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1026.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1027",
    "title": "Welcome Home",
    "collection": "Hymns for Home and Church",
    "page": "1027",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1027.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1028",
    "title": "This Little Light of Mine",
    "collection": "Hymns for Home and Church",
    "page": "1028",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/hhc-1028.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1029",
    "title": "I Can’t Count Them All",
    "collection": "Hymns for Home and Church",
    "page": "1029",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1029.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1030",
    "title": "Close as a Quiet Prayer",
    "collection": "Hymns for Home and Church",
    "page": "1030",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1030.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1031",
    "title": "Come, Hear the Word the Lord Has Spoken",
    "collection": "Hymns for Home and Church",
    "page": "1031",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1031.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1032",
    "title": "Look unto Christ",
    "collection": "Hymns for Home and Church",
    "page": "1032",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1032.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1033",
    "title": "Oh, How Great Is Our Joy",
    "collection": "Hymns for Home and Church",
    "page": "1033",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/hhc-1033.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1034",
    "title": "I’m a Pioneer Too",
    "collection": "Hymns for Home and Church",
    "page": "1034",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1034.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1035",
    "title": "As I Keep the Sabbath Day",
    "collection": "Hymns for Home and Church",
    "page": "1035",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1035.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1036",
    "title": "Read the Book of Mormon and Pray",
    "collection": "Hymns for Home and Church",
    "page": "1036",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1036.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1037",
    "title": "I’m Gonna Live So God Can Use Me",
    "collection": "Hymns for Home and Church",
    "page": "1037",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1037.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1038",
    "title": "The Lord’s My Shepherd",
    "collection": "Hymns for Home and Church",
    "page": "1038",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1038.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1039",
    "title": "Because",
    "collection": "Hymns for Home and Church",
    "page": "1039",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/hhc-1039.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1040",
    "title": "His Voice as the Sound",
    "collection": "Hymns for Home and Church",
    "page": "1040",
    "tonic": "E",
    "mode": "minor",
    "fifths": 1,
    "asset": "./assets/scores/hhc-1040.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1041",
    "title": "O Lord, Who Gave Thy Life for Me",
    "collection": "Hymns for Home and Church",
    "page": "1041",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1041.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1042",
    "title": "Thou Gracious God, Whose Mercy Lends",
    "collection": "Hymns for Home and Church",
    "page": "1042",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1042.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1043",
    "title": "Help Us Remember",
    "collection": "Hymns for Home and Church",
    "page": "1043",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1043.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1044",
    "title": "How Did the Savior Minister?",
    "collection": "Hymns for Home and Church",
    "page": "1044",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1044.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1045",
    "title": "Jesus Is the Way",
    "collection": "Hymns for Home and Church",
    "page": "1045",
    "tonic": "E♭",
    "mode": "major",
    "fifths": -3,
    "asset": "./assets/scores/hhc-1045.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1046",
    "title": "Can You Count the Stars in Heaven?",
    "collection": "Hymns for Home and Church",
    "page": "1046",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1046.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1047",
    "title": "He Cares for Me",
    "collection": "Hymns for Home and Church",
    "page": "1047",
    "tonic": "E♭",
    "mode": "major",
    "fifths": -3,
    "asset": "./assets/scores/hhc-1047.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1048",
    "title": "Our Prayer to Thee",
    "collection": "Hymns for Home and Church",
    "page": "1048",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1048.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1049",
    "title": "Joseph Prayed in Faith",
    "collection": "Hymns for Home and Church",
    "page": "1049",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1049.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1050",
    "title": "Stand by Me",
    "collection": "Hymns for Home and Church",
    "page": "1050",
    "tonic": "E♭",
    "mode": "major",
    "fifths": -3,
    "asset": "./assets/scores/hhc-1050.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1051",
    "title": "This Day Is a Good Day, Lord",
    "collection": "Hymns for Home and Church",
    "page": "1051",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1051.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1052",
    "title": "Joyfully Bound",
    "collection": "Hymns for Home and Church",
    "page": "1052",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1052.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1053",
    "title": "My Covenants",
    "collection": "Hymns for Home and Church",
    "page": "1053",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1053.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1054",
    "title": "When I Am Baptized",
    "collection": "Hymns for Home and Church",
    "page": "1054",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1054.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": [
      {
        "collection": "Children’s Songbook",
        "page": "103"
      }
    ]
  },
  {
    "id": "hhc-1055",
    "title": "The Power of the Holy Ghost",
    "collection": "Hymns for Home and Church",
    "page": "1055",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1055.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1056",
    "title": "Elijah and the Still, Small Voice",
    "collection": "Hymns for Home and Church",
    "page": "1056",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1056.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1057",
    "title": "Jesus Is My Shepherd",
    "collection": "Hymns for Home and Church",
    "page": "1057",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1057.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1058",
    "title": "My Song in the Night",
    "collection": "Hymns for Home and Church",
    "page": "1058",
    "tonic": "G",
    "mode": "minor",
    "fifths": -2,
    "asset": "./assets/scores/hhc-1058.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": [],
    "modeOverride": "minor",
    "evidence": "Opening and final G-minor harmonies establish G minor."
  },
  {
    "id": "hhc-1059",
    "title": "This Is My Father’s World",
    "collection": "Hymns for Home and Church",
    "page": "1059",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1059.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1060",
    "title": "Build an Ark",
    "collection": "Hymns for Home and Church",
    "page": "1060",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1060.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1061",
    "title": "Love Will Bless Our Home",
    "collection": "Hymns for Home and Church",
    "page": "1061",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1061.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1062",
    "title": "Lord, Accept Our Humble Fast",
    "collection": "Hymns for Home and Church",
    "page": "1062",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/hhc-1062.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1063",
    "title": "Peace, Peace, Be Still",
    "collection": "Hymns for Home and Church",
    "page": "1063",
    "tonic": "D",
    "mode": "minor",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1063.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1064",
    "title": "Great Is Thy Faithfulness",
    "collection": "Hymns for Home and Church",
    "page": "1064",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1064.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1065",
    "title": "Isaiah Said",
    "collection": "Hymns for Home and Church",
    "page": "1065",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/hhc-1065.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1066",
    "title": "Fight the Good Fight",
    "collection": "Hymns for Home and Church",
    "page": "1066",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1066.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1067",
    "title": "It’s Joyful to Live the Gospel",
    "collection": "Hymns for Home and Church",
    "page": "1067",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/hhc-1067.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1068",
    "title": "To God Be the Glory",
    "collection": "Hymns for Home and Church",
    "page": "1068",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/hhc-1068.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1069",
    "title": "Speak to Us, Lord",
    "collection": "Hymns for Home and Church",
    "page": "1069",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1069.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1070",
    "title": "The Miracle",
    "collection": "Hymns for Home and Church",
    "page": "1070",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1070.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1071",
    "title": "What God Calls Us To",
    "collection": "Hymns for Home and Church",
    "page": "1071",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1071.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1072",
    "title": "When I Survey the Wondrous Cross",
    "collection": "Hymns for Home and Church",
    "page": "1072",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1072.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1201",
    "title": "Hail the Day That Sees Him Rise",
    "collection": "Hymns for Home and Church",
    "page": "1201",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1201.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1202",
    "title": "He Is Born, the Divine Christ Child",
    "collection": "Hymns for Home and Church",
    "page": "1202",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1202.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1203",
    "title": "What Child Is This?",
    "collection": "Hymns for Home and Church",
    "page": "1203",
    "tonic": "E",
    "mode": "minor",
    "fifths": 1,
    "asset": "./assets/scores/hhc-1203.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": [],
    "modeOverride": "minor",
    "evidence": "E-minor opening, repeated B7 to E-minor cadences and final E-minor harmony establish E minor."
  },
  {
    "id": "hhc-1204",
    "title": "Star Bright",
    "collection": "Hymns for Home and Church",
    "page": "1204",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1204.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1205",
    "title": "Let Easter Anthems Ring",
    "collection": "Hymns for Home and Church",
    "page": "1205",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1205.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1206",
    "title": "Were You There?",
    "collection": "Hymns for Home and Church",
    "page": "1206",
    "tonic": "E♭",
    "mode": "major",
    "fifths": -3,
    "asset": "./assets/scores/hhc-1206.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1207",
    "title": "Still, Still, Still",
    "collection": "Hymns for Home and Church",
    "page": "1207",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/hhc-1207.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1208",
    "title": "Go Tell It on the Mountain",
    "collection": "Hymns for Home and Church",
    "page": "1208",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/hhc-1208.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1209",
    "title": "Little Baby in a Manger",
    "collection": "Hymns for Home and Church",
    "page": "1209",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/hhc-1209.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "hhc-1210",
    "title": "Long Ago, Within a Garden",
    "collection": "Hymns for Home and Church",
    "page": "1210",
    "tonic": "B♭",
    "mode": "major",
    "fifths": -2,
    "asset": "./assets/scores/hhc-1210.mxl",
    "tags": [],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-12",
    "title": "A Child’s Prayer",
    "collection": "Children’s Songbook",
    "page": "12",
    "tonic": "B♭",
    "mode": "major",
    "fifths": -2,
    "asset": "./assets/scores/cs-12.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-174",
    "title": "Called to Serve",
    "collection": "Children’s Songbook",
    "page": "174",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/cs-174.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-74",
    "title": "I Feel My Savior’s Love",
    "collection": "Children’s Songbook",
    "page": "74",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-74.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-164",
    "title": "I Will Follow God’s Plan",
    "collection": "Children’s Songbook",
    "page": "164",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-164.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-34",
    "title": "He Sent His Son",
    "collection": "Children’s Songbook",
    "page": "34",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-34.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-70",
    "title": "Jesus Has Risen",
    "collection": "Children’s Songbook",
    "page": "70",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-70.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-60",
    "title": "Jesus Wants Me for a Sunbeam",
    "collection": "Children’s Songbook",
    "page": "60",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-60.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-18",
    "title": "I Need My Heavenly Father",
    "collection": "Children’s Songbook",
    "page": "18",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-18.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-77",
    "title": "The Church of Jesus Christ",
    "collection": "Children’s Songbook",
    "page": "77",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/cs-77.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [
      "I Belong to the Church of Jesus Christ"
    ],
    "collectionMemberships": []
  },
  {
    "id": "cs-168",
    "title": "I Want to Be a Missionary Now",
    "collection": "Children’s Songbook",
    "page": "168",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-168.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-169",
    "title": "I Hope They Call Me on a Mission",
    "collection": "Children’s Songbook",
    "page": "169",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-169.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-95",
    "title": "I Love to See the Temple",
    "collection": "Children’s Songbook",
    "page": "95",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-95.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-7",
    "title": "I Thank Thee, Dear Father",
    "collection": "Children’s Songbook",
    "page": "7",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/cs-7.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-78",
    "title": "I’m Trying to Be like Jesus",
    "collection": "Children’s Songbook",
    "page": "78",
    "tonic": "B♭",
    "mode": "major",
    "fifths": -2,
    "asset": "./assets/scores/cs-78.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [
      "I’m Trying to Be Like Jesus"
    ],
    "collectionMemberships": []
  },
  {
    "id": "cs-228",
    "title": "My Heavenly Father Loves Me",
    "collection": "Children’s Songbook",
    "page": "228",
    "tonic": "E♭",
    "mode": "major",
    "fifths": -3,
    "asset": "./assets/scores/cs-228.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-109",
    "title": "Search, Ponder, and Pray",
    "collection": "Children’s Songbook",
    "page": "109",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/cs-109.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-82",
    "title": "When He Comes Again",
    "collection": "Children’s Songbook",
    "page": "82",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-82.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-138",
    "title": "Where Love Is",
    "collection": "Children’s Songbook",
    "page": "138",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-138.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-232",
    "title": "Beauty Everywhere",
    "collection": "Children’s Songbook",
    "page": "232",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-232.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-16",
    "title": "Children All Over the World",
    "collection": "Children’s Songbook",
    "page": "16",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/cs-16.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-110",
    "title": "Follow the Prophet",
    "collection": "Children’s Songbook",
    "page": "110",
    "tonic": "C",
    "mode": "minor",
    "fifths": -3,
    "asset": "./assets/scores/cs-110.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": [],
    "modeOverride": "minor",
    "evidence": "C-minor opening, repeated G7 to C-minor cadences and final C-minor harmony establish C minor."
  },
  {
    "id": "cs-2",
    "title": "I Am a Child of God",
    "collection": "Children’s Songbook",
    "page": "2",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/cs-2.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-244",
    "title": "Little Purple Pansies",
    "collection": "Children’s Songbook",
    "page": "244",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/cs-244.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-276",
    "title": "Do as I’m Doing",
    "collection": "Children’s Songbook",
    "page": "276",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/cs-276.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-236",
    "title": "“Give,” Said the Little Stream",
    "collection": "Children’s Songbook",
    "page": "236",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/cs-236.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [
      "Give, Said the Little Stream"
    ],
    "collectionMemberships": []
  },
  {
    "id": "cs-275a",
    "title": "Head, Shoulders, Knees, and Toes",
    "collection": "Children’s Songbook",
    "page": "275a",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/cs-275a.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-260",
    "title": "Hello Song",
    "collection": "Children’s Songbook",
    "page": "260",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-260.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-266",
    "title": "If You’re Happy",
    "collection": "Children’s Songbook",
    "page": "266",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-266.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-249",
    "title": "Once There Was a Snowman",
    "collection": "Children’s Songbook",
    "page": "249",
    "tonic": "F",
    "mode": "major",
    "fifths": -1,
    "asset": "./assets/scores/cs-249.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-242",
    "title": "Popcorn Popping",
    "collection": "Children’s Songbook",
    "page": "242",
    "tonic": "C",
    "mode": "major",
    "fifths": 0,
    "asset": "./assets/scores/cs-242.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-220",
    "title": "The Handcart Song",
    "collection": "Children’s Songbook",
    "page": "220",
    "tonic": "B♭",
    "mode": "major",
    "fifths": -2,
    "asset": "./assets/scores/cs-220.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-281",
    "title": "The Wise Man and the Foolish Man",
    "collection": "Children’s Songbook",
    "page": "281",
    "tonic": "G",
    "mode": "major",
    "fifths": 1,
    "asset": "./assets/scores/cs-281.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [
      "Wise Man and the Foolish Man"
    ],
    "collectionMemberships": []
  },
  {
    "id": "cs-267a",
    "title": "Smiles",
    "collection": "Children’s Songbook",
    "page": "267a",
    "tonic": "D",
    "mode": "major",
    "fifths": 2,
    "asset": "./assets/scores/cs-267a.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  },
  {
    "id": "cs-61",
    "title": "Jesus Said Love Everyone",
    "collection": "Children’s Songbook",
    "page": "61",
    "tonic": "E♭",
    "mode": "major",
    "fifths": -3,
    "asset": "./assets/scores/cs-61.mxl",
    "tags": [
      "Primary"
    ],
    "aliases": [],
    "collectionMemberships": []
  }
];
