// Read-only geometry used by the URL-gated physical-device diagnostics.
export function footerDiagnostics(){
 const rect=e=>{if(!e)return null;const r=e.getBoundingClientRect();return Object.fromEntries(['top','bottom','left','right','width','height'].map(k=>[k,r[k]]));};
 const v=visualViewport,root=getComputedStyle(document.documentElement),bar=document.querySelector('.masthead'),toolbar=bar?.querySelector('.toolbar');
 const valid=!!v&&Math.abs(v.scale-1)<=.01,visibleBottom=valid?v.offsetTop+v.height:innerHeight;
 const probe=document.createElement('div');probe.style.cssText='position:fixed;visibility:hidden;pointer-events:none;padding-bottom:env(safe-area-inset-bottom)';document.body.append(probe);const safeArea=parseFloat(getComputedStyle(probe).paddingBottom)||0;probe.remove();
 const safeClearance=parseFloat(root.getPropertyValue('--playing-safe-bottom'))||0;
 const controls=[...bar.querySelectorAll('button')].filter(e=>e.getClientRects().length).map(e=>{const bounds=rect(e),hit=document.elementFromPoint((bounds.left+bounds.right)/2,(bounds.top+bounds.bottom)/2);return {id:e.id,label:e.getAttribute('aria-label'),disabled:e.disabled,bounds,insideVisibleViewport:bounds.bottom<=visibleBottom-safeClearance+.5&&bounds.top>=(valid?v.offsetTop:0)-.5,hitTestable:e===hit||e.contains(hit),hitTarget:hit?.id||hit?.tagName||null};});
 const grid=e=>e?{display:getComputedStyle(e).display,rows:getComputedStyle(e).gridTemplateRows,columns:getComputedStyle(e).gridTemplateColumns}:null;
 return {innerWidth,innerHeight,clientHeight:document.documentElement.clientHeight,visualViewport:v?{width:v.width,height:v.height,offsetTop:v.offsetTop,scale:v.scale}:null,visibleBottom,visualScaleValid:valid,safeAreaBottom:safeArea,safeClearance,footerViewportInset:root.getPropertyValue('--footer-viewport-inset'),playingBarHeight:root.getPropertyValue('--playing-bar-height'),footer:rect(bar),toolbar:rect(toolbar),controls,grid:{masthead:grid(bar),toolbar:grid(toolbar),playing:grid(bar.querySelector('.playing-controls')),utility:grid(bar.querySelector('.utility-controls'))},controlVisibility:Object.fromEntries(['songs','reset','score-size','key','score-tools','settings','show-lyrics'].map(id=>[id,controls.some(c=>c.id===id)])),allControlsVisible:controls.every(c=>c.insideVisibleViewport),footerWithinVisibleViewport:rect(bar).bottom<=visibleBottom+.5,horizontalOverflow:document.documentElement.scrollWidth>innerWidth};
}
