import {catalogOfflineSong,createOfflineControl} from './offline-control.js';
import {textItem,itemTitle,listCount} from './list-items.js';
import {createTextEditor,cleanTextHTML} from './list-text.js';
import {createListRowSwipe} from './list-row-swipe.js';
import {createPickerSources} from './list-picker-sources.js';
import {offlineListState,offlineSummary,refreshOffline,saveOfflineList,removeOfflineList} from './offline-manager.js';
import {canOpenScore} from './score-availability.js';
import {listClipboardText,copyListText} from './list-copy.js';
import {attachReorderHandle} from './list-reorder.js';
import {editIcon,favoriteIcon,orderIcon,musicItemIcon} from './icons.js';
import {songs} from './catalog.js';
import {songSearchText,normalizeSearch} from './songs.js';
import {isFileSong} from './library-query.js';
// Appearance derives from immutable List identity, never its position or name.
function listTint(id){let hash=0;for(const c of String(id))hash=(Math.imul(hash,31)+c.codePointAt(0))>>>0;return ['blue','teal','green','violet'][hash%4];}
const $=id=>document.getElementById(id);
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;};
const button=(text,label,action)=>{const e=el('button',text,'quiet');e.type='button';e.setAttribute('aria-label',label);e.onclick=action;return e;};
// Workspace expansion is session-only; picker source preferences are separate.
// Membership/order/aliases remain in the Library store.
export function createListsView({getState,save,onLibrary,onSelect,onAdded,onChanged,onPick,onSong,onDeleteText,freshLaunch=false}){
 const swipe=createListRowSwipe();
 const textEditor=createTextEditor({deleteItem:id=>onDeleteText(id),usage:id=>getState().groups.filter(g=>g.songs.includes(id)).length,commit:({list,id},item)=>{const g=group(list);if(list&&!g)return false;const key=id||'text:'+crypto.randomUUID(),store=getState().textItems,old=store[key],order=g?[...g.songs]:null;store[key]={...old,...item};if(!id&&g)g.songs.push(key);if(!save()){if(old===undefined)delete store[key];else store[key]=old;if(g)g.songs=order;return false;}if(textDraft&&!id){textDraft.checked.add(key);renderTextPicker();$('list-text-picker-status').textContent='Note saved for reuse. Choose Apply to include it in this List.';}onChanged();render();document.dispatchEvent(new Event('text-items-changed'));return true;},remove:({list,id})=>removeSong(list,id)});
 // Primary's in-context List editor pattern, adapted to staged checkbox membership.
 const textPicker=$('list-text-picker');let textDraft=null;
 function openTextPicker(list){const g=group(list);if(!g)return;remember();textDraft={list,checked:new Set(g.songs.filter(id=>textItem(g,id))),scroll:scrollY};$('list-text-picker-title').textContent='Existing Notes · '+g.name;$('list-text-picker-search').value='';$('list-text-picker-status').textContent='';renderTextPicker();textPicker.showModal();}
 function renderTextPicker(){if(!textDraft)return;const host=$('list-text-picker-items'),query=$('list-text-picker-search').value.trim().toLocaleLowerCase();host.replaceChildren();const items=Object.entries(getState().textItems).filter(([,item])=>item?.type==='text'&&(!query||item.title.toLocaleLowerCase().includes(query))).sort((a,b)=>a[1].title.localeCompare(b[1].title,undefined,{numeric:true}));for(const [id,item] of items){const label=el('label',null,'list-membership-row'),check=document.createElement('input');check.type='checkbox';check.dataset.text=id;check.checked=textDraft.checked.has(id);check.onchange=()=>{check.checked?textDraft.checked.add(id):textDraft.checked.delete(id);};label.append(check,el('span',item.title));host.append(label);}if(!items.length)host.append(el('p',query?'No Notes match.':'No Notes yet. Choose New Note to create an item.'));}
 $('list-text-picker-search').oninput=renderTextPicker;
 $('list-text-picker-new').onclick=()=>textEditor.open(null,null,null);
 $('list-text-picker-cancel').onclick=()=>textPicker.close();
 textPicker.addEventListener('close',()=>{const draft=textDraft;textDraft=null;if(draft){window.scrollTo({top:draft.scroll,behavior:'instant'});section(draft.list)?.querySelector('.list-actions-toggle')?.focus({preventScroll:true});}});
 $('list-text-picker-form').onsubmit=e=>{e.preventDefault();if(!textDraft)return;const g=group(textDraft.list);if(!g)return;const original=structuredClone(g),removed=g.songs.filter(id=>textItem(g,id)&&!textDraft.checked.has(id));if(removed.length)stageRemoval(g,removed);for(const id of textDraft.checked)if(textItem(g,id)&&!g.songs.includes(id))g.songs.push(id);if(!save()){Object.assign(g,original);if(removed.length)clearUndo();$('list-text-picker-status').textContent='Could not save memberships. Your changes are still staged. Please retry.';return;}onChanged();render();textPicker.close();};
 let reading=null,readerOrigin=null;
 function readText(g,id){reading={list:g?.id||null,id};readerOrigin=document.activeElement;$('list-text-reader-close').textContent=g?'Back to list':'Back to Notes';$('list-text-reader-title').textContent=textItem(g,id).title;$('list-text-reader-content').innerHTML=cleanTextHTML(textItem(g,id).html);$('list-text-reader').showModal();}
 $('list-text-reader-close').onclick=()=>$('list-text-reader').close();
 $('list-text-reader').addEventListener('close',()=>readerOrigin?.isConnected&&readerOrigin.focus({preventScroll:true}));
 $('list-text-reader-edit').onclick=()=>{const {list,id}=reading;$('list-text-reader').close();textEditor.open(list,id,textItem(group(list),id));};
 let undo=null,undoTimer=0;const favoriteLists=new Set();
 let picking=null,selected=new Set(),naming=null,editingEntry=null;
 const pickerSources=createPickerSources({onChange:()=>{if(picking)renderPicker();},getListIds:()=>getState().groups.map(g=>g.id)});
 let nameReturn=null,entryReturn=null,orderingLists=false;
 const sessionKey='music-transpose-lists-expanded-v1',expanded=new Set();let workspaceScroll=0;
 try{if(freshLaunch)sessionStorage.removeItem(sessionKey);const saved=JSON.parse(sessionStorage.getItem(sessionKey)||'null');for(const id of saved?.expanded||[])if(typeof id==='string'&&getState().groups.some(g=>g.id===id)&&!expanded.size)expanded.add(id);workspaceScroll=Number(saved?.scroll)||0;}catch{}
 const persist=()=>{try{sessionStorage.setItem(sessionKey,JSON.stringify({expanded:[...expanded],scroll:workspaceScroll}));}catch{}};
 const remember=()=>{if(!$('lists-view').hidden&&!picking){workspaceScroll=scrollY;persist();}};
 window.addEventListener('scroll',remember,{passive:true});window.addEventListener('pagehide',remember);
 const section=id=>$('lists-overview').querySelector(`[data-list="${CSS.escape(id)}"]`);
 const focusRow=(list,id,selector)=>section(list)?.querySelector(`[data-song="${CSS.escape(id)}"] ${selector}`)?.focus({preventScroll:true});
 function expand(id){expanded.clear();expanded.add(id);persist();}
 function toggle(id){const y=scrollY;if(expanded.has(id)){expanded.delete(id);}else{expanded.clear();expanded.add(id);}persist();render();window.scrollTo({top:y,behavior:'instant'});section(id)?.querySelector('.list-overview-entry').focus({preventScroll:true});}
 // The existing groups array is the authoritative manual List order; no IDs/data migrate.
 function moveList(id,to,before=true){const state=getState(),from=state.groups.findIndex(g=>g.id===id);if(from<0||id===to||!state.groups.some(g=>g.id===to))return;const [list]=state.groups.splice(from,1);state.groups.splice(state.groups.findIndex(g=>g.id===to)+(before?0:1),0,list);const saved=save();onChanged();render();const control=section(id)?.querySelector('.order-list');control?.focus({preventScroll:true});control?.scrollIntoView({block:'nearest'});announce(saved?list.name+': position '+(state.groups.indexOf(list)+1)+' of '+state.groups.length+'. Order saved.':'Changes last only while this page is open.');}
 function startListOrder(id){if(getState().groups.length<2)return;orderingLists=true;render();section(id)?.querySelector('.order-list').focus({preventScroll:true});announce('Ordering Lists. Drag a List header handle or use Move Up and Move Down.');}
 function startPick(id){remember();onPick(id);}
 function finishAdded(id,added=[]){expand(id);open();if(added.length){const row=section(id)?.querySelector(`[data-song="${CSS.escape(added[0])}"]`);row?.scrollIntoView({block:'nearest'});row?.querySelector('.workspace-song-entry').focus({preventScroll:true});remember();}}
 function move(id,song,to,before=true){const g=group(id);if(!g||song===to||!g.songs.includes(song)||!g.songs.includes(to))return;g.songs.splice(g.songs.indexOf(song),1);g.songs.splice(g.songs.indexOf(to)+(before?0:1),0,song);const saved=save();onChanged();render();focusRow(id,song,'.order-song');announce(saved?'Moved to position '+(g.songs.indexOf(song)+1)+' of '+g.songs.length+'. Order saved.':'Changes last only while this page is open.');}
 let songOrderMenu=null,songOrderOrigin=null;
 function closeSongOrder(focus=false){songOrderMenu?.remove();songOrderMenu=null;songOrderOrigin?.setAttribute('aria-expanded','false');if(focus&&songOrderOrigin?.isConnected)songOrderOrigin.focus({preventScroll:true});songOrderOrigin=null;}
 function openSongOrder(list,id,origin){
  if(songOrderOrigin===origin){closeSongOrder(true);return;}closeSongOrder();const g=group(list),index=g?.songs.indexOf(id);if(!g||index<0||g.songs.length<2)return;
  const menu=el('div',null,'song-order-menu');menu.setAttribute('role','menu');menu.setAttribute('aria-label',origin.getAttribute('aria-label'));songOrderMenu=menu;songOrderOrigin=origin;origin.setAttribute('aria-expanded','true');
  for(const [label,to,before] of [['Move up',g.songs[index-1],true],['Move down',g.songs[index+1],false],['Move to top',index>0?g.songs[0]:null,true],['Move to bottom',index<g.songs.length-1?g.songs.at(-1):null,false]]){if(!to)continue;const action=button(label,label,()=>{closeSongOrder();move(list,id,to,before);});action.setAttribute('role','menuitem');menu.append(action);}
  document.body.append(menu);const r=origin.getBoundingClientRect(),box=menu.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(innerWidth-box.width-8,r.right-box.width))+'px';menu.style.top=Math.max(8,Math.min(innerHeight-box.height-8,r.bottom+4))+'px';
  menu.onkeydown=e=>{const actions=[...menu.querySelectorAll('button')],i=actions.indexOf(document.activeElement);if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeSongOrder(true);}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();actions[e.key==='Home'?0:e.key==='End'?actions.length-1:(i+(e.key==='ArrowDown'?1:-1)+actions.length)%actions.length].focus();}};
  menu.addEventListener('focusout',e=>{if(e.relatedTarget&&!menu.contains(e.relatedTarget)&&e.relatedTarget!==origin)closeSongOrder();});menu.firstElementChild.focus();
 }
 document.addEventListener('pointerdown',e=>{if(songOrderMenu&&!songOrderMenu.contains(e.target)&&!songOrderOrigin?.contains(e.target))closeSongOrder();});
 window.addEventListener('resize',()=>closeSongOrder());window.addEventListener('scroll',()=>closeSongOrder(),{passive:true});
 function songRows(g,host){
  for(const id of g.songs){if(favoriteLists.has(g.id)&&!getState().favorites.includes(id))continue;const text=textItem(g,id),s=songs.find(s=>s.id===id),title=itemTitle(g,id,songs),row=el('div',null,'workspace-song-row');row.dataset.song=id;const front=el('div',null,'workspace-song-front'),remove=button('Remove','Remove from list: '+title,()=>removeSong(g.id,id));remove.classList.add('list-song-remove');row.append(remove,front);
   const entry=button('','Open '+title,()=>{remember();if(text){readText(g,id);return;}onSong(g.id,id,g.songs.filter(id=>songs.some(s=>s.id===id&&canOpenScore(s))));});entry.classList.add('workspace-song-entry');entry.title=title;entry.append(el('strong',title),el('span',text?'Note':s?[s.collection,s.songNumber??s.page].filter(Boolean).join(' · '):'Source unavailable · retained in saved order','song-meta'));entry.disabled=!s&&!text;
   const pencil=button('',(text?'Edit Note: ':'Edit song in list: ')+title,()=>text?textEditor.open(g.id,id,text):editEntry(g.id,s||{id,title:'Unavailable song'},()=>focusRow(g.id,id,'.edit-list-entry')));pencil.classList.add('list-icon','edit-list-entry');pencil.innerHTML=editIcon;pencil.title=text?'Edit Note':'Edit song in list';
   const favored=getState().favorites.includes(id),star=button('',(favored?'Remove from Favorites: ':'Add to Favorites: ')+title,()=>{const state=getState();state.favorites=favored?state.favorites.filter(s=>s!==id):[...state.favorites,id];save();onChanged();render();focusRow(g.id,id,'.favorite');});star.classList.add('list-icon','favorite');star.innerHTML=favoriteIcon;star.setAttribute('aria-pressed',String(favored));star.disabled=!s&&!text;
   entry.append(el('span',text?'Note':'Music','list-item-badge'));const type=el('span',text?'Note':null,'list-item-type');if(!text){type.innerHTML=musicItemIcon;type.setAttribute('role','img');type.setAttribute('aria-label','Music item');type.title='Music item';}const offline=!text&&catalogOfflineSong(s)?createOfflineControl(s):el('span',null,'offline-control-slot');front.append(star,entry,type,offline,pencil);host.append(row);swipe.attach(row,front);
   if(g.songs.length>1&&!favoriteLists.has(g.id)){const order=button('','Reorder '+title,()=>{});order.classList.add('list-icon','order-song','reorder-grip');order.innerHTML=orderIcon;order.title='Drag to reorder or open movement actions';order.setAttribute('aria-haspopup','menu');order.setAttribute('aria-expanded','false');front.append(order);attachReorderHandle(order,row,host,(to,before)=>move(g.id,id,to,before),{visualMove:true,onActivate:()=>openSongOrder(g.id,id,order)});}

  }
  if(!host.children.length)host.append(el('p',favoriteLists.has(g.id)?'No Favorites in this list.':'This list is empty.','workspace-empty'));
 }
 for(const id of ['list-name-dialog','list-entry-dialog']){$(id).addEventListener('click',e=>{if(e.target!==$(id))return;const r=$(id).getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$(id).close();});}
 $('list-name-dialog').addEventListener('close',()=>nameReturn?.());
 $('list-entry-dialog').addEventListener('close',()=>entryReturn?.());
 const group=id=>getState().groups.find(g=>g.id===id);
 const announce=text=>$('lists-status').textContent=text;
 const heading=()=>$('lists-heading').focus({preventScroll:true});
 // Keep completion above a mobile keyboard that shrinks only the visual viewport.
 function syncPickerViewport(){const viewport=window.visualViewport,inset=picking&&!$('lists-view').hidden&&viewport?Math.max(0,innerHeight-viewport.height-viewport.offsetTop):0;document.documentElement.style.setProperty('--list-keyboard-inset',inset+'px');}
 window.visualViewport?.addEventListener('resize',syncPickerViewport);window.visualViewport?.addEventListener('scroll',syncPickerViewport);window.addEventListener('resize',syncPickerViewport);
 function hide(){closeListMenu();swipe.close();pickerSources.close();remember();$('lists-view').hidden=true;document.body.classList.remove('list-picker-open');syncPickerViewport();}
 function show(){document.body.classList.add('library-open');$('library').hidden=true;$('lists-view').hidden=false;render();window.scrollTo({top:0,behavior:'instant'});heading();}
 function open({fresh=false}={}){if(fresh){expanded.clear();workspaceScroll=0;persist();}pickerSources.close();refreshOffline();picking=null;show();window.scrollTo({top:workspaceScroll,behavior:'instant'});}
 function openList(id,{restoreScroll=false}={}){if(!group(id)){open();return;}expand(id);open();if(!restoreScroll)section(id)?.scrollIntoView({block:'nearest'});remember();}
 function pick(id,reset=true){remember();if(!group(id)){onLibrary();return;}if(reset||picking!==id){selected.clear();$('list-picker-search').value='';pickerSources.load(id);$('list-picker-favorites').checked=false;}picking=id;show();}
 function name(id=null){naming=id;$('list-name-delete').hidden=!id;const origin=document.activeElement;nameReturn=()=>{const target=id?($('lists-view').hidden?$('active-list-options'):$('lists-overview').querySelector(`[data-list="${CSS.escape(id)}"] .edit-list`)):origin;if(target?.isConnected)target.focus({preventScroll:true});};$('list-description-input').value=group(id)?.description||'';$('list-name-heading').textContent=id?'Edit List':'New list';$('list-name-input').value=group(id)?.name||'';$('list-name-error').textContent='';const membership=$('list-membership-items');membership.replaceChildren();$('list-membership').hidden=!id;for(const key of group(id)?.songs||[]){const label=el('label',null,'list-membership-row'),check=document.createElement('input');check.type='checkbox';check.checked=true;check.dataset.item=key;label.append(check,el('span',itemTitle(group(id),key,songs)+(textItem(group(id),key)?' · Note':'')));membership.append(label);}$('list-name-dialog').showModal();$('list-name-input').focus();}
 $('list-name-delete').onclick=()=>{if(remove(naming)){$('list-name-dialog').close();$('lists-actions').querySelector('button')?.focus();}};
 function remove(id){const g=group(id);if(!g||!confirm('Delete the List “'+g.name+'”? Catalog songs and shared Notes will not be deleted. Offline files needed by other saved Lists or individual saves remain protected.'))return;const exitOrder=orderingLists&&getState().groups.length===2;getState().groups=getState().groups.filter(g=>g.id!==id);expanded.delete(id);persist();const saved=save();onChanged();render();if(exitOrder)$('lists-overview').querySelector('.list-overview-entry')?.focus({preventScroll:true});announce(saved?'List deleted. Songs and shared Notes remain available.':'Changes last only while this page is open.');return true;}
 $('list-name-cancel').onclick=()=>$('list-name-dialog').close();
 $('list-name-form').onsubmit=e=>{e.preventDefault();const title=$('list-name-input').value.trim(),state=getState();if(!title){$('list-name-error').textContent='Enter a list name.';return;}if(state.groups.some(g=>g.id!==naming&&normalizeSearch(g.name)===normalizeSearch(title))){$('list-name-error').textContent='That list name already exists.';return;}
  const created=!naming,id=naming||crypto.randomUUID(),original=naming?structuredClone(group(naming)):null;const description=$('list-description-input').value.trim();if(created)state.groups.unshift({id,name:title,description,songs:[],displayNames:{}});else{const g=group(id);if(!g)return;g.name=title;g.description=description;const removed=[...$('list-membership-items').querySelectorAll('input')].filter(e=>!e.checked).map(e=>e.dataset.item);if(removed.length)stageRemoval(g,removed);}if(created){expand(id);nameReturn=()=>section(id)?.querySelector('.list-overview-entry').focus({preventScroll:true});}const saved=save();if(!saved){if(created)state.groups=state.groups.filter(g=>g.id!==id);else Object.assign(group(id),original);clearUndo();$('list-name-error').textContent='Could not save to device storage. Your changes are still staged. Free storage and retry.';return;}$('list-name-dialog').close();onChanged();{render();const target=$('lists-view').hidden?$('active-list-options'):$('lists-overview').querySelector(`[data-list="${CSS.escape(id)}"] .list-overview-entry`);target?.focus({preventScroll:true});}if(!saved)announce('Changes last only while this page is open.');
 };
 function editEntry(id,song,restore){const g=group(id);if(!g||!g.songs.includes(song.id))return;editingEntry={id,songId:song.id};$('list-entry-remove').setAttribute('aria-label','Remove from list: '+(g.displayNames?.[song.id]||song.title));entryReturn=restore;$('list-entry-original').textContent=song.title;const page=String(song.songNumber??song.page??'').trim();$('list-entry-page-row').hidden=!page;$('list-entry-page').textContent=page;const filename=isFileSong(song)?(song.originalFilename||song.asset?.split('/').at(-1)||''):'';$('list-entry-file-row').hidden=!filename;$('list-entry-file').textContent=filename||'';$('list-entry-name').value=Object.hasOwn(g.displayNames||{},song.id)?g.displayNames[song.id]:'';$('list-entry-name').placeholder=song.title;$('list-entry-dialog').showModal();$('list-entry-name').focus();}
 function focusAfterRemoval(list,index){const g=group(list),id=g?.songs[Math.min(index,g.songs.length-1)];if(id)focusRow(list,id,'.edit-list-entry');else section(list)?.querySelector('.list-actions-toggle')?.focus({preventScroll:true});}
 function clearUndo(){clearTimeout(undoTimer);undo=null;$('list-removal-undo').hidden=true;}
 function stageRemoval(g,ids){
  clearUndo();const removed=g.songs.map((id,index)=>({id,index,alias:g.displayNames?.[id],text:textItem(g,id)})).filter(item=>ids.includes(item.id));undo={list:g.id,items:removed};
  g.songs=g.songs.filter(id=>!ids.includes(id));for(const id of ids){if(g.displayNames)delete g.displayNames[id];}
  $('list-removal-message').textContent=removed.length===1?'Removed “'+(removed[0].text?.title||removed[0].alias||songs.find(s=>s.id===removed[0].id)?.title||'Unavailable song')+'” from '+g.name+'.':'Removed '+removed.length+' items from '+g.name+'.';$('list-removal-undo').hidden=false;undoTimer=setTimeout(clearUndo,7000);
 }
 function removeSong(list,id){const g=group(list),index=g?.songs.indexOf(id);if(!g||index<0)return;const y=scrollY;stageRemoval(g,[id]);const saved=save();onChanged();render();window.scrollTo({top:y,behavior:'instant'});focusAfterRemoval(list,index);if(!saved)$('list-removal-message').textContent+=' Changes last only while this page is open.';}
 $('list-removal-restore').onclick=()=>{
  const batch=undo,g=group(batch?.list);if(!batch)return;clearUndo();if(!g){announce('The List no longer exists.');return;}
  for(const item of batch.items){if(g.songs.includes(item.id))continue;g.songs.splice(Math.min(item.index,g.songs.length),0,item.id);if(item.alias!==undefined){g.displayNames||={};Object.defineProperty(g.displayNames,item.id,{value:item.alias,writable:true,enumerable:true,configurable:true});}}
  const y=scrollY,saved=save();onChanged();render();window.scrollTo({top:y,behavior:'instant'});focusRow(batch.list,batch.items[0].id,'.edit-list-entry');announce(saved?'Items restored to '+g.name+'.':'Items restored. Changes last only while this page is open.');
 };
 $('list-entry-remove').onclick=()=>{const item=editingEntry;if(!item)return;const index=group(item.id)?.songs.indexOf(item.songId);entryReturn=()=>focusAfterRemoval(item.id,index);$('list-entry-dialog').close();removeSong(item.id,item.songId);};
 $('list-entry-cancel').onclick=()=>$('list-entry-dialog').close();
 $('list-entry-reset').onclick=()=>{$('list-entry-name').value='';$('list-entry-name').focus();};
 $('list-entry-form').onsubmit=e=>{e.preventDefault();const g=group(editingEntry?.id),id=editingEntry?.songId;if(!g||!g.songs.includes(id))return;const name=$('list-entry-name').value.trim();g.displayNames||={};if(name)Object.defineProperty(g.displayNames,id,{value:name,writable:true,enumerable:true,configurable:true});else delete g.displayNames[id];const saved=save();onChanged();render();$('list-entry-dialog').close();if(!saved)$('library-message').textContent='Changes last only while this page is open.';};
 function selectionAction(){$('list-picker-done').textContent=selected.size+' selected — Add to list';$('list-picker-done').disabled=!selected.size;}
 function renderPicker(){const g=group(picking);if(!g){picking=null;render();return;}$('lists-heading').textContent='MusicTranspose · Lists';$('lists-context').textContent=g.name;$('list-picker-target').textContent='To: '+g.name;$('list-picker-target').title=g.name;$('lists-back').hidden=false;$('lists-back').textContent='‹ Back to list';$('list-picker').hidden=false;
  const query=normalizeSearch($('list-picker-search').value),favorites=$('list-picker-favorites').checked;
  const found=songs.filter(s=>canOpenScore(s)&&pickerSources.matches(s)&&(!favorites||getState().favorites.includes(s.id))&&query.split(/\s+/).every(word=>(songSearchText(s)+' '+normalizeSearch(s.originalFilename||'')).includes(word)));
  pickerSources.sortResults(found);
  const host=$('list-picker-results');host.replaceChildren();
  for(const s of found){const label=el('label',null,'list-picker-row'),check=document.createElement('input');check.type='checkbox';check.dataset.song=s.id;const exists=g.songs.includes(s.id);check.checked=exists||selected.has(s.id);check.disabled=exists;check.setAttribute('aria-label',(exists?'Already in list: ':'Add: ')+s.title);check.onchange=()=>{if(check.checked)selected.add(s.id);else selected.delete(s.id);selectionAction();};const text=el('span');text.append(el('strong',s.title),el('span',[s.collection,s.page,exists?'Already in list':''].filter(Boolean).join(' · '),'song-meta'));label.append(check,text);host.append(label);}
  if(!found.length)host.append(el('p','No songs match. Try another search or source.'));$('list-picker-count').textContent=found.length+' songs';selectionAction();
 }
 let listMenu=null,listMenuOrigin=null,listMenuId=null;
 function closeListMenu(focus=false){listMenu?.remove();listMenu=null;listMenuId=null;listMenuOrigin?.setAttribute('aria-expanded','false');if(focus&&listMenuOrigin?.isConnected)listMenuOrigin.focus({preventScroll:true});listMenuOrigin=null;}
 function updateListMenu(){if(!listMenu)return;const g=group(listMenuId);if(!g){closeListMenu();return;}const state=offlineListState(g),summary=offlineSummary(),save=listMenu.querySelector('.offline-list-save'),remove=listMenu.querySelector('.offline-list-remove');save.hidden=state.retained&&state.saved===state.total;save.disabled=summary.busy||!summary.shellReady;remove.hidden=!state.retained;remove.disabled=summary.busy;}
 function openListMenu(g,origin){
  if(listMenuOrigin===origin){closeListMenu(true);return;}closeListMenu();closeSongOrder();swipe.close();
  const menu=el('div',null,'list-command-menu');menu.id='list-command-menu';menu.setAttribute('role','menu');menu.setAttribute('aria-label','List actions: '+g.name);listMenu=menu;listMenuOrigin=origin;listMenuId=g.id;origin.setAttribute('aria-expanded','true');
  const add=button('Add songs','Add songs',()=>{closeListMenu();startPick(g.id);});add.classList.add('workspace-add');
  const addText=button('Add Note','Add Note',()=>{closeListMenu(true);openTextPicker(g.id);});
  const copy=button('Copy list','Copy list',async()=>{closeListMenu(true);const copied=await copyListText(listClipboardText(g,songs));announce(copied?'Copied '+listCount(g)+'.':'Unable to copy list. Try again.');});copy.classList.add('workspace-copy');
  const offline=async action=>{try{await action(g);}catch{}finally{if(listMenu===menu)closeListMenu(true);}};
  const save=button('Save list on this device','Save list on this device',()=>offline(saveOfflineList)),removeDownloads=button('Remove list downloads','Remove list downloads',()=>offline(removeOfflineList));save.classList.add('offline-list-save');removeDownloads.classList.add('offline-list-remove');
  const divider=el('hr');divider.setAttribute('role','separator');const del=button('Delete list','Delete list',()=>{closeListMenu(true);remove(g.id);});del.classList.add('workspace-delete');
  for(const item of [add,addText,copy,save,removeDownloads,del])item.setAttribute('role','menuitem');const sectionLabel=text=>{const label=el('div',text,'menu-section-label');label.setAttribute('role','presentation');return label;};menu.append(sectionLabel('Add'),add,addText,divider.cloneNode(),sectionLabel('List management'),copy,save,removeDownloads,divider,del);document.body.append(menu);updateListMenu();
  const r=origin.getBoundingClientRect(),box=menu.getBoundingClientRect();menu.style.left=Math.max(8,Math.min(innerWidth-box.width-8,r.left))+'px';menu.style.top=Math.max(8,Math.min(innerHeight-box.height-8,r.bottom+4))+'px';
  menu.onkeydown=e=>{if(e.key==='Tab'){e.preventDefault();closeListMenu(true);if(!e.shiftKey)section(g.id)?.querySelector('.workspace-song-front button')?.focus({preventScroll:true});return;}const actions=[...menu.querySelectorAll('button')].filter(b=>!b.hidden&&!b.disabled),i=actions.indexOf(document.activeElement);if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeListMenu(true);}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();actions[e.key==='Home'?0:e.key==='End'?actions.length-1:(i+(e.key==='ArrowDown'?1:-1)+actions.length)%actions.length]?.focus();}};
  menu.addEventListener('focusout',e=>{if(e.relatedTarget&&!menu.contains(e.relatedTarget)&&e.relatedTarget!==origin)closeListMenu();});add.focus({preventScroll:true});
 }
 document.addEventListener('pointerdown',e=>{if(listMenu&&!listMenu.contains(e.target)&&!listMenuOrigin?.contains(e.target))closeListMenu();});
 window.addEventListener('scroll',()=>closeListMenu(),{passive:true});window.addEventListener('resize',()=>closeListMenu());window.addEventListener('orientationchange',()=>closeListMenu());
 function commandRow(g){const box=el('div',null,'workspace-list-actions');box.dataset.offlineList=g.id;
  const menu=button('','Add and manage list',()=>openListMenu(g,menu));menu.classList.add('list-actions-toggle','toolbar-selector');menu.innerHTML='<span>Add</span><span aria-hidden="true">▾</span>';menu.setAttribute('aria-haspopup','menu');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-controls','list-command-menu');
  const status=el('span',null,'list-offline-status');status.setAttribute('role','status');const label=el('label',null,'list-favorites-filter'),check=document.createElement('input');check.type='checkbox';check.checked=favoriteLists.has(g.id);check.setAttribute('aria-label','Favorites in '+g.name);check.onchange=()=>{check.checked?favoriteLists.add(g.id):favoriteLists.delete(g.id);render();};label.append(check,document.createTextNode('Favorites'));box.append(menu,label,status);updateOfflineBox(box,g);return box;
 }
 function updateOfflineBox(box,g){const state=offlineListState(g),summary=offlineSummary(),progress=summary.progress?.listId===g.id?summary.progress:null,status=box.querySelector('.list-offline-status');status.textContent=progress?`Saving ${progress.processed} of ${progress.total}…`:`Offline: ${state.saved} of ${state.total} saved`;status.title=state.excluded?`${state.excluded} unavailable songs excluded`:'';status.setAttribute('aria-label',status.textContent+(state.excluded?`; ${state.excluded} unavailable songs excluded`:''));}
 document.addEventListener('offline-state-changed',()=>{for(const box of $('lists-overview').querySelectorAll('[data-offline-list]')){const g=group(box.dataset.offlineList);if(g)updateOfflineBox(box,g);}updateListMenu();if(offlineSummary().error&&!$('lists-view').hidden)announce(offlineSummary().error);});
 function render(){closeListMenu();swipe.close();pickerSources.prune();closeSongOrder();const canOrderLists=getState().groups.length>=2;if(!canOrderLists)orderingLists=false;if($('lists-view').hidden)return;$('lists-return').hidden=!!picking;const controls=$('lists-actions');controls.replaceChildren();$('lists-overview').replaceChildren();$('list-picker').hidden=true;document.body.classList.toggle('list-picker-open',!!picking);syncPickerViewport();document.title='Lists · MusicTranspose';if(picking){renderPicker();return;}
  $('lists-heading').textContent='MusicTranspose · Lists';$('lists-context').textContent=getState().groups.length+' '+(getState().groups.length===1?'list':'lists');$('lists-back').hidden=true;controls.append(Object.assign(button('+ New List','New list',()=>name()),{className:'quiet workspace-primary'}));if(orderingLists){const done=button('Done ordering Lists','Done ordering Lists',()=>{orderingLists=false;render();$('lists-actions').querySelector('button').focus({preventScroll:true});});done.id='lists-order-done';controls.append(done);}
  for(const g of getState().groups){const card=el('section',null,'list-workspace-section');card.dataset.list=g.id;card.dataset.listTint=listTint(g.id);const row=el('div',null,'list-overview-row'),entry=button('','List: '+g.name,()=>toggle(g.id)),content=el('div',null,'list-workspace-content');content.id='list-content-'+g.id;content.hidden=!expanded.has(g.id);card.classList.toggle('is-open',!content.hidden);entry.classList.add('list-overview-entry');entry.setAttribute('aria-expanded',String(!content.hidden));entry.setAttribute('aria-controls',content.id);const chevron=el('span',null,'list-chevron');chevron.setAttribute('aria-hidden','true');chevron.innerHTML='<svg viewBox="0 0 24 24"><path d="m9 5 7 7-7 7"/></svg>';const identity=el('span',null,'list-header-identity');identity.append(el('strong',g.name),el('span',listCount(g),'list-count'));entry.append(chevron,identity);entry.title=g.name;
   const pencil=button('','Edit list: '+g.name,()=>name(g.id));pencil.classList.add('list-icon','edit-list');pencil.innerHTML=editIcon;pencil.title='Edit List';const order=button('','Order list: '+g.name,()=>{if(!orderingLists)startListOrder(g.id);});order.classList.add('list-icon','order-list');order.innerHTML=orderIcon;order.title=orderingLists?'Drag List; Arrow Up / Down moves one place':'Order Lists';order.setAttribute('aria-pressed',String(orderingLists));row.append(entry,pencil);if(canOrderLists)row.append(order);card.append(row,content);$('lists-overview').append(card);
   if(orderingLists){const groups=getState().groups,index=groups.indexOf(g);order.classList.add('reorder-grip');attachReorderHandle(order,card,$('lists-overview'),(to,before)=>moveList(g.id,to,before),{selector:'.list-workspace-section',idKey:'list',targetSelector:'.list-overview-row'});order.onkeydown=e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();moveList(g.id,groups[index+(e.key==='ArrowUp'?-1:1)]?.id,e.key==='ArrowUp');}};const tools=el('div',null,'list-order-actions'),up=button('Move Up','Move list up: '+g.name,()=>moveList(g.id,groups[index-1]?.id,true)),down=button('Move Down','Move list down: '+g.name,()=>moveList(g.id,groups[index+1]?.id,false));up.disabled=index===0;down.disabled=index===groups.length-1;tools.append(el('span',(index+1)+' of '+groups.length),up,down);card.insertBefore(tools,content);}

   if(!content.hidden){const rows=el('div',null,'workspace-songs');const columns=el('div',null,'list-item-columns');columns.setAttribute('aria-hidden','true');columns.append(el('span'),el('span','Name'),el('span','Type'),el('span','Device'),el('span','Edit'),el('span'));content.append(commandRow(g),columns,rows);songRows(g,rows);}
  }
  if(!getState().groups.length)$('lists-overview').append(el('p','No lists yet. Create a list to organize your music.'));
 }
 const cancel=()=>{pickerSources.close();const id=picking;picking=null;selected.clear();onSelect(id);};
 $('lists-back').onclick=cancel;$('list-picker-cancel').onclick=cancel;
 for(const id of ['list-picker-search','list-picker-favorites'])$(id).addEventListener(id==='list-picker-search'?'input':'change',renderPicker);
 $('list-picker-done').onclick=()=>{pickerSources.close();const g=group(picking);if(!g)return;const valid=new Set(songs.filter(canOpenScore).map(s=>s.id)),added=[...selected].filter(id=>valid.has(id)&&!g.songs.includes(id));if(!added.length)return;g.songs.push(...added);const saved=save(),id=picking;picking=null;selected.clear();onChanged();onAdded(id,added,saved);};
 return {open,openList,pick,hide,render,name,remove,editEntry,finishAdded,remember,clearUndo,editText:(list,id)=>textEditor.open(list,id,textItem(group(list),id)),readText:id=>readText(null,id)};
}
