import {isFileSong} from './library-query.js';
import {inspectFile} from './local-music-validation.js';
import {normalizeFileTags,fileTypeLabel,byHash,localRecord,addRecord,updateRecord,removeRecord,storageMessage,fileDetails,saveBundledFileDetails} from './local-music-store.js';
import {refreshLocalMusic,releaseLocalAsset,songs} from './catalog.js';
const $=id=>document.getElementById(id);
export function initMyMusic(){
 const dialog=$('music-import');let pending=null,editing=null,working=false,fromFiles=false,previewRequest=0,origin=null,bundledEdit=false;
 const message=text=>$('import-message').textContent=text;
 function reset(){previewRequest++;working=false;pending=null;editing=null;$('music-file').value='';$('import-preview').replaceChildren();$('import-details').hidden=true;$('import-save').disabled=true;$('import-delete').hidden=true;$('import-memberships').replaceChildren();fromFiles=false;bundledEdit=false;dialog.classList.remove('editing-file');message('');}
 function show(record){pending=record;const details=fileDetails(record.metadata);$('import-title').value=details.displayName;$('import-description').value=details.description;$('import-category').value=details.category;$('import-composer').value=details.composer;$('import-arranger').value=details.arranger;$('import-tags').value=details.tags.join(', ');$('import-type').textContent=fileTypeLabel(record.metadata);$('import-filename').textContent=record.metadata.originalFilename||record.metadata.asset?.split('/').at(-1)||'';$('import-page').value=record.metadata.page||'';$('import-summary').textContent=[(record.metadata.fileType||record.metadata.scoreType||'').toUpperCase(),record.metadata.capability,record.metadata.tonic?record.metadata.tonic+' '+record.metadata.mode:'Key not determined'].join(' · ');$('import-warnings').textContent=record.metadata.warnings?.join(' ')||'';$('import-details').hidden=false;$('import-save').disabled=false;}
 $('add-music').onclick=()=>{reset();origin=$('add-music');$('import-heading').textContent='Import music';$('music-file').disabled=false;$('import-save').textContent='Add to Library';document.dispatchEvent(new Event('music-import-open'));dialog.showModal();$('music-file').focus();};
 $('close-import').onclick=$('import-cancel').onclick=()=>{if(!working)dialog.close();};dialog.addEventListener('cancel',e=>{if(working)e.preventDefault();});dialog.addEventListener('close',()=>{if(!dialog.open){const focus=origin;reset();document.dispatchEvent(new Event('music-import-close'));requestAnimationFrame(()=>focus?.isConnected&&focus.focus({preventScroll:true}));}});
 $('music-file').onchange=async()=>{const file=$('music-file').files[0];if(!file)return;const request=++previewRequest,preview=document.createElement('div');$('import-preview').replaceChildren(preview);pending=null;$('import-details').hidden=true;$('import-save').disabled=true;working=true;$('music-file').disabled=true;message('Checking file and preparing preview…');
  try{const record=await inspectFile(file,preview),duplicate=await byHash(record.metadata.hash);if(request!==previewRequest)return;if(duplicate){message('This exact file is already in Files. Nothing was added.');$('import-preview').replaceChildren();return;}show(record);memberships(record.metadata.id);message('Preview ready. Check the score before adding it.');}catch(e){if(request===previewRequest){$('import-preview').replaceChildren();message(e.message);}}finally{if(request===previewRequest){working=false;$('music-file').disabled=false;}}
 };
 function memberships(id){$('import-memberships').replaceChildren();let state={};try{state=JSON.parse(localStorage.getItem('music-transpose-library-v1')||'{}');}catch{}for(const g of state.groups||[]){const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.dataset.listId=g.id;check.checked=g.songs.includes(id);label.append(check,document.createTextNode(g.name));$('import-memberships').append(label);}if(!$('import-memberships').children.length)$('import-memberships').textContent='Not in any Lists.';}
 document.addEventListener('edit-local-music',async e=>{reset();origin=document.activeElement;working=true;try{fromFiles=!!e.detail?.fromFiles;const id=fromFiles?e.detail.id:e.detail;let record=await localRecord(id);if(!record){const song=songs.find(s=>s.id===id&&isFileSong(s));if(!song)return;record={metadata:{...song}};bundledEdit=true;}editing=id;dialog.classList.add('editing-file');$('import-heading').textContent='Edit file details';show(record);$('music-file').disabled=true;$('import-delete').hidden=bundledEdit;$('import-save').textContent='Save';memberships(id);dialog.showModal();$('import-title').focus();}catch{message('Unable to read this file.');}finally{working=false;}});
 $('import-save').onclick=async()=>{if(!pending||working)return;const title=$('import-title').value.trim()||pending.metadata.title||fileDetails(pending.metadata).displayName;working=true;$('import-save').disabled=true;const wasEditing=!!editing,savedId=pending.metadata.id,savedMessage=editing?'File details saved.':'File added to Files.';
  try{const details={displayName:title,description:$('import-description').value,category:$('import-category').value,composer:$('import-composer').value.trim(),arranger:$('import-arranger').value.trim(),tags:normalizeFileTags($('import-tags').value)};Object.assign(pending.metadata,details);if(bundledEdit)saveBundledFileDetails(editing,details);else{pending.metadata.page=$('import-page').value.trim();if(editing)await updateRecord(pending);else await addRecord(pending);}
   const memberships=[...$('import-memberships').querySelectorAll('input')].map(e=>({id:e.dataset.listId,checked:e.checked}));document.dispatchEvent(new CustomEvent('local-music-memberships',{detail:{id:savedId,memberships}}));

   await refreshLocalMusic();dialog.close();document.dispatchEvent(new CustomEvent('local-music-saved',{detail:{message:savedMessage,id:savedId,edited:wasEditing}}));if(navigator.storage?.persist)navigator.storage.persist().catch(()=>{});
  }catch(e){message(storageMessage(e));$('import-save').disabled=false;}finally{working=false;}
 };
 $('import-delete').onclick=async()=>{if(!editing||working||!confirm('Delete this file from this device? Its Favorites and list memberships will also be removed.'))return;working=true;
  try{await removeRecord(editing);releaseLocalAsset(editing);document.dispatchEvent(new CustomEvent('local-music-deleted',{detail:editing}));await refreshLocalMusic();dialog.close();document.dispatchEvent(new CustomEvent('local-music-saved',{detail:'File deleted. Favorites and list references removed.'}));}catch(e){message(storageMessage(e));}finally{working=false;}
 };
}
