export function initOfflineMusic({closeMenu,returnFocus}){
 const $=id=>document.getElementById(id),dialog=$('offline-music-dialog');let state=null,confirming=false,lastSpeech=0;
 async function request(type){const registration=await navigator.serviceWorker.ready,worker=registration.active;if(!worker)throw Error('Not ready');return new Promise((resolve,reject)=>{const channel=new MessageChannel(),timer=setTimeout(()=>{channel.port1.close();reject(Error('Not ready'));},20000);channel.port1.onmessage=e=>{clearTimeout(timer);channel.port1.close();e.data.error?reject(Error('Not ready')):resolve(e.data);};worker.postMessage({type},[channel.port2]);});}
 function show(value){state=value;const running=value.running;const summary=`${value.done} of ${value.total} available offline`;$('offline-structured').textContent=value.structuredDone===value.structuredTotal?'✓ Ready offline':`${value.structuredDone} of ${value.structuredTotal} ready offline`;$('offline-pdf-status').textContent=summary;$('offline-pdf-size').textContent=value.totalBytes?`About ${(value.totalBytes/1000000).toFixed(1)} MB for all ${value.total} Original PDFs`:'';$('offline-prepare').disabled=running||value.done===value.total;$('offline-stop').hidden=!running;$('offline-prepare').hidden=confirming;$('offline-progress').hidden=!running;$('offline-progress').max=value.total;$('offline-progress').value=value.done;
 const note=value.storageFull?'Device or browser storage prevented completion. Already prepared music has been kept.':value.failed?`${value.failed} could not be downloaded. Retry when online.`:running?'Preparing Original PDFs… You can stop after the current file.':'';$('offline-note').textContent=note;
 if(!running||Date.now()-lastSpeech>5000){$('offline-announcement').textContent=`Original PDFs: ${summary}. ${note}`;lastSpeech=Date.now();}
 }
 function confirmation(on){confirming=on;$('offline-confirm').hidden=!on;$('offline-prepare').hidden=on;if(on){$('offline-confirm-text').textContent=`Prepare ${state.total-state.done} missing Original PDFs for offline use? This may use significant device storage.`;$('offline-confirm-cancel').focus();}}
 async function refresh(){try{show(await request('offline-status'));}catch{$('offline-note').textContent='Offline preparation is not available yet. Open the app online and try again.';$('offline-prepare').disabled=true;}}
 $('offline-music').onclick=()=>{closeMenu();confirmation(false);$('offline-prepare').disabled=true;dialog.showModal();$('offline-music-close').focus();refresh();};
 $('offline-prepare').onclick=()=>{if(state&&!state.running)confirmation(true);};$('offline-confirm-cancel').onclick=()=>{confirmation(false);$('offline-prepare').focus();};
 $('offline-confirm-prepare').onclick=async()=>{confirmation(false);show({...state,running:true,failed:0,storageFull:false});try{await request('prepare-original-pdfs');await refresh();$('offline-stop').focus();}catch{$('offline-note').textContent='Unable to start preparation. Try again when online.';$('offline-prepare').disabled=false;}};
 $('offline-stop').onclick=()=>{request('stop-original-pdfs').catch(()=>{});$('offline-note').textContent='Stopping after the current file…';};$('offline-music-close').onclick=()=>dialog.close();
 dialog.addEventListener('cancel',e=>{if(confirming){e.preventDefault();confirmation(false);$('offline-prepare').focus();}});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
 dialog.addEventListener('close',()=>{if(state?.running)request('stop-original-pdfs').catch(()=>{});confirmation(false);returnFocus();});
 navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.type==='offline-music-status'&&dialog.open)show(e.data);if(e.data?.type==='score-cache-progress'&&dialog.open)refresh();});
}
