const CACHE='music-transpose-v332-'+self.registration.scope;
const SCORE_CACHE='music-transpose-scores-'+self.registration.scope;
// Fallback PDFs are intentionally absent from install/warm lists: cache on first open.
const ASSETS=["./offline-bulk.js","./metronome-sounds.js","./offline-inventory.js","./icon-paint.js","./ui-icons.js","./icon-system.css","./display-settings.js","./keyboard.js","./keyboard.css","./app-info.js","./storage-sizes.json","./offline-control.js","./score-labels.js","./texts-view.js","./primary-text.css","./list-items.js","./list-text.js","./list-row-swipe.js","./list-picker-sources.js","./pdf-continuous.js","./library-theme.js","./library-quick-access.js","./layout-state.js","./unavailable-songs.js","./score-availability.js","./footer-viewport.js","./screen-secondary-lyrics.js","./screen-pickup-layout.js","./list-copy.js","./generated-harmony.js","./generated-harmony-data.js","./offline-worker.js","./offline-manager.js","./offline-assets.js","./offline-catalog.json","./offline-score-ui.js","./offline-music.js","./offline-pdfs.json","./library-session.js", "./score-page-hints.js", "./accompaniment-layout.js", "./section-layout.js", "./tool-panel.js", "./right-hand-melody.js", "./print-source-credits.js", "./playback-voices.js", "./score-export.js", "./pdf-annotations.js", "./lead-spacing.js", "./cadence-melody.js", "./score-tools.js", "./home-screen.js", "./layout-debug.js", "./library-search.js", "./full-score-layout.js", "./system-pagination.js", "./hymn-melody.js", "./lead-layout.js", "./octave.js", "./metronome.js", "./pdf-fallbacks.js", "./playback-preferences.js", "./auto-layout.js", "./icons.js", "./files-view.js", "./lists-view.js", "./catalog.js", "./local-music-store.js", "./local-music-validation.js", "./my-music.js", "./", "./index.html", "./manifest.webmanifest", "./assets/icons/favicon.svg", "./assets/icons/favicon-32.png", "./assets/icons/apple-touch-icon.png", "./assets/icons/icon-192.png", "./assets/icons/icon-512.png", "./styles.css", "./app.js", "./lyric-placement.js", "./playback.js", "./pdf-score.js", "./vendor/pdf.min.js", "./vendor/pdf.worker.min.js", "./library.js", "./view-history.js", "./library-query.js", "./lyrics-view.js", "./lyrics-index.js", "./assets/lyrics.json", "./list-reorder.js", "./score-layout.js", "./opening-metadata.js", "./navigation.js", "./score-taps.js", "./settings-help.js", "./virtual-pages.js", "./music.js", "./lead-view.js", "./lead-availability.js", "./chord-symbol.js", "./instrument-keys.js", "./title-alignment.js", "./songs.js", "./imported-songs.js", "./vendor/opensheetmusicdisplay.min.js", "./vendor/fflate.min.js", "./offline-scores.json"];
importScripts('./offline-worker.js');
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS.map(url=>new Request(url,{cache:'reload'})))).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil((async()=>{
 // Retain already downloaded score bytes across the shell update.
 const scores=await caches.open(SCORE_CACHE);
 for(const name of await caches.keys())if(name!==CACHE&&name!==SCORE_CACHE&&name.startsWith('music-transpose-v')&&(name.endsWith('-'+self.registration.scope)||name.endsWith('-'+self.registration.scope+'-scores'))){
  let complete=true;const old=await caches.open(name);for(const request of await old.keys())if(/\.(mxl|xml|musicxml|pdf)$/.test(new URL(request.url).pathname)&&!await scores.match(request)){const response=await old.match(request);try{await scores.put(request,response);}catch{complete=false;}}
  if(complete)await caches.delete(name);
 }await self.clients.claim();
})()));
self.addEventListener('fetch',e=>{
 if(!e.request.url.startsWith('http')||e.request.method!=='GET'||new URL(e.request.url).origin!==self.location.origin)return;
 e.respondWith((async()=>{const score=/\.(mxl|xml|musicxml|pdf)$/.test(new URL(e.request.url).pathname),cache=await caches.open(score?SCORE_CACHE:CACHE);
 const saved=await(await caches.open(SAVED_CACHE)).match(e.request);if(saved)return saved;
 if(score){const stored=await storedScore(e.request);if(stored)return stored;}
 try{const r=await fetch(e.request,{cache:'no-cache'});if(r.ok){try{await cache.put(e.request,r.clone());}catch{ /* Keep readable online content even when storage is full. */ }}return r;}catch(error){const stored=await cache.match(e.request);if(stored)return stored;throw error;}
 })());
});
