import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),b=await chromium.launch({channel:'msedge',headless:true}),rows=[];
const source=fs.readFileSync('system-pagination.js','utf8');
// Fixed-gap reference changes only the permitted gap floor; all engraving is identical.
const reference=source.replace('Math.max(0,Math.min(gapCap,minimumGap))','gapCap');assert.notEqual(source,reference);
const cases=[['song-e3fab13a-2bab-4a23-8dfc-56307e1764eb','normal',402,844],['hhc-1054','normal',402,844],['song-e3fab13a-2bab-4a23-8dfc-56307e1764eb','auto',402,700],['cs-168','auto',402,568],['cs-168','large',402,650],['song-382cbc91-e68b-4945-b1c2-3ade4f9aeacf','large',402,650]];
try{for(const [id,mode,width,height] of cases){const pair=[];let originalXML;
 for(const baseline of [true,false]){const c=await b.newContext({viewport:{width,height},hasTouch:true,serviceWorkers:'block'}),p=await c.newPage();if(baseline)await p.route('**/system-pagination.js',r=>r.fulfill({contentType:'text/javascript',body:reference}));await p.addInitScript(()=>localStorage.setItem('music-transpose-navigation-v1',JSON.stringify({mode:'pages'})));
 await p.goto(process.env.TEST_URL||'http://127.0.0.1:8771/');await p.locator('.library-row').first().waitFor();const ready=async()=>{await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(250);};await p.evaluate(id=>prototype.loadSong(id),id);await ready();await p.locator('#score-size').click();await p.locator(`#score-size-options [data-size=${mode}]`).click();await ready();
 const xml=await p.evaluate(()=>prototype.viewXML);if(baseline)originalXML=xml;else assert.equal(xml,originalXML,'Exact musical content unchanged');
 const result=await p.evaluate(()=>({title:document.querySelector('.score-heading h1').textContent,zoom:document.querySelector('#score').dataset.zoom,width:document.querySelector('#score').clientWidth,pages:[...document.querySelectorAll('.mxl-page-frame')].map(f=>({available:f._view.page.available,used:f._view.used,count:+f.dataset.systems,reduction:f._view.page.gapReduction,systems:f._view.page.systems.map(s=>({start:s.start,end:s.end,height:s.height,y:s.y,gap:s.appliedGap}))}))}));pair.push(result);
 for(const page of result.pages){assert(page.used<=page.available+1e-6);page.systems.forEach((s,i)=>{if(i)assert(s.y-page.systems[i-1].y-page.systems[i-1].height>0);});}
 await p.screenshot({path:`test-results/adaptive-${id}-${mode}-${height}-${baseline?'before':'after'}.png`});
 if(!baseline){const index=result.pages.findIndex(p=>p.reduction>0);if(index>=0){for(let i=0;i<index;i++)await p.keyboard.press('ArrowRight');await p.screenshot({path:`test-results/adaptive-compressed-${id}-${mode}-${height}.png`});}}
 await c.close();}
 const [before,after]=pair;assert.equal(after.zoom,before.zoom);assert.equal(after.width,before.width);assert.deepEqual(after.pages.flatMap(p=>p.systems.map(({start,end,height})=>({start,end,height}))),before.pages.flatMap(p=>p.systems.map(({start,end,height})=>({start,end,height}))));assert(after.pages.length<before.pages.length);rows.push({id,mode,width,height,before,after});console.log('PASS identical music/size/system bounds; fewer pages',id,mode,width,height,before.pages.length,after.pages.length);
}fs.writeFileSync('test-results/adaptive-pages.json',JSON.stringify(rows,null,2));}finally{await b.close();}
