import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createRequire} from 'node:module';
const {chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright'),b=await chromium.launch({channel:'msedge'});
try{for(const width of [390,768,820,1440]){
 if(process.env.BATCH3_WIDTH&&width!==Number(process.env.BATCH3_WIDTH))continue;
 const height=width===390?844:width===768?1024:width===820?1180:1000;
 const c=await b.newContext({viewport:{width,height},hasTouch:width<1440,isMobile:width===390,...(width===390?{userAgent:"Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1"}:{}),acceptDownloads:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await c.addInitScript(()=>{window.shareMode='supported';Object.defineProperty(navigator,'canShare',{configurable:true,value:()=>shareMode!=='unsupported'});Object.defineProperty(navigator,'share',{configurable:true,value:async data=>{window.shareActivation=navigator.userActivation.isActive;if(shareMode==='cancel')throw new DOMException('Canceled','AbortError');if(shareMode==='error')throw new DOMException('Blocked','NotAllowedError');window.shared={name:data.files[0].name,type:data.files[0].type,bytes:[...new Uint8Array(await data.files[0].arrayBuffer())]};}});});
 await p.goto('http://127.0.0.1:8780/');await p.waitForFunction(()=>window.prototype?.navigation&&navigator.serviceWorker.controller);
 const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!document.body.classList.contains('song-loading')&&!document.getElementById('score-share').disabled),load=async(id,view)=>{await p.evaluate(({id,view})=>prototype.loadSong(id,view),{id,view});await ready();},open=()=>p.locator('#score-tools').click();
 await load('scripture-power');await open();const menu=p.locator('#score-tools-menu');assert.deepEqual(await menu.locator('.tools-section-label').allTextContents(),['Score tools','Output / Sharing','Offline']);assert.equal(await menu.locator('[role=separator]').count(),2);const order=await menu.locator(':scope>button:visible,:scope>label:visible').evaluateAll(es=>es.map(e=>e.id));assert(order.indexOf('score-page-theme')<order.indexOf('score-share'));assert(order.indexOf('score-share')<order.indexOf('score-export'));assert(order.indexOf('score-export')<order.indexOf('score-offline-save'));const box=await menu.boundingBox();assert(box.x>=0&&box.y>=0&&box.x+box.width<=width&&box.y+box.height<=height);assert(await menu.locator('button:visible').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44)));await p.screenshot({path:`test-results/batch3-tools-${width}.png`});
 await p.locator('#score-page-theme').click();assert.equal(await p.locator('#score-page-theme').getAttribute('aria-checked'),'true');await open();await p.locator('#score-trim').click();assert.equal(await p.locator('#pdf-trim').isChecked(),false);await ready();await open();await p.locator('#score-metronome').click();assert(await p.locator('#metronome-panel').isVisible());await p.locator('#metronome-done').click();
 await open();await p.locator('#score-annotate').click();assert.equal(await p.locator('#pdf-annotation-done').textContent(),'Close');await p.locator('.pdf-annotation-canvas:visible').first().evaluate(el=>{const r=el.getBoundingClientRect();for(const [type,dx] of [['pointerdown',0],['pointermove',30],['pointerup',30]])el.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:19,isPrimary:true,button:0,pointerType:'pen',clientX:r.x+r.width*.4+dx,clientY:r.y+r.height*.4}));});await p.waitForFunction(()=>localStorage.getItem('music-transpose-pdf-annotations-v1')?.includes('points'));const marks=await p.evaluate(()=>localStorage.getItem('music-transpose-pdf-annotations-v1'));await p.locator('#pdf-annotation-done').click();assert(await p.locator('#pdf-annotation-panel').isHidden());assert.equal(await p.evaluate(()=>localStorage.getItem('music-transpose-pdf-annotations-v1')),marks);await open();await p.locator('#score-annotate').click();assert(await p.locator('#pdf-annotation-panel').isVisible());await p.locator('#pdf-annotation-done').click();
 await p.evaluate(()=>{window.printCalls=0;window.print=()=>printCalls++;});await open();await p.locator('#print').click();await p.waitForFunction(()=>printCalls===1);assert.equal(await p.locator('#print-pages .pdf-annotation-canvas').count(),0);assert(await p.locator('#print-pages .pdf-print-page').count());await p.evaluate(()=>dispatchEvent(new Event('afterprint')));
 const original=await fs.readFile('assets/pdfs/scripture-power.pdf');await open();await p.locator('#score-export').click();assert.equal(await menu.locator('.tools-section-label:visible').count(),0);const downloaded=p.waitForEvent('download');await p.locator('#score-export-pdf').click();const d=await downloaded;assert.deepEqual(await fs.readFile(await d.path()),original);
 await open();await p.locator('#score-share').click();await p.waitForFunction(()=>window.shared);assert.deepEqual(Buffer.from(await p.evaluate(()=>shared.bytes)),original);assert(await p.evaluate(()=>shareActivation));
 if(width===820){
  // Real importer, original filename/type/bytes, supported/cancel/unsupported/failure paths.
  await p.locator('#songs').click();await p.locator('#home-files').click();await p.locator('#add-music').click();await p.locator('#music-file').setInputFiles({name:'Original Review.pdf',mimeType:'application/pdf',buffer:original});await p.waitForFunction(()=>!document.getElementById('import-save').disabled);await p.locator('#import-title').fill('Renamed display title');await p.locator('#import-save').click();await p.getByRole('button',{name:'Open file: Renamed display title',exact:true}).click();await ready();await p.evaluate(()=>window.shared=null);await open();await p.locator('#score-share').click();await p.waitForFunction(()=>window.shared);assert.equal(await p.evaluate(()=>shared.name),'Original Review.pdf');assert.equal(await p.evaluate(()=>shared.type),'application/pdf');assert.deepEqual(Buffer.from(await p.evaluate(()=>shared.bytes)),original);assert(await p.evaluate(()=>shareActivation));
  await p.evaluate(()=>shareMode='cancel');let downloads=0;p.on('download',()=>downloads++);await open();await p.locator('#score-share').click();await p.waitForFunction(()=>document.getElementById('status').textContent==='Sharing canceled.');assert.equal(downloads,0);
  for(const mode of ['unsupported','error']){await p.evaluate(mode=>shareMode=mode,mode);await open();const event=p.waitForEvent('download');await p.locator('#score-share').click();const file=await event;assert.equal(file.suggestedFilename(),'Original Review.pdf');assert.deepEqual(await fs.readFile(await file.path()),original);}
  await load('nativity','normal');await p.evaluate(()=>shareMode='supported');await open();await p.locator('#score-share').click();await p.waitForFunction(()=>shared.name.endsWith('.musicxml'));assert.match(Buffer.from(await p.evaluate(()=>shared.bytes)).toString(),/score-partwise/);await open();await p.locator('#score-export').click();const xmlDownload=p.waitForEvent('download');await p.locator('#score-export-xml').click();assert.equal((await fs.readFile(await(await xmlDownload).path())).toString(),await p.evaluate(()=>prototype.xml));await open();await p.locator('#score-export').click();await p.locator('#score-export-pdf').click();await p.waitForFunction(()=>printCalls===2);assert(await p.locator('#print-pages .print-page svg').count());await p.evaluate(()=>dispatchEvent(new Event('afterprint')));
  await open();await p.locator('#score-offline-save').click();await p.waitForFunction(async()=>{const m=await import('./offline-manager.js');await m.refreshOffline();return m.offlineSongState({id:'nativity'}).individual;});await open();assert.equal(await p.locator('#score-offline-status').textContent(),'Saved for offline use');assert.equal(await p.locator('#score-offline-remove').textContent(),'Remove song from this device');assert(await p.locator('#score-offline-remove').evaluate(e=>parseFloat(getComputedStyle(e).paddingLeft)>parseFloat(getComputedStyle(document.getElementById('score-offline-status')).paddingLeft)));await p.keyboard.press('Escape');await p.evaluate(async()=>{await(await import('./offline-manager.js')).saveOfflineList({id:'protected',songs:['nativity']});});await open();await p.locator('#score-offline-remove').click();await p.waitForFunction(async()=>{const m=await import('./offline-manager.js');await m.refreshOffline();const s=m.offlineSongState({id:'nativity'});return s.saved&&!s.individual&&s.lists.includes('protected');});await open();assert.match(await p.locator('#score-offline-status').textContent(),/Saved by List/);assert(await p.locator('#score-offline-remove').isHidden());
 }
 assert.deepEqual(errors,[]);console.log('PASS Tools, annotation Close/persistence, clean print/export, Share',width);await c.close();
}}finally{await b.close();}
