import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createRequire} from 'node:module';
const {chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright'),b=await chromium.launch({channel:'msedge'}),manifest=JSON.parse(await fs.readFile('storage-sizes.json','utf8'));
try{for(const width of [320,390,768,820,1440]){
 const c=await b.newContext({viewport:{width,height:width<600?844:1180},hasTouch:width<1440}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await c.addInitScript(()=>{const original=matchMedia.bind(window),display={matches:false,addEventListener(_,fn){window.setStandalone=value=>{display.matches=value;fn();};}};window.matchMedia=q=>q==='(display-mode: standalone)'?display:original(q);});
 await p.goto('http://127.0.0.1:8780/');await p.waitForFunction(()=>window.prototype?.navigation&&navigator.serviceWorker.controller);await p.evaluate(async()=>await(await import('./offline-manager.js')).refreshOffline());
 const open=()=>p.locator('#home-about').click(),menu=p.locator('#home-info-menu');await open();assert.deepEqual(await menu.locator('button').allTextContents(),['About MusicTranspose','App Info & Storage','Save songs to this device','Add app to your Home Screen']);assert.equal(await menu.locator('hr[role=separator]').count(),1);assert.equal(await p.locator('#home-info-saved').evaluate(e=>e.nextElementSibling.tagName),'HR');await p.keyboard.press('End');assert.equal(await p.evaluate(()=>document.activeElement.id),'add-home-screen');
 const bounds=await menu.boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=width);assert(await menu.locator('button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44)));await p.screenshot({path:`test-results/batch4-menu-${width}.png`});await p.locator('#home-info-about').click();assert(await p.locator('#about-dialog').isVisible());await p.locator('#about-close').click();await p.waitForFunction(()=>document.activeElement.id==='home-about');
 await open();await p.locator('#add-home-screen').click();assert(await p.locator('#home-screen-dialog').isVisible());await p.locator('#home-screen-close').click();await p.evaluate(()=>dispatchEvent(new Event('appinstalled')));await open();assert.equal(await p.locator('#add-home-screen').textContent(),'Add app to your Home Screen');await p.keyboard.press('Escape');
 const requests=[];p.on('request',r=>requests.push(r.url()));await open();await p.locator('#home-info-storage').click();await p.waitForFunction(()=>document.getElementById('app-storage-core').textContent.endsWith('MB'));const info=p.locator('#app-info-dialog');assert(await info.isVisible());assert(await p.locator('#app-info-title').evaluate(e=>e===document.activeElement));assert(!/NaN|undefined/.test(await info.textContent()));assert.equal(await p.locator('#app-storage-count').textContent(),'0');assert.equal(await p.locator('#app-storage-saved').textContent(),'0 MB');const sizes=await p.evaluate(async m=>{const {storageSize}=await import('./app-info.js');return [storageSize(m.coreBytes),storageSize(m.coreBytes+m.catalogBytes)];},manifest);assert.equal(await p.locator('#app-storage-core').textContent(),sizes[0]);assert.equal(await p.locator('#app-storage-all').textContent(),sizes[1]);assert.equal(requests.filter(url=>/\.(pdf|mxl|musicxml)(\?|$)/.test(url)).length,0);assert.match(await info.textContent(),/when you open or save it/);
 const rect=await info.boundingBox();assert(rect.x>=0&&rect.x+rect.width<=width);assert(await info.evaluate(e=>e.scrollWidth<=e.clientWidth));await p.screenshot({path:`test-results/batch4-storage-${width}.png`});
 if(width===820){
  const call=(name)=>p.evaluate(async name=>await(await import('./offline-manager.js'))[name]({id:'nativity'}),name);
  await call('saveOfflineSong');await p.waitForFunction(()=>document.getElementById('app-storage-count').textContent==='1');let state=await p.evaluate(async()=> (await import('./offline-manager.js')).offlineSummary());assert(state.bytes>0);assert.equal(await p.locator('#app-storage-saved').textContent(),await p.evaluate(async n=>(await import('./app-info.js')).storageSize(n),state.bytes));
  await p.evaluate(async()=>{const name=(await caches.keys()).find(n=>n.startsWith('music-transpose-saved-')),cache=await caches.open(name);await cache.delete((await cache.keys())[0]);await(await import('./offline-manager.js')).refreshOffline();});assert.equal(await p.locator('#app-storage-count').textContent(),'0');await call('saveOfflineSong');assert.equal(await p.locator('#app-storage-count').textContent(),'1');await p.locator('#app-info-close').click();await open();await p.locator('#home-info-saved').click();assert(await p.locator('#library.saved-device-view').isVisible());assert.equal(await p.locator('#library-results [data-song=nativity]').count(),1);await p.locator('#library-quick-home').click();await open();await p.locator('#home-info-storage').click();await call('removeOfflineSong');assert.equal(await p.locator('#app-storage-count').textContent(),'0');assert.equal(await p.locator('#app-storage-saved').textContent(),'0 MB');
 }
 await p.keyboard.press('Escape');assert(await info.isHidden());await p.waitForFunction(()=>document.activeElement.id==='home-about');await p.locator('#library-home .library-theme-toggle').click();await open();await p.locator('#home-info-storage').click();await p.screenshot({path:`test-results/batch4-storage-dark-${width}.png`});assert.notEqual(await info.evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(250, 252, 253)');await p.locator('#app-info-close').click();
 await p.locator('#home-text').click();assert.equal(await p.locator('#texts-heading').textContent(),'MusicTranspose · Notes');assert.equal(await p.locator('#texts-context').textContent(),'Create lyrics, cues, teaching material, and images');assert.match(await p.locator('#texts-new').textContent(),/New Note/);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/batch4-notes-dark-${width}.png`});await p.locator('#texts-home').click();await p.locator('#library-home .library-theme-toggle').click();const icon=await p.locator('#home-text').boundingBox();assert(icon.width>=44&&icon.height>=44);assert.equal(await p.locator('#home-text').getAttribute('aria-label'),'Notes');await p.locator('#home-text').click();await p.screenshot({path:`test-results/batch4-notes-${width}.png`});await p.locator('#texts-home').click();
 await p.evaluate(()=>setStandalone(true));await open();assert.equal(await p.locator('#add-home-screen').textContent(),'App installed on this device');assert(await p.locator('#add-home-screen').isDisabled());await p.keyboard.press('End');assert.equal(await p.evaluate(()=>document.activeElement.id),'home-info-saved');await p.keyboard.press('Escape');await p.locator('#home-about').press('ArrowUp');assert.equal(await p.evaluate(()=>document.activeElement.id),'home-info-saved');await p.keyboard.press('Escape');await p.evaluate(()=>setStandalone(false));await open();assert.equal(await p.locator('#add-home-screen').textContent(),'Add app to your Home Screen');assert(await p.locator('#add-home-screen').isEnabled());assert.deepEqual(errors,[]);console.log('PASS Info/Notes, estimates, install-state, responsive light/dark',width);await c.close();
}
 const c=await b.newContext(),p=await c.newPage();await c.addInitScript(()=>Object.defineProperty(navigator,'standalone',{value:true}));await p.goto('http://127.0.0.1:8780/');await p.locator('#home-about').click();assert.equal(await p.locator('#add-home-screen').textContent(),'App installed on this device');assert(await p.locator('#add-home-screen').isDisabled());console.log('PASS iOS standalone confirmation');await c.close();
}finally{await b.close();}
