import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const b=await chromium.launch({channel:'msedge'}),c=await b.newContext({viewport:{width:820,height:1180},serviceWorkers:'block'}),p=await c.newPage();
try{
 await c.addInitScript(()=>localStorage.setItem('music-transpose-library-v1',JSON.stringify({orderingVersion:1,favorites:['nativity'],textItems:{'text:cue':{type:'text',title:'Welcome',html:'<p>Welcome</p>'}},groups:[{id:'a',name:'Rehearsal',songs:['nativity','silent-night']}]})));
 await p.goto('http://127.0.0.1:8780/');await p.locator('#home-lists').click();await p.locator('.list-overview-entry').click();
 const fav=p.locator('.list-favorites-filter input');await fav.check();assert.equal(await p.locator('.workspace-song-row').count(),1);assert.equal(await fav.evaluate(e=>getComputedStyle(e).accentColor),'rgb(35, 124, 122)');await fav.uncheck();assert.equal(await p.locator('.workspace-song-row').count(),2);
 await p.locator('.list-actions-toggle').click();await p.locator('#list-command-menu').getByRole('menuitem',{name:'Add Text',exact:true}).click();await p.locator('#list-text-picker-items input').check();assert.equal(await p.locator('#list-text-picker-items input').evaluate(e=>getComputedStyle(e).accentColor),'rgb(35, 124, 122)');await p.locator('#list-text-picker-form button[type=submit]').click();assert.equal(await p.locator('.workspace-song-row').count(),3);
 await p.locator('#lists-library').click();await p.locator('#library-home .library-theme-toggle').click();await p.locator('#home-lists').click();assert.match(await p.locator('.workspace-primary').evaluate(e=>getComputedStyle(e).backgroundImage),/linear-gradient/);assert.equal(await p.locator('.workspace-primary').evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');await p.locator('.list-overview-entry').click();await fav.check();assert.equal(await fav.evaluate(e=>getComputedStyle(e).accentColor),'rgb(114, 197, 190)');await fav.focus();await p.keyboard.press('Tab');await p.keyboard.press('Shift+Tab');assert.equal(await fav.evaluate(e=>getComputedStyle(e).outlineStyle),'solid');await fav.uncheck();await p.locator('.list-actions-toggle').click();assert.equal(await p.locator('.list-actions-toggle').evaluate(e=>getComputedStyle(e).borderTopColor),'rgba(0, 0, 0, 0)');assert.equal(await p.locator('#list-command-menu .menu-section-label').first().evaluate(e=>getComputedStyle(e).color),'rgb(183, 201, 215)');await p.screenshot({path:'test-results/batch2-dark-list.png'});await p.locator('#list-command-menu .workspace-add').click();await p.locator('#list-picker-source').click();const check=p.locator('#list-picker-sources input[data-source=children]');await check.check();assert.equal(await check.evaluate(e=>getComputedStyle(e).accentColor),'rgb(114, 197, 190)');await p.keyboard.press('Escape');await p.locator('#list-picker-cancel').click();await p.locator('#lists-library').click();await p.locator('#home-files').click();assert.match(await p.locator('#add-music').evaluate(e=>getComputedStyle(e).backgroundImage),/linear-gradient/);assert.equal(await p.locator('#add-music').evaluate(e=>getComputedStyle(e).color),'rgb(255, 255, 255)');await p.locator('#files-library').click();
 await p.locator('#home-search').fill('Jesus');await p.locator('#home-search').press('Enter');assert.equal(await p.locator('[data-source-tone=children]').first().evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(38, 55, 70)');await p.screenshot({path:'test-results/batch2-dark-results.png'});await p.locator('#library-quick-home').click();
 // One exact numeric locator and one title search retain ordered source navigation.
 for(const query of ['140','Did You Think to Pray']){
  await p.locator('#home-search').fill(query);await p.locator('#home-search').press('Enter');const target=p.locator('#library-results .library-row').filter({hasText:'Did You Think to Pray'}).first();await target.locator('.song-entry').click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!document.body.classList.contains('song-loading'));const song=await p.evaluate(()=>prototype.song);assert.equal(await p.locator('#previous-song').isEnabled(),true);assert.equal(await p.locator('#next-song').isEnabled(),true);await p.locator('#next-song').click();await p.waitForFunction(id=>prototype.song!==id&&prototype.ready&&!prototype.busy&&!document.body.classList.contains('song-loading'),song);await p.locator('#previous-song').click();await p.waitForFunction(id=>prototype.song===id&&prototype.ready&&!prototype.busy&&!document.body.classList.contains('song-loading'),song);await p.locator('.score-identity-header .header-home').click();await p.locator('#library-quick-home').click();
 }
 console.log('PASS shared checkbox light/dark/focus, Favorites, Add Text membership, primary buttons, dark source tints, numeric/title Previous/Next');
}finally{await b.close();}
