import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import fs from 'node:fs/promises';import assert from 'node:assert/strict';const require=createRequire(process.env.PLAYWRIGHT_PACKAGE),{chromium}=require('playwright');const b=await chromium.launch({channel:'msedge',headless:true}),c=await b.newContext(),p=await c.newPage(),base='http://127.0.0.1:8767/';
try{
// Seed an obsolete catalog cache before first installation; unrelated app cache must survive.
await p.goto(base+'robots.txt');await p.evaluate(async base=>{const old=await caches.open('music-transpose-v12-'+base);await old.put(base+'songs.js',new Response('obsolete catalog'));await caches.open('music-transpose-v12-https://example.com/other/');localStorage.setItem('music-transpose-library-v1',JSON.stringify({favorites:['scripture-power'],groups:[],recent:[]}));},base);
await p.goto(base);await p.locator('.library-row').first().waitFor();await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);const keys=await p.evaluate(()=>caches.keys());assert(!keys.includes('music-transpose-v12-'+base));assert(keys.includes('music-transpose-v24-'+base));assert(keys.includes('music-transpose-v12-https://example.com/other/'));
// A stray old cache added later must never be used as an offline fallback.
await p.evaluate(async base=>{const old=await caches.open('music-transpose-v12-'+base);await old.put(base+'songs.js',new Response('obsolete catalog',{headers:{'Content-Type':'text/javascript'}}));},base);
const cdp=await c.newCDPSession(p);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await c.setOffline(true);await p.reload();await p.locator('.library-row').first().waitFor();assert.equal(await p.locator('.library-row').count(),121);await p.locator('#library-filter').selectOption('favorites');assert.equal(await p.locator('[data-song="scripture-power"]').count(),1);console.log('PASS scoped cache cleanup, current-cache-only offline reload, storage preservation');
}finally{await b.close();}
