import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),b=await chromium.launch({channel:'msedge',headless:true}),rows=[];
try{for(const [width,height] of [[320,568],[390,844],[430,932],[844,390],[820,1180],[1440,1000]]){
 const touch=width<1000,c=await b.newContext({viewport:{width,height},hasTouch:touch}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const ready=async()=>{await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');await p.waitForTimeout(100);};
 const mode=async value=>{await p.locator('#settings').click();await p.locator(`input[name=navigation][value=${value}]`).check();await p.locator('#close-settings').click();};const scroll=async y=>{await p.evaluate(y=>scrollTo(0,y),y);await p.waitForTimeout(80);};const visible=()=>p.locator('.return-start:visible').count();
 await p.goto(process.env.TEST_URL||'http://127.0.0.1:8771/');await p.locator('.library-row').first().waitFor();await p.evaluate(()=>prototype.loadSong('cs-110'));await ready();await mode('continuous');assert.equal(await visible(),0);
 const footer=await p.locator('.masthead').boundingBox(),xml=await p.evaluate(()=>prototype.xml);for(const y of [50,99,100,101,500]){await scroll(y);assert.equal(await visible(),y>=100?2:0);}
 const layout=await p.evaluate(async()=>{const rect=e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height};},buttons=[...document.querySelectorAll('.return-start')],{scoreVisibleBottom}=await import('./score-taps.js');return {buttons:buttons.map(rect),names:buttons.map(e=>e.getAttribute('aria-label')),icons:buttons.map(e=>e.innerHTML),footer:rect(document.querySelector('.masthead')),cutoff:scoreVisibleBottom(),overflow:document.documentElement.scrollWidth>innerWidth};});
 const [left,right]=layout.buttons;assert.deepEqual(layout.names,['Back to top','Back to top']);assert.equal(layout.icons[0],layout.icons[1]);assert(left.width===44&&left.height===44&&right.width===44&&right.height===44);assert.equal(left.top,right.top);assert(Math.abs(left.left-(width-right.right))<1);assert(left.left>=12&&right.right<=width-12);assert(left.top>=layout.cutoff+8&&left.bottom<=layout.footer.top-8);assert(!layout.overflow);assert.equal(layout.footer.height,footer.height);assert.equal(await p.evaluate(()=>prototype.xml),xml);
 // The safe lane is outside the score's visible/tappable viewport, not laid over ink.
 assert(await p.evaluate(async()=>{const {scoreTapAction}=await import('./score-taps.js'),r=document.querySelector('#return-start-left').getBoundingClientRect();return scoreTapAction(innerWidth/2,r.top+20)===null;}));assert(await p.evaluate(()=>[...document.querySelectorAll('.return-start')].every(e=>{const r=e.getBoundingClientRect();return !document.elementsFromPoint(r.left+22,r.top+22).some(n=>n.closest?.('#score,#source-credits,#original-key-reference'));})));await p.screenshot({path:`test-results/continuous-return-${width}.png`});
 for(const id of ['return-start','return-start-left']){await scroll(500);await p.evaluate(()=>{window.returnCalls=0;window.savedScrollTo=window.scrollTo;window.scrollTo=(...args)=>{window.returnCalls++;return savedScrollTo(...args);};});if(touch){const r=await p.locator('#'+id).boundingBox();await p.touchscreen.tap(r.x+r.width/2,r.y+r.height/2);}else await p.locator('#'+id).click();await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>scrollY),0);assert.equal(await p.evaluate(()=>returnCalls),1);await p.evaluate(()=>window.scrollTo=savedScrollTo);assert.equal(await visible(),0);assert.equal(await p.evaluate(()=>prototype.song),'cs-110');}
 await scroll(500);await p.keyboard.press('Tab');await p.locator('#return-start-left').focus();assert(await p.locator('#return-start-left').evaluate(e=>getComputedStyle(e).outlineStyle!=='none'));await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>scrollY),0);assert.equal(await visible(),0);
 await scroll(500);await p.locator('#return-start').focus();await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>scrollY),0);assert.equal(await visible(),0);
 await p.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await p.waitForTimeout(100);assert(await p.locator('#original-key-reference').isVisible());assert(await p.locator('#original-key-reference').evaluate(e=>{const r=e.getBoundingClientRect();return document.elementsFromPoint(r.left+1,r.top+1).some(n=>n.closest?.('.score-paper'));}));
 await mode('pages');assert.equal(await visible(),0);assert(!await p.locator('body').evaluate(e=>e.classList.contains('continuous-return-visible')));await p.keyboard.press('Home');const pos=await p.locator('#page-position').textContent();await p.evaluate(async()=>{const {scoreTapGeometry}=await import('./score-taps.js');window.tapGeometry=scoreTapGeometry();});const g=await p.evaluate(()=>tapGeometry);await p.mouse.click(g.left+g.width*.8,g.top+g.height*.65);assert.notEqual(await p.locator('#page-position').textContent(),pos);
 await mode('continuous');await scroll(500);await p.evaluate(()=>document.querySelector('#show-lyrics').click());await p.locator('#lyrics-view').waitFor({state:'visible'});assert.equal(await visible(),0);await p.locator('#songs').click();assert.equal(await visible(),0);
 await p.evaluate(()=>prototype.loadSong('choose-to-serve-the-lord'));await ready();await mode('continuous');await scroll(500);assert(await p.locator('#return-start').isVisible());assert(await p.locator('#return-start-left').isHidden());await p.locator('#return-start').click();assert.equal(await p.evaluate(()=>scrollY),0);await mode('pages');assert.equal(await visible(),0);
 if(width===390){await p.evaluate(()=>prototype.loadSong('cs-110'));await ready();await mode('continuous');await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await ready();await scroll(500);assert.equal(await visible(),2);await p.locator('#return-start-left').click();assert.equal(await p.evaluate(()=>scrollY),0);}
 assert.deepEqual(errors,[]);rows.push({width,height,...layout});await c.close();console.log('PASS paired return controls, threshold, safe lane, one touch/click, keyboard, modes/PDF, annotation and offline',width,height);
}fs.writeFileSync('test-results/continuous-return.json',JSON.stringify(rows,null,2));}finally{await b.close();}
