import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE||'C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright'),b=await chromium.launch({channel:'msedge',headless:true});
try{for(const [width,height] of [[820,1180],[1440,1000],[390,844]]){
 const c=await b.newContext({viewport:{width,height},serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await c.addInitScript(()=>{if(!localStorage.getItem('favorites-test')){localStorage.setItem('favorites-test','1');localStorage.setItem('music-transpose-library-v1',JSON.stringify({orderingVersion:1,favorites:['hhc-1035','choose-to-serve-the-lord'],groups:[{id:'practice',name:'Practice',songs:['hhc-1035','cs-138']}]}));}});
 await p.goto('http://127.0.0.1:8780/');await p.waitForFunction(()=>document.activeElement.id==='library-home-title');await p.locator('[data-home-source=children]').click();await p.locator('.library-row').first().waitFor();const first=p.locator('.library-row').first(),id=await first.getAttribute('data-song'),star=first.locator('.favorite'),before=await first.boundingBox();assert.match(await star.getAttribute('aria-label'),/^Add to Favorites:/);assert.equal(await star.getAttribute('aria-pressed'),'false');await p.keyboard.press('Tab');await star.focus();assert.notEqual(await star.evaluate(e=>getComputedStyle(e).outlineStyle),'none');await p.keyboard.press('Enter');const selected=p.locator(`[data-song="${id}"] .favorite`);assert.equal(await selected.getAttribute('aria-pressed'),'true');assert.match(await selected.getAttribute('aria-label'),/^Remove from Favorites:/);assert.equal((await p.locator(`[data-song="${id}"]`).boundingBox()).height,before.height);const geometry=await selected.evaluate(e=>{const r=e.getBoundingClientRect(),s=e.querySelector('svg'),v=s.getBoundingClientRect();return {w:r.width,h:r.height,center:Math.abs((r.left+r.right)-(v.left+v.right))<1,fill:getComputedStyle(s).fill,color:getComputedStyle(e).color,overflow:document.documentElement.scrollWidth>innerWidth};});assert(geometry.w>=44&&geometry.h>=44&&geometry.center&&!geometry.overflow);assert.notEqual(geometry.fill,'none');assert.equal(await p.locator('.favorite[aria-pressed=false] svg').first().evaluate(e=>getComputedStyle(e).fill),'none');await p.screenshot({path:`test-results/favorites-polish-${width}.png`});
 await p.locator('#library-filter').click();assert.deepEqual(await p.locator('#library-filter-menu button').allTextContents(),['Favorites']);assert.equal(await p.locator('#view-lead-sheets').count(),0);await p.locator('#view-favorites').click();await p.keyboard.press('Escape');assert.equal(await p.locator('#library-source-label').textContent(),'Children’s Songs');assert.equal(await p.locator('.library-row').count(),1);await p.locator('.favorite').click();assert.equal(await p.locator('.library-row').count(),0);assert.equal(await p.locator('#library-source-label').textContent(),'Children’s Songs');await p.locator('#library-filter').click();await p.locator('#view-favorites').click();await p.keyboard.press('Escape');assert.equal(await p.locator(`[data-song="${id}"] .favorite`).getAttribute('aria-pressed'),'false');
 if(width===820){const pick=async value=>{await p.locator('#library-source').click();await p.locator(`[data-source="${value}"]`).click();};const filter=async()=>{await p.locator('#library-filter').click();await p.locator('#view-favorites').click();await p.keyboard.press('Escape');};await pick('my-music');await filter();assert.equal(await p.locator('.library-row').count(),1);assert.equal(await p.locator('.library-row').getAttribute('data-song'),'choose-to-serve-the-lord');assert.equal(await p.locator('#library-source-label').textContent(),'Files');
 // Obsolete history flags must not filter out PDF-only favorites on reload.
 await p.evaluate(()=>{const s=history.state;s.musicTransposeNavigation.route.library.leadOnly=true;history.replaceState(s,'');});await p.reload();await p.locator('#library').waitFor({state:'visible'});assert.equal(await p.locator('.library-row').getAttribute('data-song'),'choose-to-serve-the-lord');assert.equal(await p.evaluate(()=>Object.hasOwn(history.state.musicTransposeNavigation.route.library,'leadOnly')),false);
 await pick('list:practice');await filter();assert.equal(await p.locator('#library-source-label').textContent(),'Practice');assert.equal(await p.locator('.library-row').getAttribute('data-song'),'hhc-1035');assert.equal(await p.locator('#order-toggle').inputValue(),'manual');await filter();assert.deepEqual(await p.locator('.library-row').evaluateAll(es=>es.map(e=>e.dataset.song)),['hhc-1035','cs-138']);assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1')).groups[0].songs),['hhc-1035','cs-138']);}
 assert.deepEqual(errors,[]);console.log('PASS Favorites toggle/filter, obsolete flag, Files/List context and geometry',width);await c.close();
}}finally{await b.close();}
