import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
const {chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const oldCss=execFileSync('git',['show','d52c2c2:icon-system.css'],{encoding:'utf8'});
const browser=await chromium.launch({channel:'msedge'});
try{for(const width of [390,744,820,1440]){
 const touch=width===390,c=await browser.newContext({viewport:{width,height:900},hasTouch:touch,...(touch?{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'}:{})});const p=await c.newPage();await p.goto(process.env.APP_URL||'http://127.0.0.1:8780/');await p.waitForFunction(()=>window.prototype?.navigation);await p.mouse.click(0,0);await p.evaluate(()=>prototype.loadSong('nativity'));await p.waitForFunction(()=>prototype.ready&&!prototype.busy);
 const noFooterFocus=async()=>assert(await p.evaluate(()=>!document.activeElement.closest('.masthead .toolbar')),'automatic Score opening must not focus a footer control');await noFooterFocus();
 // Reload persisted Score history while bypassing HTTP and service-worker caches.
 const session=await c.newCDPSession(p);await session.send('Network.enable');await session.send('Network.setCacheDisabled',{cacheDisabled:true});await session.send('Network.setBypassServiceWorker',{bypass:true});await p.reload();await p.waitForFunction(()=>prototype?.ready&&!prototype.busy&&!document.body.classList.contains('library-open'));await noFooterFocus();assert(!await p.locator('#show-lyrics').evaluate(e=>e.matches(':focus-visible')));
 // CSS-only border changes must preserve footer, text and score rectangles.
 const geometry=()=>p.evaluate(()=>['.masthead','.score-paper','#score','#score-size','#key','#key-name','#key-signature','#reset','#show-lyrics'].map(s=>document.querySelector(s).getBoundingClientRect().toJSON()));const before=await geometry();const css=await p.evaluate(old=>{const link=document.querySelector('link[href="icon-system.css"]'),current=[...link.sheet.cssRules].map(r=>r.cssText).join('\n');const style=document.createElement('style');style.id='state-baseline';style.textContent=old;document.head.append(style);link.disabled=true;return current;},oldCss);assert.deepEqual(await geometry(),before);await p.evaluate(css=>{document.getElementById('state-baseline').textContent=css;},css);
 for(const dark of [false,true]){await p.evaluate(dark=>document.documentElement.dataset.libraryTheme=dark?'dark':'light',dark);await p.mouse.move(0,0);const idle=await p.locator('#key').evaluate(e=>({border:getComputedStyle(e).borderColor,width:getComputedStyle(e).borderWidth,shadow:getComputedStyle(e).boxShadow,after:getComputedStyle(e,'::after').content}));assert.equal(idle.border,await p.locator('#score-size').evaluate(e=>getComputedStyle(e).borderColor));assert.equal(idle.width,'1px');assert.equal(idle.shadow,'none');assert.equal(idle.after,'none');await p.locator('#key').hover();assert.notEqual(await p.locator('#key').evaluate(e=>getComputedStyle(e).borderColor),idle.border);await p.locator('#key').click();await p.mouse.move(0,0);assert(await p.locator('#key-dialog').isVisible());assert.notEqual(await p.locator('#key').evaluate(e=>getComputedStyle(e).borderColor),idle.border);await p.keyboard.press('Escape');await p.keyboard.press('Tab');await p.locator('#key').focus();assert(await p.locator('#key').evaluate(e=>e.matches(':focus-visible')&&getComputedStyle(e).outlineStyle==='solid'));}
 await p.evaluate(()=>document.activeElement.blur());await p.mouse.click(0,0);for(let n=0;n<30;n++){await p.keyboard.press('Tab');if(await p.locator('#show-lyrics').evaluate(e=>e===document.activeElement))break;}assert(await p.locator('#show-lyrics').evaluate(e=>e===document.activeElement&&e.matches(':focus-visible')),'Tab retains the real Lyrics focus ring');await p.keyboard.press('Enter');await p.locator('.lyrics-score-toggle').waitFor({state:'visible'});await p.keyboard.press('Enter');await p.locator('#show-lyrics').waitFor({state:'visible'});assert(await p.locator('#show-lyrics').evaluate(e=>e===document.activeElement&&e.matches(':focus-visible')),'explicit keyboard return restores Lyrics focus');
 if(touch)await p.locator('#show-lyrics').tap();else await p.locator('#show-lyrics').click();await p.locator('.lyrics-score-toggle').waitFor({state:'visible'});if(touch)await p.locator('.lyrics-score-toggle').tap();else await p.locator('.lyrics-score-toggle').click();assert(await p.locator('#show-lyrics').evaluate(e=>!e.matches(':focus-visible')),'pointer return has no phantom ring');
 // Browser history is automatic restoration, distinct from the explicit toggle.
 await p.goBack();await p.locator('.lyrics-score-toggle').waitFor({state:'visible'});await p.goForward();await p.locator('#show-lyrics').waitFor({state:'visible'});await noFooterFocus();
 await p.screenshot({path:`test-results/footer-state-${width}.png`});console.log('PASS neutral Key, hover/open/keyboard focus, hard refresh, normal open, explicit keyboard/pointer return, history and unchanged geometry',width);await c.close();
}}finally{await browser.close();}
