import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs';
const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));assert.equal(manifest.display,'standalone');assert.equal(new URL(manifest.start_url,'https://utahbug.github.io/MusicTranspose/manifest.webmanifest').href,'https://utahbug.github.io/MusicTranspose/');assert(manifest.name&&manifest.short_name);for(const icon of manifest.icons){const bytes=fs.readFileSync(icon.src);assert.equal(`${bytes.readUInt32BE(16)}x${bytes.readUInt32BE(20)}`,icon.sizes);}const apple=fs.readFileSync('assets/icons/apple-touch-icon.png');assert.equal(apple.readUInt32BE(16),180);assert.equal(apple.readUInt32BE(20),180);
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),b=await chromium.launch({channel:'msedge',headless:true}),url=process.env.TEST_URL||'http://127.0.0.1:8771/';
const iphone='Mozilla/5.0 (iPhone; CPU iPhone OS 18_7 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1';
try{for(const [kind,width,height] of [['iphone',320,568],['iphone',390,844],['iphone',844,390],['ipad',820,1180],['android',412,915],['desktop',1440,1000]]){
 const c=await b.newContext({viewport:{width,height},hasTouch:kind!=='desktop',...(kind==='iphone'?{userAgent:iphone}:kind==='android'?{userAgent:'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/130.0 Mobile Safari/537.36'}:{})}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));if(kind==='ipad')await p.addInitScript(()=>{Object.defineProperty(navigator,'platform',{get:()=> 'MacIntel'});Object.defineProperty(navigator,'maxTouchPoints',{get:()=>5});});
 await p.goto(url);await p.waitForFunction(()=>window.prototype?.navigation);if(kind==='desktop'){const session=await c.newCDPSession(p),m=await session.send('Page.getAppManifest');assert.equal(m.errors.length,0);assert.match(m.url,/manifest.webmanifest$/);}
 await p.locator('#home-about').click();await p.locator('#add-home-screen').click();assert(await p.locator('#home-screen-dialog').isVisible());assert.equal(await p.evaluate(()=>document.activeElement.id),'home-screen-close');assert(await p.locator('#home-info-menu').isHidden());assert.match(await p.locator('#home-screen-note').textContent(),/does not save all songs/);
 if(['iphone','ipad'].includes(kind)){assert.match(await p.locator('#home-screen-intro').textContent(),/Safari/);assert.equal(await p.locator('#home-screen-steps li').count(),3);assert(await p.locator('#home-screen-install').isHidden());}
 const r=await p.locator('#home-screen-dialog').boundingBox();assert(r.x>=0&&r.y>=0&&r.x+r.width<=width&&r.y+r.height<=height);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/home-screen-${kind}-${width}.png`});await p.keyboard.press('Escape');assert(await p.locator('#home-screen-dialog').isHidden());assert.equal(await p.evaluate(()=>document.activeElement.id),'home-about');
 if(kind==='desktop'){for(const outcome of ['dismissed','accepted','error']){await p.evaluate(outcome=>{window.installCalls=0;const e=new Event('beforeinstallprompt',{cancelable:true});e.prompt=async()=>{window.installCalls++;if(outcome==='error')throw Error('unavailable');};e.userChoice=Promise.resolve({outcome});window.dispatchEvent(e);},outcome);await p.locator('#home-about').click();await p.locator('#add-home-screen').click();await p.locator('#home-screen-install').click();assert.equal(await p.evaluate(()=>window.installCalls),1);await p.waitForFunction(()=>document.querySelector('#home-screen-status').textContent.length>0);await p.locator('#home-screen-close').click();}await p.evaluate(()=>dispatchEvent(new Event('appinstalled')));await p.locator('#home-about').click();assert(await p.locator('#add-home-screen').isHidden());await p.keyboard.press('End');assert.equal(await p.evaluate(()=>document.activeElement.id),'home-info-about');}
 if(kind==='iphone'&&width===390){await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await p.waitForFunction(()=>window.prototype?.navigation);await p.locator('#home-about').click();await p.locator('#add-home-screen').click();assert(await p.locator('#home-screen-dialog').isVisible());await c.setOffline(false);}
 assert.deepEqual(errors,[]);console.log('PASS guidance, dismissal/focus, bounds, install behavior',kind,width,height);await c.close();
}
for(const mechanism of ['navigator','media']){const c=await b.newContext(),p=await c.newPage();await p.addInitScript(mechanism=>{if(mechanism==='navigator')Object.defineProperty(navigator,'standalone',{get:()=>true});else{const original=window.matchMedia.bind(window);window.matchMedia=q=>q==='(display-mode: standalone)'?{matches:true,addEventListener(){},removeEventListener(){}}:original(q);}},mechanism);await p.goto(new URL(manifest.start_url,url).href);await p.waitForFunction(()=>window.prototype?.navigation);await p.locator('#home-about').click();assert(await p.locator('#add-home-screen').isHidden());console.log('PASS standalone launch detection',mechanism);await c.close();}
}finally{await b.close();}
console.log('PASS manifest, icons, start URL and metadata');
