import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createRequire} from 'node:module';import {songs} from '../songs.js';import {generatedHarmony} from '../generated-harmony-data.js';
const numbers=[280],targets=songs.filter(s=>s.collection==='Hymns (1985)'&&numbers.includes(Number(s.page)));
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE||'C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright'),b=await chromium.launch({channel:'msedge'}),c=await b.newContext({viewport:{width:820,height:1180},serviceWorkers:'block',acceptDownloads:true}),p=await c.newPage();p.setDefaultTimeout(60000);
const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!prototype.loading&&document.querySelector('#score').getAttribute('aria-busy')==='false');
try{await p.goto(process.env.TEST_URL||'http://127.0.0.1:8780/');await p.waitForFunction(()=>window.prototype?.navigation);
for(const s of targets)for(const mode of ['normal','large'])for(const shift of [-2,1,2,6]){
 await p.evaluate(({id,mode})=>prototype.loadSong(id,mode),{id:s.id,mode});await ready();await p.evaluate(shift=>prototype.changeKey(shift),shift);await ready();const expected=await p.evaluate(mode=>mode==='large'?prototype.viewXML:prototype.xml,mode);
 await p.locator('#score-tools').click();await p.locator('#score-export').click();const pending=p.waitForEvent('download');await p.locator('#score-export-xml').click();const download=await pending;assert.equal(await download.failure(),null);const xml=await fs.readFile(await download.path(),'utf8');assert.equal(xml,expected,'export is musical working XML');const state=await p.evaluate(xml=>{const d=new DOMParser().parseFromString(xml,'application/xml');return {error:!!d.querySelector('parsererror'),count:d.querySelectorAll('harmony').length,ids:[...d.querySelectorAll('harmony')].map(n=>n.id),keys:[...d.querySelectorAll('part')].map(p=>[...p.querySelectorAll('key fifths')].map(n=>Number(n.textContent)))};},xml);assert(!state.error);const fifths={[-2]:-2,1:-5,2:2,6:-6}[shift];assert(state.keys.every(k=>JSON.stringify(k)===JSON.stringify([fifths,fifths+1,fifths])),'export preserves all modulations');assert.equal(state.count,generatedHarmony[s.id].events.length);assert.equal(new Set(state.ids).size,state.count);await p.keyboard.press('Escape');console.log('PASS actual MusicXML download',s.page,mode,shift,state.count);
}
}finally{await b.close();}
