import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright');const b=await chromium.launch({channel:'msedge',headless:true}),c=await b.newContext({viewport:{width:820,height:1180},hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const ready=async()=>{await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');await p.waitForTimeout(100);};
try{await p.goto(process.env.TEST_URL||'http://127.0.0.1:8768/');await p.locator('.library-row').first().waitFor();const catalog=await p.evaluate(async()=>(await import('./songs.js')).songs),hymns=catalog.filter(s=>s.collection==='Hymns (1985)');assert.equal(hymns.length,335);assert.equal(catalog.length,681);assert.equal(new Set(catalog.map(s=>s.id)).size,catalog.length);assert.equal(hymns.find(s=>s.page==='202').id,'faithful');assert.equal(hymns.find(s=>s.page==='204').id,'silent-night');
await p.locator('#library-source').selectOption('hymnal');await p.locator('#order-toggle').click();assert.deepEqual(await p.locator('.library-row').evaluateAll(es=>es.map(e=>Number(e.querySelector('strong').textContent.split(' · ')[0]))),hymns.map(s=>Number(s.page)).sort((a,b)=>a-b));
for(const q of ['223','God Be with You Till We Meet Again','be with you']){await p.locator('#library-search').fill(q);assert(await p.locator('.library-row').count()>0);}await p.locator('#library-search').fill('Because I Have Been Given Much');assert.equal(await p.locator('.library-row').count(),0);await p.locator('#library-search').fill('');
for(const [width,height] of [[390,844],[820,1180],[1180,820],[1440,1000]]){await p.setViewportSize({width,height});const before=Date.now();await p.locator('#library-search').fill('God');await p.locator('#library-search').fill('');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));console.log('Library search roundtrip ms',width,Date.now()-before);}
await p.setViewportSize({width:820,height:1180});
const samples=[1,2,13,100,126,150,162,280,284,335,341];
for(const n of samples){const s=hymns.find(s=>Number(s.page)===n);await p.locator(`[data-song="${s.id}"] .song-entry`).click();await ready();assert.equal(await p.evaluate(()=>prototype.song),s.id);assert((await p.locator('.score-heading h1').textContent()).includes(s.title));assert(await p.locator('#score svg').count());if(s.transpositionAvailable!==false){await p.locator('#key').click();await p.locator('[data-shift="1"]').click();await ready();await p.locator('#key').click();await p.locator('[data-shift="-1"]').click();await ready();await p.locator('#reset').click();await ready();assert(await p.evaluate(()=>prototype.xml===prototype.original));}else assert(await p.locator('#key').isHidden()||await p.locator('#key').isDisabled());
await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');await p.locator('.score-heading .song-playback').click();
await p.screenshot({path:`test-results/hymnal-${n}.png`});if(await p.locator('#show-lyrics').isVisible()){await p.locator('#show-lyrics').click();await p.locator('#lyrics-view').waitFor({state:'visible'});await p.getByRole('button',{name:'Open score',exact:true}).click();await ready();}
if(n===280||n===1){await p.evaluate(()=>prototype.preparePrint());assert(await p.locator('#print-pages svg').count());}
await p.locator('#songs').click();console.log('PASS song',n,s.title);}
// Wait for explicit complete score caching, not merely service-worker installation.
await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(async()=>{const urls=await(await fetch('./offline-scores.json')).json(),names=(await caches.keys()).filter(n=>n.endsWith('-scores'));if(!names.length)return false;const c=await caches.open(names[0]);return (await Promise.all(urls.map(u=>c.match(new URL(u,location.href).href)))).every(Boolean);},{},{timeout:120000});
const cacheStatus=await p.evaluate(async()=>{const urls=await(await fetch('./offline-scores.json')).json();return {assets:urls.length,caches:await caches.keys()};});console.log('CACHE READY',cacheStatus.assets);fs.writeFileSync('test-results/hymnal-offline.json',JSON.stringify(cacheStatus));
await c.setOffline(true);await p.reload();await p.locator('.library-row').first().waitFor();await p.locator('#library-source').selectOption('hymnal');await p.locator('#library-search').fill('223');const hymn=hymns.find(s=>s.page==='223');await p.locator(`[data-song="${hymn.id}"] .favorite`).click();await p.locator(`[data-song="${hymn.id}"] .song-entry`).click();await ready();await p.locator('#key').click();await p.locator('[data-shift="1"]').click();await ready();await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');await p.locator('#songs').click();
await p.locator('#manage-lists').click();await p.getByRole('button',{name:'New list',exact:true}).click();await p.locator('#list-name-input').fill('Sunday hymns');await p.locator('#list-name-form button[type=submit]').click();await p.getByRole('button',{name:'Add songs',exact:true}).click();await p.locator('#list-picker-search').fill('223');await p.locator(`#list-picker-results input[data-song="${hymn.id}"]`).check();await p.locator('#list-picker-done').click();const state=await p.evaluate(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1')));assert(state.favorites.includes(hymn.id));assert(state.groups.some(g=>g.songs.includes(hymn.id)));assert.deepEqual(errors,[]);console.log('PASS all hymn counts, source/numeric/search, sample playback/render/transpose/lyrics/print, offline unvisited hymn, Favorite and list');
}finally{await b.close();}
