import {chooseRelativeKey} from './key-selection-helper.mjs';
import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const require=createRequire(process.env.PLAYWRIGHT_PACKAGE),{chromium}=require('playwright');
const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');
try{await p.goto(process.env.TEST_URL||'http://127.0.0.1:8767/');await p.locator('.library-row').first().waitFor();
const results=await p.evaluate(async()=>{const {instrumentKeys}=await import('./instrument-keys.js');return [['C',0],['D',2],['E♭',-3],['F',-1],['G',1],['A',3],['B♭',-2]].map(([name,fifths])=>instrumentKeys({name,fifths,mode:'major'}).map(r=>r.key.name));});
assert.deepEqual(results,[['C','D','A','G'],['D','E','B','A'],['E♭','F','C','B♭'],['F','G','D','C'],['G','A','E','D'],['A','B','G♭','E'],['B♭','C','G','F']]);
assert(await p.evaluate(async()=>{const {instrumentKeys}=await import('./instrument-keys.js');for(const mode of ['major','minor'])for(let fifths=-7;fifths<=7;fifths++){const pc=((7*fifths+(mode==='minor'?9:0))%12+12)%12;for(const {key,semitones} of instrumentKeys({name:'C',mode,fifths})){const actual=((7*key.fifths+(mode==='minor'?9:0))%12+12)%12;if(actual!==(pc+semitones)%12||key.mode!==mode||Math.abs(key.fifths)>7)return false;}}return true;}));
await p.evaluate(()=>prototype.loadSong('nativity'));await ready();await p.locator('#key').click();assert.equal(await p.locator('#instrument-toggle').getAttribute('aria-expanded'),'false');await p.locator('#instrument-toggle').focus();await p.keyboard.press('Enter');assert(await p.locator('#instrument-panel').isVisible());assert.equal(await p.locator('#instrument-concert').textContent(),'Concert key: G major');
for(const [width,height] of [[390,844],[820,1180],[1180,820],[1440,1000]]){await p.setViewportSize({width,height});await p.waitForTimeout(400);await p.locator('#instrument-toggle').scrollIntoViewIfNeeded();assert(await p.evaluate(()=>{const d=document.querySelector('#key-dialog');return d.scrollWidth<=d.clientWidth+1&&d.getBoundingClientRect().width<=innerWidth;}));await p.locator('#instrument-panel').scrollIntoViewIfNeeded();await p.screenshot({path:`test-results/instrument-keys-${width}.png`});await p.locator('#instrument-panel [data-close-ensemble]').click();assert(await p.locator('#instrument-panel').isHidden());await p.locator('#instrument-toggle').click();}
await p.locator('#instrument-panel [data-close-ensemble]').click();await p.locator('#higher [data-shift="2"]').click();await ready();assert.equal(await p.locator('#instrument-concert').textContent(),'Concert key: A major');
await chooseRelativeKey(p,-1);await ready();assert.equal(await p.locator('#instrument-concert').textContent(),'Concert key: A♭ major');await chooseRelativeKey(p,1);await ready();assert.equal(await p.locator('#instrument-concert').textContent(),'Concert key: A major');await p.locator('#reset').click();await ready();assert.equal(await p.locator('#instrument-concert').textContent(),'Concert key: G major');
await p.evaluate(()=>prototype.loadSong('shepherd'));await ready();assert.equal(await p.locator('#instrument-concert').textContent(),'Concert key: D minor');assert.equal(await p.locator('#instrument-toggle').getAttribute('aria-expanded'),'false');assert.deepEqual(await p.locator('.instrument-written strong').allTextContents(),['D minor','E minor','B minor','A minor']);
await p.emulateMedia({media:'print'});assert(await p.locator('#key-dialog').isHidden());await p.emulateMedia({media:'screen'});
assert.deepEqual(errors,[]);console.log('PASS seven-key matrix, all signatures in both modes, enharmonics, keyboard disclosure, four layouts, selection/up/down/reset/song updates and print exclusion');
}finally{await b.close();}
