import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');const b=await chromium.launch({channel:'msedge'});
try{for(const width of [375,390,744,820,900,1440]){const c=await b.newContext({viewport:{width,height:1000},...(width<600?{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'}:{})});const p=await c.newPage();await p.goto(process.env.APP_URL||'http://127.0.0.1:8780/');await p.waitForFunction(()=>window.prototype?.navigation);await p.evaluate(()=>prototype.loadSong('nativity'));await p.waitForFunction(()=>prototype.ready&&!prototype.busy);
 await p.evaluate(()=>prototype.changeKey((prototype.current+1)%12));await p.waitForFunction(()=>!prototype.busy&&!document.getElementById('reset').hidden&&!document.getElementById('reset').disabled&&document.getElementById('score').getAttribute('aria-busy')==='false');
 const frame=()=>p.locator('.score-paper').evaluate(e=>e.getBoundingClientRect().toJSON()),baseline=await frame(),widths=[];
 let anchors=new Map();for(const reset of [false,true])for(const [name,sig] of [['C Maj',''],['F Maj','(♭)'],['B♭ Maj','(♭♭)'],['D♭ Maj','(♭♭♭♭♭)'],['F♯ Maj','(♯♯♯♯♯♯)'],['C Maj',''],['C♭ Maj','(♭♭♭♭♭♭♭)'],['C♯ Maj','(♯♯♯♯♯♯♯)'],['A♭ Min','(♭♭♭♭♭♭♭)'],['A♯ Min','(♯♯♯♯♯♯♯)'],['C Maj','']]){
  await p.evaluate(({name,sig,reset})=>{document.getElementById('key-name').textContent=name;document.getElementById('key-name').dataset.compact=name;document.getElementById('key-signature').textContent=sig;document.getElementById('reset').hidden=!reset;document.getElementById('reset').disabled=false;},{name,sig,reset});
  assert(await p.locator('#key-signature').isHidden());assert.equal(await p.locator('#key-name').textContent(),name);const result=await p.evaluate(()=>{const e=document.getElementById('key'),r=e.getBoundingClientRect();const spans=[...e.querySelectorAll('#key-name,#key-signature')].filter(e=>e.textContent&&e.getClientRects().length).map(e=>{const range=document.createRange();range.selectNodeContents(e);return [...range.getClientRects()].map(r=>r.toJSON());});const controls=[...document.querySelectorAll('.masthead .toolbar button')].filter(e=>e.getClientRects().length&&getComputedStyle(e).visibility!=='hidden').map(e=>({id:e.id,...e.getBoundingClientRect().toJSON()}));return {key:r.toJSON(),spans,controls,scroll:e.scrollWidth,client:e.clientWidth};});
  assert(result.scroll<=result.client+1,JSON.stringify({width,name,sig,reset,result}));assert(result.spans.every(rs=>rs.length===1&&rs[0].x>=result.key.x&&rs[0].right<=result.key.right),'complete text fits inside Key on one line');if(result.spans.length>1)assert(Math.abs((result.spans[0][0].y+result.spans[0][0].height/2)-(result.spans[1][0].y+result.spans[1][0].height/2))<3,'name and signature share one line');
  for(const r of result.controls)assert(r.x>=0&&r.right<=width&&r.width>=44&&r.height>=44,JSON.stringify({width,name,sig,reset,control:r}));const row=result.controls.sort((a,b)=>a.x-b.x);for(let i=1;i<row.length;i++)assert(row[i].x>=row[i-1].right,JSON.stringify({width,name,sig,reset,row}));assert.equal(result.controls.find(e=>e.id==='score-size').width,44);assert.equal(result.controls.some(e=>e.id==='reset'),reset);if(reset){assert.equal(result.controls.find(e=>e.id==='reset').width,44);assert(result.controls.find(e=>e.id==='reset').x>=result.key.right);}widths.push(result.key.width);if(width>600){const positions=result.controls.filter(e=>['score-size','key','reset'].includes(e.id)).map(e=>({id:e.id,x:e.x,w:e.width}));if(anchors.has(reset))assert.deepEqual(positions,anchors.get(reset),'short/long key changes never move the cluster');else anchors.set(reset,positions);}
  if(width<600)assert(await p.locator('#score-hide-controls').isHidden());else{const f=await p.locator('#score-hide-controls').boundingBox();assert.equal(f.x+22,width/2);assert(await p.locator('.playing-controls').evaluate((e,x)=>e.getBoundingClientRect().right<=x,f.x));}assert.deepEqual(await frame(),baseline);assert.equal(await p.locator('.masthead').evaluate(e=>e.getBoundingClientRect().height),54);
 }
 if(width<=600)assert(widths.every(w=>w===64),'phone Key reserves a stable tonic/mode width');else assert(widths.every(w=>w===84),'wide Key reserves a compact stable width');await p.screenshot({path:`test-results/key-elastic-${width}.png`});console.log('PASS repeated short/long and seven-accidental keys, stable wider cluster, responsive phone, Reset shown/hidden',width);await c.close();}}finally{await b.close();}
