import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium,webkit}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright');const results=[];
for(const kind of ['chromium','webkit']){const b=await (kind==='webkit'?webkit:chromium).launch(kind==='webkit'?{headless:true}:{channel:'msedge',headless:true});try{
 for(const [width,height] of [[512,682],[390,844]]){
  const c=await b.newContext({viewport:{width,height},deviceScaleFactor:3,hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>localStorage.setItem('music-transpose-navigation-v1',JSON.stringify({mode:'pages'})));
  const url=process.env.TEST_URL||'http://127.0.0.1:8771/';
  const load=async debug=>{await p.goto(url+(debug?'?layoutdebug=1':''));await p.locator('.library-row').first().waitFor();await p.evaluate(()=>prototype.loadSong('song-e1cfcf58-9d20-4563-be05-856e4e8d936a'));await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');await p.locator('#score-size').click();await p.locator('#score-size-options [data-size=normal]').click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');await p.waitForTimeout(1300);};
  const geometry=()=>p.evaluate(()=>({width:document.querySelector('#score').clientWidth,height:document.querySelector('.mxl-page-frame').style.height,pages:document.querySelectorAll('.mxl-page-frame').length,zoom:document.querySelector('#score').dataset.zoom}));
  await load(false);assert.equal(await p.locator('#layout-debug').count(),0);const before=await geometry();await load(true);await p.waitForFunction(()=>window.musicTransposeLayoutReport?.music.mode==='Normal');assert.deepEqual(await geometry(),before);
  await p.locator('#layout-debug #toggle').click();await p.waitForFunction(()=>window.musicTransposeLayoutReport);const report=await p.evaluate(()=>musicTransposeLayoutReport);assert.equal(report.viewport.innerWidth,width);assert.equal(report.viewport.innerHeight,height);assert.equal(report.music.pageCount,before.pages);assert.equal(report.music.mode,'Normal');assert.equal(report.readiness.fonts,'loaded');assert(report.settledForMs>=1000);assert(report.pages.every(page=>page.systems.length&&page.systems.every(s=>s.renderedHeight>0&&s.measures>0)));if(width===512)assert.equal(report.music.pageCount,4);
  await p.locator('#layout-debug #copy').click();await p.waitForFunction(()=>/copied|copy the report/.test(document.querySelector('#layout-debug').shadowRoot.getElementById('status').textContent));assert.deepEqual(await geometry(),before);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/layout-debug-${kind}-${width}.png`});
  await p.locator('#layout-debug #refresh').click();assert.equal(await p.evaluate(()=>musicTransposeLayoutReport),null);await p.waitForFunction(()=>window.musicTransposeLayoutReport);
  await p.locator('#layout-debug #close').click();await p.setViewportSize({width:768,height:1024});await p.waitForFunction(()=>musicTransposeLayoutReport?.viewport.innerWidth===768&&musicTransposeLayoutReport?.music.pageCount===1);const resized=await p.evaluate(()=>musicTransposeLayoutReport);assert.equal(resized.layout.effectiveScoreWidth,720);assert.equal(resized.music.notationScale,'0.78');
  await p.locator('#score-size').click();await p.locator('#score-size-options [data-size=large]').click();await p.waitForFunction(()=>musicTransposeLayoutReport?.music.mode==='Lead');assert.equal((await p.evaluate(()=>musicTransposeLayoutReport)).music.spacingProfile,'lead');
  assert.deepEqual(errors,[]);results.push({engine:kind,before,report,resized});console.log('PASS gate, stable capture, zero geometry change, refresh, resize, mode',kind,width);await c.close();
 }
}finally{await b.close();}}
fs.writeFileSync('test-results/layout-debug.json',JSON.stringify(results,null,2));

