import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),b=await chromium.launch({channel:'msedge',headless:true}),c=await b.newContext(),p=await c.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');
try{await p.goto(process.env.TEST_URL||'http://127.0.0.1:8771/');await p.locator('.library-row').first().waitFor();
const result=await p.evaluate(async()=>{
 const {songs}=await import('./songs.js'),{unpackMXL,transposeXML,shiftOctaveXML}=await import('./music.js'),{createLeadXML}=await import('./lead-view.js'),{scoreTimeline}=await import('./playback.js'),{bundledLeadIds}=await import('./lead-availability.js');
 const must=(x,m)=>{if(!x)throw Error(m);},parse=x=>new DOMParser().parseFromString(x,'application/xml'),child=(e,name)=>[...e.children].find(n=>n.localName===name),txt=(e,name,f='')=>child(e,name)?.textContent.trim()??f,pitch=n=>{const p=child(n,'pitch');return p?(Number(txt(p,'octave'))+1)*12+{C:0,D:2,E:4,F:5,G:7,A:9,B:11}[txt(p,'step')]+Number(txt(p,'alter','0')):null;};
 const clean=e=>{const n=e.cloneNode(true);for(const a of [n,...n.querySelectorAll('*')])for(const k of ['default-x','default-y','relative-x','relative-y'])a.removeAttribute(k);for(const a of [...n.children])if(['staff','voice','offset'].includes(a.localName))a.remove();return n.outerHTML.replace(/\s+/g,'');};
 const read=source=>{const d=parse(source),notes=[],marks=[];for(const part of d.querySelectorAll('score-partwise > part')){let div=1;for(const [mi,m] of [...part.children].filter(n=>n.localName==='measure').entries()){let at=0,last=0;for(const n of m.children){if(n.localName==='attributes')div=Number(txt(n,'divisions',String(div)));else if(n.localName==='backup')at-=Number(txt(n,'duration'))/div;else if(n.localName==='forward')at+=Number(txt(n,'duration'))/div;else if(n.localName==='note'){const duration=Number(txt(n,'duration','0'))/div,when=child(n,'chord')?last:at;if(!child(n,'chord')){last=at;at+=duration;}notes.push({part:part.id,staff:txt(n,'staff','1'),voice:txt(n,'voice','1'),mi,at:when,duration,pitch:pitch(n),node:n});}else if(['direction','harmony','sound'].includes(n.localName))marks.push({mi,at:at+Number(txt(n,'offset','0'))/div,tag:n.localName,xml:clean(n)});}}}return {d,notes,marks};};
 const rows=[];let previous=0;
 for(const song of songs.filter(s=>s.scoreType!=='pdf')){
  const source=unpackMXL(await(await fetch(song.asset)).arrayBuffer()),lead=createLeadXML(source,song),old=createLeadXML(source);must(lead.ok===bundledLeadIds.has(song.id),song.title+' index mismatch');
  if(song.collection!=='Hymns (1985)'){must(lead.ok===old.ok,song.title+' non-hymn coverage changed');if(lead.ok){previous++;must(lead.xml===old.xml,song.title+' previous Lead changed');}continue;}
  if(!lead.ok){must(lead.xml===source,song.title+' fallback changed source');continue;}
  const src=read(source),dst=read(lead.xml);must(dst.d.querySelectorAll('part').length===1,song.title+' one part');must(!dst.d.querySelector('note > chord'),song.title+' monophonic');must(dst.notes.length===lead.melodyProof.length,song.title+' melody event count');
  for(const [i,proof] of lead.melodyProof.entries()){
   const group=src.notes.filter(n=>n.part===proof.part&&n.staff===proof.staff&&n.voice===proof.voice&&n.mi===proof.measure&&Math.abs(n.at-proof.at)<1e-7);must(group.length>0&&group.length<=2,song.title+' source chord group');const expected=group.reduce((a,n)=>(n.pitch??-Infinity)>(a.pitch??-Infinity)?n:a,group[0]),actual=dst.notes[i];
   must(actual.pitch===expected.pitch&&actual.mi===proof.measure&&Math.abs(actual.at-proof.at)<1e-7&&Math.abs(actual.duration-expected.duration)<1e-7,song.title+' soprano pitch/rest/timing '+i);
   const lyrics=group.flatMap(n=>[...n.node.querySelectorAll('lyric')].map(l=>l.outerHTML));must(JSON.stringify(lyrics)===JSON.stringify([...actual.node.querySelectorAll('lyric')].map(l=>l.outerHTML)),song.title+' lyric attachment '+i);
   const ties=n=>[...n.querySelectorAll(':scope > tie')].map(t=>t.getAttribute('type'));must(JSON.stringify(ties(actual.node))===JSON.stringify(ties(expected.node)),song.title+' borrowed/lost tie '+i);
   const beams=n=>[...n.querySelectorAll(':scope > beam')].map(t=>t.getAttribute('number')+':'+t.textContent);const expectedBeams=beams(expected.node).length?beams(expected.node):beams(group[0].node);must(JSON.stringify(beams(actual.node))===JSON.stringify(expectedBeams),song.title+' beams '+i);
  }
  for(const mark of src.marks)must(dst.marks.some(m=>m.mi===mark.mi&&Math.abs(m.at-mark.at)<1e-7&&m.tag===mark.tag&&m.xml===mark.xml),song.title+' missing/moved annotation '+mark.tag);
  const bar=d=>[...d.querySelectorAll('repeat,ending')].map(n=>[n.localName,...['number','direction','type','times'].map(a=>n.getAttribute(a)||''),n.textContent.trim()].join(':'));for(const mark of bar(src.d))must(bar(dst.d).includes(mark),song.title+' repeat/ending');
  const slurs=new Map();for(const n of dst.d.querySelectorAll('notations > slur')){const k=n.getAttribute('number')||'1',t=n.getAttribute('type');if(t==='start'){must(!slurs.has(k),song.title+' slur overlap');slurs.set(k,true);}if(t==='stop'){must(slurs.has(k),song.title+' slur lost start');slurs.delete(k);}}must(!slurs.size,song.title+' slur lost stop');
  must(Math.abs(scoreTimeline(source).duration-scoreTimeline(lead.xml).duration)<1e-6,song.title+' total duration');
  const features={rests:dst.notes.filter(n=>n.pitch===null).length,ties:dst.d.querySelectorAll('tie').length,slurs:dst.d.querySelectorAll('slur').length,repeat:dst.d.querySelectorAll('repeat,ending').length,meters:[...dst.d.querySelectorAll('time')].map(n=>n.textContent.replace(/\s+/g,'')),voices:lead.selection.sourceVoices.length};
  rows.push({id:song.id,title:song.title,features});
  if(['silent-night','song-a13c43da-0243-4019-ad08-d7be530074f5','song-a5d8ad72-20f6-4adb-86ad-1ca300b93804','song-f76df380-7901-4f21-bf86-a6b36a10a8e8'].includes(song.id)){
   for(const shift of [-3,2]){const transposed=createLeadXML(transposeXML(source,shift,song.modeOverride),song);must(transposed.ok&&parse(transposed.xml).documentElement.outerHTML===parse(transposeXML(lead.xml,shift,song.modeOverride)).documentElement.outerHTML,song.title+' transposition commutes');}
   const normal=scoreTimeline(lead.xml).notes,up=scoreTimeline(shiftOctaveXML(lead.xml,1)).notes;must(up.every((n,i)=>n.midi===normal[i].midi+12),song.title+' octave playback');
  }
 }
 must(previous===34,'Original 34-song coverage');return {rows,previous};
});fs.writeFileSync('test-results/lead-hymn-validation.json',JSON.stringify(result,null,2));console.log('PASS independent source soprano/lyrics/timing/ties/beams/annotations/repeats/playback for',result.rows.length,'new hymns; original',result.previous,'Leads unchanged');
// Every enabled hymn must actually engrave before being exposed in the catalog.
for(const [i,row] of result.rows.entries()){await p.evaluate(id=>prototype.loadSong(id,'large'),row.id);await ready();assert(await p.evaluate(()=>prototype.lead.ok),row.title);assert(await p.locator('#score svg').count());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(i%25===0)console.log('PASS rendered hymn',i+1,row.title);}
for(const [width,height] of [[320,568],[390,844],[844,390],[820,1180],[1440,1000]]){await p.setViewportSize({width,height});await p.evaluate(()=>prototype.loadSong('silent-night','normal'));await ready();await p.evaluate(()=>prototype.changeKey(2));await ready();await p.evaluate(()=>prototype.changeOctave(1,'rh'));await ready();const state=await p.evaluate(()=>({song:prototype.song,key:prototype.current,oct:prototype.octaveState}));await p.locator('#score-size').click();await p.locator('#score-size-options [data-size=large]').click();await ready();await p.evaluate(()=>prototype.changeOctave(-1));await ready();await p.evaluate(()=>prototype.playback.prepare());assert(await p.evaluate(async()=>{const {scoreTimeline}=await import('./playback.js');return JSON.stringify(prototype.playback.timeline.notes)===JSON.stringify(scoreTimeline(prototype.viewXML).notes);}));await p.screenshot({path:`test-results/hymn-lead-${width}.png`});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#score-size').click();await p.locator('#score-size-options [data-size=normal]').click();await ready();assert.deepEqual(await p.evaluate(()=>({song:prototype.song,key:prototype.current,oct:{...prototype.octaveState,lead:0}})),state);console.log('PASS key/octave/playback/Score-Lead-Score',width,height);}
await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await ready();await p.evaluate(()=>prototype.loadSong('silent-night','large'));await ready();assert(await p.evaluate(()=>prototype.lead.ok));await p.evaluate(()=>prototype.playback.prepare());await c.setOffline(false);assert.deepEqual(errors,[]);console.log('PASS offline hymn Lead and no browser errors');
}finally{await b.close();}
