import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import fs from 'node:fs';import assert from 'node:assert/strict';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage();
const baseline=execFileSync('git',['show','6444d90:lead-view.js'],{encoding:'utf8'});await p.route('**/lead-baseline.js',r=>r.fulfill({contentType:'text/javascript',body:baseline}));
try{await p.goto(process.env.TEST_URL||'http://127.0.0.1:8771/');const result=await p.evaluate(async()=>{
const {createLeadXML}=await import('./lead-view.js'),{createLeadXML:old}=await import('./lead-baseline.js'),{unpackMXL,transposeXML,shiftOctaveXML}=await import('./music.js'),{songs}=await import('./songs.js');
const parse=x=>new DOMParser().parseFromString(x,'application/xml'),ser=n=>new XMLSerializer().serializeToString(n),must=(v,m)=>{if(!v)throw Error(m);},same=(a,b,m)=>must(JSON.stringify(a)===JSON.stringify(b),m),ctx={id:'hhc-1035'};
const source=unpackMXL(await(await fetch('assets/scores/hhc-1035.mxl')).arrayBuffer()),original=parse(source),lead=createLeadXML(source,ctx);must(lead.ok,'new lead');must(old(source,ctx).reason==='chordal-melody','original rejection');
function notes(doc){return [...doc.querySelectorAll('part > measure')].map(m=>[...m.querySelectorAll(':scope > note')].map(n=>({pitch:n.querySelector('pitch')?.textContent.replace(/\s/g,''),duration:n.querySelector('duration')?.textContent,lyrics:[...n.querySelectorAll('lyric')].map(ser),slurs:[...n.querySelectorAll('slur')].map(e=>[e.getAttribute('number'),e.getAttribute('type')]),ties:[...n.querySelectorAll('tie')].map(e=>e.getAttribute('type')),rest:!!n.querySelector('rest')})));}
function harmonies(d){let div=1;const result=[];for(const [mi,m] of [...d.querySelector('part').querySelectorAll(':scope > measure')].entries()){let at=0;for(const n of m.children){const t=k=>n.querySelector(':scope > '+k)?.textContent;if(n.localName==='attributes')div=Number(t('divisions')||div);const duration=Number(t('duration')||0)/div;if(n.localName==='backup')at-=duration;if(n.localName==='forward')at+=duration;if(n.localName==='note'&&!n.querySelector('chord,grace'))at+=duration;if(n.localName==='harmony')result.push({mi,at:at+Number(t('offset')||0)/div,root:n.querySelector('root')?.textContent.replace(/\s/g,''),kind:t('kind'),bass:n.querySelector('bass')?.textContent.replace(/\s/g,'')});}}return result;}
same(harmonies(parse(lead.xml)),harmonies(original),'harmony onset and spelling');
// Independently construct expected source voice: only the two reviewed cadence
// events select C4, carrying the anchor's lyrics. Everything else is unchanged.
const expected=original.cloneNode(true);expected.querySelectorAll('part')[1].remove();
for(const m of expected.querySelectorAll('part > measure')){for(const n of [...m.querySelectorAll(':scope > note')])if(n.querySelector('voice')?.textContent==='2')n.remove();if(['15','20'].includes(m.getAttribute('number'))){const ns=[...m.querySelectorAll(':scope > note')],top=ns.find(n=>n.querySelector('step')?.textContent==='C'&&n.querySelector('octave')?.textContent==='4');for(const l of ns[0].querySelectorAll('lyric'))top.append(l.cloneNode(true));ns.filter(n=>n!==top).forEach(n=>n.remove());}}
same(notes(parse(lead.xml)),notes(expected),'20 measures exact source pitch/rhythm/lyrics/slurs');must(parse(lead.xml).querySelectorAll('note').length===56,'56 melody events');same([...parse(lead.xml).querySelectorAll('harmony')].map(h=>[...h.children].filter(n=>['root','kind','bass','degree','inversion'].includes(n.localName)).map(n=>n.textContent.replace(/\s/g,'')).join('|')),[...original.querySelector('part').querySelectorAll('harmony')].map(h=>[...h.children].filter(n=>['root','kind','bass','degree','inversion'].includes(n.localName)).map(n=>n.textContent.replace(/\s/g,'')).join('|')),'upper-part harmony symbols');
for(const shift of [-3,2])same(notes(parse(transposeXML(lead.xml,shift))),notes(parse(transposeXML(ser(expected),shift))),'transposition '+shift);
for(const shift of [-1,1])same(notes(parse(shiftOctaveXML(lead.xml,shift))),notes(parse(shiftOctaveXML(ser(expected),shift))),'octave '+shift);
const mutate=fn=>{const d=parse(source);fn(d);return ser(d);};
const noLyrics=mutate(d=>d.querySelectorAll('part')[0].querySelectorAll('measure')[3].querySelectorAll('note')[1].querySelectorAll('lyric').forEach(n=>n.remove()));const nr=createLeadXML(noLyrics,ctx);must(nr.ok&&parse(nr.xml).querySelectorAll('note').length===56,'non-lyric passing note survives');
const tied=mutate(d=>{const ms=d.querySelectorAll('part')[0].querySelectorAll('measure'),a=[...ms[1].querySelectorAll('note')].filter(n=>n.querySelector('voice').textContent==='1').at(-1),z=ms[2].querySelector('note');for(const [n,type] of [[a,'start'],[z,'stop']]){const t=d.createElement('tie');t.setAttribute('type',type);n.insertBefore(t,n.querySelector('voice'));}});const tr=createLeadXML(tied,ctx);must(tr.ok&&parse(tr.xml).querySelectorAll('tie').length===2,'same-voice ties survive');
const slurred=mutate(d=>{const ns=d.querySelector('part').querySelectorAll('measure')[0].querySelectorAll('note');for(const [n,type] of [[ns[0],'start'],[ns[1],'stop']]){const notation=d.createElement('notations'),slur=d.createElement('slur');slur.setAttribute('type',type);slur.setAttribute('number','9');notation.append(slur);n.insertBefore(notation,n.querySelector('lyric'));}});const sr=createLeadXML(slurred,ctx);must(sr.ok&&parse(sr.xml).querySelectorAll('slur[number="9"]').length===2,'same-voice slurs survive');
const rested=mutate(d=>{const n=d.querySelector('part note');n.querySelector('pitch').replaceWith(d.createElement('rest'));n.querySelectorAll('lyric').forEach(e=>e.remove());});const rr=createLeadXML(rested,ctx);must(rr.ok&&parse(rr.xml).querySelectorAll('rest').length===1,'same-voice rest survives');
const bad=[['different cadence',d=>d.querySelector('part > measure[number="15"] note:last-of-type pitch step').textContent='D'],['cue crossing',d=>d.querySelector('cue').parentElement.querySelector('octave').textContent='6'],['small cue',d=>d.querySelector('cue').parentElement.querySelector('type').setAttribute('size','cue')],['ambiguous chord slur',d=>{const n=d.createElement('slur');n.setAttribute('type','start');d.querySelector('part > measure[number="15"] notations').append(n);}],['second lyrical voice',d=>{const n=d.querySelector('cue').parentElement;n.append(d.querySelector('lyric').cloneNode(true));}],['voice gap',d=>d.querySelector('part > measure[number="3"] note').remove()]];
// Phase 3 may safely resolve formerly rejected chords/cues. Keep the genuine
// broken rhythm and ambiguous slur guards; the full Phase 3 suite checks provenance.
for(const [name,fn] of bad.filter(([name])=>['ambiguous chord slur','voice gap'].includes(name))){const xml=mutate(fn),r=createLeadXML(xml,ctx);must(!r.ok&&r.xml===xml,'safety fallback '+name);}
const samples=['silent-night','nativity','cs-168','hhc-1054','song-e1cfcf58-9d20-4563-be05-856e4e8d936a'];const regress=[];
for(const id of samples){const s=songs.find(s=>s.id===id),x=unpackMXL(await(await fetch(s.asset)).arrayBuffer());const prior=old(x,s);if(prior.ok)same(createLeadXML(x,s),prior,'unchanged '+id);regress.push(id);}
const negative=[];
return {negative,measures:20,melodyEvents:56,chords:34,cadences:lead.cadences,accompanimentCues:lead.accompanimentCues,guards:['ambiguous chord slur','voice gap'],regress};});console.log(result);fs.writeFileSync('test-results/hhc1035-structural.json',JSON.stringify(result,null,2));}finally{await b.close();}
