import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),b=await chromium.launch({channel:'msedge',headless:true}),c=await b.newContext({viewport:{width:390,height:844},hasTouch:true}),p=await c.newPage();
const base=process.env.TEST_URL||'http://127.0.0.1:8768/',ready=async()=>{await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');await p.waitForTimeout(120);};
const view=async s=>{await p.locator('#score-size').click();await p.locator(`#score-size-options [data-size=${s}]`).click();await ready();};
const saved={favorites:['hhc-1054'],groups:[{id:'lead-check',name:'Lead rehearsal',songs:['hhc-1054','shepherd']}]};await c.addInitScript(saved=>localStorage.setItem('music-transpose-library-v1',JSON.stringify(saved)),saved);
try{
 await p.goto(base);await p.locator('.library-row').first().waitFor();
 const unit=await p.evaluate(async()=>{
  const {createLeadXML}=await import('./lead-view.js'),{transposeXML}=await import('./music.js');const check=(ok,msg)=>{if(!ok)throw Error(msg);};
  const attrs='<attributes><divisions>2</divisions><key><fifths>0</fifths><mode>major</mode></key><time><beats>4</beats><beat-type>4</beat-type></time><staves>2</staves><clef number="1"><sign>G</sign><line>2</line></clef><clef number="2"><sign>F</sign><line>4</line></clef></attributes>';
  const n=(step,staff,voice,lyric='',extras='')=>`<note>${extras}<pitch><step>${step}</step><octave>4</octave></pitch><duration>4</duration><voice>${voice}</voice><type>half</type><staff>${staff}</staff>${lyric}</note>`;
  const lyrics='<lyric number="2" placement="above"><syllabic>begin</syllabic><text>Glo</text><extend type="start"/></lyric>';
  const harmony='<harmony><root><root-step>G</root-step></root><kind text="maj7">major-seventh</kind><bass><bass-step>B</bass-step></bass><root><root-step>D</root-step></root><kind>minor</kind><offset>1</offset></harmony>';
  const direction='<direction><direction-type><words>(G/B)</words></direction-type><offset>1</offset></direction>';
  const source='<?xml version="1.0"?><score-partwise version="4.0"><part-list><score-part id="P1"><part-name>Piano</part-name></score-part><score-part id="P2"><part-name>Choir</part-name></score-part></part-list><part id="P1"><measure number="0" implicit="yes">'+attrs+harmony+direction+n('G',1,1)+'</measure></part><part id="P2"><measure number="0" implicit="yes">'+attrs+n('E',1,1)+'<backup><duration>4</duration></backup>'+n('C',2,5,lyrics)+'<barline location="right"><ending number="1" type="stop"/><repeat direction="backward"/></barline></measure></part></score-partwise>';
  // Distinct lower staff in the second part: no top-part, top-staff or lowest-voice shortcut.
  const lead=createLeadXML(source);check(lead.ok,JSON.stringify(lead));check(lead.selection.part==='P2'&&lead.selection.staff==='2'&&lead.selection.voice==='5','melody selection');
  const doc=new DOMParser().parseFromString(lead.xml,'application/xml');check(doc.querySelectorAll('part').length===1,'single part');check(doc.querySelector('clef sign').textContent==='F','selected clef');check(doc.querySelector('lyric').outerHTML===lyrics,'exact lyric structure');check(doc.querySelector('measure').getAttribute('implicit')==='yes','pickup');check(doc.querySelector('repeat').getAttribute('direction')==='backward','repeat');
  const transposed=transposeXML(lead.xml,2);check(transposed.includes('(A/C#)'),'optional/slash');const td=new DOMParser().parseFromString(transposed,'application/xml');check([...td.querySelectorAll('harmony root-step')].map(e=>e.textContent).join(',')==='A,E','stacked roots');check(td.querySelector('harmony bass-step').textContent==='C','bass transposed');check(td.querySelector('note pitch step').textContent==='D','melody transposed');
  const ambiguous=source.replace(n('E',1,1),n('E',1,1,lyrics));check(createLeadXML(ambiguous).reason==='multiple-lyrics','competing lyrics rejected');
  const chordal=source.replace(n('C',2,5,lyrics),n('C',2,5,lyrics)+n('E',2,5,'','<chord/>'));check(createLeadXML(chordal).reason==='chordal-melody','polyphonic lyric lane rejected');
  const foreignCue=source.replace(n('G',1,1),n('G',1,1,'','<cue/>'));check(createLeadXML(foreignCue).reason==='outside-cues','foreign cue preserved by fallback');
  const ownCue=source.replace('<pitch><step>C', '<cue/><pitch><step>C');check(createLeadXML(ownCue).xml.includes('<cue/>'),'melody cue retained');
  const missing=source.replace(lyrics,'');check(createLeadXML(missing).reason==='no-melody','no lyrics fallback');
  return {source:lead.xml};
 });await p.evaluate(async xml=>{const host=document.createElement('div');host.style.width='500px';document.body.append(host);const engine=new opensheetmusicdisplay.OpenSheetMusicDisplay(host,{backend:'svg',autoResize:false,drawTitle:false});const {leadEngravingXML}=await import('./lead-view.js');await engine.load(leadEngravingXML(xml));engine.render();window.stackedLeadBeats=engine.Sheet.SourceMeasures[0].VerticalSourceStaffEntryContainers.filter(c=>c.StaffEntries.some(e=>e?.ChordContainers?.length)).map(c=>c.Timestamp.RealValue*4);window.stackedLeadText=host.textContent;window.stackedLeadBoxes=[...host.querySelectorAll('text')].map(e=>({t:e.textContent,x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height}));host.remove();},unit.source);const boxes=await p.evaluate(()=>stackedLeadBoxes),top=boxes.find(b=>b.t==='Gmaj7/B'),bottom=boxes.find(b=>b.t==='Dm');assert(top&&bottom);assert(Math.abs(top.x-bottom.x)<1);assert(bottom.y>=top.y+top.h);assert.deepEqual(await p.evaluate(()=>stackedLeadBeats),[.5]);console.log('PASS conservative selection, lower staff/second part, pickups, above lyrics, cue preservation, stacked/optional/slash chords');
 // Open through the active list, preserving Favorite and List context.
 await p.locator('#library-list').selectOption('lead-check');await p.getByRole('button',{name:'Open score: When I Am Baptized',exact:true}).click();await ready();
 await p.evaluate(()=>prototype.changeKey(2));await ready();const before=await p.evaluate(()=>({store:localStorage.getItem('music-transpose-library-v1'),route:history.state,xml:prototype.xml}));
 await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');await view('large');assert(await p.evaluate(()=>prototype.lead.ok));assert.equal(await p.evaluate(()=>prototype.playback.state),'playing');await view('normal');assert.equal(await p.evaluate(()=>prototype.playback.state),'playing');await view('large');
 assert.equal(await p.evaluate(()=>prototype.xml),before.xml);assert.equal(await p.evaluate(()=>localStorage.getItem('music-transpose-library-v1')),before.store);assert.deepEqual(await p.evaluate(()=>history.state),before.route);
 // Capture exactly what is supplied to the print engraver; screen/print share derived music.
 await p.evaluate(()=>{const proto=opensheetmusicdisplay.OpenSheetMusicDisplay.prototype,load=proto.load;proto.load=function(xml,...args){if(this.container.id==='print-staging')window.printedXML=xml;return load.call(this,xml,...args);};});
 await p.evaluate(()=>prototype.preparePrint());assert.equal(await p.evaluate(()=>printedXML),await p.evaluate(()=>prototype.viewXML));assert.equal(await p.evaluate(()=>new DOMParser().parseFromString(printedXML,'application/xml').querySelectorAll('part').length),1);
 await view('pdf');assert.equal(await p.evaluate(()=>prototype.playback.state),'stopped');await view('large');assert(await p.evaluate(()=>prototype.lead.ok));assert.equal(await p.evaluate(()=>prototype.current),2);assert.equal(await p.evaluate(()=>prototype.xml),before.xml);assert.equal(await p.evaluate(()=>prototype.song),'hhc-1054');assert.equal(await p.evaluate(()=>localStorage.getItem('music-transpose-library-v1')),before.store);
 await p.locator('#songs').click();assert.equal(await p.locator('#library-list').inputValue(),'lead-check');assert(await p.locator('#library').isVisible());
 console.log('PASS active List/Favorite/key/session, Lead/PDF/Normal switching and exact Lead print source');
 await p.getByRole('button',{name:'Open score: When I Am Baptized',exact:true}).click();await ready();await view('large');await p.locator('#settings').click();await p.locator('input[name=navigation][value=pages]').check();await p.locator('#close-settings').click();
 const pages=await p.locator('.mxl-page-frame').count();assert(pages>1);const r=await p.evaluate(async()=> (await import('./score-taps.js')).scoreTapGeometry());await p.touchscreen.tap(r.left+r.width*.8,r.top+r.height*.65);assert.equal(await p.locator('#page-position').textContent(),`2 / ${pages}`);await p.locator('#score-tap-zones').click();await p.keyboard.press('Escape');assert.equal(await p.locator('#page-position').textContent(),`2 / ${pages}`);
 await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await ready();assert(await p.evaluate(()=>prototype.lead.ok));await p.evaluate(()=>prototype.changeKey(-2));await ready();assert.equal(await p.evaluate(()=>prototype.current),-2);assert(await p.evaluate(()=>prototype.lead.ok));
 console.log('PASS Lead touch navigation, overlay and offline reload/transposition');
}finally{await b.close();}
