import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),b=await chromium.launch({channel:'msedge',headless:true});
const hymn='song-e1cfcf58-9d20-4563-be05-856e4e8d936a',sequence=['cs-168','nativity',hymn],favorites=['cs-168','nativity',hymn];
try{for(const [width,height] of [[320,568],[390,844],[844,390],[820,1180],[1440,1000]]){
 const c=await b.newContext({viewport:{width,height},hasTouch:width<1000}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(({sequence,favorites})=>{if(!localStorage.getItem('filter-seed')){localStorage.setItem('filter-seed','1');localStorage.setItem('music-transpose-library-v1',JSON.stringify({orderingVersion:1,favorites,groups:[{id:'test',name:'Prelude',songs:sequence}]}));localStorage.setItem('music-transpose-library-preferences-v1',JSON.stringify({favoritesFirst:true}));}},{sequence,favorites});
 await p.goto(process.env.TEST_URL||'http://127.0.0.1:8771/');await p.locator('.library-row').first().waitFor();
 const ids=()=>p.locator('.library-row').evaluateAll(es=>es.map(e=>e.dataset.song)),toggle=async id=>{if(await p.locator('#library-filter-menu').isHidden())await p.locator('#library-filter').click();await p.locator(id).click();await p.keyboard.press('Escape');},source=async id=>{await p.locator('#library-source').click();await p.locator(`[data-source="${id}"]`).click();},ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');
 const catalog=await p.evaluate(async()=>{const {songs,supportsLead}=await import('./catalog.js');return songs.map(s=>({id:s.id,lead:supportsLead(s)}));}),leadIds=catalog.filter(s=>s.lead).map(s=>s.id);const initial=await ids();assert.equal(initial.length,catalog.length);assert.equal(new Set(initial).size,initial.length);
 await toggle('#view-favorites');assert.deepEqual(await ids(),initial.filter(id=>favorites.includes(id)));await toggle('#view-lead-sheets');assert.deepEqual(await ids(),initial.filter(id=>favorites.includes(id)&&leadIds.includes(id)));assert.equal(await p.locator('#view-lead-sheets').textContent(),`Lead sheets (${leadIds.length})`);assert(await p.locator('#library-filter').evaluate(e=>e.classList.contains('filters-active')));
 await toggle('#view-favorites');assert.deepEqual(await ids(),initial.filter(id=>leadIds.includes(id)));await source('hymnal');assert((await ids()).includes(hymn));await toggle('#view-favorites');assert.deepEqual(await ids(),[hymn]);await source('children');assert.deepEqual(await ids(),['cs-168']);
 await source('list:test');assert.deepEqual(await ids(),sequence.filter(id=>leadIds.includes(id)));assert.equal(await p.locator('#order-toggle').inputValue(),'manual');await p.locator('#library-search').fill('Missionary');assert.deepEqual(await ids(),['cs-168']);await p.locator('#library-clear').click();
 await p.locator('[data-song="cs-168"] .song-entry').click();await ready();await p.locator('#score-size').click();assert(await p.locator('#score-size-options [data-size=large]').isVisible());await p.keyboard.press('Escape');await p.locator('#songs').click();assert.equal(await p.locator('#library-source-label').textContent(),'Prelude');assert.deepEqual(await ids(),sequence.filter(id=>leadIds.includes(id)));assert.equal(await p.locator('#view-lead-sheets').getAttribute('aria-checked'),'true');
 await p.locator('[data-song="cs-168"] [title=Lyrics]').click();await p.locator('#lyrics-view').waitFor({state:'visible'});await p.locator('#songs').click();assert.deepEqual(await ids(),sequence.filter(id=>leadIds.includes(id)));assert.notEqual(await p.evaluate(()=>document.activeElement.id),'library-search');
 await p.locator('#order-toggle').selectOption('title');await p.locator('#order-toggle').selectOption('manual');assert.deepEqual(await ids(),sequence.filter(id=>leadIds.includes(id)));await p.locator('#edit-list-order').click();assert.deepEqual(await ids(),sequence);await p.locator('#edit-list-order').click();assert.deepEqual(await ids(),sequence.filter(id=>leadIds.includes(id)));
 await p.locator('[data-song="cs-168"] .favorite').click();assert.deepEqual(await ids(),[hymn]);await toggle('#view-favorites');await p.locator('[data-song="cs-168"] .favorite').click();await toggle('#view-favorites');assert.deepEqual(await ids(),sequence.filter(id=>leadIds.includes(id)));
 await p.locator('#library-filter').focus();await p.keyboard.press('Enter');await p.keyboard.press('ArrowDown');assert.equal(await p.evaluate(()=>document.activeElement.id),'view-lead-sheets');const menu=await p.locator('#library-filter-menu').boundingBox();assert(menu.x>=0&&menu.x+menu.width<=width&&menu.y+menu.height<=height);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const controls=await p.locator('.library-filter-row').evaluate(e=>[...e.children].map(x=>x.getBoundingClientRect().top));assert(controls.every(y=>Math.abs(y-controls[0])<2));await p.screenshot({path:`test-results/library-filters-${width}.png`});await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'library-filter');
 await p.locator('#library-more').click();assert.deepEqual(await p.locator('#library-more-dialog button').allTextContents(),['Files / My Music','Import music']);await p.locator('#view-files').click();await p.locator('#files-library').click();assert.deepEqual(await ids(),sequence.filter(id=>leadIds.includes(id)));await p.locator('#library-more').click();await p.locator('#library-import').click();await p.locator('#music-import').waitFor({state:'visible'});await p.locator('#close-import').click();
 assert.deepEqual(await p.evaluate(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1')).groups[0].songs),sequence);
 if(width===390){await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await p.locator('.library-row').first().waitFor();assert.deepEqual(await ids(),sequence);await toggle('#view-favorites');await toggle('#view-lead-sheets');assert.deepEqual(await ids(),sequence.filter(id=>leadIds.includes(id)));await c.setOffline(false);}
 assert.deepEqual(errors,[]);console.log('PASS combined filters, source/list, Score/Lyrics return, order, favorites, utilities, keyboard, responsive',width,height);await c.close();
}}finally{await b.close();}
