import fs from 'node:fs';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {createRequire} from 'node:module';import {songs} from '../songs.js';
const {webkit,chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const base='http://127.0.0.1:8780/',key='music-transpose-library-v1',ids=[84,85,87].map(n=>songs.find(s=>s.collection==='Hymns (1985)'&&s.page===String(n)).id);
const results=[],errors=[],oldIcons=execFileSync('git',['show','9710055:icons.js'],{encoding:'utf8'}),oldLyrics=oldIcons.match(/export const lyricsIcon = `([^`]+)`/)[1];
const saved={orderingVersion:1,favorites:ids,groups:[{id:'polish-list',name:'Sunday',description:'Keep this description',songs:[ids[2],ids[0]],displayNames:{[ids[0]]:'My title'}}],recent:[]};
const engines={phone:await webkit.launch(),desktop:await chromium.launch({channel:'msedge',headless:true})};
async function geometry(p,label){const r=await p.evaluate(label=>{const nav=document.querySelector('.library-quick-access'),r=nav.getBoundingClientRect(),v=visualViewport,s=getComputedStyle(document.querySelector('#library'));return {label,width:innerWidth,height:innerHeight,visibleBottom:v.height+v.offsetTop,inset:s.getPropertyValue('--library-quick-inset'),safe:parseFloat(s.getPropertyValue('--library-quick-safe-bottom'))||0,footer:{top:r.top,bottom:r.bottom,height:r.height},overflow:document.documentElement.scrollWidth>innerWidth,buttons:[...nav.querySelectorAll('button')].map(e=>{const b=e.getBoundingClientRect(),hit=document.elementFromPoint(b.x+b.width/2,b.y+b.height/2);return {id:e.id,left:b.left,bottom:b.bottom,width:b.width,height:b.height,hit:e===hit||e.contains(hit)}})}},label);assert(!r.overflow,label);assert(r.footer.bottom<=r.visibleBottom+.5,label);for(const b of r.buttons){assert(b.width>=44&&b.height>=44,label);assert(b.bottom<=r.visibleBottom-r.safe+.5,label);assert(b.hit,label);}assert(r.buttons[0].left<r.buttons[1].left);results.push(r);}
try{for(const width of [390,430,820,1024,1440]){
 const height=width<600?(width===390?844:932):1180,c=await (width<600?engines.phone:engines.desktop).newContext({viewport:{width,height},hasTouch:width<1024,isMobile:width<600,serviceWorkers:'block'}),p=await c.newPage();p.setDefaultTimeout(60000);p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(({saved,key,height})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(saved));localStorage.setItem('music-transpose-search-fields-v1',JSON.stringify(['title','page']));window.testViewport={height,offsetTop:0,scale:1};for(const k of ['height','offsetTop','scale'])Object.defineProperty(visualViewport,k,{configurable:true,get:()=>testViewport[k]});},{saved,key,height});
 await p.goto(base);assert.deepEqual(await p.locator('#library-home nav>button').evaluateAll(es=>es.slice(-2).map(e=>e.id)),['home-lists','home-files']);assert.equal(await p.locator('.library-quick-access').isVisible(),false);
 if([390,820,1440].includes(width))await p.screenshot({path:`test-results/library-polish-home-${width}.png`});
 await p.locator('[data-home-source=hymnal]').click();await p.locator('#order-toggle').selectOption('number');await geometry(p,width+'-full');
 const heights=await p.locator('#library-results .library-row').evaluateAll(es=>es.slice(0,5).map(e=>e.getBoundingClientRect().height));
 await p.locator('#library-quick-lists').click();assert(await p.locator('#lists-view').isVisible());assert(!await p.locator('.library-quick-access').isVisible());await p.locator('#lists-library').click();await p.locator('[data-home-source=hymnal]').click();await p.locator('#library-quick-files').click();assert(await p.locator('#files-view').isVisible());assert(!await p.locator('.library-quick-access').isVisible());await p.locator('#files-library').click();await p.locator('[data-home-source=hymnal]').click();
 if(width<600){for(const [h,offset] of [[650,0],[630,20]]){await p.evaluate(({h,offset})=>{Object.assign(testViewport,{height:h,offsetTop:offset});visualViewport.dispatchEvent(new Event('resize'));visualViewport.dispatchEvent(new Event('scroll'));},{h,offset});await p.waitForTimeout(200);await geometry(p,`${width}-reduced-${offset}`);}
 await p.evaluate(()=>document.querySelector('#library').style.setProperty('--library-quick-safe-bottom','34px'));await p.waitForTimeout(200);await geometry(p,width+'-safe34');
 await p.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight));await p.waitForTimeout(200);const last=await p.locator('.library-row').last().boundingBox(),footer=await p.locator('.library-quick-access').boundingBox();assert(last.y+last.height<=footer.y,width+' last row clears footer');
 await p.evaluate(height=>{document.querySelector('#library').style.removeProperty('--library-quick-safe-bottom');Object.assign(testViewport,{height,offsetTop:0});visualViewport.dispatchEvent(new Event('resize'));window.scrollTo(0,0);},height);await p.waitForTimeout(200);}
 assert.deepEqual(await p.locator('#library-results .library-row').evaluateAll(es=>es.slice(0,5).map(e=>e.getBoundingClientRect().height)),heights,'row rhythm unchanged');
 if([390,820,1440].includes(width))await p.screenshot({path:`test-results/library-polish-results-${width}.png`});
 // Confirm Cancel/Escape/backdrop leave favorites intact; confirmation changes only favorites.
 await p.locator('#order-toggle').selectOption('number');await p.locator('#library-search').fill('God');await p.locator('#view-favorites').click();
 const before=await p.evaluate(key=>({state:JSON.parse(localStorage.getItem(key)),preferences:localStorage.getItem('music-transpose-library-preferences-v1'),fields:localStorage.getItem('music-transpose-search-fields-v1'),source:document.querySelector('#library-source-label').textContent,query:document.querySelector('#library-search').value}),key);
 const open=async()=>{await p.locator('#library-more').click();await p.locator('#clear-favorites').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'clear-favorites-cancel');};
 await open();await p.locator('#clear-favorites-cancel').click();assert.deepEqual(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).favorites,key),before.state.favorites);
 await open();await p.keyboard.press('Escape');assert(!await p.locator('#clear-favorites-dialog').isVisible());
 await open();await p.mouse.click(1,1);assert(!await p.locator('#clear-favorites-dialog').isVisible());
 await open();await p.locator('#clear-favorites-confirm').click();assert.equal(await p.locator('#library-message').textContent(),'Favorites cleared.');assert.equal(await p.locator('#library-results .library-row').count(),0);assert.equal(await p.locator('#view-favorites').getAttribute('aria-pressed'),'true');
 const after=await p.evaluate(key=>({state:JSON.parse(localStorage.getItem(key)),preferences:localStorage.getItem('music-transpose-library-preferences-v1'),fields:localStorage.getItem('music-transpose-search-fields-v1'),source:document.querySelector('#library-source-label').textContent,query:document.querySelector('#library-search').value}),key);assert.deepEqual(after,{...before,state:{...before.state,favorites:[]}});await p.waitForFunction(()=>document.activeElement.id==='library-more');
 await p.locator('#library-more').click();assert(!await p.locator('#clear-favorites').isVisible());await p.keyboard.press('Escape');
 // A real reload reads the cleared favorites from the existing browser storage.
 await p.reload();assert.deepEqual(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).favorites,key),[]);assert.deepEqual(await p.evaluate(key=>JSON.parse(localStorage.getItem(key)).groups,key),before.state.groups);if(await p.locator('#library').isVisible())await p.locator('.library-heading .header-home').click();await p.locator('[data-home-source=hymnal]').click();
 await p.locator('#library-search').fill('');await p.locator(`[data-song="${ids[0]}"] .song-entry`).click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!prototype.loading);assert(!await p.locator('.library-quick-access').isVisible());
 const newIcon=await p.locator('#show-lyrics').innerHTML();const bounds=()=>p.locator('.masthead button').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>{const r=e.getBoundingClientRect();return {id:e.id,x:r.x,y:r.y,w:r.width,h:r.height}}));const originalBounds=await bounds();
 await p.locator('#show-lyrics').evaluate((e,svg)=>e.innerHTML=svg,oldLyrics);assert.deepEqual(await bounds(),originalBounds);if([390,820,1440].includes(width))await p.locator('.masthead').screenshot({path:`test-results/lyrics-icon-before-${width}.png`});
 await p.locator('#show-lyrics').evaluate((e,svg)=>e.innerHTML=svg,newIcon);assert.deepEqual(await bounds(),originalBounds);assert.equal(await p.locator('#show-lyrics').getAttribute('aria-label'),'View Lyrics');assert.equal(await p.locator('#show-lyrics').getAttribute('title'),'View Lyrics');const icon=await p.locator('#show-lyrics svg').evaluate(e=>({w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height,stroke:getComputedStyle(e).strokeWidth}));assert.deepEqual(icon,{w:24,h:24,stroke:'1.7px'});if([390,820,1440].includes(width))await p.locator('.masthead').screenshot({path:`test-results/lyrics-icon-after-${width}.png`});
 await p.locator('#show-lyrics').click();await p.locator('#lyrics-view').waitFor({state:'visible'});assert(!await p.locator('.library-quick-access').isVisible());await p.getByRole('button',{name:'View Score',exact:true}).click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy);assert.deepEqual(await bounds(),originalBounds);
 await c.close();console.log('PASS polish',width);
}
 assert.deepEqual(errors,[]);fs.writeFileSync('test-results/library-polish.json',JSON.stringify({results,errors},null,2));console.log('PASS Home order, quick navigation, safe geometry, clear confirmation/persistence/isolation, icon geometry and Lyrics return');
}finally{await engines.phone.close();await engines.desktop.close();}
