import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {freshLibraryLaunch} from '../library-session.js';
assert(freshLibraryLaunch('navigate',true));assert(freshLibraryLaunch('navigate',false));assert(!freshLibraryLaunch('reload',true));assert(!freshLibraryLaunch('back_forward',true));assert(freshLibraryLaunch('reload',false));
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE||'C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright'),b=await chromium.launch({channel:'msedge',headless:true});
try{for(const [width,height] of [[820,1180],[1440,1000],[390,844]]){
const c=await b.newContext({viewport:{width,height},serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await c.addInitScript(()=>{if(!localStorage.getItem('home-test-seed')){localStorage.setItem('home-test-seed','1');localStorage.setItem('music-transpose-library-preferences-v1',JSON.stringify({source:'children',order:'number'}));localStorage.setItem('music-transpose-library-v1',JSON.stringify({orderingVersion:1,favorites:['hhc-1035'],groups:[{id:'stale',name:'Christmas',songs:['hhc-1035']}]}));localStorage.setItem('music-transpose-list-workspace-v1',JSON.stringify({activeList:'stale',contexts:[['stale',{query:'Christmas',source:'children',sort:'title',scroll:800,favoritesOnly:true,leadOnly:true}]]}));localStorage.setItem('music-transpose-test-preference','keep');}});
const base='http://127.0.0.1:8780/';await p.goto(base);await p.locator('#library-home').waitFor({state:'visible'});await p.waitForFunction(()=>window.prototype&&document.querySelector('#library-home-title')===document.activeElement);
assert(await p.locator('#library').isHidden());assert.deepEqual(await p.locator('#library-home nav button').evaluateAll(es=>es.map(e=>e.getAttribute('aria-label'))),['All Music','Children’s Songbook','Hymns for Home and Church','Hymns (1985)','Files','Lists']);
const geometry=await p.locator('#library-home').evaluate(e=>({gradient:getComputedStyle(e.querySelector('header')).backgroundImage,overflow:document.documentElement.scrollWidth>innerWidth,rows:[...e.querySelectorAll('nav button')].map(b=>{const r=b.getBoundingClientRect();return {x:r.x,w:r.width,h:r.height};})}));assert.match(geometry.gradient,/linear-gradient/);assert(!geometry.overflow);assert(geometry.rows.every(r=>r.h>=60&&r.x===geometry.rows[0].x&&r.w===geometry.rows[0].w));await p.screenshot({path:`test-results/library-home-${width}.png`});
const home=()=>p.locator('#library .header-home').click();const source=()=>p.locator('#library-source-label').textContent();
await p.locator('[data-home-source=all]').click();assert.equal(await source(),'All Sources');assert.equal(await p.locator('#library-search').inputValue(),'');assert.equal(await p.locator('#order-toggle').inputValue(),'number');assert.equal(await p.locator('#view-favorites').getAttribute('aria-checked'),'false');assert.equal(await p.locator('#view-lead-sheets').count(),0);assert((await p.locator('.library-row').count())>600);
for(const [id,label] of [['children','Children’s Songs'],['home-church','Hymns for Home and Church'],['hymnal','Hymns']]){await home();await p.locator(`[data-home-source="${id}"]`).click();assert.equal(await source(),label);assert(await p.locator('.library-row').count()>0);}
await home();await p.locator('#home-files').click();await p.locator('#files-view').waitFor({state:'visible'});assert(await p.locator('[data-file=scripture-power]').count());assert(await p.locator('[data-file=choose-to-serve-the-lord]').count());await p.goBack();await p.locator('#library-home').waitFor({state:'visible'});await p.goForward();await p.locator('#files-view').waitFor({state:'visible'});await p.goBack();await p.locator('#home-lists').click();assert.equal(await p.locator('#lists-heading').textContent(),'All Lists');await p.locator('#lists-library').click();assert(await p.locator('#library').isVisible());assert.equal(await source(),'Hymns');
if(width===820){
 await home();await p.locator('[data-home-source=home-church]').click();await p.locator('#library-search').fill('Sabbath');await p.locator('#library-filter').click();await p.locator('#view-favorites').click();await p.keyboard.press('Escape');
 const state=()=>p.evaluate(()=>({source:document.querySelector('#library-source-label').textContent,search:document.querySelector('#library-search').value,sort:document.querySelector('#order-toggle').value,favorites:document.querySelector('#view-favorites').getAttribute('aria-checked'),ids:[...document.querySelectorAll('.library-row')].map(e=>e.dataset.song),scroll:scrollY}));const before=await state();
 await p.reload();await p.locator('#library').waitFor({state:'visible'});assert.deepEqual(await state(),before);await p.locator('[data-song=hhc-1035] .song-entry').click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy);assert(await p.locator('#library-home').isHidden());const snapshot=await p.evaluate(()=>history.state.musicTransposeNavigation.route.songSet.ids);assert.deepEqual(snapshot,before.ids);await p.locator('#songs').click();assert.deepEqual(await state(),before);assert(await p.locator('#library-home').isHidden());
 // A new top-level start URL resets even if the browser retained session storage.
 await p.goto(base);await p.locator('#library-home').waitFor({state:'visible'});await p.locator('[data-home-source=all]').click();assert.equal(await source(),'All Sources');assert.equal(await p.locator('#library-search').inputValue(),'');assert.equal(await p.locator('#view-lead-sheets').count(),0);assert.equal(await p.locator('#order-toggle').inputValue(),'number');assert.equal(await p.evaluate(()=>localStorage.getItem('music-transpose-test-preference')),'keep');
 // New browsing session shares persistent data, but no tab session state/history.
 const saved=await c.storageState(),fresh=await b.newContext({storageState:saved,viewport:{width:820,height:1180},serviceWorkers:'block'}),q=await fresh.newPage();await q.addInitScript(()=>Object.defineProperty(navigator,'standalone',{value:true}));await q.goto(base);await q.locator('#library-home').waitFor({state:'visible'});await q.locator('[data-home-source=all]').click();assert.equal(await q.locator('#order-toggle').inputValue(),'number');assert.equal(await q.locator('#library-search').inputValue(),'');await fresh.close();
}
assert.deepEqual(errors,[]);console.log('PASS Library Home fresh/reload/history/source navigation',width);await c.close();
}}finally{await b.close();}
