import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),b=await chromium.launch({channel:'msedge',headless:true}),base=process.env.TEST_URL||'http://127.0.0.1:8768/',reports=[];
try{for(const [width,height] of [[320,568],[390,844],[430,932],[844,390],[820,1180],[1440,1000]]){
 const c=await b.newContext({viewport:{width,height},hasTouch:width<1000}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');
 const lead=p.locator('#score-size-options [data-size=large]');
 await p.goto(base);await p.locator('.library-row').first().waitFor();
 assert.equal(await p.locator('.lead-entry,[title="Open score"]').count(),0);
 const geometry=await p.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height};},row=document.querySelector('.library-row');return {overflow:document.documentElement.scrollWidth-innerWidth,panel:rect(document.querySelector('.library-header-panel')),heading:rect(document.querySelector('.library-column-headings')),filters:[...document.querySelectorAll('.library-filter-row label')].map(rect),row:rect(row),title:rect(row.querySelector('.song-entry')),lyrics:rect(row.querySelector('.song-view-actions')),star:rect(row.querySelector('.favorite')),headings:document.querySelector('.library-column-headings').textContent};});
 assert(geometry.overflow<=0);assert(geometry.star.width>=44&&geometry.star.height>=44);assert(Math.abs(geometry.row.right-geometry.star.right)<2);assert(geometry.title.right<=geometry.lyrics.x+1&&geometry.lyrics.right<=geometry.star.x+1);assert(geometry.title.width>=geometry.row.width-90);assert.equal(geometry.headings,'Song / ScoreLyrics');
 assert(geometry.filters.every(r=>r.height===44&&r.y===geometry.filters[0].y));assert(geometry.filters.every((r,i)=>i===0||r.x>=geometry.filters[i-1].right));
 if(width<=600||height<=500){assert.equal(geometry.heading.height,0);assert(geometry.panel.height<=96);}else assert(geometry.heading.height>=44);
 await p.locator('#library-more').click();const anchor=await p.locator('#library-more').boundingBox(),menu=await p.locator('#library-more-dialog').boundingBox();assert(menu.y>=anchor.y+anchor.height&&menu.y<=anchor.y+anchor.height+8);assert(menu.x>=0&&menu.x+menu.width<=width);assert(menu.y+menu.height<=height);assert(menu.width<280);assert.equal(await p.locator('#library-more-dialog').evaluate(e=>e.tagName),'DIV');
 await p.screenshot({path:`test-results/library-cleanup-more-${width}.png`});await p.keyboard.press('End');assert.equal(await p.evaluate(()=>document.activeElement.id),'view-lead-sheets');await p.keyboard.press('Escape');assert(await p.locator('#library-more-dialog').isHidden());assert.equal(await p.evaluate(()=>document.activeElement.id),'library-more');await p.locator('#library-more').click();if(width<1000)await p.touchscreen.tap(1,1);else await p.mouse.click(1,1);assert(await p.locator('#library-more-dialog').isHidden());
 await p.locator('#library-source').selectOption('children');await p.locator('#order-toggle').selectOption('number');assert.equal(await p.locator('#library-sort-label').textContent(),'#');await p.locator('#order-toggle').selectOption('title');assert.equal(await p.locator('#library-sort-label').textContent(),'A–Z');await p.locator('#library-source').selectOption('all');
 await p.locator('[data-song=nativity] .song-entry').click();await ready();assert.equal(await p.evaluate(()=>prototype.song),'nativity');await p.locator('#score-size').click();assert(await lead.isHidden());assert.equal(await p.locator('#lead-notice').count(),0);assert(!await p.locator('#playing-view').innerText().then(t=>t.includes('Lead unavailable')));await p.keyboard.press('Escape');
 // An explicit legacy request must resolve to Normal before rendering or saving state.
 await p.evaluate(()=>prototype.loadSong('nativity','large'));await ready();assert.equal(await p.locator('#score-size').getAttribute('data-size'),'normal');assert.equal(await p.evaluate(()=>prototype.xml===prototype.viewXML),true);assert.equal(await p.evaluate(()=>localStorage.getItem('music-transpose-score-size-v1')),'normal');assert(await p.locator('#score-size').isVisible());
 // Reload also repairs a saved Lead preference on an unsupported current song.
 await p.evaluate(()=>localStorage.setItem('music-transpose-score-size-v1','large'));await p.reload();await ready();assert.equal(await p.locator('#score-size').getAttribute('data-size'),'normal');assert(await lead.isHidden());
 await p.evaluate(()=>prototype.loadSong('hhc-1054'));await ready();await p.locator('#score-size').click();assert(await lead.isVisible());await lead.click();await ready();assert(await p.evaluate(()=>prototype.lead.ok));assert(await p.locator('#score-size').isVisible());
 // Moving directly from Lead to an unsupported score cannot hide the View control.
 await p.evaluate(()=>prototype.loadSong('nativity'));await ready();assert(await p.locator('#score-size').isVisible());assert.equal(await p.locator('#score-size').getAttribute('data-size'),'normal');assert(await lead.isHidden());
 if(width===390){
  // Imported scores use their actual source, not the bundled availability index.
  await p.evaluate(async()=>{const {songs,refreshLocalMusic}=await import('./catalog.js'),{unpackMXL}=await import('./music.js'),{addRecord}=await import('./local-music-store.js');for(const id of ['hhc-1054','nativity']){const s=songs.find(s=>s.id===id),xml=unpackMXL(await(await fetch(s.asset)).arrayBuffer());await addRecord({metadata:{...s,id:'local-cleanup-'+id,hash:'cleanup-'+id,title:'Local '+s.title,fileType:'mxl',capability:'Transposable',originalFilename:id+'.mxl'},xml,file:new Blob([xml])});}await refreshLocalMusic();});
  for(const [id,ok] of [['hhc-1054',true],['nativity',false]]){await p.evaluate(id=>prototype.loadSong('local-cleanup-'+id,'large'),id);await ready();assert.equal(await lead.evaluate(e=>!e.hidden),ok);assert.equal(await p.locator('#score-size').getAttribute('data-size'),ok?'large':'normal');}
 }
 await p.locator('#songs').click();assert.notEqual(await p.evaluate(()=>document.activeElement.id),'library-search');await p.screenshot({path:`test-results/library-cleanup-${width}.png`});assert.deepEqual(errors,[]);reports.push({width,height,stickyHeight:geometry.panel.height,titleWidth:geometry.title.width,passed:true});console.log('PASS cleanup columns, far-right Favorite, two-row phones, anchored More, sorting, conditional Lead, legacy fallback',width,height);await c.close();
}fs.writeFileSync('test-results/library-cleanup.json',JSON.stringify(reports,null,2));}finally{await b.close();}
