import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),browser=await chromium.launch({channel:'msedge',headless:true}),results=[];
try{for(const [width,height] of [[320,568],[390,844],[430,932],[844,390],[820,1180],[1440,1000]]){
 const context=await browser.newContext({viewport:{width,height},hasTouch:width<1000}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const sequence=['cs-168','nativity','hhc-1054'];await context.addInitScript(sequence=>{if(!localStorage.getItem('header-seed')){localStorage.setItem('header-seed','1');localStorage.setItem('music-transpose-library-v1',JSON.stringify({orderingVersion:1,favorites:[],groups:[{id:'test',name:'Prelude',songs:sequence}]}));}},sequence);
 const pick=async value=>{await page.locator('#library-source')[width<1000?'tap':'click']();await page.locator(`[data-source="${value}"]`)[width<1000?'tap':'click']();};
 const ids=()=>page.locator('.library-row').evaluateAll(es=>es.map(e=>e.dataset.song));
 const ready=()=>page.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');
 await page.goto(process.env.TEST_URL||'http://127.0.0.1:8771/');await page.locator('.library-row').first().waitFor();
 assert.equal(await page.locator('#library-list').count(),0);await pick('hymnal');assert.equal(await page.locator('#library-source-label').textContent(),'Hymns');await page.locator('#order-toggle').selectOption('number');assert((await page.locator('#library-sort-label').innerText()).includes('Number'));
 const geometry=await page.evaluate(()=>{const label=document.querySelector('#library-source-label'),header=document.querySelector('.library-header-panel');return {clipped:label.scrollWidth>label.clientWidth,overflow:document.documentElement.scrollWidth>innerWidth,height:header.getBoundingClientRect().height};});assert(!geometry.clipped&&!geometry.overflow);if(width<=600||height<500)assert(geometry.height<=100);
 await page.screenshot({path:`test-results/header-${width}.png`});await page.locator('#library-source').click();assert.deepEqual(await page.locator('.source-menu-heading').allTextContents(),['Sources','My Lists']);assert.equal(await page.locator('#library-source-menu hr').count(),2);const menu=await page.locator('#library-source-menu').boundingBox();assert(menu.x>=0&&menu.y>=0&&menu.x+menu.width<=width&&menu.y+menu.height<=height);await page.screenshot({path:`test-results/source-menu-${width}.png`});await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'library-source');
 await pick('home-church');if(width>=700&&height>500)assert(await page.locator('#library-source-label').evaluate(e=>e.scrollWidth<=e.clientWidth));
 await pick('list:test');assert.deepEqual(await ids(),sequence);assert.equal(await page.locator('#order-toggle').inputValue(),'manual');for(const order of ['title','number','manual'])await page.locator('#order-toggle').selectOption(order);assert.deepEqual(await ids(),sequence);
 await page.locator('#library-search').fill('Missionary');assert.deepEqual(await ids(),['cs-168']);await page.locator('#library-clear').click();await page.locator('[data-song=cs-168] .favorite').click();assert.equal(await page.locator('[data-song=cs-168] .favorite').getAttribute('aria-pressed'),'true');
 await page.locator('#edit-list-order').click();await page.locator('[data-song=cs-168] button[aria-label^="Move down"]').click();await page.locator('#edit-list-order').click();const reordered=['nativity','cs-168','hhc-1054'];assert.deepEqual(await ids(),reordered);await page.reload();await page.locator('.library-row').first().waitFor();assert.deepEqual(await ids(),reordered);
 await page.locator('#library-more').click();assert.equal(await page.locator('#library-more-dialog button').last().getAttribute('id'),'view-lead-sheets');await page.locator('#view-lead-sheets').click();assert.deepEqual(await ids(),['cs-168','hhc-1054']);await page.locator('#library-clear').click();
 await pick('edit-lists');await page.locator('#lists-view').waitFor({state:'visible'});await page.locator('.list-overview-entry').filter({hasText:'Prelude'}).click();assert.deepEqual(await ids(),reordered);
 if(width===390){
  await page.locator('[data-song=hhc-1054] .song-entry').click();await ready();await page.locator('#score-size').click();await page.locator('#score-size-options [data-size=large]').click();await ready();await page.locator('#songs').click();assert.deepEqual(await ids(),reordered);assert.equal(await page.locator('#library-source-label').textContent(),'Prelude');
  await page.locator('[data-song=hhc-1054] [title=Lyrics]').click();await page.locator('#lyrics-view').waitFor({state:'visible'});await page.locator('#songs').click();assert.deepEqual(await ids(),reordered);assert.notEqual(await page.evaluate(()=>document.activeElement.id),'library-search');
  await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForFunction(()=>navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await page.locator('.library-row').first().waitFor();assert.deepEqual(await ids(),reordered);await pick('all');assert((await ids()).length>600);await pick('list:test');assert.deepEqual(await ids(),reordered);
 }
 await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));assert(await page.locator('.library-header-panel').evaluate(e=>e.getBoundingClientRect().top>=0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);results.push({width,height,geometry,menu,passed:true});console.log('PASS Library header / menus / manual order / persistence',width,height);await context.close();
}fs.writeFileSync('test-results/library-header.json',JSON.stringify(results,null,2));}finally{await browser.close();}
