import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE||'C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright'),b=await chromium.launch({channel:'msedge',headless:true});
try{for(const [width,height] of [[820,1180],[1440,1000],[390,844]]){
 const c=await b.newContext({viewport:{width,height},serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await c.addInitScript(()=>{if(!localStorage.getItem('lists-polish-seed')){localStorage.setItem('lists-polish-seed','1');localStorage.setItem('music-transpose-library-v1',JSON.stringify({orderingVersion:1,favorites:[],groups:[{id:'practice',name:'Sunday rehearsal with an unusually long descriptive list name for narrow screens',songs:['hhc-1035','cs-138']}]}));}});
 await p.goto('http://127.0.0.1:8780/');await p.locator('[data-home-source=all]').click();await p.locator('.library-row').first().waitFor();
 const overview=async()=>{await p.locator('#library-more').click();await p.locator('#view-lists').click();await p.locator('#lists-view').waitFor({state:'visible'});};const home=()=>p.locator('#lists-view .header-home').click();const store=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1')));const row=()=>p.locator('.list-overview-row[data-list=practice]');
 await overview();assert.equal(await p.locator('#lists-heading').textContent(),'All Lists');assert.equal(await p.locator('#lists-context').textContent(),'1 personal list');assert.equal(await p.locator('#lists-library').count(),0);
 const visual=await p.evaluate(()=>{const h=document.querySelector('.lists-heading'),buttons=[...document.querySelectorAll('#lists-view button')].filter(b=>b.getClientRects().length);return {background:getComputedStyle(h).backgroundImage,overflow:document.documentElement.scrollWidth>innerWidth,targets:buttons.every(b=>{const r=b.getBoundingClientRect();return r.width>=44&&r.height>=44;})};});assert.match(visual.background,/linear-gradient/);assert(!visual.overflow&&visual.targets);await p.locator('#lists-view .header-home').focus();assert.equal(await p.locator('#lists-view .header-home').evaluate(e=>getComputedStyle(e).outlineStyle),'none');await p.screenshot({path:`test-results/lists-polish-${width}.png`});
 if(width===820){
 await p.getByRole('button',{name:'New list',exact:true}).click();await p.locator('#list-name-input').fill('New practice');await p.keyboard.press('Enter');await p.locator('#list-name-dialog').waitFor({state:'hidden'});assert(await p.locator('#lists-view').isVisible());assert.equal(await p.locator('#lists-context').textContent(),'2 personal lists');const created=(await store()).groups.find(g=>g.name==='New practice');assert(created);assert.equal(await p.locator(`[data-list="${created.id}"] .list-overview-entry span`).textContent(),'0 songs');assert.equal(await p.locator('#library-source-label').textContent(),'All Sources');
 await p.getByRole('button',{name:'Rename list: New practice',exact:true}).click();await p.locator('#list-name-input').fill('Cancelled');await p.keyboard.press('Escape');assert((await store()).groups.some(g=>g.name==='New practice'));await p.getByRole('button',{name:'Rename list: New practice',exact:true}).click();await p.locator('#list-name-input').fill('Evening practice');await p.keyboard.press('Enter');await p.locator('#list-name-dialog').waitFor({state:'hidden'});await p.reload();await p.locator('#lists-view').waitFor({state:'visible'});assert((await store()).groups.some(g=>g.name==='Evening practice'));
 await p.getByRole('button',{name:'Open list Evening practice',exact:true}).click();assert.match(await p.locator('.empty-library').textContent(),/No songs yet/);await overview();p.once('dialog',d=>{assert.match(d.message(),/Evening practice/);return d.dismiss();});await p.getByRole('button',{name:'Delete list: Evening practice',exact:true}).click();assert.equal((await store()).groups.length,2);p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'Delete list: Evening practice',exact:true}).click();assert.equal((await store()).groups.length,1);assert.equal(await p.locator('#lists-context').textContent(),'1 personal list');
 await row().locator('.list-overview-entry').click();const ids=()=>p.locator('.library-row').evaluateAll(es=>es.map(e=>e.dataset.song));assert.deepEqual(await ids(),['hhc-1035','cs-138']);for(const sort of ['title','number','manual']){await p.locator('#order-toggle').selectOption(sort);assert.deepEqual((await store()).groups[0].songs,['hhc-1035','cs-138']);}assert.deepEqual(await ids(),['hhc-1035','cs-138']);
 // Import one local XML, then use the same list picker and browsing path as bundled songs.
 await p.locator('#library-more').click();await p.locator('#view-files').click();await p.locator('#add-music').click();const xml=await p.evaluate(async()=>{const {unpackMXL}=await import('./music.js');return unpackMXL(await(await fetch('./assets/scores/hhc-1054.mxl')).arrayBuffer());});
 await p.locator('#music-file').setInputFiles({name:'Local list test.musicxml',mimeType:'application/xml',buffer:Buffer.from(xml)});await p.waitForFunction(()=>!document.querySelector('#music-file').disabled);assert(await p.locator('#import-save').isEnabled(),await p.locator('#import-message').textContent());await p.locator('#import-save').click();await p.locator('#music-import').waitFor({state:'hidden'});const local=await p.evaluate(async()=>(await(await import('./local-music-store.js')).localMetadata())[0].id);await p.locator('#files-library').click();await p.locator('#add-list-songs').click();await p.locator(`#list-picker-results input[data-song="${local}"]`).check();await p.locator('#list-picker-done').click();assert((await store()).groups[0].songs.includes(local));await overview();assert.equal(await row().locator('.list-overview-entry span').textContent(),'3 songs');await row().locator('.list-overview-entry').click();await p.locator(`.library-row[data-song="${local}"] .song-entry`).click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy);assert.equal(await p.evaluate(()=>prototype.song),local);await p.locator('#previous-song').click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&prototype.song==='cs-138');await p.locator('#songs').click();await p.locator('#edit-list-order').click();await p.locator(`.library-row[data-song="${local}"]`).getByRole('button',{name:/Remove from list/}).click();assert(!(await store()).groups[0].songs.includes(local));assert(await p.evaluate(async id=>!!await(await import('./local-music-store.js')).localRecord(id),local));await p.locator('#edit-list-order').click();await overview();assert.equal(await row().locator('.list-overview-entry span').textContent(),'2 songs');
 p.once('dialog',d=>d.accept());await row().getByRole('button',{name:/Delete list:/}).click();assert.match(await p.locator('#lists-overview').textContent(),/No lists yet/);assert.equal(await p.locator('#lists-context').textContent(),'0 personal lists');assert(await p.evaluate(async id=>!!await(await import('./local-music-store.js')).localRecord(id),local));
 }
 assert.deepEqual(errors,[]);console.log('PASS Lists overview, accessible layout and focused flows',width);await c.close();
}}finally{await b.close();}
