import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const require=createRequire(process.env.PLAYWRIGHT_PACKAGE),{chromium}=require('playwright');const b=await chromium.launch({channel:'msedge',headless:true}),c=await b.newContext({viewport:{width:820,height:1180},hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
const key='music-transpose-library-v1',saved={orderingVersion:1,favorites:['nativity'],groups:[{id:'existing',name:'Prelude',songs:['nativity','faithful','silent-night','missing-preserved']}],recent:[]};
const state=()=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);const rows=()=>p.locator('#list-songs [data-song]').evaluateAll(es=>es.map(e=>e.dataset.song));const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.getElementById('score').getAttribute('aria-busy')==='false');
try{await p.goto(process.env.TEST_URL||'http://127.0.0.1:8768/');await p.locator('.library-row').first().waitFor();await p.evaluate(({key,saved})=>localStorage.setItem(key,JSON.stringify(saved)),{key,saved});await p.reload();await p.locator('#manage-lists').click();assert(await p.locator('#lists-view').isVisible());assert.equal(await p.locator('#lists-dialog').count(),0);assert.deepEqual((await state()).groups,saved.groups);await p.locator('[data-list="existing"]').click();assert.deepEqual(await rows(),saved.groups[0].songs);
await p.getByRole('button',{name:'Move down: The Nativity Song',exact:true}).click();assert.deepEqual(await rows(),['faithful','nativity','silent-night','missing-preserved']);
const d=await c.newCDPSession(p),grip=await p.locator('.reorder-grip').first().boundingBox(),target=await p.locator('.list-song-row').nth(2).boundingBox();const touch=(type,x,y)=>d.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x,y}]});await touch('touchStart',grip.x+20,grip.y+20);await touch('touchMove',target.x+20,target.y+target.height-5);await touch('touchEnd');assert.deepEqual(await rows(),['nativity','silent-night','faithful','missing-preserved']);
await p.getByRole('button',{name:'Add songs',exact:true}).click();await p.locator('#list-picker-search').fill('shepherd');await p.locator('#list-picker-results input[data-song="shepherd"]').check();await p.locator('#list-picker-search').fill('scripture');await p.locator('#list-picker-source').selectOption('other');await p.locator('#list-picker-results input').check();await p.locator('#list-picker-done').click();assert.deepEqual((await state()).groups[0].songs,['nativity','silent-night','faithful','missing-preserved','shepherd','scripture-power']);
await p.getByRole('button',{name:'Remove from this list: The Nativity Song',exact:true}).click();assert.deepEqual((await state()).favorites,['nativity']);assert(!(await rows()).includes('nativity'));
await p.locator('summary').click();await p.getByRole('button',{name:'Rename list',exact:true}).click();await p.locator('#list-name-input').fill('Evening Prelude');await p.locator('#list-name-form button[type=submit]').click();assert.equal(await p.locator('#lists-heading').textContent(),'Evening Prelude');assert.equal((await state()).groups[0].id,'existing');
await p.getByRole('button',{name:'Open score: Silent Night',exact:true}).click();await ready();await p.locator('#songs').click();assert.equal(await p.locator('#lists-heading').textContent(),'Evening Prelude');assert(await p.locator('#lists-view').isVisible());
await p.getByRole('button',{name:'Open lyrics: The Shepherd’s Carol',exact:true}).click();await p.locator('#lyrics-view').waitFor({state:'visible'});await p.locator('#lyrics-view').getByRole('button',{name:'Back to list',exact:true}).click();assert(await p.locator('#lists-view').isVisible());
for(const [width,height] of [[390,844],[820,1180],[1180,820],[1440,1000]]){await p.setViewportSize({width,height});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/lists-page-${width}.png`});await p.getByRole('button',{name:'Add songs',exact:true}).click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/lists-picker-${width}.png`});await p.locator('#lists-back').click();}
const expected=(await state()).groups;await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await p.locator('#manage-lists').click();await p.locator('[data-list="existing"]').click();assert.deepEqual((await state()).groups,expected);await p.getByRole('button',{name:'Open score: Scripture Power',exact:true}).click();await ready();await p.locator('#songs').click();
await p.locator('#lists-back').click();await p.getByRole('button',{name:'New list',exact:true}).click();await p.locator('#list-name-input').fill('New practice');await p.locator('#list-name-form button[type=submit]').click();assert.match(await p.locator('#list-songs').textContent(),/No songs yet/);p.on('dialog',d=>d.accept());await p.locator('summary').click();await p.getByRole('button',{name:'Delete list',exact:true}).click();assert.equal((await state()).groups.length,1);assert.deepEqual((await state()).favorites,['nativity']);await p.locator('#lists-library').click();assert(await p.locator('#library').isVisible());assert.equal(await p.locator('.library-row').count(),121);assert.deepEqual(errors,[]);console.log('PASS Lists preserved, CRUD, multiselect across filters, remove isolation, touch/keyboard reorder, missing IDs, Score/Lyrics return, offline PDF, persistence and four layouts');}finally{await b.close();}
