import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE||'C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright'),b=await chromium.launch({channel:'msedge',headless:true});
try{for(const [width,height] of [[820,1180],[390,844],[1440,1000]].filter(([w])=>!process.env.ORDER_TEST_WIDTH||w===Number(process.env.ORDER_TEST_WIDTH))){
 const c=await b.newContext({viewport:{width,height},hasTouch:true,serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await c.addInitScript(()=>{if(!localStorage.getItem('order-seed')){localStorage.setItem('order-seed','1');localStorage.setItem('music-transpose-library-v1',JSON.stringify({favorites:['choose-to-serve-the-lord'],groups:[{id:'a',name:'Primary — Oct 4',description:'Rehearsal',songs:['hhc-1035','cs-138'],displayNames:{'hhc-1035':'Sabbath'}},{id:'b',name:'Christmas Program',songs:['choose-to-serve-the-lord'],displayNames:{'choose-to-serve-the-lord':'Files song'}},{id:'c',name:'Prelude',songs:[]}]}));}});
 await p.goto('http://127.0.0.1:8780/');await p.waitForFunction(()=>document.activeElement.id==='library-home-title');await p.locator('#home-lists').click();
 const section=id=>p.locator(`.list-workspace-section[data-list="${id}"]`),order=id=>section(id).locator('.order-list'),toggle=id=>section(id).locator('.list-overview-entry'),store=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1'))),sequence=async()=>(await store()).groups.map(g=>g.id),groups=async()=>Object.fromEntries((await store()).groups.map(g=>[g.id,g]));
 const original=await groups();assert.deepEqual(await sequence(),['a','b','c']);await toggle('a').click();await toggle('b').click();await order('c').focus();await p.keyboard.press('Enter');assert(await p.locator('#lists-order-done').isVisible());await order('c').press('ArrowUp');assert.deepEqual(await sequence(),['a','c','b']);await order('c').press('ArrowUp');assert.deepEqual(await sequence(),['c','a','b']);assert.match(await p.locator('#lists-status').textContent(),/position 1 of 3/);assert(await section('c').getByRole('button',{name:'Move list up: Prelude',exact:true}).isDisabled());
 // Header-based drop hit testing works with expanded Lists and never selects nested song rows.
 const drag=async(from,to,before,touch=false)=>{const f=await order(from).boundingBox(),r=await section(to).locator('.list-overview-row').boundingBox(),x=f.x+22,y=f.y+22,end=r.y+(before?4:r.height-4);if(touch){const client=await c.newCDPSession(p);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=8;i++)await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y+(end-y)*i/8}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await client.detach();}else{await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x,end,{steps:8});await p.mouse.up();}};
 await drag('a','b',false);await p.waitForFunction(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1')).groups.map(g=>g.id).join(',')==='c,b,a');
 if(width===390){await drag('c','b',false,true);await p.waitForFunction(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1')).groups.map(g=>g.id).join(',')==='b,c,a');}else{await section('c').getByRole('button',{name:'Move list down: Prelude',exact:true}).click();assert.deepEqual(await sequence(),['b','c','a']);}
 assert.deepEqual(await groups(),original);assert.deepEqual((await store()).favorites,['choose-to-serve-the-lord']);assert.equal(await toggle('a').getAttribute('aria-expanded'),'true');assert.equal(await toggle('b').getAttribute('aria-expanded'),'true');assert.equal(await toggle('c').getAttribute('aria-expanded'),'false');
 const geometry=await p.locator('#lists-overview').evaluate(h=>({overflow:document.documentElement.scrollWidth>innerWidth,targets:[...h.querySelectorAll('.order-list,.edit-list')].every(e=>{const r=e.getBoundingClientRect();return r.width>=44&&r.height>=44;}),after:[...h.querySelectorAll('.list-overview-row')].every(r=>r.lastElementChild.classList.contains('order-list'))}));assert(!geometry.overflow&&geometry.targets&&geometry.after);await p.screenshot({path:`test-results/lists-order-${width}.png`});
 await p.locator('#lists-order-done').click();await p.reload();await p.locator('#lists-view').waitFor({state:'visible'});assert.deepEqual(await sequence(),['b','c','a']);assert.deepEqual(await p.locator('.list-workspace-section').evaluateAll(es=>es.map(e=>e.dataset.list)),['b','c','a']);assert.equal(await toggle('a').getAttribute('aria-expanded'),'true');
 if(width===820){
  await section('a').locator('.edit-list').click();await p.locator('#list-name-input').fill('Primary next Sunday');await p.locator('#list-name-form button[type=submit]').click();await p.locator('#list-name-dialog').waitFor({state:'hidden'});assert.deepEqual(await sequence(),['b','c','a']);assert.equal((await groups()).a.description,'Rehearsal');
  const song=id=>section('a').locator(`[data-song="${id}"]`);await song('hhc-1035').locator('.order-song').click();await song('hhc-1035').locator('.order-song').press('ArrowDown');assert.deepEqual((await groups()).a.songs,['cs-138','hhc-1035']);assert.deepEqual(await sequence(),['b','c','a']);assert.deepEqual((await groups()).b,original.b);assert.equal((await groups()).a.displayNames['hhc-1035'],'Sabbath');const handle=await song('hhc-1035').locator('.order-song').boundingBox(),target=await song('cs-138').boundingBox();await p.mouse.move(handle.x+22,handle.y+22);await p.mouse.down();await p.mouse.move(handle.x+22,target.y+4,{steps:8});await p.mouse.up();await p.waitForFunction(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1')).groups.find(g=>g.id==='a').songs[0]==='hhc-1035');assert.deepEqual(await sequence(),['b','c','a']);await song('hhc-1035').locator('.order-song').press('ArrowDown');await section('a').locator('.workspace-edit-order').click();
  await song('cs-138').locator('.workspace-song-entry').click();await p.waitForFunction(()=>prototype.song==='cs-138'&&prototype.ready&&!prototype.busy);assert.deepEqual(await p.evaluate(()=>history.state.musicTransposeNavigation.route.songSet.ids),['cs-138','hhc-1035']);await p.locator('#next-song').click();await p.waitForFunction(()=>prototype.song==='hhc-1035'&&prototype.ready&&!prototype.busy);await p.locator('#songs').click();assert.deepEqual(await sequence(),['b','c','a']);
  await p.locator('#lists-library').click();await p.locator('#library-source').click();await p.locator('[data-source="list:a"]').click();for(const sort of ['title','number'])await p.locator('#order-toggle').selectOption(sort);assert.deepEqual(await sequence(),['b','c','a']);assert.deepEqual((await groups()).a.songs,['cs-138','hhc-1035']);await p.locator('#library-more').click();await p.locator('#view-lists').click();
  await p.getByRole('button',{name:'New list',exact:true}).click();await p.locator('#list-name-input').fill('Most relevant');await p.locator('#list-name-input').press('Enter');await p.locator('#list-name-dialog').waitFor({state:'hidden'});const created=(await store()).groups[0];assert.equal(created.name,'Most relevant');assert.equal(await p.locator('.list-workspace-section').first().getAttribute('data-list'),created.id);assert.equal(await toggle(created.id).getAttribute('aria-expanded'),'true');assert.deepEqual((await sequence()).slice(1),['b','c','a']);
  await toggle('c').click();p.once('dialog',d=>d.accept());await section('c').locator('.workspace-delete').click();assert.deepEqual(await sequence(),[created.id,'b','a']);assert.deepEqual((await groups()).b,original.b);await p.reload();await p.locator('#lists-view').waitFor({state:'visible'});assert.deepEqual(await sequence(),[created.id,'b','a']);
 }
 assert.deepEqual(errors,[]);console.log('PASS independent persistent List/song order, pointer/keyboard and geometry',width);await c.close();
}}finally{await b.close();}
