import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium,webkit}=createRequire(process.env.PLAYWRIGHT_PACKAGE||'C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const base=process.env.APP_URL||'http://127.0.0.1:8780/';
const seed=[{id:'a',name:'Practice',description:'Rehearsal notes',songs:['faithful','silent-night'],displayNames:{faithful:'Opening hymn'}},{id:'b',name:'Christmas',description:'Keep B',songs:['nativity'],displayNames:{}},{id:'c',name:'Prelude',description:'',songs:[],displayNames:{}},{id:'d',name:'Closing',description:'',songs:['silent-night'],displayNames:{}}];
for(const [engine,width] of [[chromium,390],[chromium,820],[chromium,1440],[webkit,390],[webkit,820]]){
 const touch=width<1000&&engine===chromium,b=await engine.launch(engine===chromium?{channel:'msedge'}:{});
 try{const c=await b.newContext({viewport:{width,height:1000},hasTouch:width<1000,isMobile:width<1000,serviceWorkers:'block',...(width<1000?{userAgent:width===390?'iPhone':'iPad'}:{})});await c.addInitScript(seed=>{if(!localStorage.getItem('direct-list-seeded')){localStorage.setItem('direct-list-seeded','1');localStorage.setItem('music-transpose-library-v1',JSON.stringify({orderingVersion:1,favorites:['faithful'],groups:seed}));}},seed);
 const p=await c.newPage(),errors=[];p.on('pageerror',e=>{if(!e.message.startsWith('ResizeObserver loop'))errors.push(e.message);});await p.goto(base);await p.locator('#home-footer-lists').click();const card=id=>p.locator(`.list-workspace-section[data-list=${id}]`),handle=id=>card(id).locator('.order-list'),title=id=>card(id).locator('.list-overview-entry');
 const saved=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1'))),ids=async()=>(await saved()).groups.map(g=>g.id),contents=async()=>Object.fromEntries((await saved()).groups.map(g=>[g.id,g]));const original=await contents();const tints=()=>p.locator('.list-workspace-section').evaluateAll(es=>Object.fromEntries(es.map(e=>[e.dataset.list,[e.dataset.listTint,getComputedStyle(e.querySelector('.list-overview-row')).backgroundColor]])));const colors=await tints();
 assert.equal(await p.locator('#lists-order-done,.list-order-actions').count(),0);assert.equal(await p.getByRole('button',{name:/Move list (up|down)/}).count(),0);assert.equal(await p.locator('.order-list').count(),4);assert.equal(await handle('a').evaluate(e=>getComputedStyle(e).touchAction),'none');assert.match(await handle('a').getAttribute('aria-description'),/Arrow Up.*Arrow Down.*Escape/);
 await handle('a').click();assert.equal(await title('a').getAttribute('aria-expanded'),'false');await title('b').click();assert.equal(await title('b').getAttribute('aria-expanded'),'true');await title('b').click();assert.equal(await title('b').getAttribute('aria-expanded'),'false');
 await p.evaluate(()=>{window.orderWrites=0;const write=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='music-transpose-library-v1')orderWrites++;return write.call(this,k,v);};});
 const client=touch?await c.newCDPSession(p):null;
 async function drag(from,to,before,{cancel=null,source=null}={}){
  const h=source||handle(from);await h.scrollIntoViewIfNeeded();const f=await h.boundingBox(),r=await card(to).locator('.list-overview-row').boundingBox(),x=f.x+f.width/2,y=f.y+f.height/2,end=r.y+(before?4:r.height-4);const writes=await p.evaluate(()=>orderWrites),old=await ids();
  if(touch){await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=10;i++)await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y+(end-y)*i/10}]});}else{await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x,end,{steps:10});}
  if(!source){assert.equal(await card(from).evaluate(e=>e.classList.contains('dragging')),true);assert.equal(await p.locator('.list-workspace-section.drop-before,.list-workspace-section.drop-after').count(),1);assert.deepEqual(await ids(),old,'no saved mutation during drag');await p.waitForTimeout(40);assert.notEqual(await card(from).evaluate(e=>e.style.transform),'');}
  if(cancel==='escape')await p.keyboard.press('Escape');if(cancel==='capture')await h.evaluate(e=>{for(let id=1;id<10;id++)if(e.hasPointerCapture(id))e.releasePointerCapture(id);});
  if(touch)await client.send('Input.dispatchTouchEvent',{type:cancel==='pointer'?'touchCancel':'touchEnd',touchPoints:[]});else await p.mouse.up();
  if(cancel||source){await p.waitForTimeout(100);assert.deepEqual(await ids(),old);assert.equal(await p.evaluate(()=>orderWrites),writes);}else{await p.waitForFunction(w=>orderWrites>w,writes);assert.equal(await p.evaluate(()=>orderWrites),writes+1,'one drop saves exactly once');}
  assert.equal(await p.locator('.dragging,.drop-before,.drop-after').count(),0);assert(await p.locator('#lists-view').isVisible());assert.equal(await p.locator('#lists-order-done').count(),0);
 }
 await drag('a','c',false);assert.deepEqual(await ids(),['b','c','a','d']);await drag('a','b',true);assert.deepEqual(await ids(),['a','b','c','d']);
 await drag('a','c',false,{cancel:'escape'});await drag('a','c',false,{cancel:touch?'pointer':'capture'});
 // Ordinary title drags never reorder. A stationary title tap retains accordion behavior.
 await drag('a','c',false,{source:title('a')});if(await title('a').getAttribute('aria-expanded')==='true')await title('a').click();await title('b').click();assert.equal(await title('b').getAttribute('aria-expanded'),'true');await drag('a','c',false);assert.equal(await title('b').getAttribute('aria-expanded'),'true');assert.equal(await title('a').getAttribute('aria-expanded'),'false');assert.equal(await p.locator('.workspace-song-entry:visible').count(),1);
 await handle('a').press('ArrowUp');assert.deepEqual(await ids(),['b','a','c','d']);assert(await handle('a').evaluate(e=>document.activeElement===e));assert.match(await p.locator('#lists-status').textContent(),/position 2 of 4.*saved/);await handle('a').press('ArrowUp');await handle('a').press('ArrowUp');assert.deepEqual(await ids(),['a','b','c','d']);await handle('a').press('ArrowDown');assert.deepEqual(await ids(),['b','a','c','d']);
 assert.deepEqual(await contents(),original);assert.deepEqual(await tints(),colors);assert.deepEqual((await saved()).favorites,['faithful']);await p.reload();await p.locator('#lists-view').waitFor();assert.deepEqual(await ids(),['b','a','c','d']);assert.deepEqual(await contents(),original);assert.deepEqual(await tints(),colors);
 await title('a').click();await card('a').locator('[data-song=faithful] .workspace-song-entry').click();await p.waitForFunction(()=>prototype.song==='faithful'&&prototype.ready&&!prototype.busy&&!prototype.loading);await p.locator('#songs').click();await p.locator('#lists-view').waitFor();assert.equal(await p.locator('.list-overview-entry[aria-expanded=true]').count(),0);assert.deepEqual(await ids(),['b','a','c','d']);assert.deepEqual(await contents(),original);
 assert(await p.locator('.order-list').evaluateAll(es=>es.every(e=>{const r=e.getBoundingClientRect();return r.width>=44&&r.height>=44;})));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/direct-list-order-${engine===webkit?'webkit':'edge'}-${width}.png`});// Long pages auto-scroll only during a handle drag; cancelling after scrolling still saves nothing.
 await p.evaluate(()=>{const key='music-transpose-library-v1',state=JSON.parse(localStorage.getItem(key));state.groups.push(...Array.from({length:14},(_,i)=>({id:'extra-'+i,name:'Extra '+i,description:'',songs:[],displayNames:{}})));localStorage.setItem(key,JSON.stringify(state));});await p.reload();await p.locator('#lists-view').waitFor();await p.evaluate(()=>scrollTo(0,0));const longOrder=await ids(),start=await handle('b').boundingBox(),x=start.x+22,y=start.y+22;
 if(touch){await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:984}]});}else{await p.mouse.move(x,y);await p.mouse.down();await p.mouse.move(x,984,{steps:10});}
 await p.waitForFunction(()=>scrollY>100);if(touch)await client.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});else{await p.keyboard.press('Escape');await p.mouse.up();}await p.waitForTimeout(100);assert.deepEqual(await ids(),longOrder);assert.equal(await p.locator('.dragging,.drop-before,.drop-after').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS',engine===webkit?'WebKit mouse':'Edge '+(touch?'native touch':'mouse'),width,'direct drop, cancel/auto-scroll, title/expanded-song protection, one save, reload, keyboard/focus/announcements, stable content/colors, collapsed Score return');await c.close();
 }finally{await b.close();}
}
