import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),browser=await chromium.launch({channel:'msedge',headless:true}),base=process.env.TEST_URL||'http://127.0.0.1:8768/',results=[];
try{for(const [width,height] of [[320,568],[390,844],[430,932],[844,390],[820,1180],[1440,1000]]){
 const touch=width<1000,c=await browser.newContext({viewport:{width,height},hasTouch:touch}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await c.addInitScript(()=>{if(!localStorage.getItem('lyrics-cleanup-seed')){localStorage.setItem('lyrics-cleanup-seed','1');localStorage.setItem('music-transpose-library-v1',JSON.stringify({favorites:['nativity'],groups:[{id:'rehearsal',name:'Sunday rehearsal',songs:['hhc-1054','nativity','hhc-1010']}]}));localStorage.setItem('music-transpose-lyrics-fun-v1',JSON.stringify({enabled:true,count:2}));}});
 const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');
 const lyrics=()=>p.locator('#lyrics-view').waitFor({state:'visible'}),stop=p.locator('.lyrics-footer .lyrics-fun-stop');
 const point=()=>p.locator('.lyrics-hold-target').evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x+12,y:r.y+Math.min(15,r.height/2)};});
 const session=touch?await c.newCDPSession(p):null;
 const down=async pt=>touch?session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pt]}):(await p.mouse.move(pt.x,pt.y),p.mouse.down());
 const up=()=>touch?session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]}):p.mouse.up();
 const hold=async()=>{await p.locator('.lyrics-hold-target').scrollIntoViewIfNeeded();const pt=await point();await down(pt);await p.waitForTimeout(2100);await up();};
 const context=()=>p.evaluate(()=>({source:document.querySelector('#library-source-label').textContent,sort:document.querySelector('#order-toggle').value,query:document.querySelector('#library-search').value,store:(({favorites,groups})=>({favorites,groups}))(JSON.parse(localStorage.getItem('music-transpose-library-v1')))}));
 await p.goto(base);await p.locator('.library-row').first().waitFor();await p.evaluate(()=>window.sharedLibraryControl=document.querySelector('#songs'));
 await p.locator('#library-source').click();await p.locator('[data-source="list:rehearsal"]').click();await p.locator('#library-search').fill('Nativity');await p.locator('#order-toggle').selectOption('number');const expected=await context();
 await p.locator('[data-song=nativity] [title=Lyrics]').click();await lyrics();assert.equal(await p.evaluate(()=>prototype.ready),false);assert.equal(await p.locator('.lyrics-fun-layer').count(),0,'old enabled preference must not silently start Fun');assert(await stop.isHidden());assert.equal(await p.locator('#songs').count(),1);assert(await p.evaluate(()=>document.querySelector('#songs')===sharedLibraryControl));assert.equal(await p.locator('.lyrics-top > button').count(),0);assert(!/\b(Game|Fun)\b/.test(await p.locator('#lyrics-view').innerText()));
 const libraryBox=await p.locator('#songs').boundingBox();assert(libraryBox.x<=16&&libraryBox.y>height-80&&libraryBox.width>=(width<=360?40:44)&&libraryBox.height>=44);assert.equal(await p.locator('#songs').getAttribute('aria-label'),'Back to list');const svg=await p.locator('#songs').innerHTML();
 const text=await p.locator('.lyrics-body').textContent();await p.getByRole('button',{name:'Use light background',exact:true}).click();await p.getByRole('button',{name:'Lyrics font size: Medium',exact:true}).click();
 // A short title press, a drag, cancellation, and scroll must never activate Fun.
 let pt=await point();await down(pt);await p.waitForTimeout(150);await up();await p.waitForTimeout(2100);assert.equal(await p.locator('.lyrics-fun-layer').count(),0);
 pt=await point();await down(pt);if(touch){await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:pt.x,y:pt.y+35}]});}else await p.mouse.move(pt.x+35,pt.y);await p.waitForTimeout(2100);await up();assert.equal(await p.locator('.lyrics-fun-layer').count(),0);
 await p.locator('.lyrics-hold-target').evaluate(e=>{e.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,isPrimary:true,button:0,pointerId:88,clientX:50,clientY:100}));e.dispatchEvent(new PointerEvent('pointercancel',{bubbles:true,pointerId:88}));});await p.waitForTimeout(2100);assert.equal(await p.locator('.lyrics-fun-layer').count(),0);
 await hold();await p.locator('.lyrics-fun-layer').waitFor();assert(await stop.isVisible());assert.equal(await p.locator('.lyrics-fun-note').count(),2);assert.equal(await p.locator('.lyrics-body').textContent(),text);const stopBox=await stop.boundingBox();assert(stopBox.height>=44&&stopBox.width>=100&&stopBox.y+stopBox.height<=height);
 if(width===390){await hold();await p.locator('.fun-settings select').selectOption('3');await p.getByRole('button',{name:'Close Fun settings',exact:true}).click();assert.equal(await p.locator('.lyrics-fun-note').count(),3);}
 await p.screenshot({path:`test-results/lyrics-hidden-fun-${width}.png`});await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));const bottom=await p.locator('.lyrics-body').boundingBox(),footer=await p.locator('.lyrics-footer').boundingBox();assert(bottom.y+bottom.height<=footer.y,'last verse can scroll fully above footer');assert(await stop.isVisible());if(touch)await stop.tap();else await stop.click();assert.equal(await p.locator('.lyrics-fun-layer').count(),0);assert(await stop.isHidden());assert.equal(await p.locator('.lyrics-body').textContent(),text);assert.equal(await p.locator('#lyrics-view').getAttribute('data-size'),'large');assert(!(await p.locator('#lyrics-view').evaluate(e=>e.classList.contains('lyrics-dark'))));
 await p.locator('.lyrics-score-toggle').click();await ready();assert.equal(await p.evaluate(()=>prototype.song),'nativity');assert(await p.locator('.masthead #songs').isVisible());assert.equal(await p.locator('#songs').innerHTML(),svg);assert(await p.evaluate(()=>document.querySelector('#songs')===sharedLibraryControl));
 await p.evaluate(()=>prototype.changeKey(2));await ready();const score=await p.evaluate(()=>({xml:prototype.xml,key:prototype.current,octave:prototype.octave,song:prototype.song}));await p.locator('#show-lyrics').click();await lyrics();assert.equal(await p.locator('#lyrics-view').getAttribute('data-size'),'large');assert(!(await p.locator('#lyrics-view').evaluate(e=>e.classList.contains('lyrics-dark'))));
 // Keyboard hold is a desktop equivalent, with the same threshold and cleanup.
 await p.locator('.lyrics-hold-target').focus();await p.keyboard.down('Space');await p.waitForTimeout(2100);await p.keyboard.up('Space');assert.equal(await p.locator('.lyrics-fun-layer').count(),1);await p.locator('.lyrics-score-toggle').click();await ready();assert.equal(await p.locator('.lyrics-fun-layer').count(),0);assert.deepEqual(await p.evaluate(()=>({xml:prototype.xml,key:prototype.current,octave:prototype.octave,song:prototype.song})),score);
 await p.locator('#show-lyrics').click();await lyrics();await p.locator('#songs').click();await p.locator('#library').waitFor({state:'visible'});assert.deepEqual(await context(),expected);assert.notEqual(await p.evaluate(()=>document.activeElement.id),'library-search');
 await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await p.locator('.library-row').first().waitFor();assert.deepEqual(await context(),expected);await p.locator('[data-song=nativity] [title=Lyrics]').click();await lyrics();assert.equal(await p.locator('#lyrics-view').getAttribute('data-size'),'large');assert(!(await p.locator('#lyrics-view').evaluate(e=>e.classList.contains('lyrics-dark'))));await hold();assert(await stop.isVisible());await stop.click();assert.equal(await p.locator('.lyrics-fun-layer').count(),0);await p.screenshot({path:`test-results/lyrics-cleanup-${width}.png`});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#songs').click();assert.deepEqual(await context(),expected);assert.deepEqual(errors,[]);
 results.push({width,height,touch,passed:true});console.log('PASS Lyrics shared Library/List state, hidden touch/mouse/keyboard hold, rejection, Stop, appearance, score session, offline',width,height);await c.close();
}fs.writeFileSync('test-results/lyrics-cleanup.json',JSON.stringify(results,null,2));}finally{await browser.close();}
