import {holdLyrics} from './lyrics-hold-helper.mjs';
import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage();
try{await p.clock.install();await p.goto(process.env.TEST_URL||'http://127.0.0.1:8768/');await p.locator('.library-row').first().waitFor();
 await p.evaluate(async()=>{const {attachLyricsHold}=await import('./lyrics-hold.js');const title=document.createElement('h1');title.id='hold-test';title.innerHTML='Heading <button>Playback</button>';document.body.append(title);window.holdCount=0;window.disposeHold=attachLyricsHold(title,()=>holdCount++);window.holdEvent=(type,props={},nested=false)=>(nested?title.querySelector('button'):title).dispatchEvent(new PointerEvent(type,{bubbles:true,isPrimary:true,button:0,pointerId:11,clientX:50,clientY:50,...props}));});
 const event=(type,props={},nested=false)=>p.evaluate(({type,props,nested})=>holdEvent(type,props,nested),{type,props,nested}),count=()=>p.evaluate(()=>holdCount);
 await event('pointerdown');await p.clock.runFor(1999);assert.equal(await count(),0);await p.clock.runFor(1);assert.equal(await count(),1);await p.clock.runFor(3000);assert.equal(await count(),1);await event('pointerup');
 for(const cancel of ['pointerup','pointercancel','lostpointercapture','move','scroll','blur','resize','visibility','second-pointer','playback','dispose']){
  await event('pointerdown',{},cancel==='playback');await p.clock.runFor(1000);
  if(cancel==='move')await event('pointermove',{clientX:60});else if(cancel==='second-pointer')await event('pointerdown',{pointerId:12,isPrimary:false});else if(cancel==='dispose')await p.evaluate(()=>disposeHold());else if(['scroll','blur','resize'].includes(cancel))await p.evaluate(type=>window.dispatchEvent(new Event(type)),cancel);else if(cancel==='visibility')await p.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));else if(cancel!=='playback')await event(cancel);
  await p.clock.runFor(2100);assert.equal(await count(),1,cancel);await event('pointerup');
 }
 await p.reload();await p.locator('.library-row').first().waitFor();await p.locator('[data-song=hhc-1010] [title=Lyrics]').click();await p.locator('#lyrics-view').waitFor({state:'visible'});await holdLyrics(p);await holdLyrics(p);await p.locator('.fun-settings select').selectOption('2');await p.getByRole('button',{name:'Close Fun settings',exact:true}).click();assert.equal(await p.locator('.lyrics-fun-note').count(),2);await p.locator('.lyrics-footer .lyrics-fun-stop').click();await holdLyrics(p);assert.equal(await p.locator('.lyrics-fun-note').count(),2);await holdLyrics(p);await p.locator('.fun-settings').getByRole('button',{name:'Stop Fun',exact:true}).click();assert.equal(await p.locator('.lyrics-fun-layer').count(),0);assert(await p.locator('.fun-settings').isHidden());await p.reload();await p.locator('#lyrics-view').waitFor({state:'visible'});assert.equal(await p.locator('.lyrics-fun-layer').count(),0);await holdLyrics(p);assert.equal(await p.locator('.lyrics-fun-note').count(),2);
 console.log('PASS note-count preference across Stop/re-entry/reload; one-tap exit from hidden settings');
 console.log('PASS exact 2s threshold, single activation, release/cancel/movement/scroll/blur/resize/visibility/multitouch/playback/disposal rejection');
}finally{await b.close();}
