import {createRequire} from 'node:module';import assert from 'node:assert/strict';const require=createRequire(process.env.PLAYWRIGHT_PACKAGE),{chromium}=require('playwright');const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
await page.clock.install();await page.goto(process.env.TEST_URL||'http://127.0.0.1:8767/');await page.locator('.library-row').first().waitFor();
const toggle=()=>page.getByRole('button',{name:'Toggle lyrics fun mode',exact:true});
const open=async id=>{await page.locator(`[data-song="${id}"] .song-view-actions button`).last().click();await page.locator('#lyrics-view').waitFor();};
const tap=async()=>{await page.locator('.lyrics-body p').first().click({position:{x:20,y:20}});};
for(const id of ['hhc-1010','nativity','cs-236']){
await open(id);assert.equal(await toggle().getAttribute('aria-pressed'),'false');assert.equal(await page.locator('.lyrics-fun-layer').count(),0);
assert.equal(await page.locator('#show-lyrics').getAttribute('title'),'Lyrics');assert.equal(await page.locator('#show-lyrics .lyrics-icon').count(),1);const before=await page.locator('.lyrics-body').boundingBox();await toggle().click();await page.clock.runFor(100);assert.equal(await page.locator('.lyrics-fun-note').count(),1);assert.deepEqual(await page.locator('.lyrics-body').boundingBox(),before);assert.equal(await page.locator('.lyrics-fun-note').evaluate(e=>getComputedStyle(e).color),await page.locator('.lyrics-body').evaluate(e=>getComputedStyle(e).color));
await page.clock.fastForward(11000);assert.equal(await page.locator('.lyrics-fun-note').count(),1);
await page.locator('.lyrics-body').evaluate(e=>{e.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:1,isPrimary:true,button:0,clientX:50,clientY:300}));e.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerId:1,isPrimary:true,clientX:50,clientY:350}));e.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:1,isPrimary:true,clientX:50,clientY:350}));});assert.equal(await page.locator('.lyrics-fun-note').count(),1);assert.equal(await page.locator('.lyrics-fun-effect').count(),0);
await page.mouse.wheel(0,100);await page.clock.runFor(200);assert.equal(await page.locator('.lyrics-fun-note').count(),1);
await tap();assert.equal(await page.locator('.lyrics-fun-note').count(),0);assert.equal(await page.locator('.lyrics-fun-effect').count(),1);await page.clock.runFor(401);assert.equal(await page.locator('.lyrics-fun-effect').count(),0);await page.clock.fastForward(4500);assert.equal(await page.locator('.lyrics-fun-note').count(),0);await page.clock.fastForward(5100);assert.equal(await page.locator('.lyrics-fun-note').count(),1);
await page.getByRole('button',{name:'Use light background',exact:true}).click();assert.equal(await page.locator('.lyrics-fun-effect').count(),0);assert.equal(await page.locator('.lyrics-fun-note').count(),1);assert.equal(await page.locator('.lyrics-fun-note').evaluate(e=>getComputedStyle(e).color),await page.locator('.lyrics-body').evaluate(e=>getComputedStyle(e).color));await page.getByRole('button',{name:'Use dark background',exact:true}).click();await page.clock.runFor(100);
await page.getByRole('button',{name:'Open score',exact:true}).click();assert.equal(await page.locator('.lyrics-fun-layer').count(),0);await page.waitForFunction(()=>prototype.ready&&!prototype.busy);await page.locator('#show-lyrics').click();assert.equal(await toggle().getAttribute('aria-pressed'),'false');await toggle().click();await page.getByRole('button',{name:'Return to Library',exact:true}).click();await page.clock.fastForward(11000);assert.equal(await page.locator('.lyrics-fun-layer').count(),0);console.log('PASS tap/drag, one target, interval, theme and view cleanup',id);
}
await open('hhc-1010');await toggle().click();const types=new Set(),sides=new Set();for(let i=0;i<90;i++){await page.clock.runFor(100);types.add(await page.locator('.lyrics-fun-note').getAttribute('data-note-type'));await tap();sides.add(await page.locator('.lyrics-fun-effect').getAttribute('data-origin'));await page.clock.fastForward(10001);}assert.equal(types.size,6);assert.equal(sides.size,2);
for(const [width,height] of [[390,844],[820,1180],[1180,820],[1440,1000]]){await page.setViewportSize({width,height});await page.clock.runFor(100);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const note=await page.locator('.lyrics-fun-note').boundingBox(),layer=await page.locator('.lyrics-fun-layer').boundingBox();assert(note.x>=layer.x&&note.x+note.width<=layer.x+layer.width+1);await page.screenshot({path:`test-results/lyrics-fun-${width}.png`});}
await page.emulateMedia({reducedMotion:'reduce'});await page.clock.runFor(100);const position=await page.locator('.lyrics-fun-note').getAttribute('style');await page.clock.fastForward(3000);assert.equal(await page.locator('.lyrics-fun-note').getAttribute('style'),position);await page.emulateMedia({media:'print'});assert(await page.locator('.lyrics-fun-layer').isHidden());await page.emulateMedia({media:'screen'});await toggle().click();await page.clock.fastForward(11000);assert.equal(await page.locator('.lyrics-fun-layer').count(),0);assert.deepEqual(errors,[]);console.log('PASS six note types, both beam origins, responsive bounds, reduced motion, print and disable cleanup');
}finally{await browser.close();}
