import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {planFlight} from '../lyrics-fun.js';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright');
let upper=0,total=0,mixed=0;const signatures=new Set();
for(let run=0;run<2000;run++){const flights=[];for(let i=0;i<4;i++){const f=planFlight(flights);flights.push(f);upper+=f.upper;total++;assert(f.duration>=18000&&f.duration<=34000);assert(f.delay>=350&&f.delay<=5500);assert(Math.sign(f.endX-f.startX)===f.direction);}if(new Set(flights.map(f=>f.direction)).size===2)mixed++;signatures.add(JSON.stringify(flights));}
assert(upper/total>.75&&upper/total<.85);assert(mixed>1600);assert.equal(signatures.size,2000);console.log('PASS 2000 batches', {upperBias:upper/total,mixedDirections:mixed});
const b=await chromium.launch({channel:'msedge',headless:true}),c=await b.newContext({hasTouch:true}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_URL||'http://127.0.0.1:8768/',pref='music-transpose-lyrics-fun-v1';
const open=async()=>{await p.locator('[data-song="hhc-1010"] .song-view-actions button').last().click();await p.locator('#lyrics-view').waitFor({state:'visible'});};
const panel=()=>p.getByRole('button',{name:'Lyrics Fun settings',exact:true}).click(),done=()=>p.getByRole('button',{name:'Close Fun settings',exact:true}).click();
const library=()=>p.getByRole('button',{name:'Return to Library',exact:true}).click();
const tap=()=>p.locator('.lyrics-paper').evaluate(paper=>{const note=document.querySelector('.lyrics-fun-note:not([hidden])'),r=(note||paper).getBoundingClientRect();for(const type of ['pointerdown','pointerup'])paper.dispatchEvent(new PointerEvent(type,{bubbles:true,isPrimary:true,button:0,pointerId:3,clientX:r.x+r.width/2,clientY:r.y+r.height/2}));});
try{
await p.clock.install();await p.goto(base);await p.locator('.library-row').first().waitFor();await open();await panel();assert(await p.locator('.fun-settings input').isChecked());assert.equal(await p.locator('.fun-settings select').inputValue(),'4');await done();await p.clock.runFor(6000);assert.equal(await p.locator('.lyrics-fun-note:visible').count(),4);
await tap();assert.equal(await p.locator('[data-shot=hit]').count(),1);await p.clock.runFor(301);assert.equal(await p.locator('.lyrics-fun-note:visible').count(),3);assert.equal(await p.locator('.lyrics-fun-note').count(),4);assert.equal(await p.locator('.lyrics-fun-spark').count(),8);await p.clock.runFor(401);assert.equal(await p.locator('.lyrics-fun-effect').count(),0);
await p.locator('.lyrics-body').evaluate(e=>{for(const [type,y] of [['pointerdown',250],['pointermove',300],['pointerup',300]])e.dispatchEvent(new PointerEvent(type,{bubbles:true,isPrimary:true,button:0,pointerId:2,clientX:30,clientY:y}));});assert.equal(await p.locator('.lyrics-fun-effect').count(),0);
await p.clock.runFor(28000);assert.equal(await p.locator('.lyrics-fun-note').count(),0);assert.equal(await p.locator('.lyrics-fun-layer').getAttribute('data-phase'),'worm');await p.clock.runFor(1000);assert.equal(await p.locator('.lyrics-fun-note').count(),0);await tap();assert.equal(await p.locator('.lyrics-fun-effect').count(),1);await p.clock.runFor(301);assert.equal(await p.locator('.lyrics-fun-effect').count(),0);
await panel();await p.locator('.fun-settings input').uncheck();await p.locator('.fun-settings select').selectOption('2');await done();await p.reload();await p.locator('#lyrics-view').waitFor({state:'visible'});await panel();assert(!(await p.locator('.fun-settings input').isChecked()));assert.equal(await p.locator('.fun-settings select').inputValue(),'2');await p.locator('.fun-settings input').check();await done();await p.clock.runFor(6000);assert.equal(await p.locator('.lyrics-fun-note:visible').count(),2);await panel();await p.locator('.fun-settings select').selectOption('4');await done();await p.clock.runFor(6000);assert.equal(await p.locator('.lyrics-fun-note:visible').count(),4);await library();
for(const [w,h] of [[390,844],[820,1180],[1180,820],[1440,1000]]){
 await p.setViewportSize({width:w,height:h});
 for(let run=0;run<3;run++){
  await open();await p.clock.runFor(6000);assert.equal(await p.locator('.lyrics-fun-note:visible').count(),4);
  const before=await p.locator('.lyrics-fun-note').evaluateAll(es=>es.map(e=>e.style.left));await p.clock.runFor(1000);const after=await p.locator('.lyrics-fun-note').evaluateAll(es=>es.map(e=>e.style.left));assert.notDeepEqual(before,after);
  const bounds=await p.locator('.lyrics-fun-layer').boundingBox();assert(bounds.x>=0&&bounds.y>=0&&bounds.x+bounds.width<=w+1&&bounds.y+bounds.height<=h+1);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  if(run===0){await p.screenshot({path:`test-results/fun-random-${w}.png`});for(const name of ['Use light background','Use dark background']){await p.getByRole('button',{name,exact:true}).click();assert.equal(await p.locator('.lyrics-fun-effect').count(),0);assert.equal(await p.locator('.lyrics-fun-note').first().evaluate(e=>getComputedStyle(e).color),await p.locator('.lyrics-body').evaluate(e=>getComputedStyle(e).color));}}
  await library();assert.equal(await p.locator('.lyrics-fun-layer').count(),0);
 }console.log('PASS responsive flights and cleanup',w,h);
}
await open();await p.clock.runFor(6000);await p.emulateMedia({reducedMotion:'reduce'});await p.clock.runFor(100);const styles=await p.locator('.lyrics-fun-note').evaluateAll(es=>es.map(e=>e.getAttribute('style')));await p.clock.runFor(1000);assert.deepEqual(await p.locator('.lyrics-fun-note').evaluateAll(es=>es.map(e=>e.getAttribute('style'))),styles);await p.emulateMedia({media:'print'});assert(await p.locator('.lyrics-fun-layer').isHidden());await p.emulateMedia({media:'screen'});
await p.getByRole('button',{name:'View Score',exact:true}).click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy);assert.equal(await p.locator('.lyrics-fun-layer').count(),0);await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');await p.locator('#show-lyrics').click();assert.equal(await p.evaluate(()=>prototype.playback.state),'playing');await library();assert.equal(await p.evaluate(()=>prototype.playback.state),'stopped');
await open();for(let i=0;i<5;i++){await panel();await p.locator('.fun-settings input').uncheck();assert.equal(await p.locator('.lyrics-fun-layer').count(),0);await p.locator('.fun-settings input').check();assert.equal(await p.locator('.lyrics-fun-layer').count(),1);await done();}await panel();await p.locator('.fun-settings input').uncheck();await done();await library();
await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await p.locator('.library-row').first().waitFor();await open();await panel();assert(!(await p.locator('.fun-settings input').isChecked()));assert.equal(await p.locator('.fun-settings select').inputValue(),'4');await done();assert.equal(await p.locator('.lyrics-fun-layer').count(),0);assert.deepEqual(errors,[]);
console.log('PASS defaults, saved OFF/count, count changes, hits/free fire/scroll safety, finite misses, themes, reduced motion, print, playback/view switching, offline preferences');
}finally{await b.close();}
