import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const engines=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),engine=process.env.WEBKIT?'webkit':'chromium',browser=await engines[engine].launch(engine==='chromium'?{channel:'msedge',headless:true}:{});
try{for(const [width,height] of [[390,844],[768,1024],[820,1180],[1180,820],[1440,1000]]){
 if(process.env.METRONOME_WIDTH&&width!==Number(process.env.METRONOME_WIDTH))continue;
 const c=await browser.newContext({viewport:{width,height},hasTouch:width<1440,serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await c.addInitScript(()=>localStorage.setItem('music-transpose-navigation-v1',JSON.stringify({mode:'pages'})));
 await p.goto(process.env.TEST_URL||'http://127.0.0.1:8780/');await p.locator('.library-row').first().waitFor();
 const ready=async()=>{await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');await p.waitForTimeout(180);};
 const enable=async value=>{await p.locator('#settings').click();await p.locator('#metronome-mode').selectOption(value);await p.locator('#close-settings').click();};
 const shown=()=>p.waitForFunction(()=>document.querySelectorAll('.beat-rail:not([hidden])').length===2);
 const geometry=()=>p.evaluate(()=>({rect:document.querySelector('#score').getBoundingClientRect().toJSON(),padding:getComputedStyle(document.querySelector('#score')).padding,clip:getComputedStyle(document.querySelector('#score')).clipPath,pages:document.querySelectorAll('.mxl-page-frame').length}));
 // Unit cases use the unchanged playback parser, including embedded tempos and pickups.
 const cases=await p.evaluate(async()=>{const {scoreTimeline}=await import('./playback.js'),{pulseState}=await import('./metronome.js');const measure=(beats,unit,tempo,length=beats*4/unit)=>`<measure><attributes><divisions>4</divisions><time><beats>${beats}</beats><beat-type>${unit}</beat-type></time></attributes><direction><sound tempo="${tempo}"/></direction><note><pitch><step>C</step><octave>4</octave></pitch><duration>${length*4}</duration></note></measure>`;
 const rows=[[4,4,4],[3,4,3],[2,4,2],[2,2,2],[6,8,2],[9,8,3],[12,8,4]].map(([beats,unit,count])=>{const t=scoreTimeline('<score-partwise><part id="P">'+measure(beats,unit,60)+measure(beats,unit,120)+'</part></score-partwise>'),step=beats*4/unit/count;return {count,states:[...Array(count).keys()].map(i=>pulseState(t,i*step+.001)).concat([...Array(count).keys()].map(i=>pulseState(t,beats*4/unit+i*step/2+.001))),loop:pulseState(t,t.duration+.001),fast:pulseState(t,.08,2),normal:pulseState(t,.08,1)};});const t=scoreTimeline('<score-partwise><part id="P">'+measure(4,4,60,1)+measure(4,4,60)+'</part></score-partwise>');const mid=scoreTimeline('<score-partwise><part id="P"><measure><attributes><divisions>4</divisions><time><beats>2</beats><beat-type>4</beat-type></time></attributes><direction><sound tempo="60"/></direction><note><pitch><step>C</step><octave>4</octave></pitch><duration>2</duration></note><direction><sound tempo="120"/></direction><note><pitch><step>D</step><octave>4</octave></pitch><duration>6</duration></note></measure></part></score-partwise>');return {rows,pickup:pulseState(t,.001),next:pulseState(t,1.001),mid:pulseState(mid,.76)};});
 for(const row of cases.rows){assert.deepEqual(row.states.map(s=>s.side),row.states.map((_,i)=>i%2?'right':'left'));assert.deepEqual(row.states.map(s=>s.index),row.states.map((_,i)=>i%row.count));assert.deepEqual(row.states.map(s=>s.downbeat),row.states.map((_,i)=>i%row.count===0));assert.equal(row.loop.sequence,row.count*2);assert(Math.abs(row.fast.elapsed*2-row.normal.elapsed)<.00001);}assert.equal(cases.pickup.index,3);assert(!cases.pickup.downbeat);assert.equal(cases.next.side,'right');assert(cases.next.downbeat);assert.equal(cases.mid.index,1);assert(Math.abs(cases.mid.elapsed-.01)<.0001);
 for(const view of ['auto','large']){
  await p.evaluate(()=>prototype.loadSong('song-a13c43da-0243-4019-ad08-d7be530074f5','normal'));await ready();await p.locator('#score-size').click();await p.locator(`#score-size-options [data-size=${view}]`).click();await ready();await enable('off');assert.equal(await p.locator('.beat-rail:visible').count(),0);const before=await geometry();await enable('dots');await shown();assert.deepEqual(await geometry(),before,'metronome causes no score reflow or pagination change');assert.equal(await p.locator('#metronome-mode option[value=dots]').textContent(),'Side pulse');assert.equal(await p.locator('.beat-dot,.beat-rail-top,.beat-rail-bottom').count(),0);
  const g=await p.evaluate(()=>{const r=document.querySelector('#score').getBoundingClientRect(),h=document.querySelector('.score-heading').getBoundingClientRect(),f=document.querySelector('.masthead').getBoundingClientRect();return [...document.querySelectorAll('.beat-rail')].map((e,i)=>{const b=e.getBoundingClientRect();return {width:b.width,height:b.height,inside:b.left>=0&&b.right<=innerWidth,clear:i===0?b.right<=r.left:b.left>=r.right,top:b.top>=Math.max(0,h.bottom,r.top),bottom:b.bottom<=f.top-8,pointer:getComputedStyle(e).pointerEvents,aria:e.getAttribute('aria-hidden')};});});for(const r of g){assert.equal(r.width,4);assert(r.height>100&&r.inside&&r.clear&&r.top&&r.bottom);assert.equal(r.pointer,'none');assert.equal(r.aria,'true');}
  assert.equal(await p.evaluate(()=>prototype.playback.state),'stopped');assert.equal(await p.evaluate(()=>prototype.playback.nodes),0);
  const samples=await p.evaluate(async()=>{const seen=[];for(let i=0;i<150;i++){await new Promise(requestAnimationFrame);const es=[...document.querySelectorAll('.beat-rail')],sequence=Number(es[0].dataset.sequence),op=es.map(e=>Number(e.style.opacity));if(op.some(n=>n>0)&&seen.at(-1)?.sequence!==sequence)seen.push({sequence,side:op[0]>0?'left':'right'});}return seen;});assert(samples.length>=2);for(const s of samples)assert.equal(s.side,s.sequence%2?'right':'left');
  const seq=Number(await p.locator('.beat-rail-left').getAttribute('data-sequence')),page=await p.locator('#page-position').textContent();const tap=await p.evaluate(async()=>(await import('./score-taps.js')).scoreTapGeometry());await p.mouse.click(tap.left+tap.width*.8,tap.top+tap.height*.65);if(before.pages>1)assert.notEqual(await p.locator('#page-position').textContent(),page);else assert.equal(await p.locator('#page-position').textContent(),page,'single-page score stays on its only page');await shown();assert(Number(await p.locator('.beat-rail-left').getAttribute('data-sequence'))>=seq,'page turn never resets clock');
  await p.waitForFunction(()=>Number(document.querySelector('.beat-rail-left').style.opacity)>.3);await p.screenshot({path:`test-results/metronome-side-${engine}-${width}-${view}.png`});await p.locator('#score-tools').click();await p.locator('#score-page-theme').click();assert.equal(await p.locator('.beat-rail-left').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(102, 201, 196)');await p.waitForFunction(()=>Number(document.querySelector('.beat-rail-right').style.opacity)>.3);await p.screenshot({path:`test-results/metronome-side-${engine}-${width}-${view}-dark.png`});await p.locator('#score-tools').click();await p.locator('#score-page-theme').click();
  await p.emulateMedia({reducedMotion:'reduce'});const op=await p.evaluate(async()=>{const values=[];for(let i=0;i<30;i++){await new Promise(requestAnimationFrame);values.push(...[...document.querySelectorAll('.beat-rail')].map(e=>Number(e.style.opacity)));}return values;});assert(op.every(v=>[0,.65,.9].includes(v)));await p.emulateMedia({reducedMotion:'no-preference'});
  if(engine==='chromium'&&width===820){await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');
   const synced=async()=>{const mismatch=await p.evaluate(async()=>{const {pulseState}=await import('./metronome.js');let wrong=0;for(let i=0;i<40;i++){await new Promise(requestAnimationFrame);const beat=pulseState(prototype.playback.timeline,prototype.playback.position,prototype.playback.tempo.rate);if(Number(document.querySelector('.beat-rail-left').dataset.sequence)!==beat.sequence)wrong++;}return wrong;});assert(mismatch<=1,'playback clock synchronization');};await synced();await p.locator('#settings').click();const tempo=await p.evaluate(()=>prototype.playback.tempo.bpm);await p.locator('#tempo-up').click();assert((await p.evaluate(()=>prototype.playback.tempo.bpm))>tempo);await p.locator('#close-settings').click();await synced();await p.locator('#settings').click();await p.locator('#tempo-reset').click();assert.equal(await p.evaluate(()=>prototype.playback.tempo.bpm),await p.evaluate(()=>prototype.playback.tempo.original));await p.locator('#close-settings').click();await synced();
   await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='paused');await p.waitForTimeout(80);const paused=await p.locator('.beat-rail-left').getAttribute('data-sequence');assert(await p.locator('.beat-rail').evaluateAll(es=>es.every(e=>Number(e.style.opacity)===0)));await p.waitForTimeout(200);assert.equal(await p.locator('.beat-rail-left').getAttribute('data-sequence'),paused);await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');await synced();await p.evaluate(()=>prototype.playback.stop());await p.waitForTimeout(80);assert(Number(await p.locator('.beat-rail-left').getAttribute('data-sequence'))<=1);}
  await p.locator('#settings').click();await p.locator('input[name=navigation][value=continuous]').check();await p.locator('#close-settings').click();await p.evaluate(()=>scrollTo(0,400));await p.waitForTimeout(100);assert(await p.locator('.beat-rail').evaluateAll(es=>es.every(e=>{const r=e.getBoundingClientRect(),f=document.querySelector('.masthead').getBoundingClientRect();return r.top>=0&&r.bottom<=f.top-8;})));await p.locator('#settings').click();await p.locator('input[name=navigation][value=pages]').check();await p.locator('#close-settings').click();await shown();
  const rate=await p.evaluate(()=>prototype.playback.tempo.rate);await p.evaluate(()=>prototype.changeKey(1));await ready();await shown();assert.equal(await p.evaluate(()=>prototype.playback.tempo.rate),rate);
  await p.locator('#show-lyrics').click();await p.locator('#lyrics-view').waitFor({state:'visible'});assert.equal(await p.locator('.beat-rail:visible').count(),0);await p.locator('.lyrics-score-toggle').click();await ready();await shown();await p.emulateMedia({media:'print'});assert.equal(await p.locator('.beat-rail:visible').count(),0);await p.emulateMedia({media:'screen'});
  await p.locator('#score-size').click();await p.locator('#score-size-options [data-size=pdf]').click();await ready();assert.equal(await p.locator('.beat-rail:visible').count(),0);await p.locator('#settings').click();assert(await p.locator('#playback-settings').isHidden());await p.locator('#close-settings').click();await p.locator('#songs').click();assert.equal(await p.locator('.beat-rail:visible').count(),0);
 }
 await p.locator('#library-more').click();await p.locator('#view-files').click();await p.locator('#files-view').waitFor({state:'visible'});assert.equal(await p.locator('.beat-rail:visible').count(),0);await p.locator('#files-library').click();await p.locator('#library-source').click();await p.locator('[data-source=edit-lists]').click();await p.locator('#lists-view').waitFor({state:'visible'});assert.equal(await p.locator('.beat-rail:visible').count(),0);
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS peripheral metronome',engine,width,height,'meters/pickup/tempo map, alternating beats, no reflow, page turn, two structured views, PDF unavailable, dark/reduced motion, Lyrics/Library/print hiding',engine==='chromium'&&width===820?'audio tempo/reset/pause/resume/stop':'');await c.close();
}}finally{await browser.close();}
