import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),browser=await chromium.launch({channel:'msedge',headless:true});
try{for(const [width,height] of [[320,568],[390,844],[844,390],[820,1180],[1440,1000]]){
 const c=await browser.newContext({viewport:{width,height},hasTouch:width<1000,reducedMotion:width===320?'reduce':'no-preference'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(15000);await p.goto(process.env.TEST_URL||'http://127.0.0.1:8771/');await p.locator('.library-row').first().waitFor();
 const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!document.body.classList.contains('song-loading')&&document.querySelector('#score').getAttribute('aria-busy')==='false');
 const mode=async value=>{await p.locator('#settings').click();await p.locator(`input[name=navigation][value=${value}]`).check();await p.locator('#close-settings').click();};
 const enable=async value=>{await p.locator('#settings').click();await p.locator('#metronome-mode').selectOption(value);await p.locator('#close-settings').click();};
 const shown=()=>p.waitForFunction(()=>document.querySelectorAll('.beat-rail:not([hidden])').length===2);
 if(width===320){const cases=await p.evaluate(async()=>{const {scoreTimeline}=await import('./playback.js'),{beatState}=await import('./metronome.js');return [[2,4,2],[3,4,3],[4,4,4],[6,8,2],[9,8,3],[12,8,4]].map(([beats,unit,count])=>{const xml=`<score-partwise><part id="P"><measure><attributes><divisions>2</divisions><time><beats>${beats}</beats><beat-type>${unit}</beat-type></time></attributes><direction><sound tempo="60"/></direction><note><pitch><step>C</step><octave>4</octave></pitch><duration>${beats*8/unit}</duration></note></measure></part></score-partwise>`,t=scoreTimeline(xml),step=t.duration/count;return {count,states:Array.from({length:count},(_,i)=>beatState(t,i*step+.01)),duration:t.duration};});});for(const row of cases){assert(row.states.every(s=>s.count===row.count));assert.deepEqual(row.states.map(s=>s.index),Array.from({length:row.count},(_,i)=>i));}console.log('PASS 2/4 3/4 4/4 6/8 9/8 12/8 musical grouping');
 const changes=await p.evaluate(async()=>{const {beatState}=await import('./metronome.js'),{scoreTimeline}=await import('./playback.js');const m=(beats,unit,duration,tempo)=>`<measure><attributes><divisions>2</divisions><time><beats>${beats}</beats><beat-type>${unit}</beat-type></time></attributes><direction><sound tempo="${tempo}"/></direction><note><pitch><step>C</step><octave>4</octave></pitch><duration>${duration}</duration></note></measure>`;const t=scoreTimeline('<score-partwise><part id="P">'+m(6,8,6,60)+m(3,4,6,120)+'</part></score-partwise>');const pickup=scoreTimeline('<score-partwise><part id="P">'+m(4,4,2,60)+'</part></score-partwise>');return {before:beatState(t,1.51),after:beatState(t,3.01),later:beatState(t,3.51),pickup:beatState(pickup,.01)};});assert.equal(changes.before.count,2);assert.equal(changes.before.index,1);assert.equal(changes.after.count,3);assert.equal(changes.after.index,0);assert.equal(changes.later.index,1);assert.equal(changes.pickup.index,3);
}
 await p.evaluate(()=>prototype.loadSong('cs-110'));await ready();assert.equal(await p.locator('.beat-rail:visible').count(),0);assert.equal(await p.locator('#metronome-mode').inputValue(),'off');const xml=await p.evaluate(()=>prototype.xml);await enable('dots');await shown();assert.equal(await p.evaluate(()=>prototype.playback.state),'stopped');assert.equal(await p.evaluate(()=>prototype.playback.nodes),0);
 const before=await p.locator('.beat-rail-top').getAttribute('data-beat');await p.waitForFunction(b=>document.querySelector('.beat-rail-top').dataset.beat!==b,before);
 for(const nav of ['continuous','pages']){await mode(nav);await shown();if(nav==='continuous'){await p.evaluate(()=>scrollTo(0,450));await p.waitForTimeout(150);assert(await p.locator('#return-start-left').isVisible());}
 const geo=await p.evaluate(()=>{const rails=[...document.querySelectorAll('.beat-rail')],r=rails.map(e=>e.getBoundingClientRect().toJSON()),footer=document.querySelector('.masthead').getBoundingClientRect();return {r,same:rails[0].dataset.beat===rails[1].dataset.beat,count:rails[0].children.length,pass:rails.every(e=>getComputedStyle(e).pointerEvents==='none'),footer:footer.top,overflow:document.documentElement.scrollWidth>innerWidth};});assert(geo.same&&geo.pass&&!geo.overflow&&geo.count>0);assert(await p.evaluate(()=>[...document.querySelectorAll('.beat-rail')].every(rail=>{const r=rail.getBoundingClientRect();return !document.elementsFromPoint(r.x+r.width/2,r.y+7).some(e=>e.closest?.('#score svg'));})),'Beat lanes do not paint over notation');assert(geo.r[0].top>=0&&geo.r[0].bottom<geo.r[1].top&&geo.r[1].bottom<=geo.footer+1);await p.screenshot({path:`test-results/metronome-${nav}-${width}.png`});
 if(nav==='pages'){const initial=await p.locator('#page-position').textContent(),g=await p.evaluate(async()=>{const {scoreTapGeometry}=await import('./score-taps.js');return scoreTapGeometry();});await p.mouse.click(g.left+g.width*.8,g.top+g.height*.65);assert.notEqual(await p.locator('#page-position').textContent(),initial);}
 }
 await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');
 const sync=await p.evaluate(async()=>{const {beatState}=await import('./metronome.js');let mismatch=0;for(let i=0;i<30;i++){await new Promise(requestAnimationFrame);const expected=beatState(prototype.playback.timeline,prototype.playback.position);if(Number(document.querySelector('.beat-rail-top').dataset.beat)!==expected.index)mismatch++;if(document.querySelector('.beat-rail-top').dataset.beat!==document.querySelector('.beat-rail-bottom').dataset.beat)throw Error('rows out of sync');}return mismatch;});assert(sync<=1,'audio/visual frame synchronization');
 await p.locator('#settings').click();const old=await p.evaluate(()=>prototype.playback.tempo.bpm);await p.locator('#tempo-up').click();assert((await p.evaluate(()=>prototype.playback.tempo.bpm))>old);await p.locator('#close-settings').click();assert.equal(await p.evaluate(()=>prototype.xml),xml);const tempoSync=await p.evaluate(async()=>{const {beatState}=await import('./metronome.js');await new Promise(requestAnimationFrame);return {expected:beatState(prototype.playback.timeline,prototype.playback.position).index,actual:Number(document.querySelector('.beat-rail-top').dataset.beat)};});assert.equal(tempoSync.actual,tempoSync.expected);
 await p.locator('.score-heading .song-playback').click();const paused=await p.locator('.beat-rail-top').getAttribute('data-beat');await p.waitForTimeout(200);assert.equal(await p.locator('.beat-rail-top').getAttribute('data-beat'),paused);await p.evaluate(()=>prototype.playback.stop());
 await enable('off');assert.equal(await p.locator('.beat-rail:visible').count(),0);await enable('dots');await shown();await p.evaluate(()=>prototype.changeKey(1));await ready();await shown();assert.equal(await p.evaluate(()=>prototype.current),1);
 console.log('key and modes',width);await p.evaluate(()=>prototype.loadSong('hhc-1054','large'));await ready();await shown();assert(await p.evaluate(()=>prototype.lead.ok));console.log('Lead',width);await p.locator('#show-lyrics').click();await p.locator('#lyrics-view').waitFor({state:'visible'});assert.equal(await p.locator('.beat-rail:visible').count(),0);console.log('Lyrics',width);await p.getByRole('button',{name:'View Score',exact:true}).click();await ready();await shown();await p.evaluate(()=>prototype.loadSong('choose-to-serve-the-lord'));await ready();assert.equal(await p.locator('.beat-rail:visible').count(),0);await p.locator('#songs').click();assert.equal(await p.locator('.beat-rail:visible').count(),0);
 if(width===390){await p.evaluate(()=>Promise.all([prototype.loadSong('nativity'),prototype.loadSong('hhc-1054')]));assert.equal(await p.evaluate(()=>prototype.song),'hhc-1054');await ready();await shown();await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await ready();await shown();}
 assert.deepEqual(errors,[]);console.log('PASS visual metronome placement, clock, tempo, stop/start, navigation, Lead/Lyrics/PDF',width,height);await c.close();
}}finally{await browser.close();}
