import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const require=createRequire(process.env.PLAYWRIGHT_PACKAGE),{chromium}=require('playwright');
const b=await chromium.launch({channel:'msedge',headless:true}),c=await b.newContext(),p=await c.newPage();const errors=[];p.on('console',m=>{if(m.type()==='error')console.log(m.text());});p.on('pageerror',e=>errors.push(e.message));
const xml=`<?xml version="1.0"?><score-partwise version="4.0"><work><work-title>Local synthetic practice</work-title></work><part-list><score-part id="P1"><part-name>Piano</part-name></score-part></part-list><part id="P1">${Array.from({length:24},(_,i)=>`<measure number="${i+1}">${i===0?'<attributes><divisions>1</divisions><key><fifths>0</fifths><mode>major</mode></key><time><beats>4</beats><beat-type>4</beat-type></time><clef><sign>G</sign><line>2</line></clef></attributes>':''}<note><pitch><step>C</step><octave>4</octave></pitch><duration>4</duration><type>whole</type></note></measure>`).join('')}</part></score-partwise>`;
const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.getElementById('score').getAttribute('aria-busy')==='false');
const records=()=>p.evaluate(async()=> (await import('./local-music-store.js')).localRecords().then(rs=>rs.map(r=>r.metadata)));
async function preview(name,buffer){await p.locator('#add-music').click();await p.locator('#music-file').setInputFiles({name,mimeType:'application/octet-stream',buffer:Buffer.from(buffer)});await p.waitForFunction(()=>!document.getElementById('music-file').disabled);}
async function save(){await p.locator('#import-save').click();try{await p.waitForFunction(()=>!document.getElementById('music-import').open,{},{timeout:5000});}catch(e){console.log('SAVE ERROR',await p.locator('#import-message').textContent());throw e;}}
try{
 await p.goto(process.env.TEST_URL||'http://127.0.0.1:8768/');await p.locator('.library-row').first().waitFor();await p.locator('#library-source').selectOption('my-music');
 for(const [name,data] of [['bad.xml','<bad'],['unrelated.xml','<data/>'],['bad.mxl','PKbroken'],['bad.txt','hello']]){await preview(name,data);assert(await p.locator('#import-save').isDisabled());assert.equal((await records()).length,0);await p.locator('#close-import').click();}
 await preview('practice.musicxml',xml);assert.match(await p.locator('#import-summary').textContent(),/Transposable/);await p.locator('#import-page').fill('999');for(const [width,height] of [[390,844],[820,1180],[1180,820],[1440,1000]]){await p.setViewportSize({width,height});assert(await p.locator('#import-preview svg').count());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/my-music-preview-${width}.png`});}await save();const id=(await records())[0].id;assert.match(id,/^local-[0-9a-f-]{36}$/);assert.equal(await p.evaluate(async id=>(await (await import('./local-music-store.js')).localRecord(id)).file.text(),id),xml);
 await preview('same.xml',xml);assert.match(await p.locator('#import-message').textContent(),/already/);await p.locator('#close-import').click();
 await p.locator(`[data-song="${id}"] .favorite`).click();await p.locator(`[data-song="${id}"] .song-entry`).click();await ready();assert.equal(await p.locator('#key-name').textContent(),'C Maj');await p.locator('#key').click();await p.locator('[data-shift="2"]').click();await ready();assert.equal(await p.evaluate(()=>prototype.current),2);await p.locator('#reset').click();await ready();assert.equal(await p.evaluate(()=>prototype.xml===prototype.original),true);
 await p.locator('#score-size').click();await p.locator('[data-size="compact"]').click();await ready();await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');await p.locator('#songs').click();assert.equal(await p.evaluate(()=>prototype.playback.state),'stopped');
 await preview('view.xml',xml.replace('<key><fifths>0</fifths><mode>major</mode></key>',''));assert.match(await p.locator('#import-summary').textContent(),/View only/);await save();const view=(await records()).find(r=>r.capability==='View only');await p.locator(`[data-song="${view.id}"] .song-entry`).click();await ready();assert(await p.locator('#key').isHidden());assert.match(await p.locator('.footnote').textContent(),/unavailable/);await p.locator('#songs').click();
 const zip=await p.evaluate(xml=>Array.from(fflate.zipSync({'META-INF/container.xml':fflate.strToU8('<container><rootfiles><rootfile full-path="score.xml" media-type="application/vnd.recordare.musicxml+xml"/></rootfiles></container>'),'score.xml':fflate.strToU8(xml)})),xml);await preview('practice.mxl',zip);await save();const mxl=(await records()).find(r=>r.fileType==='mxl');
 // A small synthetic PDF generated in memory, never published as user content.
 const parts=['%PDF-1.4\n'],offsets=[0];const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R >>','<< /Length 24 >>\nstream\n100 100 200 300 re S\nendstream'];for(let i=0;i<objects.length;i++){offsets.push(parts.join('').length);parts.push(`${i+1} 0 obj\n${objects[i]}\nendobj\n`);}const xref=parts.join('').length;parts.push('xref\n0 5\n0000000000 65535 f \n'+offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 5 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`);
 await preview('local.pdf',parts.join(''));await save();const pdf=(await records()).find(r=>r.scoreType==='pdf');await p.locator(`[data-song="${pdf.id}"] .favorite`).click();await p.locator(`[data-song="${pdf.id}"] .song-entry`).click();await ready();assert(await p.locator('#score canvas').count());await p.locator('#songs').click();
 await p.evaluate(id=>{const k='music-transpose-library-v1',s=JSON.parse(localStorage.getItem(k));s.groups.push({id:'existing-list',name:'Practice',songs:[id]});localStorage.setItem(k,JSON.stringify(s));},id);await p.reload();await p.locator('.library-row').first().waitFor();
 await p.locator(`[data-song="${pdf.id}"] button[aria-label^="Edit local"]`).click();await p.locator('#import-memberships input').check();await p.locator('#import-title').fill('Renamed PDF');await save();assert.equal((await records()).find(r=>r.id===pdf.id).title,'Renamed PDF');await p.locator('#manage-lists').click();await p.locator('[data-list="existing-list"]').click();await p.getByRole('button',{name:'Add songs',exact:true}).click();await p.locator('#list-picker-source').selectOption('my-music');await p.locator('#list-picker-results input[data-song="'+mxl.id+'"]').check();await p.locator('#list-picker-done').click();await p.locator('#lists-library').click();
 await p.evaluate(async()=>{for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister();for(const key of await caches.keys())if(key.startsWith('music-transpose-'))await caches.delete(key);});await p.reload();await p.locator('.library-row').first().waitFor();
 await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await p.locator('.library-row').first().waitFor();assert.equal((await records()).length,4);
 for(const song of [id,pdf.id,mxl.id]){await p.locator(`[data-song="${song}"] .song-entry`).click();await ready();if(song===mxl.id){await p.locator('#key').click();await p.locator('[data-shift="1"]').click();await ready();assert.equal(await p.evaluate(()=>prototype.current),1);await p.locator('#settings').click();await p.locator('input[name=navigation][value=pages]').check();await p.locator('#close-settings').click();await p.evaluate(()=>prototype.preparePrint());assert(await p.locator('#print-pages svg').count());}await p.locator('#songs').click();}
 const state=await p.evaluate(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1')));assert(state.favorites.includes(id)&&state.favorites.includes(pdf.id));assert.deepEqual(state.groups[0].songs,[id,pdf.id,mxl.id]);
 await p.locator('#manage-lists').click();await p.locator('[data-list="existing-list"]').click();await p.getByRole('button',{name:'Edit list item: Renamed PDF',exact:true}).click();await p.getByRole('button',{name:'Remove from this list: Renamed PDF',exact:true}).click();assert.equal((await records()).length,4);assert((await records()).some(r=>r.id===pdf.id));const afterRemove=await p.evaluate(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1')));assert(afterRemove.favorites.includes(pdf.id));assert.deepEqual(afterRemove.groups[0].songs,[id,mxl.id]);await p.locator('#lists-library').click();

 for(const [width,height] of [[390,844],[820,1180],[1180,820],[1440,1000]]){await p.setViewportSize({width,height});await p.locator('#add-music').click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/my-music-${width}.png`});await p.locator('#close-import').click();}
 p.on('dialog',d=>d.accept());await p.locator(`[data-song="${pdf.id}"] button[aria-label^="Edit local"]`).click();await p.locator('#import-delete').click();await p.waitForFunction(()=>!document.getElementById('music-import').open);assert.equal((await records()).length,3);assert(!JSON.stringify(await p.evaluate(()=>JSON.parse(localStorage.getItem('music-transpose-library-v1')))).includes(pdf.id));
await c.setOffline(false);await p.locator('#add-music').click();await p.locator('#music-file').setInputFiles({name:'quota.xml',mimeType:'application/xml',buffer:Buffer.from(xml.replace('Local synthetic practice','Quota fixture'))});await p.waitForFunction(()=>!document.getElementById('music-file').disabled);await p.evaluate(()=>{window.savedAdd=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(){if(this.name==='songs')throw new DOMException('Synthetic quota','QuotaExceededError');return window.savedAdd.apply(this,arguments);};});await p.locator('#import-save').click();await p.waitForFunction(()=>document.getElementById('import-message').textContent.includes('Not enough'));await p.evaluate(()=>IDBObjectStore.prototype.add=window.savedAdd);assert.equal((await records()).length,3);assert.equal(await p.evaluate(async()=>(await (await import('./local-music-store.js')).localMetadata()).length),3);await p.locator('#close-import').click();
 assert.deepEqual(errors,[]);console.log('PASS local import, invalid formats, duplicate detection, view-only, key/reset/size/playback, PDF, persistent IDs/lists/favorites, offline, deletion, responsive dialogs');
}finally{await b.close();}
