import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const b=await chromium.launch({channel:'msedge'});
try{for(const width of [390,820,1440]){
 const c=await b.newContext({viewport:{width,height:900}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>(errors.push(e.message),console.log('PAGE ERROR',e.message)));
 await c.addInitScript(()=>{if(localStorage.getItem('offline-ux'))return;localStorage.setItem('offline-ux','1');localStorage.setItem('music-transpose-library-v1',JSON.stringify({orderingVersion:1,favorites:[],textItems:{'text:cue':{type:'text',title:'Welcome',html:'<p>Welcome</p>'}},groups:[{id:'a',name:'Rehearsal',songs:['nativity','scripture-power','silent-night','text:cue']},{id:'single',name:'Single',songs:['scripture-power']}]}));});
 p.setDefaultTimeout(60000);console.log('start',width);await p.goto('http://127.0.0.1:8780/');await p.waitForFunction(()=>window.prototype?.navigation&&navigator.serviceWorker.controller);
 const call=(method,arg)=>p.evaluate(async({method,arg})=>(await import('./offline-manager.js'))[method](arg),{method,arg});console.log('worker ready');await call('refreshOffline');
 const openList=async(id='a')=>{await p.locator('#home-lists').click();const x=p.locator(`[data-list="${id}"] .list-overview-entry`);if(await x.getAttribute('aria-expanded')!=='true')await x.click();};
 console.log('list');await openList();const row=id=>p.locator(`[data-list="a"] [data-song="${id}"]`),control=()=>row('nativity').locator('.catalog-offline');
 assert.equal(await row('scripture-power').locator('.catalog-offline').count(),0);assert.equal(await row('text:cue').locator('.catalog-offline').count(),0);assert.equal(await row('nativity').locator('.offline-saved-badge').count(),0);
 assert.equal(await control().getAttribute('aria-label'),'Save on this device');const bounds=await control().boundingBox();assert(bounds.width>=44&&bounds.height>=44&&bounds.x+bounds.width<=width);
 await control().click();await p.waitForFunction(()=>document.querySelector('[data-list="a"] [data-song="nativity"] .catalog-offline').getAttribute('aria-pressed')==='true');
 assert.equal(await p.locator('[data-list="a"] .list-offline-status').textContent(),'Offline: 1 of 3 saved');await p.screenshot({path:`test-results/offline-list-${width}.png`});await control().click();await p.waitForFunction(()=>document.querySelector('[data-list="a"] [data-song="nativity"] .catalog-offline').getAttribute('aria-pressed')==='false');
 await p.locator('[data-list="a"] .list-actions-toggle').click();await p.getByRole('menuitem',{name:'Save list on this device',exact:true}).click();await p.waitForFunction(()=>document.querySelector('[data-list="a"] .list-offline-status').textContent==='Offline: 3 of 3 saved');await control().click();await p.locator('#offline-control-notice').waitFor({state:'visible'});assert((await call('offlineSongState',{id:'nativity'})).saved);await p.keyboard.press('Escape');await p.locator('[data-list="a"] .list-actions-toggle').click();await p.getByRole('menuitem',{name:'Remove list downloads',exact:true}).click();await p.waitForFunction(()=>document.querySelector('[data-list="a"] .list-offline-status').textContent==='Offline: 0 of 3 saved');assert(!(await call('offlineSongState',{id:'nativity'})).saved);assert.equal(await control().getAttribute('aria-pressed'),'false');
 await row('nativity').locator('.workspace-song-entry').click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!prototype.loading);assert.equal(await p.locator('#score-offline-control').count(),0);await p.locator('#score-tools').click();await p.locator('#score-offline-save').click();await p.waitForFunction(async()=> (await import('./offline-manager.js')).offlineSongState({id:'nativity'}).saved);await p.keyboard.press('Escape');
 assert(await p.locator('#previous-song').isHidden());assert(await p.locator('#next-song').isVisible());
 await p.locator('#next-song').click();await p.waitForFunction(()=>prototype.song==='scripture-power'&&prototype.ready&&!prototype.loading&&!prototype.busy);assert.equal(await p.locator('#score-song-number').textContent(),'');assert(await p.locator('.score-song-navigation').isHidden());assert.equal(await p.locator('#score-source').textContent(),'Music from the Friend');assert.equal(await p.locator('#score-offline-control').count(),0);
 await p.locator('#songs').click();await p.locator('#home-about').click();await p.locator('#home-info-saved').click();await p.waitForFunction(()=>document.querySelectorAll('#library .catalog-offline').length===1);assert.match(await p.locator('#library .song-meta').first().textContent(),/\d/);await p.screenshot({path:`test-results/offline-saved-${width}.png`});await p.locator('#library .song-entry').click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!prototype.loading);assert(await p.locator('.score-song-navigation').isHidden());assert((await call('offlineSongState',{id:'nativity'})).saved);await p.locator('.score-header-home').click();await p.locator('#library .catalog-offline').click();await p.getByText('No music is saved on this device yet.',{exact:true}).waitFor();
 await p.locator('#library .header-home').click();await openList('single');await p.locator('[data-list="single"] .workspace-song-entry').click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!prototype.loading);assert(await p.locator('.score-song-navigation').isHidden());
 assert.deepEqual(await p.evaluate(async()=>{const m=await import('./score-labels.js');return [{collection:'<XXX>',page:'<Song>'},{collection:'Source',page:'Song'},{page:'212'},{collection:'Source',songNumber:12}].map(m.scoreMetadata);}),['','Source','212','Source · 12']);assert.deepEqual(errors,[]);console.log('PASS',width,'offline actions, protected List, global saved view, header and bounded navigation');await c.close();
}}finally{await b.close();}
