import {createServer} from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {songs} from '../songs.js';
const root=process.cwd(),pdfs=JSON.parse(await fs.readFile('offline-pdfs.json','utf8')),expected=[...new Set(songs.flatMap(s=>[s.pdfAsset,s.scoreType==='pdf'?s.asset:null]).filter(Boolean))].sort();assert.deepEqual(pdfs.assets.map(a=>a.url),expected);for(const a of pdfs.assets)assert.equal(a.bytes,(await fs.stat(a.url)).size);assert.equal(pdfs.totalBytes,pdfs.assets.reduce((n,a)=>n+a.bytes,0));
const ids=['hhc-1035','cs-2','cs-138'],assets=ids.map(id=>pdfs.assets.find(a=>a.url===songs.find(s=>s.id===id).pdfAsset)),structured=ids.slice(0,2).map(id=>songs.find(s=>s.id===id).asset);let failing=true,delay=0,version=1;const requests=[];
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'),relative=decodeURIComponent(url.pathname).slice(1)||'index.html';if(relative==='test-blank'){res.setHeader('Content-Type','text/html');res.end('<!doctype html>');return;}if(relative.endsWith('.pdf')){requests.push('./'+relative);if(failing&&'./'+relative===assets[2].url){res.writeHead(503);res.end();return;}if(delay)await new Promise(r=>setTimeout(r,delay));}let text=null;if(relative==='offline-pdfs.json')text=JSON.stringify({assets,totalBytes:assets.reduce((n,a)=>n+a.bytes,0)});if(relative==='offline-scores.json')text=JSON.stringify(structured);if(relative==='sw.js'){text=(await fs.readFile('sw.js','utf8')).replace('music-transpose-v197-',`music-transpose-v197test${version}-`);text+="\nlet testQuota=false;const realPut=Cache.prototype.put;Cache.prototype.put=function(request,response){if(testQuota&&String(request.url||request).endsWith('.pdf'))return Promise.reject(new DOMException('Full','QuotaExceededError'));return realPut.call(this,request,response);};self.addEventListener('message',e=>{if(e.data?.type==='test-quota'){testQuota=e.data.value;e.ports[0]?.postMessage({ok:true});}});";}const file=path.resolve(root,relative);if(!file.startsWith(root+path.sep)){res.writeHead(403);res.end();return;}res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',relative.endsWith('.js')?'text/javascript':relative.endsWith('.json')?'application/json':relative.endsWith('.css')?'text/css':relative.endsWith('.pdf')?'application/pdf':relative.endsWith('.html')?'text/html':'application/octet-stream');res.end(text??await fs.readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/`;
const {chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright'),browser=await chromium.launch({channel:'msedge',headless:true});
try{const c=await browser.newContext({viewport:{width:820,height:1180}}),p=await c.newPage();p.setDefaultTimeout(30000);await p.goto(base+'test-blank');await p.evaluate(async({base,pdf,xml})=>{const cache=await caches.open('music-transpose-v196-'+base+'-scores');for(const a of [pdf,xml])await cache.put(new URL(a,base),await fetch(a));localStorage.setItem('music-transpose-library-v1',JSON.stringify({favorites:['hhc-1035'],groups:[{id:'offline',name:'Offline practice',songs:['hhc-1035','cs-2']}]}));},{base,pdf:assets[1].url,xml:structured[0]});await p.goto(base);await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);
const rpc=(type,extra={})=>p.evaluate(({type,extra})=>new Promise(resolve=>{const ch=new MessageChannel();ch.port1.onmessage=e=>resolve(e.data);navigator.serviceWorker.controller.postMessage({type,...extra},[ch.port2]);}),{type,extra});
await p.waitForFunction(()=>document.querySelector('#offline').textContent==='Structured scores ready offline');let status=await rpc('offline-status');assert.equal(status.structuredDone,2);assert.equal(status.done,1);assert.equal(status.total,3);assert(await p.evaluate(async base=>(await caches.keys()).includes('music-transpose-scores-'+base),base));
await p.locator('[data-home-source=all]').click();const open=async()=>{await p.locator('#library-more').click();await p.locator('#offline-music').click();await p.waitForFunction(()=>!document.querySelector('#offline-prepare').disabled||document.querySelector('#offline-pdf-status').textContent==='3 of 3 available offline');};await open();assert.equal(await p.locator('#offline-structured').textContent(),'✓ Ready offline');const initial=requests.length;await p.locator('#offline-prepare').click();assert.equal(requests.length,initial);await p.locator('#offline-confirm-cancel').click();assert.equal(requests.length,initial);
await p.locator('#offline-prepare').click();await p.locator('#offline-confirm-prepare').click();await p.waitForFunction(()=>document.querySelector('#offline-note').textContent.includes('1 could not'));status=await rpc('offline-status');assert.equal(status.done,2);assert.equal(status.failed,1);assert.equal(requests.filter(x=>x===assets[1].url).length,1,'migrated PDF not downloaded again');
failing=false;const n=requests.length;await p.locator('#offline-prepare').click();await p.locator('#offline-confirm-prepare').click();await p.waitForFunction(()=>document.querySelector('#offline-pdf-status').textContent==='3 of 3 available offline');assert.deepEqual(requests.slice(n),[assets[2].url]);
for(const width of [390,820,1440]){await p.setViewportSize({width,height:1000});const r=await p.locator('#offline-music-dialog').boundingBox();assert(r.x>=0&&r.x+r.width<=width);assert(await p.locator('#offline-music-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth));await p.screenshot({path:`test-results/offline-music-${width}.png`});}await p.keyboard.press('Escape');assert(await p.locator('#offline-music-dialog').isHidden());
// Shell update retains score bytes in the stable store.
version=2;await Promise.all([p.waitForEvent('load'),p.evaluate(async()=>{const reg=await navigator.serviceWorker.getRegistration();await reg.update();})]);await p.waitForFunction(()=>!!window.prototype);await p.waitForFunction(async()=>!(await caches.keys()).some(n=>n.startsWith('music-transpose-v197test1-')));assert.equal((await rpc('offline-status')).done,3);
// Explicit storage-limit simulation preserves existing PDFs and stops without eviction.
await p.evaluate(async({base,url})=>{await(await caches.open('music-transpose-scores-'+base)).delete(new URL(url,base));},{base,url:assets[2].url});await rpc('test-quota',{value:true});await rpc('prepare-original-pdfs');await p.waitForFunction(async()=>{const ch=new MessageChannel();const s=await new Promise(r=>{ch.port1.onmessage=e=>r(e.data);navigator.serviceWorker.controller.postMessage({type:'offline-status'},[ch.port2]);});return s.storageFull&&!s.running;});assert.equal((await rpc('offline-status')).done,2);await rpc('test-quota',{value:false});
// Stop waits for the current file; retry only requests missing content.
delay=250;await rpc('prepare-original-pdfs');await rpc('stop-original-pdfs');await p.waitForTimeout(400);assert(!(await rpc('offline-status')).running);await rpc('prepare-original-pdfs');await p.waitForFunction(async()=>{const ch=new MessageChannel();return new Promise(r=>{ch.port1.onmessage=e=>r(e.data.done===3&&!e.data.running);navigator.serviceWorker.controller.postMessage({type:'offline-status'},[ch.port2]);});});delay=0;
// Cache-on-first-open remains available outside the preparation manifest.
const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!document.body.classList.contains('song-loading'));const load=async id=>{console.log('Checking score',id);await p.evaluate(id=>prototype.loadSong(id),id);try{await ready();}catch(e){console.log(await p.locator('#status').textContent());throw e;}};await load('nativity');assert(await p.evaluate(async()=>!!await caches.match(new URL('./assets/pdfs/fallback/nativity.pdf',location.href))));
// Local imports retain their original stored bytes and structured XML.
await p.evaluate(async({xmlAsset,pdfAsset})=>{const {addRecord}=await import('./local-music-store.js'),{unpackMXL}=await import('./music.js'),{refreshLocalMusic}=await import('./catalog.js');const blob=await(await fetch(pdfAsset)).blob(),raw=await(await fetch(xmlAsset)).arrayBuffer(),xml=unpackMXL(raw);await addRecord({metadata:{id:'local-offline-pdf',hash:'offline-pdf',title:'Local offline PDF',originalFilename:'local.pdf',scoreType:'pdf',fileType:'pdf',transpositionAvailable:false},file:blob});await addRecord({metadata:{id:'local-offline-xml',hash:'offline-xml',title:'Local offline XML',originalFilename:'local.mxl',scoreType:'musicxml',fileType:'mxl',tonic:'C',mode:'major',fifths:0},file:new Blob([raw]),xml});await refreshLocalMusic();},{xmlAsset:structured[0],pdfAsset:assets[0].url});
await p.evaluate(async({base,url})=>{await(await caches.open('music-transpose-scores-'+base)).delete(new URL(url,base));},{base,url:assets[0].url});const cdp=await c.newCDPSession(p);await cdp.send('Network.enable');await cdp.send('Network.setCacheDisabled',{cacheDisabled:true});await c.setOffline(true);await p.goto(base);await p.locator('#home-files').waitFor({state:'visible'});await p.locator('[data-home-source=all]').click();await p.locator('#library-search').fill('Sabbath');assert(await p.locator('[data-song=hhc-1035]').count()>0);await p.locator('#view-favorites').click();assert(await p.locator('[data-song=hhc-1035]').count()>0);await p.locator('#library-lists').click();await p.locator('[data-list=offline]').waitFor({state:'visible'});await p.locator('#lists-library').click();await p.locator('#library-more').click();await p.locator('#view-files').click();assert(await p.locator('[data-file=local-offline-pdf]').count()>0);
await load('cs-2');assert(await p.locator('#score .pdf-page-frame').count()>0);await load('hhc-1035');assert(await p.locator('#pdf-offline-message').isVisible());assert((await p.locator('#pdf-offline-message').textContent()).includes('prepare Original PDFs'));for(const mode of ['auto','large']){await p.locator('#score-size').click();await p.locator(`#score-size-options [data-size=${mode}]`).click();await ready();assert(await p.locator('#score svg').count()>0);}await load('local-offline-pdf');assert(await p.locator('#score .pdf-page-frame').count()>0);await load('local-offline-xml');assert(await p.locator('#score svg').count()>0);
console.log('PASS real service worker: counts, confirmation, failure/retry, stop/resume, quota preservation, shell upgrade, cache-on-open, offline Home/search/Favorites/Lists/Files, prepared/missing Original, Transpose/Melody, local PDF/MXL, 3 viewport layouts');await c.close();}finally{await browser.close();await new Promise(r=>server.close(r));}
