import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const {chromium,webkit}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright');
const browser=await (process.env.WEBKIT?webkit:chromium).launch(process.env.WEBKIT?{}:{channel:'msedge',headless:true});
const base=process.env.TEST_URL||'http://127.0.0.1:8775/';
try{for(const [width,height] of [[820,1180],[1180,820],[390,844],[1440,1000]]){
 if(process.env.PDF_WIDTH&&width!==Number(process.env.PDF_WIDTH))continue;
 const c=await browser.newContext({viewport:{width,height},hasTouch:width!==1440,serviceWorkers:'block'}),p=await c.newPage(),errors=[],warnings=[];
 // Reproduced in pre-change 3fbba06 with explicit PDF -> Lyrics on WebKit phone.
 p.on('pageerror',e=>{if(process.env.WEBKIT&&e.message==='ResizeObserver loop completed with undelivered notifications.')warnings.push(e.message);else errors.push(e.message);});
 await c.addInitScript(()=>{localStorage.setItem('music-transpose-navigation-v1',JSON.stringify({mode:'pages'}));localStorage.setItem('music-transpose-library-v1',JSON.stringify({favorites:[],groups:[{id:'pdf-first-list',name:'PDF first rehearsal',songs:['nativity','hhc-1035','choose-to-serve-the-lord']}]}));});
 const ready=async()=>{await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');await p.waitForTimeout(160);};
 const pdf=()=>p.locator('body').evaluate(e=>e.classList.contains('pdf-score-open'));
 const library=async()=>{await p.locator('#songs').click();await p.locator('#library').waitFor({state:'visible'});};
 const open=async id=>{await p.locator(`[data-song="${id}"] .song-entry`).click();await ready();};
 const view=async name=>{await p.locator('#score-size').click();await p.locator(`#score-size-options [data-size=${name}]`).click();await ready();};
 const position=()=>p.locator('#page-position').textContent();
 const state=()=>p.evaluate(()=>({song:prototype.song,xml:prototype.xml,key:prototype.current,octave:prototype.octaveState,view:document.querySelector('#score-size').dataset.size,page:document.querySelector('#page-position').textContent,pageVisible:!document.querySelector('#page-position').hidden&&document.querySelector('#page-position').getClientRects().length>0,pdf:document.body.classList.contains('pdf-score-open')}));
 const roundtrip=async()=>{const before=await state();await p.locator('#show-lyrics').click();await p.locator('#lyrics-view').waitFor({state:'visible'});await p.locator('.lyrics-score-toggle').click();await ready();assert.deepEqual(await state(),before);};
 await p.goto(base);await p.locator('.library-row').first().waitFor();
 await p.evaluate(()=>{window.unexpectedXML=0;new MutationObserver(()=>{const s=document.querySelector('#score');if(!document.body.classList.contains('library-open')&&getComputedStyle(s).visibility==='visible'&&s.querySelector('svg'))window.unexpectedXML++;}).observe(document.querySelector('#score'),{childList:true,subtree:true});});
 const renders=await p.evaluate(()=>prototype.metrics.length);await open('nativity');assert(await pdf());assert.equal(await p.evaluate(()=>prototype.metrics.length),renders);assert.equal(await p.evaluate(()=>unexpectedXML),0);assert.equal(await p.evaluate(()=>scrollY),0);assert.equal(await p.locator('.score-heading .song-playback').count(),0);assert(await p.locator('#score-size').isVisible());assert.equal(await p.locator('#score-pdf-option').getAttribute('aria-pressed'),'true');assert(!/fallback|error/i.test(await p.locator('#status').textContent()));
 const pages=await p.locator('.pdf-page-frame').count();assert(pages>1);await p.keyboard.press('End');assert.equal(await position(),`${pages} / ${pages}`);await roundtrip();await p.keyboard.press('ArrowLeft');assert.equal(await position(),`${pages-1} / ${pages}`);await p.keyboard.press('Home');
 for(let i=0;i<5;i++){const r=await p.evaluate(async()=>(await import('./score-taps.js')).scoreTapGeometry());const click=async(x,y)=>width===1440?p.mouse.click(x,y):p.touchscreen.tap(x,y);await click(r.left+r.width*.8,r.top+r.height*.65);assert.equal(await position(),`2 / ${pages}`);await click(r.left+r.width*.2,r.top+r.height*.65);assert.equal(await position(),`1 / ${pages}`);}
 await p.locator('#show-tap-zones').click();assert.equal(await p.locator('#score-tap-overlay').evaluate(e=>e.style.getPropertyValue('--tap-upper')),'25%');await p.keyboard.press('Escape');
 await p.locator('#score-tools').click();await p.locator('#score-page-theme').click();assert.equal(await p.locator('#score-page-theme').getAttribute('aria-pressed'),'true');assert.match(await p.locator('#score').evaluate(e=>getComputedStyle(e).filter),/invert/);
 await p.evaluate(()=>{window.printCalls=0;window.print=()=>window.printCalls++;});await p.locator('#score-tools').click();await p.locator('#print').click();await p.waitForFunction(()=>printCalls===1);assert.equal(await p.locator('#print-pages .pdf-print-page').count(),pages);await p.evaluate(()=>dispatchEvent(new Event('afterprint')));
 await p.locator('#settings').click();const trim=await p.locator('#pdf-trim').isChecked();await p.locator('#pdf-trim').setChecked(!trim);await p.locator('#close-settings').click();assert.equal(await p.locator('.pdf-page-frame').count(),pages);
 assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const box of await p.locator('.masthead button:visible').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right};})))assert(box.left>=0&&box.right<=width);
 await p.screenshot({path:`test-results/pdf-first-${width}.png`});
 await view('normal');assert(!await pdf());assert(await p.locator('#score svg').count());await roundtrip();await p.evaluate(()=>prototype.changeKey(2));await ready();await p.evaluate(()=>prototype.changeOctave(1));await ready();const working=await state();await roundtrip();assert.equal((await state()).key,2);assert.equal(await p.locator('.score-heading .song-playback').count(),1);
 await library();await open('nativity');const resumed=await state();for(const key of ['key','octave','view','xml'])assert.deepEqual(resumed[key],working[key]);assert(!await pdf());
 await library();await open('choose-to-serve-the-lord');assert(await pdf());assert(await p.locator('#score-size').isHidden());await library();await open('nativity');assert(await pdf(),'different song clears previous structured working view');await library();
 await p.locator('#library-source').click();await p.locator('[data-source="list:pdf-first-list"]').click();await open('hhc-1035');assert(await pdf());assert.equal(await p.locator('#songs').getAttribute('aria-label'),'Back to list');await view('large');assert(await p.evaluate(()=>prototype.lead?.ok));await p.evaluate(()=>prototype.changeKey(1));await ready();await p.evaluate(()=>prototype.changeOctave(1));await ready();const lead=await state();await roundtrip();assert.equal((await state()).view,'large');await library();assert.equal(await p.locator('#library-source-label').textContent(),'PDF first rehearsal');await open('hhc-1035');for(const key of ['key','octave','view','xml'])assert.deepEqual((await state())[key],lead[key]);assert(await p.evaluate(()=>prototype.lead?.ok));
 await library();await p.locator('#library-source').click();await p.locator('#library-source-menu [data-source=all]').click();await open('hhc-1035');assert(await pdf(),'different browse context uses PDF default');await library();
 await p.locator('[data-song="hhc-1035"] [title="Lead sheet"]').click();await ready();assert(!await pdf());assert(await p.evaluate(()=>prototype.lead?.ok));
 // All bundled structured songs currently have PDFs. Import real XML to cover XML-only.
 if(width===820&&!process.env.WEBKIT){const xml=await p.evaluate(()=>prototype.original);await library();await p.locator('#library-more').click();await p.locator('#library-import').click();await p.locator('#music-file').setInputFiles({name:'PDF-first XML-only.musicxml',mimeType:'application/xml',buffer:Buffer.from(xml)});await p.waitForFunction(()=>!document.querySelector('#import-save').disabled);await p.locator('#import-save').click();await p.locator('#music-import').waitFor({state:'hidden'});const id=await p.evaluate(async()=>(await (await import('./local-music-store.js')).localMetadata())[0].id);await open(id);assert(!await pdf());assert(await p.locator('#score svg').count());assert(await p.locator('#score-pdf-option').isHidden());assert.equal(await p.locator('#score-size').getAttribute('data-size'),'normal');}
 if(warnings.length)console.log('KNOWN pre-existing WebKit ResizeObserver warning',width,warnings.length);
 assert.deepEqual(errors,[]);console.log('PASS PDF first, no XML engraving/flash, PDF/Lyrics page and working-state return, same-context resume, different-song/context reset, explicit Lead, tools/print/trim/taps/viewport',width,height);await c.close();
}}finally{await browser.close();}
