import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs';
const engines=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),engine=process.env.TAP_ENGINE||'chromium',b=await engines[engine].launch(engine==='chromium'?{channel:'msedge',headless:true}:{headless:true});const baseline=!!process.env.TAP_BASELINE,results=[];
try{for(const [width,height,touch] of (baseline?[[820,1180,true]]:[[820,1180,true],[1180,820,true],[390,844,true],[1440,1000,false]])){
 const c=await b.newContext({viewport:{width,height},hasTouch:touch}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_URL||'http://127.0.0.1:8771/');await p.locator('.library-row').first().waitFor();
 // Import the exact bundled file through the normal upload/validation/IndexedDB UI.
 let local=null;if(!process.env.TAP_BUNDLED_ONLY){await p.locator('#library-more').click();await p.locator('#library-import').click();await p.locator('#music-file').setInputFiles({name:'Tap parity.pdf',mimeType:'application/pdf',buffer:fs.readFileSync('assets/pdfs/choose-to-serve-the-lord.pdf')});await p.waitForFunction(()=>!document.querySelector('#import-save').disabled);await p.locator('#import-save').click();await p.locator('#music-import').waitFor({state:'hidden'}).catch(async error=>{console.log('Import failure:',await p.locator('#import-message').textContent(),await p.locator('#import-title').inputValue(),errors);throw error;});
 local=await p.evaluate(async()=>{const {localMetadata}=await import('./local-music-store.js');return (await localMetadata())[0].id;});}
 const ready=async()=>{await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');await p.waitForTimeout(100);};
 const mode=async value=>{await p.locator('#settings').click();await p.locator(`input[name=navigation][value=${value}]`).check();await p.locator('#close-settings').click();await p.waitForTimeout(100);};
 const pos=async()=>Number((await p.locator('#page-position').textContent()).split('/')[0]);
 const tap=async(x,y)=>{const r=await p.evaluate(async()=>(await import('./score-taps.js')).scoreTapGeometry());if(touch)await p.touchscreen.tap(r.left+r.width*x,r.top+r.height*y);else await p.mouse.click(r.left+r.width*x,r.top+r.height*y);await p.waitForTimeout(30);};
 const gesture=async opts=>p.evaluate(async opts=>{const r=(await import('./score-taps.js')).scoreTapGeometry(),host=document.querySelector('#score'),x=r.left+r.width*(opts.x??.8),y=r.top+r.height*(opts.y??.65),pointerType=opts.pointerType||'touch';const ev=(type,dx=0,dy=0)=>host.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:51,isPrimary:true,button:0,pointerType,clientX:x+dx,clientY:y+dy}));ev('pointerdown');if(opts.move)ev('pointermove',opts.move);if(opts.cancel){if(opts.cancel==='replace'){const marker=document.createElement('span');host.append(marker);await Promise.resolve();marker.remove();}else if(['pointercancel','lostpointercapture'].includes(opts.cancel))ev(opts.cancel);else if(['scroll','resize'].includes(opts.cancel))window.dispatchEvent(new Event(opts.cancel));else document.dispatchEvent(new Event(opts.cancel));}if(opts.delay)await new Promise(r=>setTimeout(r,opts.delay));ev('pointerup',opts.dx||0,opts.dy||0);host.dispatchEvent(new MouseEvent('click',{bubbles:true,clientX:x,clientY:y}));},opts);
 for(const id of ['choose-to-serve-the-lord',local].filter(Boolean)){
  await p.evaluate(id=>prototype.loadSong(id),id);await ready();await mode('pages');assert.equal(await p.locator('.pdf-page-frame').count(),5);
  const outcomes=[];for(const dx of [0,8,10,12,16,18,24,40]){await tap(.2,.1);await gesture({dx,move:dx});outcomes.push({dx,accepted:(await pos())===2});}
  results.push({width,height,source:id===local?'imported':'bundled',outcomes});if(baseline)continue;
  assert.deepEqual(outcomes.map(x=>x.accepted),[true,true,true,true,true,false,false,false]);
  await tap(.2,.1);await tap(.8,.35);assert.equal(await pos(),2);await tap(.8,.35);assert.equal(await pos(),3);await tap(.2,.35);assert.equal(await pos(),2);await tap(.8,.1);assert.equal(await pos(),5);await tap(.8,.65);assert.equal(await pos(),5);await tap(.2,.1);await tap(.2,.65);assert.equal(await pos(),1);
  for(let i=0;i<4;i++)await tap(.8,.65);assert.equal(await pos(),5);await tap(.2,.1);
  await gesture({cancel:'replace'});assert.equal(await pos(),2);await tap(.2,.1);
  // Slight crossing of the upper-quarter boundary keeps the intended down-zone.
  await gesture({y:.251,dy:-4});assert.equal(await pos(),2);await tap(.2,.1);await gesture({y:.249,dy:4});assert.equal(await pos(),5);await tap(.2,.1);await gesture({delay:550});assert.equal(await pos(),2);await tap(.2,.1);
  for(const opts of [{move:24},{delay:650},{cancel:'pointercancel'},{cancel:'lostpointercapture'},{cancel:'scroll'},{cancel:'resize'},{cancel:'score-session-reset'},{pointerType:'mouse',dx:12}]){await gesture(opts);assert.equal(await pos(),1,JSON.stringify(opts));}
  await p.evaluate(()=>{const range=document.createRange();range.selectNodeContents(document.querySelector('.score-heading h1'));getSelection().removeAllRanges();getSelection().addRange(range);});await gesture({});assert.equal(await pos(),1);await p.evaluate(()=>getSelection().removeAllRanges());
  await p.locator('#settings').click();await gesture({});assert.equal(await pos(),1);await p.locator('#close-settings').click();await p.locator('#show-tap-zones').click();assert.equal(await p.locator('#score-tap-overlay').evaluate(e=>e.style.getPropertyValue('--tap-upper')),'25%');const ratios=await p.locator('.score-tap-grid').evaluate(e=>e.children[0].getBoundingClientRect().height/e.getBoundingClientRect().height);assert(Math.abs(ratios-.25)<.01);await p.screenshot({path:`test-results/pdf-taps-${width}-${id===local?'local':'bundled'}.png`});await p.keyboard.press('Escape');assert.equal(await pos(),1);
  await mode('continuous');const before=await pos();await gesture({});assert.equal(await pos(),before);await mode('pages');
 }
 if(!baseline&&local&&width===820){await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await ready();await p.evaluate(id=>prototype.loadSong(id),local);await ready();await mode('pages');await tap(.2,.1);await tap(.8,.65);assert.equal(await pos(),2);await c.setOffline(false);}
 assert.deepEqual(errors,[]);await c.close();console.log('PASS PDF tap parity',width,height,baseline?'baseline measured':'touch/mouse, zones, jitter, rejection, overlay, mode');
}fs.writeFileSync(`test-results/pdf-taps-${engine}-${baseline?'before':'after'}.json`,JSON.stringify(results,null,2));}finally{await b.close();}
