import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';import assert from 'node:assert/strict';const require=createRequire(process.env.PLAYWRIGHT_PACKAGE),{chromium}=require('playwright');const b=await chromium.launch({channel:'msedge',headless:true}),base=process.env.TEST_URL||'http://127.0.0.1:8767/';const c=await b.newContext({serviceWorkers:'block'}),old=await b.newContext({serviceWorkers:'block'});for(const file of ['app.js','index.html','styles.css','score-fit.js']){const body=execFileSync('git',['show','b25d67d:'+file],{encoding:'utf8'});await old.route('**/'+file,r=>r.fulfill({body,contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'}));if(file==='index.html')await old.route(base,r=>r.fulfill({body,contentType:'text/html'}));}
const p=await c.newPage(),q=await old.newPage(),errors=[],fetches=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().endsWith('.mxl'))fetches.push(r.url());});const done=p=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.getElementById('score').getAttribute('aria-busy')==='false');const open=async(p,id)=>{await p.evaluate(id=>prototype.loadSong(id),id);await done(p);};const geometry=p=>p.locator('#print-pages svg').evaluateAll(es=>es.map(e=>[e.getAttribute('viewBox'),...Array.from(e.querySelectorAll('path')).map(n=>n.getAttribute('d'))]));
try{for(const page of [p,q]){await page.setViewportSize({width:390,height:844});await page.goto(base);await page.locator('.library-row').first().waitFor();}
for(const id of ['hhc-1010','cs-236','nativity','shepherd','faithful','silent-night','hhc-1001']){await open(q,id);await open(p,id);const before=await q.locator('#score').evaluate(e=>e.offsetHeight),after=await p.locator('#score').evaluate(e=>e.offsetHeight);assert.equal(await p.evaluate(()=>prototype.xml),await q.evaluate(()=>prototype.xml));assert(after<=before+2);assert.equal(await p.locator('#score-fit').count(),0);assert.equal(await p.locator('#score').evaluate(e=>getComputedStyle(e).transform),'none');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/reflow-${id}.png`});await q.screenshot({path:`test-results/reflow-before-${id}.png`});await p.evaluate(()=>prototype.preparePrint());await q.evaluate(()=>prototype.preparePrint());assert.deepEqual(await geometry(p),await geometry(q));
 assert(await p.locator('[data-compact-tempo]').evaluateAll(groups=>groups.every(g=>{const boxes=[...g.querySelectorAll('text')].map(t=>t.getBoundingClientRect());return boxes.every((a,i)=>boxes.every((b,j)=>i===j||Math.min(a.right,b.right)-Math.max(a.left,b.left)<.5||Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)<.5));})), 'Tempo/expression text overlap');
 const count=fetches.length;for(const button of ['up','down','octave-toggle','reset']){await p.locator('#'+button).click();await done(p);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await p.locator('#key').click();await p.locator('[data-shift="-2"]').click();await done(p);await p.locator('#reset').click();await done(p);assert.equal(fetches.length,count);assert.equal(await p.evaluate(()=>prototype.xml===prototype.original),true);
 console.log(id,JSON.stringify({before,after,reduction:Math.round((1-after/before)*100)+'%'}));}
await open(p,'hhc-1010');await open(q,'hhc-1010');const count=fetches.length;
for(const [width,height] of [[375,812],[600,844],[844,390],[768,1024],[820,1180],[1180,820],[1440,1000]]){for(const page of [p,q]){await page.setViewportSize({width,height});await page.waitForTimeout(400);await done(page);}assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width>600){assert.equal(await p.locator('#score').evaluate(e=>e.offsetHeight),await q.locator('#score').evaluate(e=>e.offsetHeight));assert.equal(await p.locator('#score').textContent(),await q.locator('#score').textContent());}const ys=await p.locator('.toolbar button:visible').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().y));assert(Math.max(...ys)-Math.min(...ys)<1);console.log('PASS viewport',width);}
assert.equal(fetches.length,count);await p.setViewportSize({width:390,height:844});await p.waitForTimeout(400);await done(p);
await p.locator('#settings').click();await p.locator('input[value="hybrid"]').check();await p.locator('#close-settings').click();await p.evaluate(()=>scrollTo(0,0));await p.locator('#screenful-next').click();assert(await p.evaluate(()=>scrollY)>300);await p.locator('#settings').click();await p.locator('input[value="auto"]').check();await p.locator('#scroll-speed').fill('40');await p.locator('#close-settings').click();await p.evaluate(()=>scrollTo(0,0));await p.locator('#auto-toggle').click();await p.waitForTimeout(600);assert(await p.evaluate(()=>scrollY)>10);await p.locator('#auto-toggle').click();
for(const id of ['scripture-power','choose-to-serve-the-lord']){await open(p,id);assert(await p.locator('.pdf-page').count());assert.equal(await p.locator('#score').evaluate(e=>getComputedStyle(e).transform),'none');}
assert.deepEqual(errors,[]);console.log('PASS engraving reflow, source/print invariance, controls, resize without refetch, navigation and PDF');}finally{await b.close();}
