import {createRequire} from 'node:module';import assert from 'node:assert/strict';import fs from 'node:fs/promises';const require=createRequire(process.env.PLAYWRIGHT_PACKAGE),{chromium}=require('playwright');const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:390,height:844}});const errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.addInitScript(()=>{window.audioFrequencies=[];const original=AudioContext.prototype.createOscillator;AudioContext.prototype.createOscillator=function(){const o=original.call(this),start=o.start.bind(o);o.start=(...args)=>{window.audioFrequencies.push(o.frequency.value);return start(...args);};return o;};});
const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');
try{await p.goto(process.env.TEST_URL||'http://127.0.0.1:8767/');await p.locator('.library-row').first().waitFor();
const audit=await p.evaluate(async()=>{const {songs}=await import('./songs.js'),{scoreTimeline}=await import('./playback.js'),{unpackMXL}=await import('./music.js');const rows=[];for(const s of songs.filter(s=>s.scoreType!=='pdf')){const r=await fetch(s.asset),xml=unpackMXL(await r.arrayBuffer()),t=scoreTimeline(xml);rows.push({id:s.id,title:s.title,notes:t.notes.length,seconds:t.duration,fallback:t.fallbackTempo,repeat:t.repeats,warnings:t.warnings,staves:[...new Set(t.notes.map(n=>n.part+':'+n.staff))].length});}return rows;});assert.equal(audit.length,119);assert(audit.every(s=>s.notes>0&&s.seconds>0));await fs.writeFile('test-results/playback-audit.json',JSON.stringify(audit,null,2));console.log('AUDIT',audit.length,'scores; fallback:',audit.filter(s=>s.fallback).map(s=>s.title));
// Synthetic timing fixture: chord, backup, ties, rests and a tempo change.
const fixture=await p.evaluate(async()=>{const {scoreTimeline}=await import('./playback.js');return scoreTimeline('<score-partwise><part id="P"><measure><attributes><divisions>2</divisions></attributes><direction><sound tempo="60"/></direction><note><pitch><step>C</step><octave>4</octave></pitch><duration>2</duration><voice>1</voice><tie type="start"/></note><note><chord/><pitch><step>E</step><octave>4</octave></pitch><duration>2</duration><voice>1</voice></note><backup><duration>2</duration></backup><note><pitch><step>C</step><octave>3</octave></pitch><duration>2</duration><voice>2</voice></note></measure><measure><direction><sound tempo="120"/></direction><note><pitch><step>C</step><octave>4</octave></pitch><duration>2</duration><voice>1</voice><tie type="stop"/></note><note><rest/><duration>2</duration></note></measure></part></score-partwise>');});assert.equal(fixture.notes.length,3);assert.equal(fixture.notes[0].duration,1.5);assert.equal(fixture.duration,2);assert(fixture.notes.every(n=>n.start===0));
for(const id of ['hhc-1010','cs-236','nativity','shepherd','faithful','silent-night','cs-12','cs-110']){
await p.evaluate(id=>prototype.loadSong(id),id);await ready();const play=p.locator('.score-heading .song-playback');await play.click();await p.waitForFunction(()=>prototype.playback.state==='playing');assert(await p.evaluate(()=>prototype.playback.nodes>0));await p.waitForTimeout(120);await play.click();assert.equal(await play.getAttribute('aria-label'),'Resume song');const paused=await p.evaluate(()=>prototype.playback.position);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>prototype.playback.position),paused);await play.click();await p.waitForFunction(()=>prototype.playback.state==='playing');await play.click({button:'right'});assert.equal(await play.getAttribute('aria-label'),'Play song');assert.equal(await p.evaluate(()=>prototype.playback.nodes),0);console.log('PASS playback',id);
}
await p.evaluate(()=>prototype.loadSong('nativity'));await ready();await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');const base=await p.evaluate(()=>prototype.playback.timeline.notes.map(n=>n.midi));await p.locator('#up').click();await ready();assert.equal(await p.evaluate(()=>prototype.playback.state),'stopped');await p.evaluate(()=>audioFrequencies=[]);await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');const frequencies=await p.evaluate(()=>audioFrequencies);assert(frequencies.some(f=>Math.abs(f-440*2**((base[0]+1-69)/12))<.01));const raised=await p.evaluate(()=>prototype.playback.timeline.notes.map(n=>n.midi));assert.deepEqual(raised,base.map(n=>n+1));assert(await p.evaluate(()=>audioFrequencies.length>0));await p.locator('#octave-toggle').click();await ready();await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');assert.deepEqual(await p.evaluate(()=>prototype.playback.timeline.notes.map(n=>n.midi)),base.map(n=>n+13));await p.locator('#reset').click();await ready();await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');assert.deepEqual(await p.evaluate(()=>prototype.playback.timeline.notes.map(n=>n.midi)),base);
await p.locator('#show-lyrics').click();assert.equal(await p.locator('#lyrics-view .song-playback').getAttribute('aria-label'),'Pause song');await p.locator('#lyrics-view .song-playback').click();await p.getByRole('button',{name:'Open score',exact:true}).click();await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');await p.locator('#songs').click();assert.equal(await p.evaluate(()=>prototype.playback.state),'stopped');assert.equal(await p.evaluate(()=>prototype.playback.nodes),0);
// Direct Lyrics playback loads the source without engraving, and survives switching to Score.
await p.locator('[data-song="hhc-1010"] .song-view-actions button').last().click();await p.locator('#lyrics-view .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');assert.equal(await p.evaluate(()=>prototype.ready),false);await p.getByRole('button',{name:'Open score',exact:true}).click();await ready();assert.equal(await p.evaluate(()=>prototype.playback.state),'playing');await p.locator('.score-heading .song-playback').click({button:'right'});
for(const [width,height] of [[390,844],[820,1180],[1180,820],[1440,1000]]){await p.setViewportSize({width,height});await p.waitForTimeout(400);await ready();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const box=await p.locator('.score-heading .song-playback').boundingBox();assert(box.width>=44&&box.height>=44);await p.screenshot({path:`test-results/playback-score-${width}.png`});await p.locator('#show-lyrics').click();await p.screenshot({path:`test-results/playback-lyrics-${width}.png`});await p.getByRole('button',{name:'Open score',exact:true}).click();}
await p.emulateMedia({media:'print'});assert(await p.locator('.song-playback').first().isHidden());await p.emulateMedia({media:'screen'});
for(const id of ['scripture-power','choose-to-serve-the-lord']){await p.evaluate(id=>prototype.loadSong(id),id);await p.waitForFunction(()=>prototype.ready&&!prototype.busy);assert.equal(await p.locator('.score-heading .song-playback').count(),0);}
await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await p.context().setOffline(true);await p.reload();await p.locator('.library-row').first().waitFor();await p.evaluate(()=>prototype.loadSong('shepherd'));await ready();await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');assert(await p.evaluate(()=>prototype.playback.nodes>0));assert.deepEqual(errors,[]);await p.locator('.score-heading .song-playback').dispatchEvent('pointerdown',{clientX:10,clientY:10});await p.waitForTimeout(650);await p.locator('.score-heading .song-playback').dispatchEvent('pointerup');assert.equal(await p.evaluate(()=>prototype.playback.state),'stopped');const ended=await p.evaluate(async()=>{const {createPlayback}=await import('./playback.js');const h=document.createElement('h1');document.body.append(h);const engine=createPlayback(async()=>({key:'end-test',xml:'<score-partwise><part id="P"><measure><direction><sound tempo="6000"/></direction><note><pitch><step>C</step><octave>4</octave></pitch><duration>1</duration></note></measure></part></score-partwise>'}));engine.attach(h);h.querySelector('button').click();await new Promise(r=>setTimeout(r,400));const result={state:engine.state,nodes:engine.nodes};engine.stop();h.remove();return result;});assert.deepEqual(ended,{state:'stopped',nodes:0});console.log('PASS timeline, key/octave/reset, paired views, responsive, PDF, print exclusion and offline audio');
}finally{await b.close();}
