import {createRequire} from 'node:module';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';
const {chromium}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),b=await chromium.launch({channel:'msedge',headless:true});
try{
 const c=await b.newContext({viewport:{width:820,height:1180}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(process.env.TEST_URL||'http://127.0.0.1:8780/');await p.locator('.library-row').first().waitFor({state:'attached'});
 const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');
 const baseline=execFileSync('git',['show','72255d8:playback.js'],{encoding:'utf8'});
 // Parser and scheduler/state/control functions must remain byte-for-byte unchanged.
 const current=(await(await p.request.get(new URL('playback.js',p.url()).href)).text()).replaceAll('\r\n','\n');
 for(const [start,end] of [['export function scoreTimeline','export function createPlayback'],[' function schedule()',' async function toggle()'],[' function attach(',' return {']])assert.equal(current.slice(current.indexOf(start),current.indexOf(end)),baseline.slice(baseline.indexOf(start),baseline.indexOf(end)));
 const rendered=await p.evaluate(async()=>{const {createScoreVoice,configurePlaybackOutput}=await import('./playback-voices.js'),results=[];
  for(const sound of ['grand-piano','electric-piano','simple-tone']){const ctx=new OfflineAudioContext(1,48000*8,48000),master=ctx.createGain(),compressor=ctx.createDynamicsCompressor();configurePlaybackOutput(master,compressor,sound);master.connect(compressor);compressor.connect(ctx.destination);let voices=0,ended=0,oscillators=0,disconnected=0;const original=ctx.createOscillator.bind(ctx);ctx.createOscillator=()=>{const o=original(),disconnect=o.disconnect.bind(o);oscillators++;o.disconnect=()=>{disconnected++;disconnect();};return o;};
   const play=(midi,start,duration)=>{voices++;createScoreVoice(ctx,master,midi,start,duration,sound,()=>ended++);};
   [48,55,60].forEach(n=>play(n,.05,.25));for(let i=0;i<20;i++)[48,55,60,64].forEach(n=>play(n,.5+i*.15,.12));[36,43,48,52,55,60,64,67,72,76,79,84].forEach(n=>play(n,3.6,.8));play(60,4.5,2);
   const buffer=await ctx.startRendering(),data=buffer.getChannelData(0);let peak=0;for(const v of data){if(!Number.isFinite(v))throw Error('non-finite audio');peak=Math.max(peak,Math.abs(v));}const tail=Math.max(...data.slice(-2000).map(Math.abs));results.push({sound,peak,tail,voices,ended,oscillators,disconnected});
  }return results;
 });for(const r of rendered){assert(r.peak>0&&r.peak<.95,JSON.stringify(r));assert(r.tail<.00001);assert.equal(r.ended,r.voices);assert.equal(r.disconnected,r.oscillators);}console.log('PASS offline triads/repeated four-note chords/dense chords/long note',JSON.stringify(rendered));
 const hymn=await p.evaluate(async()=>{const {createScoreVoice,configurePlaybackOutput}=await import('./playback-voices.js'),{scoreTimeline}=await import('./playback.js'),{unpackMXL}=await import('./music.js'),{songs}=await import('./songs.js');const song=songs.find(s=>s.title==='The Spirit of God'),timeline=scoreTimeline(unpackMXL(await(await fetch(song.asset)).arrayBuffer())),ctx=new OfflineAudioContext(1,Math.ceil((timeline.duration+1)*24000),24000),master=ctx.createGain(),compressor=ctx.createDynamicsCompressor();configurePlaybackOutput(master,compressor,'grand-piano');master.connect(compressor);compressor.connect(ctx.destination);let ended=0;for(const n of timeline.notes)createScoreVoice(ctx,master,n.midi,n.start,n.duration,'grand-piano',()=>ended++);const buffer=await ctx.startRendering();let peak=0;for(const v of buffer.getChannelData(0))peak=Math.max(peak,Math.abs(v));return {notes:timeline.notes.length,ended,peak,duration:timeline.duration};});assert.equal(hymn.ended,hymn.notes);assert(hymn.peak<.95);console.log('PASS full SATB hymn offline render',hymn);
 assert.equal(await p.evaluate(()=>prototype.playback.sound),'grand-piano');await p.evaluate(()=>prototype.loadSong('hhc-1035'));await ready();const pdf=await p.locator('#score').innerHTML();
 const settings=async()=>{await p.locator('#settings').click();await p.waitForFunction(()=>document.querySelector('#tempo-value').textContent.includes('BPM'));};await settings();assert.equal(await p.evaluate(()=>prototype.playback.nodes),0);assert.equal(await p.evaluate(()=>prototype.playback.state),'stopped');
 await p.locator('#playback-sound').selectOption('electric-piano');assert.equal(await p.evaluate(()=>localStorage.getItem('music-transpose-playback-sound-v1')),'electric-piano');await p.locator('#close-settings').click();await p.reload();await p.locator('.library-row').first().waitFor({state:'attached'});assert.equal(await p.evaluate(()=>prototype.playback.sound),'electric-piano');await p.evaluate(()=>prototype.loadSong('hhc-1035'));await ready();
 await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await p.waitForFunction(async()=>!!await caches.match(new URL('./playback-voices.js',location.href)));
 await c.setOffline(true);await p.reload();await p.locator('.library-row').first().waitFor({state:'attached'});await p.evaluate(()=>prototype.loadSong('hhc-1035'));await ready();
 for(const sound of ['grand-piano','electric-piano','simple-tone']){await settings();await p.locator('#playback-sound').selectOption(sound);await p.locator('#close-settings').click();await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing'&&prototype.playback.nodes>0);assert(await p.locator('#score .pdf-page-frame').count()>0);await p.locator('.score-heading .song-playback').click();assert.equal(await p.evaluate(()=>prototype.playback.nodes),0);assert.equal(await p.evaluate(()=>prototype.playback.state),'paused');await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.state==='playing');await p.evaluate(()=>prototype.playback.stop());assert.equal(await p.evaluate(()=>prototype.playback.nodes),0);}
 await c.setOffline(false);await settings();await p.locator('#playback-sound').selectOption('grand-piano');await p.locator('#close-settings').click();await p.locator('.score-heading .song-playback').click();await p.waitForFunction(()=>prototype.playback.nodes>0);await settings();const before=await p.evaluate(()=>prototype.playback.position);await p.locator('#playback-sound').selectOption('electric-piano');assert.equal(await p.evaluate(()=>prototype.playback.state),'playing');assert((await p.evaluate(()=>prototype.playback.position))>=before);await p.locator('#tempo-up').click();await p.locator('#close-settings').click();await p.evaluate(()=>prototype.loadSong('choose-to-serve-the-lord'));await ready();assert.equal(await p.evaluate(()=>prototype.playback.nodes),0);assert.equal(await p.locator('.song-playback').count(),0);
 await p.evaluate(()=>prototype.loadSong('hhc-1035','normal'));await ready();await p.evaluate(()=>prototype.changeKey(2));await ready();await p.evaluate(()=>prototype.changeOctave(1));await ready();await p.evaluate(()=>prototype.playback.prepare());assert(await p.evaluate(async()=>JSON.stringify(prototype.playback.timeline)==JSON.stringify((await import('./playback.js')).scoreTimeline(prototype.xml))));
 await p.locator('#score-size').click();await p.locator('#score-size-options [data-size=large]').click();await ready();await p.evaluate(()=>prototype.playback.prepare());assert(await p.evaluate(async()=>JSON.stringify(prototype.playback.timeline)==JSON.stringify((await import('./playback.js')).scoreTimeline(prototype.viewXML))));
 for(const [width,height] of [[390,844],[820,1180],[1180,820],[1440,1000]]){await p.setViewportSize({width,height});await ready();await settings();const r=await p.locator('#playback-sound').boundingBox();assert(r.x>=0&&r.x+r.width<=width);assert.equal(await p.locator('#playback-sound').getAttribute('id'),'playback-sound');await p.locator('#playback-sound').focus();await p.keyboard.press('Home');await p.keyboard.press('ArrowDown');await p.locator('#close-settings').click();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 assert.deepEqual(errors,[]);console.log('PASS default/persistence/offline reload/all sounds, PDF, transpose/register/Melody, tempo/live sound change, pause/resume/stop/song cleanup, responsive selector');
}finally{await b.close();}
