import {setView,getView,setOrder,getOrder} from './library-controls-helper.mjs';
import {createRequire} from 'node:module';import assert from 'node:assert/strict';const require=createRequire(process.env.PLAYWRIGHT_PACKAGE),{chromium}=require('playwright');const b=await chromium.launch({channel:'msedge',headless:true}),c=await b.newContext(),p=await c.newPage(),base=process.env.TEST_URL||'http://127.0.0.1:8767/',phase=process.env.AUDIT_PHASE||'after';const errors=[];p.on('pageerror',e=>errors.push(e.message));const done=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.getElementById('score').getAttribute('aria-busy')==='false');
try{await p.goto(base);await p.locator('.library-row').first().waitFor();assert.equal(await p.locator('.library-row').count(),121);assert.equal(await p.locator('#score svg,#score canvas').count(),0);assert.equal(await p.evaluate(()=>performance.getEntriesByType('resource').filter(e=>/\.(mxl|pdf)(\?|$)/.test(e.name)).length),0);await p.evaluate(()=>localStorage.setItem('music-transpose-library-v1',JSON.stringify({orderingVersion:1,favorites:['nativity','scripture-power'],groups:[{id:'audit',name:'Practice',songs:['scripture-power','nativity','hhc-1001']}],recent:['nativity']})));await p.reload();await p.locator('.library-row').first().waitFor();
for(const [width,height] of [[375,812],[820,1180],[1180,820],[1440,1000]]){await p.setViewportSize({width,height});await p.locator('#library-list').selectOption('');await setView(p,'all');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/polish-${phase}-library-${width}.png`});if(phase==='after')assert.equal(await p.locator('.library-header-panel').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(226, 232, 236)');
await setView(p,'favorites');await p.locator('#reorder-list').click();await p.screenshot({path:`test-results/polish-${phase}-reorder-${width}.png`});await p.locator('#reorder-list').click();await setView(p,'all');await p.locator('#library-list').selectOption('audit');assert.equal(await p.locator('.library-row').count(),3);await p.locator('#library-list').selectOption('@manage-lists');assert.equal(await p.locator('#library-list').inputValue(),'audit');await p.screenshot({path:`test-results/polish-${phase}-manage-${width}.png`});await p.locator('#close-lists').click();await p.locator('#library-list').selectOption('');
await p.locator('#library-search').fill('zzzz-unmatched');assert(await p.locator('.empty-library').isVisible());await p.locator('#library-search').fill('');
for(const id of ['nativity','hhc-1001','scripture-power','choose-to-serve-the-lord']){await p.locator(`[data-song="${id}"] .song-entry`).click();await done();assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`test-results/polish-${phase}-${id}-${width}.png`});await p.locator('#settings').click();assert(await p.locator('#settings-dialog').isVisible());const box=await p.locator('#settings-dialog').boundingBox();assert(box.x>=0&&box.x+box.width<=width);if(id==='nativity')await p.screenshot({path:`test-results/polish-${phase}-settings-${width}.png`});await p.locator('#close-settings').click();if(id==='nativity'){await p.locator('#key').click();await p.screenshot({path:`test-results/polish-${phase}-key-${width}.png`});await p.locator('#close-dialog').click();}await p.locator('#songs').click();}
}
assert.deepEqual(errors,[]);console.log('PASS live UI audit: Library, Favorites/reorder, ordered list/Manage, empty state, MXL/PDF, Settings/key panels, four widths, metadata-only startup, no page errors');}finally{await b.close();}
