import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const engines=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),engine=process.env.WEBKIT?'webkit':'chromium',b=await engines[engine].launch(engine==='chromium'?{channel:'msedge',headless:true}:{});
try{for(const [width,height] of [[320,740],[390,844],[820,1180],[1180,820],[1440,1000]]){
 const c=await b.newContext({viewport:{width,height},hasTouch:width<1440,serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await c.addInitScript(()=>{if(!localStorage.getItem('row-seed')){localStorage.setItem('row-seed','1');localStorage.setItem('music-transpose-library-v1',JSON.stringify({orderingVersion:1,favorites:[],groups:[{id:'a',name:'Prelude',songs:['nativity','cs-168','hhc-1054']}]}));}});
 const pick=async id=>{await p.locator('#library-source').click();await p.locator(`[data-source="${id}"]`).click();};
 const ids=()=>p.locator('.library-row').evaluateAll(es=>es.map(e=>e.dataset.song));
 const input=p.locator('#library-search'),clear=p.locator('#library-clear');
 await p.goto(process.env.TEST_URL||'http://127.0.0.1:8780/');await p.locator('.library-row').first().waitFor();
 assert.equal(await p.locator('.song-view-actions,.lyrics-slot,.song-view-heading').count(),0);assert(!await p.locator('#library').getByTitle('Lyrics',{exact:true}).count());assert(!await p.locator('#library').getByTitle('Lead sheet',{exact:true}).count());
 await pick('hymnal');assert.equal(await p.locator('#library-source-label').textContent(),'Hymns');await pick('my-music');assert.equal(await p.locator('#library-source-label').textContent(),'My Music');await pick('list:a');await p.locator('#order-toggle').selectOption('number');
 const original=await ids(),source=await p.locator('#library-source-label').textContent(),sort=await p.locator('#order-toggle').inputValue();assert(await clear.isHidden());
 assert(await p.locator('#library-source-label').evaluate(e=>Number(getComputedStyle(e).fontWeight)>Number(getComputedStyle(e.parentElement).fontWeight)));
 await input.fill('Nativity');assert(await clear.isVisible());assert.equal(await clear.getAttribute('aria-label'),'Clear search');
 const geometry=await p.evaluate(()=>{const q=document.querySelector('#library-search'),x=document.querySelector('#library-clear'),r=q.getBoundingClientRect(),a=x.getBoundingClientRect(),row=q.closest('.library-search-row').getBoundingClientRect(),scope=document.querySelector('.search-scope').getBoundingClientRect(),more=document.querySelector('#library-more').getBoundingClientRect();return {width:r.width,row:row.width,x:a.x,right:a.right,inputRight:r.right,left:r.left,target:a.width,height:a.height,padding:parseFloat(getComputedStyle(q).paddingRight),scope:scope.left,more:more.left,scopeRight:scope.right,overflow:document.documentElement.scrollWidth>innerWidth};});
 assert(!geometry.overflow);assert(geometry.x>=geometry.left&&geometry.right<=geometry.inputRight+.5);assert(geometry.padding>=44&&geometry.target>=44&&geometry.height>=44);assert(geometry.scope>=geometry.inputRight&&geometry.more>=geometry.scopeRight);if(width>600)assert(geometry.width>=480&&geometry.width<=520);else assert(Math.abs(geometry.width-(geometry.row-88))<1);
 await clear.click();assert(await input.evaluate(e=>e===document.activeElement));assert(await clear.isHidden());assert.deepEqual(await ids(),original);assert.equal(await p.locator('#library-source-label').textContent(),source);assert.equal(await p.locator('#order-toggle').inputValue(),sort);
 await p.keyboard.type('Nativity');await p.keyboard.press('Escape');assert.equal(await input.inputValue(),'');assert(await input.evaluate(e=>e===document.activeElement));assert.deepEqual(await ids(),original);
 await p.locator('[data-song=nativity] .favorite').click();assert.equal(await p.locator('[data-song=nativity] .favorite').getAttribute('aria-pressed'),'true');
 for(const row of await p.locator('.library-row').all()){const g=await row.evaluate(e=>{const a=e.querySelector('.song-entry').getBoundingClientRect(),f=e.querySelector('.favorite').getBoundingClientRect();return {end:a.right,favorite:f.left,right:f.right,width:a.width};});assert(g.width>60&&g.end<=g.favorite+1&&g.right<=width);}
 await p.locator('#edit-list-order').click();assert(await input.isDisabled());assert.equal(await p.locator('.reorder-grip').count(),3);for(const button of await p.locator('.list-row-tools button').all()){const r=await button.boundingBox();assert(r.width>=44&&r.height>=44&&r.x>=0&&r.x+r.width<=width);}
 await p.locator('[data-song=nativity] button[aria-label^="Move down"]').click();await p.locator('#edit-list-order').click();const reordered=await ids();assert.deepEqual(reordered,['cs-168','nativity','hhc-1054']);await p.reload();await p.locator('.library-row').first().waitFor();assert.deepEqual(await ids(),reordered);
 await p.locator('[data-song=nativity] .song-entry').click();await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');await p.locator('#songs').click();assert.equal(await p.locator('#library-source-label').textContent(),'Prelude');assert(await p.locator('[data-song=nativity]').evaluate(e=>e.classList.contains('current-song')));
 await input.fill('Nativity');await p.screenshot({path:`test-results/library-navigation-${engine}-${width}.png`});assert.deepEqual(errors,[]);console.log('PASS source emphasis, simplified rows, favorite, inline clear/focus/Escape/state, width, reorder/persistence and title return',engine,width,height);await c.close();
}}finally{await b.close();}
