import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');const browser=await chromium.launch({channel:'msedge'});
try{for(const width of [390,744,820,1440]){const c=await browser.newContext({viewport:{width,height:1000},...(width===390?{userAgent:'iPhone'}:{})});const p=await c.newPage();await p.goto(process.env.APP_URL||'http://127.0.0.1:8780/');await p.waitForFunction(()=>prototype?.navigation);const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!prototype.loading);const tools=async()=>{await p.locator('#score-tools').click();await p.locator('#score-frame').waitFor({state:'visible'});};const toggle=async key=>{await tools();await p.locator('#score-frame').focus();await p.locator('#score-frame').press(key||'Enter');assert(await p.locator('#score-tools-menu').isHidden());};
 const snapshot=()=>p.evaluate(()=>({rects:[...document.querySelectorAll('.score-paper,#score,.masthead,#score svg,#score canvas,.pdf-page-frame,.mxl-page-frame')].map(e=>({tag:e.tagName,rect:e.getBoundingClientRect().toJSON(),viewBox:e.getAttribute('viewBox'),width:e.getAttribute('width'),height:e.getAttribute('height'),style:e.getAttribute('style')})),mode:document.getElementById('score-navigation-label').textContent,page:document.getElementById('page-position')?.textContent,xml:prototype.viewXML,body:document.body.className,scroll:[scrollX,scrollY],auto:document.getElementById('auto-toggle').textContent}));
 const ink=()=>p.locator('.score-paper').evaluate(e=>[getComputedStyle(e).borderTopColor,getComputedStyle(e,'::after').borderTopColor,getComputedStyle(e,'::before').content==='none'?'rgba(0, 0, 0, 0)':getComputedStyle(e,'::before').borderBottomColor]);
 assert.equal(await p.locator('#score-frame').getAttribute('aria-checked'),'true');assert(await p.locator('#score-frame-input').isChecked());
 for(const id of ['nativity','scripture-power']){await p.evaluate(id=>prototype.loadSong(id),id);await ready();const pdf=id==='scripture-power';if(!pdf){await p.evaluate(()=>prototype.changeKey(1));await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!prototype.loading&&prototype.current===1&&document.querySelector('#score svg'));}assert.equal(await p.locator('#score canvas.pdf-page').count()>0,pdf);
 for(const dark of [false,true]){await tools();assert.equal((await p.locator('#score-trim').textContent()).trim(),'Trim margins');assert.equal(await p.locator('#score-frame').getAttribute('role'),'menuitemcheckbox');assert.equal((await p.locator('#score-frame').textContent()).trim(),'Show score frame');assert(await p.locator('#score-frame').evaluate(e=>e.previousElementSibling.id==='score-trim'&&e.nextElementSibling.id==='score-page-theme'));assert((await p.locator('#score-frame').boundingBox()).height>=44);if(pdf)assert(await p.locator('#score-trim').isVisible());else assert(await p.locator('#score-trim').isHidden());if(dark)await p.locator('#score-page-theme').click();else await p.keyboard.press('Escape');
 for(const mode of ['pages','continuous','auto']){await p.locator('#score-navigation-button').click();await p.locator(`[data-navigation="${mode}"]`).click();if(mode==='auto')await p.keyboard.press('Escape');await p.mouse.move(0,0);await p.evaluate(()=>scrollTo(0,0));const before=await snapshot(),visible=await ink();assert.notEqual(visible[0],'rgba(0, 0, 0, 0)');assert.notEqual(visible[1],'rgba(0, 0, 0, 0)');await toggle('Enter');assert.equal(await p.locator('#score-frame').getAttribute('aria-checked'),'false');assert((await ink()).every(v=>v==='rgba(0, 0, 0, 0)'));assert.deepEqual(await snapshot(),before,`${width} ${id} ${dark} ${mode}: frame OFF leaves score geometry/state unchanged`);await toggle('Space');assert.deepEqual(await ink(),visible);assert.deepEqual(await snapshot(),before,`${width} ${id} ${dark} ${mode}: frame ON leaves score geometry/state unchanged`);}
 if(dark){await tools();await p.locator('#score-page-theme').click();}}
 if(pdf){await p.locator('#score-navigation-button').click();await p.locator('[data-navigation="pages"]').click();const original=await p.locator('.pdf-page-frame').first().getAttribute('data-trim');await tools();await p.locator('#score-trim').press('Enter');assert.equal(await p.locator('#score-trim').getAttribute('aria-checked'),'false');assert.equal(await p.evaluate(()=>sessionStorage.getItem('music-transpose-pdf-trim-v1')),'false');assert.notEqual(await p.locator('.pdf-page-frame').first().getAttribute('data-trim'),original);await tools();await p.locator('#score-trim').press('Space');assert.equal(await p.locator('.pdf-page-frame').first().getAttribute('data-trim'),original);}
 }
 await toggle();if(width>600){await p.locator('#score-hide-controls').click();assert(await p.locator('#playing-view').evaluate(e=>e.classList.contains('score-frame-hidden')));await p.locator('#score-show-controls').click();assert(await p.locator('#playing-view').evaluate(e=>e.classList.contains('score-frame-hidden')));}else assert(await p.locator('#score-hide-controls').isHidden());await p.reload();await ready();assert.equal(await p.locator('#score-frame').getAttribute('aria-checked'),'false');assert((await ink()).every(v=>v==='rgba(0, 0, 0, 0)'));await p.evaluate(()=>prototype.loadSong('nativity'));await ready();assert.equal(await p.locator('#score-frame').getAttribute('aria-checked'),'false');await tools();await p.keyboard.press('Home');for(let n=0;n<8;n++){if(await p.locator('#score-frame').evaluate(e=>e===document.activeElement))break;await p.keyboard.press('ArrowDown');}assert(await p.locator('#score-frame').evaluate(e=>e===document.activeElement&&getComputedStyle(e).outlineStyle==='solid'));await p.screenshot({path:`test-results/score-frame-${width}.png`});await p.keyboard.press('Enter');assert.equal(await p.locator('#score-frame').getAttribute('aria-checked'),'true');console.log('PASS frame toggle, structured/PDF geometry, trim, all navigation modes, themes, Focus independence, keyboard and persistence',width);await c.close();}
}finally{await browser.close();}
