import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium,webkit}=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),browser=await (process.env.WEBKIT?webkit:chromium).launch(process.env.WEBKIT?{}:{channel:'msedge',headless:true});
const ready=p=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');
try{for(const [width,height] of [[320,568],[390,844],[844,390],[820,1180],[1440,1000]]){
const c=await browser.newContext({viewport:{width,height},hasTouch:width!==1440}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.addInitScript(()=>localStorage.setItem('music-transpose-navigation-v1',JSON.stringify({mode:'pages'})));
await p.goto(process.env.TEST_URL||'http://127.0.0.1:8771/');await p.locator('.library-row').first().waitFor();await p.evaluate(()=>prototype.loadSong('nativity','normal'));await ready(p);await p.waitForTimeout(200);
const before=await p.locator('#page-position').textContent(),frames=await p.locator('.mxl-page-frame').count();
await p.locator('#score-tools').click();assert.equal(await p.locator('#score-tools').getAttribute('aria-expanded'),'true');assert.equal(await p.locator('#print').count(),1);
const menu=await p.locator('#score-tools-menu').boundingBox(),button=await p.locator('#score-tools').boundingBox();assert(Math.abs(button.y-menu.y-menu.height-9)<1);assert(menu.x>=0&&menu.y>=0&&menu.x+menu.width<=width);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert(await p.locator('#score-tools-menu button').nth(1).isDisabled());await p.screenshot({path:`test-results/score-tools-${process.env.WEBKIT?'webkit':'edge'}-${width}.png`});
await p.keyboard.press('End');assert.equal(await p.evaluate(()=>document.activeElement.id),'score-page-theme');await p.keyboard.press('Home');assert.equal(await p.evaluate(()=>document.activeElement.id),'print');await p.keyboard.press('Escape');assert(await p.locator('#score-tools-menu').isHidden());assert.equal(await p.evaluate(()=>document.activeElement.id),'score-tools');
await p.locator('#score-tools').click();await p.locator('#score').click({position:{x:40,y:50}});assert(await p.locator('#score-tools-menu').isHidden());assert.equal(await p.locator('#page-position').textContent(),before);
await p.locator('#score-tools').click();await p.locator('#score-page-theme').click();assert(await p.locator('#score-tools-menu').isHidden());assert.equal(await p.locator('#score-page-theme').textContent(),'Light page');assert.equal(await p.locator('#score-page-theme').getAttribute('aria-pressed'),'true');assert(await p.locator('#score-tools').evaluate(e=>e.classList.contains('has-active-tool')));assert.match(await p.locator('#score').evaluate(e=>getComputedStyle(e).filter),/invert/);assert.equal(await p.locator('.masthead').evaluate(e=>getComputedStyle(e).filter),'none');assert.equal(await p.locator('.mxl-page-frame').count(),frames);
await p.locator('#settings').click();assert(await p.locator('#settings-dialog').isVisible());await p.locator('input[name=navigation][value=continuous]').check();await p.locator('#close-settings').click();assert(!await p.locator('body').evaluate(e=>e.classList.contains('mxl-page-navigation')));await p.locator('#score-tools').click();await p.keyboard.press('Escape');await p.locator('#settings').click();await p.locator('input[name=navigation][value=pages]').check();await p.locator('#close-settings').click();
if(width===820){await p.evaluate(()=>{window.printCalls=0;window.print=()=>window.printCalls++;});await p.locator('#score-tools').click();await p.locator('#print').click();await p.waitForFunction(()=>window.printCalls===1);assert(await p.locator('#score-tools-menu').isHidden());assert(await p.locator('#print-pages .print-page').count()>0);await p.emulateMedia({media:'print'});assert.equal(await p.locator('#score').evaluate(e=>getComputedStyle(e).filter),'none');await p.emulateMedia({media:'screen'});await p.evaluate(()=>dispatchEvent(new Event('afterprint')));}
if(width===390&&!process.env.WEBKIT){await p.evaluate(()=>navigator.serviceWorker.ready);await p.waitForFunction(()=>navigator.serviceWorker.controller);await c.setOffline(true);await p.reload();await ready(p);await p.locator('#score-tools').click();assert.equal(await p.locator('#score-page-theme').textContent(),'Light page');await p.locator('#score-page-theme').click();assert.equal(await p.locator('#score').evaluate(e=>getComputedStyle(e).filter),'none');await c.setOffline(false);}
if(width===820){await p.evaluate(()=>prototype.loadSong('choose-to-serve-the-lord'));await ready(p);await p.waitForTimeout(200);assert(await p.locator('.pdf-page-frame').count()>1);const old=await p.locator('#page-position').textContent();await p.locator('#score-tools').click();await p.locator('#score').click({position:{x:40,y:100}});assert.equal(await p.locator('#page-position').textContent(),old);await p.keyboard.press('ArrowRight');assert.notEqual(await p.locator('#page-position').textContent(),old);await p.locator('#score-tools').click();await p.screenshot({path:`test-results/score-tools-pdf-${process.env.WEBKIT?'webkit':'edge'}.png`});await p.evaluate(()=>{window.printCalls=0;window.print=()=>window.printCalls++;});await p.locator('#print').click();await p.waitForFunction(()=>window.printCalls===1);assert(await p.locator('#print-pages .pdf-print-page').count()>0);console.log('PASS PDF tools, dark page, page turn and print');}
assert.deepEqual(errors,[]);console.log('PASS Tools',width,height,'menu, keyboard, theme, settings, navigation',width===820?'print':'',width===390&&!process.env.WEBKIT?'offline':'');await c.close();}
}finally{await browser.close();}
