import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const {chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright'),b=await chromium.launch({channel:'msedge'});
try{for(const width of [390,820,1440]){
 const c=await b.newContext({viewport:{width,height:width===390?740:1000},hasTouch:width<1000,serviceWorkers:'block'}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8780/');await p.waitForFunction(()=>window.prototype?.navigation);
 const ready=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&!prototype.loading&&document.querySelector('#score').getAttribute('aria-busy')==='false');
 const mode=async name=>{await p.locator('#score-navigation-button').click();await p.locator(`[data-navigation=${name}]`).click();if(name==='auto')await p.keyboard.press('Escape');await p.waitForTimeout(250);};
 const geometry=()=>p.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return [r.x,r.y+scrollY,r.width,r.height];};return {footer:document.querySelector('.masthead').offsetHeight,reserve:document.documentElement.style.getPropertyValue('--playing-bar-height'),score:rect(document.querySelector('#score')),nodes:[...document.querySelectorAll('#score svg,#score canvas')].map(rect),count:document.querySelector('#score-navigation-label').textContent,xml:prototype.original};});
 const toggle=async()=>{const before=await geometry(),y=await p.evaluate(()=>scrollY);await p.locator('#score-hide-controls')[width<1000?'tap':'click']();assert(await p.locator('#score-show-controls').isVisible());assert.equal(await p.locator('#key').isVisible(),false);assert.deepEqual(await geometry(),before);assert.equal(await p.evaluate(()=>scrollY),y);const box=await p.locator('#score-show-controls').boundingBox();assert(box.width===44&&box.height===44);await p.screenshot({path:`test-results/focus-${width}.png`});await p.locator('#score-show-controls')[width<1000?'tap':'click']();assert(await p.locator('#key').isVisible());assert.deepEqual(await geometry(),before);assert.equal(await p.evaluate(()=>scrollY),y);assert.equal(await p.evaluate(()=>document.activeElement.id),'score-hide-controls');};
 await p.locator('[data-home-source=all]').click();await p.locator('[data-song=song-138d4697-d2d9-414a-885c-82b760f1f371] .song-entry').click();await ready();
 for(const format of ['pdf','structured']){
  if(format==='structured'){await p.locator('#key').click();await p.locator('#key-dialog [data-shift="0"]').click();await ready();}
  for(const kind of ['pages','continuous','auto']){
   await mode(kind);await toggle();
   if(kind==='pages'){const label=await p.locator('#score-navigation-label').textContent();await p.locator('#score').click({position:{x:180,y:160}});await p.keyboard.press('ArrowRight');assert.notEqual(await p.locator('#score-navigation-label').textContent(),label);}
   else{await p.evaluate(()=>scrollTo({top:400,behavior:'instant'}));await p.waitForTimeout(100);await p.locator('#score-hide-controls').click();assert.equal(await p.locator('.return-start:visible').count(),2);await p.locator('#return-start-left').click();assert.equal(await p.evaluate(()=>scrollY),0);await p.locator('#score-show-controls').click();}
   if(kind==='auto'){await p.locator('#score-navigation-button').click();await p.locator('#auto-toggle').click();const speed=await p.locator('#scroll-speed').inputValue();for(const id of ['score-hide-controls','score-show-controls']){await p.locator('#'+id)[width<1000?'tap':'click']();assert.equal(await p.locator('#auto-toggle').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('#scroll-speed').inputValue(),speed);}await p.keyboard.press('Space');assert(await p.locator('#score-show-controls').isVisible());await p.keyboard.press('Enter');assert(await p.locator('#score-hide-controls').isVisible());assert.equal(await p.locator('#auto-toggle').getAttribute('aria-pressed'),'true');await p.locator('#score').dispatchEvent('wheel',{deltaY:40});assert.equal(await p.locator('#auto-toggle').getAttribute('aria-pressed'),'false');}
  }
 }
 await mode('continuous');await p.locator('#score-size').click();await p.locator('[data-size=large]').click();await ready();await toggle();
 await p.locator('#score-hide-controls').click();await mode('auto');assert(await p.locator('#score-show-controls').isVisible());await p.locator('#score-show-controls').click();
 const controls=await p.locator('.masthead button:visible').evaluateAll(es=>es.filter(e=>!e.closest('[role=menu]')).map(e=>{const r=e.getBoundingClientRect();return {id:e.id,x:r.x,right:r.right,w:r.width,h:r.height};}));for(const r of controls){assert(r.x>=0&&r.right<=width,JSON.stringify(r));assert(r.w>=44&&r.h>=44,JSON.stringify(r));}
 for(const [button,panel] of [['#key','#key-dialog'],['#score-size','#score-size-options'],['#score-tools','#score-tools-menu']]){await p.locator(button).click();assert(await p.locator(panel).isVisible());await p.keyboard.press('Escape');}
 assert(await p.locator('#previous-song').isVisible());assert(await p.locator('#next-song').isVisible());assert(await p.locator('#score-navigation-button').isVisible());
 if(await p.locator('#show-lyrics').isVisible()){await p.locator('#show-lyrics').click();assert(await p.locator('#lyrics-view').isVisible());}
 assert.deepEqual(errors,[]);console.log('PASS',width,'Focus geometry, PDF/structured x three modes, Auto-scroll, Back-to-Top, restored controls');await c.close();
}}finally{await b.close();}
