import {createRequire} from 'node:module';import assert from 'node:assert/strict';const require=createRequire(process.env.PLAYWRIGHT_PACKAGE),{chromium}=require('playwright');const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const done=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.getElementById('score').getAttribute('aria-busy')==='false');
try{await p.goto(process.env.TEST_URL||'http://127.0.0.1:8767/');await p.locator('.library-row').first().waitFor();
for(const id of ['cs-236','nativity','shepherd','faithful','silent-night']){
 await p.locator(`[data-song="${id}"] .song-entry`).click();await done();assert(await p.locator('#score-fit').isVisible());assert.equal(await p.locator('#score-fit').getAttribute('aria-label'),'Fit score to page');const xml=await p.evaluate(()=>prototype.xml),h=await p.locator('#score').evaluate(e=>e.getBoundingClientRect().height);await p.evaluate(()=>prototype.preparePrint());const printBefore=await p.locator('#print-pages').textContent();const geometry=()=>p.locator('#print-pages svg').evaluateAll(es=>es.map(e=>[e.getAttribute('viewBox'),...Array.from(e.querySelectorAll('path')).map(n=>n.getAttribute('d'))]));const printGeometry=await geometry();
 await p.locator('#score-fit').click();await p.waitForTimeout(80);assert.equal(await p.locator('#score-fit').getAttribute('aria-label'),'Fit score to width');const ratio=await p.locator('#score').evaluate(e=>e.getBoundingClientRect().height)/h;assert(Math.abs(ratio-.72)<.01);assert.equal(await p.evaluate(()=>prototype.xml),xml);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert(await p.evaluate(()=>{const button=document.getElementById('score-fit').getBoundingClientRect();return [...document.querySelectorAll('.score-heading h1,.score-heading .subtitle,#score')].every(e=>{const r=e.getBoundingClientRect();return Math.min(r.right,button.right)<=Math.max(r.left,button.left)||Math.min(r.bottom,button.bottom)<=Math.max(r.top,button.top);});}));
 await p.screenshot({path:`test-results/fit-page-${id}.png`});await p.evaluate(()=>prototype.preparePrint());assert.equal(await p.locator('#print-pages').textContent(),printBefore);assert.deepEqual(await geometry(),printGeometry);await p.emulateMedia({media:'print'});assert(await p.locator('#score-fit').isHidden());assert.equal(await p.locator('#score').evaluate(e=>getComputedStyle(e).transform),'none');await p.emulateMedia({media:'screen'});
 await p.locator('#up').click();await done();assert.equal(await p.locator('#score-fit').getAttribute('data-fit'),'page');await p.locator('#reset').click();await done();assert.equal(await p.locator('#score-fit').getAttribute('data-fit'),'page');await p.locator('#score-fit').click();assert.equal(await p.locator('#score-fit').getAttribute('data-fit'),'width');await p.locator('#score-fit').click();await p.locator('#songs').click();await p.locator(`[data-song="${id}"] .song-entry`).click();await done();assert.equal(await p.locator('#score-fit').getAttribute('data-fit'),'width');await p.locator('#songs').click();console.log('PASS fit/print/reset/reopen',id);
}
await p.locator('[data-song="nativity"] .song-entry').click();await done();for(const [width,height] of [[375,812],[390,844],[768,1024],[820,1180],[1180,820],[1440,1000]]){await p.setViewportSize({width,height});await p.waitForTimeout(500);await done();assert.equal(await p.locator('#score-fit').isVisible(),width<=600);if(width>600)assert.equal(await p.locator('#score').evaluate(e=>getComputedStyle(e).transform),'none');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const ys=await p.locator('.toolbar button:visible').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().y));assert(Math.max(...ys)-Math.min(...ys)<1);await p.screenshot({path:`test-results/fit-layout-${width}.png`});}
await p.locator('#songs').click();await p.setViewportSize({width:390,height:844});for(const id of ['scripture-power','choose-to-serve-the-lord']){await p.locator(`[data-song="${id}"] .song-entry`).click();await done();assert(await p.locator('#score-fit').isHidden());assert(await p.locator('.pdf-page').count());await p.locator('#songs').click();}assert.deepEqual(errors,[]);console.log('PASS responsive visibility, no overflow, single-row toolbar, PDF unchanged');}finally{await b.close();}
