import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const engines=createRequire(process.env.PLAYWRIGHT_PACKAGE)('playwright'),engine=process.env.WEBKIT?'webkit':'chromium';
const browser=await engines[engine].launch(engine==='chromium'?{channel:'msedge',headless:true}:{});
try{for(const [width,height] of [[320,740],[390,844],[820,1180],[1180,820],[1440,1000]]){
 if(process.env.EXPORT_WIDTH&&width!==Number(process.env.EXPORT_WIDTH))continue;
 const c=await browser.newContext({viewport:{width,height},hasTouch:width<1440,serviceWorkers:'block',acceptDownloads:true}),p=await c.newPage(),errors=[];
 p.on('pageerror',e=>errors.push(e.message));await c.addInitScript(()=>localStorage.setItem('music-transpose-navigation-v1',JSON.stringify({mode:'pages'})));
 const ready=async()=>{await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.querySelector('#score').getAttribute('aria-busy')==='false');await p.waitForTimeout(180);};
 const load=async id=>{await p.evaluate(id=>prototype.loadSong(id),id);await ready();};
 const view=async name=>{await p.locator('#score-size').click();await p.locator(`#score-size-options [data-size=${name}]`).click();await ready();};
 const tools=p.locator('#score-tools-menu'),sub=p.locator('#score-export-options');
 const open=async()=>{await p.locator('#score-tools').click();await p.locator('#score-export').click();assert(await sub.isVisible());const r=await tools.boundingBox();assert(r.x>=7&&r.y>=7&&r.x+r.width<=width-7&&r.y+r.height<=height,'export menu within viewport');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));};
 const download=async format=>{await open();const promise=p.waitForEvent('download');await p.locator('#score-export-'+format).click();const d=await promise;assert.equal(await d.failure(),null);const bytes=await fs.readFile(await d.path());assert(await tools.isHidden());assert.equal(await p.evaluate(()=>document.activeElement.id),'score-tools');return {bytes,name:d.suggestedFilename()};};
 const parse=xml=>p.evaluate(xml=>{const d=new DOMParser().parseFromString(xml,'application/xml');if(d.querySelector('parsererror'))throw Error('Invalid exported XML');const notes=[...d.querySelectorAll('note')];return {root:d.documentElement.localName,parts:d.querySelectorAll('score-partwise > part').length,notes:notes.length,harmony:d.querySelectorAll('harmony').length,measures:d.querySelectorAll('part > measure').length,anchors:[...d.querySelectorAll('voice')].filter(e=>e.textContent==='lead-harmony-spacing').length,fifths:d.querySelector('key fifths')?.textContent,pitches:notes.filter(n=>n.querySelector('pitch')).map(n=>{const q=n.querySelector('pitch');return 12*(Number(q.querySelector('octave').textContent)+1)+({C:0,D:2,E:4,F:5,G:7,A:9,B:11}[q.querySelector('step').textContent])+Number(q.querySelector('alter')?.textContent||0);})};},xml);
 const print=async()=>{await p.evaluate(()=>{window.exportPrintCalls=0;window.print=()=>exportPrintCalls++;window.exportSavedLoad=opensheetmusicdisplay.OpenSheetMusicDisplay.prototype.load;opensheetmusicdisplay.OpenSheetMusicDisplay.prototype.load=function(xml){window.exportPrintInput=xml;return exportSavedLoad.call(this,xml);};});await open();assert.equal(await p.locator('#score-export-pdf-label').textContent(),'Save / Print PDF');await p.locator('#score-export-pdf').click();await p.waitForFunction(()=>exportPrintCalls===1);await p.evaluate(()=>opensheetmusicdisplay.OpenSheetMusicDisplay.prototype.load=exportSavedLoad);const printed=await parse(await p.evaluate(()=>exportPrintInput)),musical=await parse(await p.evaluate(()=>prototype.viewXML));assert.deepEqual(printed.pitches,musical.pitches);assert.equal(printed.harmony,musical.harmony);assert(await tools.isHidden());assert(await p.locator('#print-pages .print-page svg').count()>0);assert.equal(await p.locator('#print-pages .pdf-annotation-canvas,#print-pages #page-position,#print-pages #page-turn-feedback').count(),0);await p.emulateMedia({media:'print'});assert(await p.locator('#page-position').isHidden());await p.emulateMedia({media:'screen'});await p.evaluate(()=>dispatchEvent(new Event('afterprint')));};
 await p.goto(process.env.TEST_URL||'http://127.0.0.1:8780/');await p.locator('.library-row').first().waitFor();
 // PDF-only: real original bytes, disabled MusicXML and keyboard skips it.
 await load('choose-to-serve-the-lord');await open();assert(await p.locator('#score-export-xml').isDisabled());assert.match(await p.locator('#score-export-xml').getAttribute('aria-description'),/not available/);await p.keyboard.press('End');assert.equal(await p.evaluate(()=>document.activeElement.id),'score-export-pdf');await p.keyboard.press('Escape');assert(await sub.isHidden());assert.equal(await p.evaluate(()=>document.activeElement.id),'score-export');await p.keyboard.press('ArrowRight');assert(await sub.isVisible());await p.keyboard.press('ArrowLeft');assert(await sub.isHidden());await p.keyboard.press('Escape');assert(await tools.isHidden());assert.equal(await p.evaluate(()=>document.activeElement.id),'score-tools');
 const expected=await p.evaluate(async()=>Array.from(new Uint8Array(await(await fetch(document.querySelector('#pdf-original').href)).arrayBuffer())));
 const pdf=await download('pdf');assert.deepEqual(pdf.bytes,Buffer.from(expected));assert.match(pdf.name,/\.pdf$/);
 const before=await p.locator('#page-position').textContent();await open();await p.locator('#score').click({position:{x:30,y:90}});assert(await tools.isHidden());assert.equal(await p.locator('#page-position').textContent(),before);
 await open();await p.screenshot({path:`test-results/export-${engine}-${width}-pdf-only.png`});await p.keyboard.press('Escape');await p.keyboard.press('Escape');
 // Cached, loaded PDF data needs no network, including while annotations exist.
 await p.locator('#score-tools').click();await p.locator('#score-annotate').click();await p.locator('.current-page .pdf-annotation-canvas').evaluate(el=>{const r=el.getBoundingClientRect();for(const [type,dx] of [['pointerdown',0],['pointermove',30],['pointerup',30]])el.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:19,isPrimary:true,button:0,pointerType:'pen',clientX:r.x+r.width*.4+dx,clientY:r.y+r.height*.4}));});
 assert(await p.evaluate(()=>JSON.stringify(localStorage.getItem('music-transpose-pdf-annotations-v1')).includes('points')));await c.setOffline(true);const offlinePdf=await download('pdf');assert.deepEqual(offlinePdf.bytes,pdf.bytes);await c.setOffline(false);await p.locator('#pdf-annotation-done').click();
 // PDF+XML, cold Original has source XML even before any XML engraving.
 await load('hhc-1035');const original=await p.evaluate(()=>prototype.original);const ox=await download('xml');assert.equal(ox.bytes.toString('utf8'),original);assert.match(ox.name,/As I Keep the Sabbath Day\.musicxml$/);
 await view('auto');const source=await parse(original);
 // Requested but not committed changes must disable both formats immediately.
 const pending=await p.evaluate(()=>{prototype.changeKey(2);return ['score-export','score-export-pdf','score-export-xml'].map(id=>document.getElementById(id).disabled);});assert.deepEqual(pending,[true,true,true]);await ready();
 let output=await download('xml'),xml=output.bytes.toString('utf8');assert.equal(xml,await p.evaluate(()=>prototype.xml));let parsed=await parse(xml);assert.equal(parsed.root,'score-partwise');assert.deepEqual(parsed.pitches,source.pitches.map(n=>n+2));assert.notEqual(parsed.fifths,source.fifths);assert.equal(parsed.harmony,source.harmony);assert.match(output.name,/Major\.musicxml$/);
 await p.evaluate(()=>prototype.changeOctave(1));await ready();output=await download('xml');xml=output.bytes.toString('utf8');parsed=await parse(xml);assert.equal(xml,await p.evaluate(()=>prototype.xml));assert.deepEqual(parsed.pitches,source.pitches.map(n=>n+14));
 await open();await p.screenshot({path:`test-results/export-${engine}-${width}-transpose.png`});await p.keyboard.press('Escape');await p.keyboard.press('Escape');await print();assert.match(await p.locator('#print-pages .print-key').first().textContent(),/major/);
 await view('large');await p.evaluate(()=>prototype.changeOctave(-1));await ready();assert(await p.evaluate(()=>prototype.lead.ok));
 await c.setOffline(true);output=await download('xml');xml=output.bytes.toString('utf8');assert.equal(xml,await p.evaluate(()=>prototype.viewXML));parsed=await parse(xml);assert.deepEqual({parts:parsed.parts,notes:parsed.notes,measures:parsed.measures,harmony:parsed.harmony,anchors:parsed.anchors},{parts:1,notes:56,measures:20,harmony:34,anchors:0});assert.match(output.name,/Melody only\.musicxml$/);assert(!xml.includes('lead-harmony-spacing'));await print();await c.setOffline(false);
 // Returning to Original must export original XML, not retained transposed state.
 await view('pdf');output=await download('xml');assert.equal(output.bytes.toString('utf8'),original);
 // XML-only catalog score and safe filenames/validation of rejected malformed XML.
 const xmlOnly=await p.evaluate(async xml=>{const {songs,refreshLocalMusic}=await import('./catalog.js'),{addRecord}=await import('./local-music-store.js');const metadata={...songs.find(s=>s.id==='hhc-1035'),id:'local-export-xml',title:'Export XML-only fixture',local:true,pdfAsset:undefined,hash:'export-xml-fixture'};await addRecord({metadata,xml}); // XML loading/export reads the stored musical string, not the original-file Blob.
await refreshLocalMusic();return metadata.id;},original);await load(xmlOnly);await open();assert(!await p.locator('#score-export-xml').isDisabled());assert.equal(await p.locator('#score-export-pdf-label').textContent(),'Save / Print PDF');await p.keyboard.press('Escape');await p.keyboard.press('Escape');await c.setOffline(true);output=await download('xml');assert.equal(output.bytes.toString('utf8'),await p.evaluate(()=>prototype.xml));await print();await c.setOffline(false);
 const filenameChecks=await p.evaluate(async()=>{const {exportFilename,musicXmlBlob}=await import('./score-export.js');let rejected=0;for(const x of ['<broken>','<html/>'])try{musicXmlBlob(x);}catch{rejected++;}return {names:['CON','A/B:C*D?E"F<G>H|I\\J','. '.repeat(100),'Long '.repeat(100)].map(t=>exportFilename(t,'melody','D Major','musicxml')),rejected};});assert.equal(filenameChecks.rejected,2);for(const n of filenameChecks.names){assert(!/[<>:"/\\|?*\x00-\x1f]/.test(n));assert(n.length<=160);assert(n.endsWith('D Major - Melody only.musicxml'));}
 assert.deepEqual(errors,[]);console.log('PASS export',engine,width,'PDF bytes/annotations/offline, source/current XML, key/register, HHC1035 56 notes/34 chords/no anchors, Save/Print, filenames, menu/focus/availability');await c.close();
}}finally{await browser.close();}
