import {createRequire} from 'node:module';import assert from 'node:assert/strict';const require=createRequire(process.env.PLAYWRIGHT_PACKAGE),{chromium}=require('playwright');const browser=await chromium.launch({channel:'msedge',headless:true}),context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),p=await context.newPage(),cdp=await context.newCDPSession(p),errors=[];p.on('pageerror',e=>errors.push(e.message));const done=()=>p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.getElementById('score').getAttribute('aria-busy')==='false');const scale=()=>p.locator('#score-fit').getAttribute('data-scale').then(Number);
async function pinch(start,end){await p.evaluate(()=>scrollTo(0,0));const y=250,x=190;const points=d=>[{x:x-d/2,y,id:1},{x:x+d/2,y,id:2}];await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points(start)});for(let i=1;i<=8;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points(start+(end-start)*i/8)});}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(100);}
async function drag(x1,y1,x2,y2){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x1,y:y1,id:1}]});for(let i=1;i<=10;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x1+(x2-x1)*i/10,y:y1+(y2-y1)*i/10,id:1}]});}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(350);}
const geometry=()=>p.locator('#print-pages svg').evaluateAll(es=>es.map(e=>[e.getAttribute('viewBox'),...Array.from(e.querySelectorAll('path')).map(n=>n.getAttribute('d'))]));
try{await p.goto(process.env.TEST_URL||'http://127.0.0.1:8767/');await p.locator('.library-row').first().waitFor();for(const id of ['cs-236','nativity','shepherd','faithful','silent-night']){
 await p.locator(`[data-song="${id}"] .song-entry`).click();await done();assert.equal(await scale(),1);const xml=await p.evaluate(()=>prototype.xml);await p.evaluate(()=>prototype.preparePrint());const before=await geometry();await pinch(80,160);assert(Math.abs(await scale()-2)<.05);assert.equal(await p.evaluate(()=>visualViewport.scale),1);assert.equal(await p.evaluate(()=>prototype.xml),xml);
 await p.evaluate(()=>{scrollTo(0,0);document.getElementById('score-fit-viewport').scrollLeft=0;});await drag(290,350,90,350);assert(await p.locator('#score-fit-viewport').evaluate(e=>e.scrollLeft)>20,'native horizontal pan');await p.evaluate(()=>scrollTo(0,0));await drag(180,450,180,250);assert(await p.evaluate(()=>scrollY)>20,'native vertical scroll');
 await pinch(160,80);assert(Math.abs(await scale()-1)<.05);await pinch(160,80);assert.equal(await scale(),.75);await pinch(50,300);assert.equal(await scale(),3);await p.screenshot({path:`test-results/pinch-${id}.png`});await p.evaluate(()=>prototype.preparePrint());assert.deepEqual(await geometry(),before);await p.emulateMedia({media:'print'});assert(await p.locator('#score-fit').isHidden());assert.equal(await p.locator('#score').evaluate(e=>getComputedStyle(e).transform),'none');await p.emulateMedia({media:'screen'});
 await p.locator('#up').click();await done();await p.locator('#reset').click();await done();assert.equal(await scale(),3);await p.locator('#score-fit').click();assert.equal(await scale(),1);assert.equal(await p.locator('#score-fit-viewport').evaluate(e=>e.scrollLeft),0);await pinch(80,160);await p.locator('#songs').click();await p.locator(`[data-song="${id}"] .song-entry`).click();await done();assert.equal(await scale(),1);await p.locator('#songs').click();console.log('PASS actual touch pinch, pan, clamps, print, resets',id);
}
await p.locator('[data-song="nativity"] .song-entry').click();await done();for(const [width,height] of [[375,812],[390,844],[768,1024],[820,1180],[1180,820],[1440,1000]]){await p.setViewportSize({width,height});await p.waitForTimeout(500);await done();assert.equal(await p.locator('#score-fit').isVisible(),width<=600);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const ys=await p.locator('.toolbar button:visible').evaluateAll(es=>es.map(e=>e.getBoundingClientRect().y));assert(Math.max(...ys)-Math.min(...ys)<1);if(width>600)assert.equal(await p.locator('#score').evaluate(e=>getComputedStyle(e).transform),'none');await p.screenshot({path:`test-results/pinch-layout-${width}.png`});}
await p.locator('#songs').click();await p.setViewportSize({width:390,height:844});for(const id of ['scripture-power','choose-to-serve-the-lord']){await p.locator(`[data-song="${id}"] .song-entry`).click();await done();assert(await p.locator('#score-fit').isHidden());assert(!(await p.locator('#score-fit-viewport').getAttribute('class')||'').includes('pinch-enabled'));await p.locator('#songs').click();}assert.deepEqual(errors,[]);console.log('PASS responsive layout/visibility, toolbar, PDFs');}finally{await browser.close();}
