import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
const {chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const oldCss=execFileSync('git',['show','1e2dec0:icon-system.css'],{encoding:'utf8'});
const browser=await chromium.launch({channel:'msedge'});
try{for(const width of [390,744,820,900,1440]){
 const c=await browser.newContext({viewport:{width,height:1000},...(width===390?{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'}:{})});const p=await c.newPage();await p.goto(process.env.APP_URL||'http://127.0.0.1:8780/');await p.waitForFunction(()=>window.prototype?.navigation);
 const geometry=()=>p.evaluate(()=>Object.fromEntries(['.masthead','.score-paper','#score','#songs','#score-tools','#score-hide-controls'].map(s=>[s,document.querySelector(s).getBoundingClientRect().toJSON()])));
 const unchanged=async()=>{const current=await geometry();await p.evaluate(css=>{document.querySelector('link[href="icon-system.css"]').disabled=true;const s=document.createElement('style');s.id='baseline-css';s.textContent=css;document.head.append(s);},oldCss);assert.deepEqual(await geometry(),current,'footer shell, fixed edge controls and score rectangles match deployed baseline');await p.evaluate(()=>{document.getElementById('baseline-css').remove();document.querySelector('link[href="icon-system.css"]').disabled=false;});};
 for(const dark of [false,true]){
  const theme=p.locator('#library-home .library-theme-toggle');if(dark)await theme.click();assert.equal(await theme.getAttribute('aria-pressed'),String(dark));const t=await theme.boundingBox();assert(t.width>=44&&t.height>=44);assert(await theme.getAttribute('aria-label'));assert.equal(await theme.locator('.pdf-mobile-theme-swatch').count(),1);
  const tile=await theme.evaluate(e=>{const s=getComputedStyle(e);return [s.backgroundColor,s.backgroundImage,s.borderTopColor,s.boxShadow];});assert.deepEqual(tile,['rgba(0, 0, 0, 0)','none','rgba(0, 0, 0, 0)','none']);await p.keyboard.press('Tab');await theme.focus();assert.equal(await theme.evaluate(e=>getComputedStyle(e).outlineStyle),'solid');await p.screenshot({path:`test-results/family-home-${width}-${dark}.png`});
  await p.evaluate(()=>prototype.loadSong('nativity'));await p.waitForFunction(()=>prototype.ready&&!prototype.busy&&document.getElementById('score').getAttribute('aria-busy')==='false');assert(await p.locator('#reset').isHidden());await unchanged();
  await p.evaluate(()=>prototype.changeKey((prototype.current+1)%12));await p.waitForFunction(()=>!prototype.busy&&!document.getElementById('reset').hidden&&!document.getElementById('reset').disabled&&document.getElementById('score').getAttribute('aria-busy')==='false');await p.mouse.move(0,0);await unchanged();
  const family=await p.locator('#score-size,#key,#reset').evaluateAll(es=>es.map(e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return {id:e.id,h:r.height,w:r.width,bg:s.backgroundColor,image:s.backgroundImage,radius:s.borderRadius,border:s.borderTopColor,bw:s.borderTopWidth,shadow:s.boxShadow};}));assert(family.every(e=>e.h===44&&e.w>=44&&e.radius==='6px'&&e.bw==='1px'&&e.image==='none'&&e.shadow==='none'));assert.equal(family.find(e=>e.id==='reset').bg,dark?family.find(e=>e.id==='score-size').bg:'rgba(0, 0, 0, 0)');assert.equal(await p.locator('#key').evaluate(e=>getComputedStyle(e,'::after').borderTopWidth),'2px');assert.notEqual(family.find(e=>e.id==='key').border,family.find(e=>e.id==='score-size').border);
  assert.match(await p.locator('#songs').evaluate(e=>getComputedStyle(e).backgroundImage),/linear-gradient/);const key=await p.locator('#key').boundingBox(),reset=await p.locator('#reset').boundingBox();assert(reset.x>=key.x+key.width);const tools=await p.locator('#score-tools').boundingBox();assert(tools.x+tools.width>=width-16);if(width===390)assert(await p.locator('#score-hide-controls').isHidden());else{const f=await p.locator('#score-hide-controls').boundingBox();assert.equal(f.x+22,width/2);}
  await p.screenshot({path:`test-results/family-score-${width}-${dark}.png`});
 const contained=await p.locator('#key').evaluate(e=>{const r=e.getBoundingClientRect();return [...e.querySelectorAll('#key-name,#key-signature')].every(n=>{const t=n.getBoundingClientRect();return t.x>=r.x&&t.right<=r.right;});});assert(contained,'key text remains inside its control');
  for(const id of ['score-size','key','reset']){await p.keyboard.press('Tab');await p.locator('#'+id).focus();assert.equal(await p.locator('#'+id).evaluate(e=>getComputedStyle(e).outlineStyle),'solid');}
  await p.locator('#score-size').click();assert(await p.locator('#score-size-options').isVisible());assert.equal(await p.locator('#score-size').evaluate(e=>getComputedStyle(e).boxShadow),'none');await p.keyboard.press('Escape');await p.locator('#key').click();assert(await p.locator('#key-dialog').isVisible());await p.keyboard.press('Escape');await p.locator('#reset').click();await p.waitForFunction(()=>!prototype.busy&&document.getElementById('reset').hidden);await p.locator('#songs').click();
 }
 console.log('PASS standalone Home theme, musical-control styling, real Key/Reset, baseline geometry, light/dark',width);await c.close();
}}finally{await browser.close();}
