import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {chromium}=createRequire('C:/Users/kenro/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json')('playwright');
const b=await chromium.launch({channel:'msedge'});
try {for(const width of [390,820,1440]){
 const c=await b.newContext({viewport:{width,height:1000},...(width===390?{userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1'}:{})}),p=await c.newPage();await p.goto(process.env.APP_URL||'http://127.0.0.1:8780/');await p.waitForFunction(()=>window.prototype?.navigation);
 const check=async selector=>{const control=p.locator(selector),r=await control.boundingBox();assert(r.width>=44&&r.height>=44);assert.equal(await control.locator('.pdf-mobile-theme-swatch').count(),1);assert.equal(await control.locator('svg').count(),0);const style=await control.locator('span.pdf-mobile-theme-swatch').evaluate(e=>({bg:getComputedStyle(e).backgroundImage,radius:getComputedStyle(e).borderRadius,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height,hidden:e.getAttribute('aria-hidden')}));assert.match(style.bg,/135deg/);assert.match(style.bg,/rgb\(255, 255, 255\)/);assert.match(style.bg,/rgb\(17, 24, 32\)/);assert.equal(style.w,20);assert.equal(style.h,20);assert.equal(style.hidden,'true');};
 const home='#library-home .library-theme-toggle';await check(home);await p.locator(home).click();assert.equal(await p.locator(home).getAttribute('aria-pressed'),'true');assert.equal(await p.locator('html').getAttribute('data-library-theme'),'dark');await check(home);await p.locator(home).click();
 await p.locator('#home-keyboard').click();await p.locator('#keyboard-settings').click();await check('#keyboard-theme');await p.locator('#keyboard-theme').click();assert.equal(await p.locator('#keyboard-theme').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('html').getAttribute('data-library-theme'),'dark');await p.screenshot({path:`test-results/theme-keyboard-${width}.png`});await p.locator('#keyboard-theme').click();await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'keyboard-settings');await p.locator('#keyboard-home').click();
 await p.evaluate(()=>prototype.loadSong('nativity'));await p.waitForFunction(()=>prototype.ready&&!prototype.busy);await p.locator('#score-tools').click();await check('#score-page-theme');await p.locator('#score-page-theme').click();assert.equal(await p.locator('#score-page-theme').getAttribute('aria-pressed'),'true');assert(await p.locator('#playing-view').evaluate(e=>e.classList.contains('score-page-dark')));await p.locator('#score-tools').click();await check('#score-page-theme');await p.screenshot({path:`test-results/theme-score-${width}.png`});await p.locator('#score-page-theme').click();assert.equal(await p.locator('#score-page-theme').getAttribute('aria-pressed'),'false');
 await p.keyboard.press('Escape');await p.locator('#show-lyrics').click();await p.locator('#lyrics-settings').click();await check('#lyrics-theme');await p.locator('#lyrics-theme').click();assert.equal(await p.locator('#lyrics-theme').getAttribute('aria-pressed'),'true');assert(await p.locator('#lyrics-view').evaluate(e=>e.classList.contains('lyrics-dark')));await check('#lyrics-theme');await p.screenshot({path:`test-results/theme-lyrics-${width}.png`});await p.locator('#lyrics-theme').click();await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>document.activeElement.id),'lyrics-settings');
 console.log('PASS original diagonal theme artwork, 44px targets, theme states and settings focus',width);await c.close();
}}finally{await b.close();}
