"""Phase 3C rollout only; reuses frozen analysis, root/local and temporal policies.
Run directly to generate/check only Batch 3. Order is the user's List order.
"""
import collections,hashlib,json,pathlib,re,runpy,subprocess,sys
import xml.etree.ElementTree as ET
ROOT=pathlib.Path(__file__).resolve().parents[1]
NUMBERS=[228,229,230,232,237,239,241,243,244,249,250,251,252,254,255,256,259,260,264,266,272,273,274,277,294,303,304,308,317]
BASELINE='1ee33233ba712b7aa49cbff34e13cc7ee03b9c64bdde98f7e96d953b8f39d1e4'
HEADER='// Generated by tools/harmony-inference.py. Seventy-two approved hymns plus twenty-nine Phase 3C hymns; inferred accompaniment, not authoritative.\n'

def extend(overlays):
    assert len(overlays)==72 and hashlib.sha256(json.dumps(overlays,sort_keys=True,separators=(',',':')).encode()).hexdigest()==BASELINE,'STOP: accepted 72 overlays changed'
    h=runpy.run_path(str(ROOT/'tools/harmony-inference.py'));d=runpy.run_path(str(ROOT/'tools/harmony-display.py'))
    songs=json.loads(subprocess.check_output(['node','--input-type=module','-e',"import {songs} from './songs.js';console.log(JSON.stringify(songs))"],cwd=ROOT))
    rows=[]
    for n in NUMBERS:
        matches=[s for s in songs if s['collection']=='Hymns (1985)' and s['page']==str(n)]
        assert len(matches)==1,('Ambiguous catalog identity',n)
        song=matches[0];xml=h['source'](song);doc=ET.fromstring(xml)
        native=doc.findall('.//harmony');words=[w.text or '' for w in doc.findall('.//direction-type/words')];chords=[w for w in words if re.fullmatch(r'\s*[A-G][#b♭♯]?(?:m|maj7|7|dim|aug)?(?:/[A-G][#b♭♯]?)?\s*',w)]
        r=dict(number=n,id=song['id'],title=song['title'],asset=song['asset'],sourceSha256=hashlib.sha256((ROOT/song['asset']).read_bytes()).hexdigest(),harmonyCount=len(native),chordText=chords)
        if native or chords:rows.append({**r,'skipped':'Authoritative source harmony'});continue
        ms=h['extract'](xml);a=h['infer'](xml);s=d['simplify'](a['events'],ms);root=d['root_only_display'](s['events'],ms,local_density=True);t=d['temporal_display'](root['events'],ms);es=t['events']
        tonic=(7*ms[0]['fifths']+(9 if ms[0]['mode']=='minor' else 0))%12
        scale={(tonic+x)%12 for x in ([0,2,3,5,7,8,10] if ms[0]['mode']=='minor' else [0,2,4,5,7,9,11])}
        counts=collections.Counter(e['measure'] for e in es);flags=[]
        if any(len(c['events'])>=4 for c in t['remainingClusters']):flags.append('4+ symbols in a short temporal cluster')
        if sum(v>=3 for v in counts.values())>=3:flags.append('Several measures with 3+ symbols')
        if len(a['review'])>=10:flags.append('10+ uncertainty/review windows')
        if len(es)/len(ms)>2:flags.append('More than two displayed events per source measure on average')
        if any(e['kind'] in ['augmented','major-seventh'] for e in es):flags.append('Augmented/major-seventh interpretation')
        if not es or es[0]['rootPC']!=tonic or es[-1]['rootPC']!=tonic:flags.append('Non-tonic opening or ending')
        omitted={w['measure'] for w in a['review'] if w['reason'].startswith('Omitted')};gaps=[];run=[]
        for m in ms:
            if m['number'] in omitted and not any(e['measure']==m['measure'] for e in a['events']):run.append(m['number'])
            else:
                if len(run)>=2:gaps.append(run)
                run=[]
        if len(run)>=2:gaps.append(run)
        if gaps:flags.append('Consecutive uncertain measures with no new analysis event')
        chromatic=any(e['rootPC'] not in scale or (e['rootPC']+(3 if e['kind'] in ['minor','diminished'] else 4))%12 not in scale or e['kind'] in ['diminished','augmented','major-seventh'] for e in es)
        rows.append({**r,'originalKey':h['spelling'](tonic,ms[0]['fifths'])+' '+ms[0]['mode'],'analysis':a,'displaySimplification':s,'rootDisplay':root,'temporalDisplay':t,'measureCount':len(ms),'denseMeasures':[dict(measure=ms[mi]['number'],events=[dict(offset=e['offset'],chord=e['label']) for e in es if e['measure']==mi]) for mi,v in counts.items() if v>=3],'uncertainGaps':gaps,'reviewFlags':flags,'chromatic':chromatic,'alternateRender':bool(flags or chromatic or n in [228,239,254,308,317])})
        overlays[song['id']]=dict(provenance='generated',version=1,xmlSha256=hashlib.sha256(xml.encode()).hexdigest(),events=[{k:e[k] for k in ['measure','offset','root','kind','bass']} for e in es])
    return rows

def main():
    path=ROOT/'generated-harmony-data.js';data=json.loads(path.read_text(encoding='utf8').split('export const generatedHarmony = ')[1].strip().rstrip(';'))
    # Existing 72 are the prefix; remove only this batch on repeat runs.
    songs=json.loads(subprocess.check_output(['node','--input-type=module','-e',"import {songs} from './songs.js';console.log(JSON.stringify(songs))"],cwd=ROOT))
    ids={s['id'] for s in songs if s['collection']=='Hymns (1985)' and s['page'] in set(map(str,NUMBERS))}
    data={k:v for k,v in data.items() if k not in ids};rows=extend(data)
    for p,content in [(path,HEADER+'export const generatedHarmony = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n'),(ROOT/'reports/harmony-batch3c.json',json.dumps(rows,ensure_ascii=False,indent=2)+'\n')]:
        if '--check' in sys.argv:assert p.read_text(encoding='utf8')==content,str(p)+' not reproducible'
        else:p.write_text(content,encoding='utf8')
    for r in rows:print(r['number'],r['id'],r.get('skipped') or f"{len(r['analysis']['events'])} -> {len(r['temporalDisplay']['events'])}; review {r['reviewFlags']}; alternate {r['alternateRender']}")
if __name__=='__main__':main()
