"""Summarize the focused Phase 3C test artifacts; no analysis or display policy changes."""
import collections,html,json,pathlib,shutil
ROOT=pathlib.Path(__file__).resolve().parents[1]
read=lambda name:json.loads((ROOT/name).read_text(encoding='utf8'))
raw=read('reports/harmony-batch3c.json');numbers=[r['number'] for r in raw]
renders=[r for r in read('test-results/harmony-batch3c-renders.json')+read('test-results/harmony-batch3c-extra.json') if int(r['number']) in numbers]
bare=[r for r in read('test-results/harmony-batch3c-bare.json') if int(r['number']) in numbers]
assert len([r for r in renders if r['shift']==0])==58
assert len({(r['number'],r['mode'],r['shift']) for r in renders})==len(renders)==112
notes={232:'Full lyric crowding remains without chords (collision metric 1 in both).',244:'Melody has close lyric joins near the bottom; also visible without chords.',255:'Highest review priority: Full grows from 2 to 3 pages; lyric crowding metric rises from 0 to 3. Chord symbols themselves remain above the staff. Opening D7 in G is a plausible dominant pickup, but not proof of correctness. Review chromatic/augmented interpretations and 24 uncertainty windows.',264:'Full lyric crowding remains without chords (metric 1 in both).',266:'Full lyric-spacing warning remains without chords (metric 1 in both).',273:'Full lyric crowding remains without chords (metric 3 in both).',317:'Full remains two pages; its three-staff systems and sparse first page also occur without harmony. Layout untouched.'}
rows=[]
for r in raw:
 n=r['number'];rs=[x for x in renders if int(x['number'])==n];bs=[x for x in bare if int(x['number'])==n]
 lookup=lambda seq,mode,shift=0:next((x for x in seq if x['mode']==mode and x['shift']==shift),None)
 f,m=lookup(rs,'auto'),lookup(rs,'large');bf,bm=lookup(bs,'auto'),lookup(bs,'large');af,am=lookup(rs,'auto',2),lookup(rs,'large',2)
 a=r['analysis']['events'];s=r['displaySimplification']['events'];root=r['rootDisplay'];t=r['temporalDisplay'];es=t['events'];flags=list(r['reviewFlags'])
 added={'Full':f['pageCount']-bf['pageCount'],'Melody':m['pageCount']-bm['pageCount']}
 if any(v>0 for v in added.values()):flags.append('Harmony adds a page: '+str(added))
 if af and (af['pageCount']!=f['pageCount'] or am['pageCount']!=m['pageCount']):flags.append('Alternate-key page count differs')
 if n in notes:flags.append(notes[n])
 row=dict(number=n,title=r['title'],id=r['id'],key=r['originalKey'],sourceHarmony=r['harmonyCount'],sourceChordText=r['chordText'],sourceSha256=r['sourceSha256'],analysisCount=len(a),displayCount=len(es),firstStageRemoved=len(a)-len(s),rootDedupRemoved=root['slashDuplicates'],localRemoved=root['localSuppressed'],temporalRemoved=len(root['events'])-len(es),reviewWindows=len(r['analysis']['review']),dense3Plus=len(t['remainingClusters']),dense4Plus=sum(len(c['events'])>=4 for c in t['remainingClusters']),denseMeasures=r['denseMeasures'],remainingClusters=t['remainingClusters'],pdfPages=f['pdfPageCount'],fullPages=f['pageCount'],melodyPages=m['pageCount'],bareFullPages=bf['pageCount'],bareMelodyPages=bm['pageCount'],addedPages=added,alternateFull=af['pageCount'] if af else None,alternateMelody=am['pageCount'] if am else None,fullCollisionMetric=(f.get('report') or {}).get('collisions'),bareCollisionMetric=(bf.get('report') or {}).get('collisions'),opening=es[0]['label'],ending=es[-1]['label'],qualities=dict(collections.Counter(e['kind'] for e in es)),reviewPriority='Review recommended' if flags else 'Normal',reviewReasons=flags,reviewDetails=r['analysis']['review'],uncertainGaps=r['uncertainGaps'],events=[{k:e[k] for k in ['sourceMeasure','offset','label']} for e in es])
 assert row['analysisCount']-row['displayCount']==sum(row[k] for k in ['firstStageRemoved','rootDedupRemoved','localRemoved','temporalRemoved'])
 rows.append(row)
shortlist=[(255,'Carry On: 44 displayed events, 24 review windows, chromatic/augmented material, Full 2→3 pages and tighter lyrics.'),(249,'Called to Serve: retained short-span cluster, 18 review windows and major-seventh/diminished interpretations.'),(277,'As I Search the Holy Scriptures: three retained temporal clusters and major-seventh interpretations in a short hymn.'),(241,'Count Your Blessings: consecutive uncertain gaps; Melody expands from 2 to 3 pages at +2.'),(230,'Scatter Sunshine: retained four-event cluster, 13 review windows and Melody 1→2 pages with chords.'),(254,'True to the Faith: two retained temporal clusters and an uncertain X12–X13 gap. Existing Full pagination is unchanged.')]
tests=['Deterministic append-only generation: tools/harmony-batch3c.py --check','tests/harmony-batch3c.py: 4 passed (72-overlay equality, source bytes, frozen policy/runtime, revised membership)','tests/harmony-display.py: 14 passed','tests/harmony-temporal.py: 7 passed','tests/harmony-inference.py: 7 passed','tests/chord-harmony.mjs CHORD_UNIT_ONLY=1: 7,288 assertions, 25 examples','tests/generated-harmony.mjs HARMONY_UNIT_ONLY=1, all 29: source/text precedence, fingerprint protection, idempotence, notation invariance, Full/Melody positional equality and +2 root/quality assertions','58 original-key renders, 54 alternate-key renders (27 hymns), 58 original-key no-overlay controls at 820×1180; no horizontal overflow or browser errors','All original/alternate virtual pages visually inspected through contact sheets; focused no-overlay visual comparisons','git diff --check']
summary=dict(scope='29 additions; user explicitly excluded 314 and 315',baseline='9ae1b6b',coverage=dict(batch1=30,batch2=30,batch3=29,processedPriority=89,originalPriority=91,userExcluded=[314,315],earlier=12,totalOverlays=101),nativeHarmonySongs=0,chordTextSongs=0,sourceSkipped=0,analysisEvents=sum(r['analysisCount'] for r in rows),displayEvents=sum(r['displayCount'] for r in rows),displayedSlash=0,existing72Unchanged=True,sourceAssetsUnchanged=True,policyUnchanged=True,phoneWorkIncluded=False,originalRenders=58,alternateRenders=54,alternateNumbers=sorted({int(r['number']) for r in renders if r['shift']==2}),bareRenders=58,viewport='820×1180',shortlist=[dict(number=n,reason=s) for n,s in shortlist],tests=tests,rows=rows)
# Keep compact structural evidence and all recorded layout metrics, without duplicating engraved text.
summary['filesChanged']=['generated-harmony-data.js','sw.js','tools/harmony-inference.py','tools/harmony-batch3c.py','tools/harmony-batch3c-report.py','tests/generated-harmony.mjs','tests/harmony-display.py','tests/harmony-batch3c.py','reports/harmony-batch3c.json','reports/harmony-batch3c-validation.json','reports/harmony-batch3c-validation.html','reports/harmony-batch3c-shots/ (54 contact sheets)']
summary['renderEvidence']=[{k:v for k,v in r.items() if k not in ['text','screenshots']} for r in renders]
summary['bareEvidence']=[{k:v for k,v in r.items() if k not in ['text','screenshots']} for r in bare]
(ROOT/'reports/harmony-batch3c-validation.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
esc=lambda x:html.escape(str(x))
p=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Harmony Phase 3C — final batch</title><style>body{font:16px system-ui;max-width:1500px;margin:32px auto;padding:0 20px;color:#223}table{border-collapse:collapse;font-size:13px;width:100%}td,th{text-align:left;vertical-align:top;padding:8px;border-bottom:1px solid #ddd}code{font-size:12px;overflow-wrap:anywhere}.scroll{overflow:auto}summary{cursor:pointer;padding:12px;background:#eef3f5}pre{white-space:pre-wrap;font-size:13px}img{max-width:100%;height:auto}h2{margin-top:36px}</style><h1>Generated harmony Phase 3C</h1><p>29 new Hymns (1985) overlays. #314 and #315 were explicitly excluded by the user. Batch totals: 30 + 30 + 29 = <strong>89 of the original 91</strong>, with two user exclusions. Earlier pilot/Christmas overlays: 12. Final total: <strong>101</strong>. No source-authoritative harmony was found or skipped.</p><p>Frozen production analysis/display policy; accepted 72 overlays remain exactly equivalent. Source MXL/PDF assets unchanged. No iPhone, UI, pagination, playback, Melody extraction or Hymn 201/223 work.</p><p>673 detailed analysis events produce 622 displayed root+quality symbols; zero generated slash basses. Detailed bass/inversion metadata and uncertainty windows remain in <a href="harmony-batch3c.json">the analysis report</a>. Existing source-harmony precedence, SHA-256 protection, offline precomputed data and injection-before-transposition path are unchanged.</p><h2>Physical review shortlist</h2><p>These are inferred suggestions, not authoritative harmony or human musical approval. No thresholds were retuned for outliers.</p><ol>']
for n,s in shortlist:p.append('<li>'+esc(s)+'</li>')
p+=['</ol><h2>Counts and pages</h2><p>First = first-stage removal; dedup = root-only duplicate removal; local/temporal = the two density stages. Dense 3+/4+ counts are retained short temporal spans, not symbols per system. Spans can overlap; they are not a numerical quality score. Full/Melody are original-key pages. Bare is the same rendering without overlays. PDF counts came from repository assets already used by the test, without external bulk downloads.</p><div class="scroll"><table><tr>'+''.join('<th>'+x+'</th>' for x in ['Hymn / key','Analysis → display','Removed: first / dedup / local / temporal','Review windows','Dense 3+ / 4+','PDF','Full / Melody','Bare F / M','+2 F / M','Priority'])+'</tr>']
for r in rows:
 vals=[f"{r['number']} — {r['title']} ({r['key']})",f"{r['analysisCount']} → {r['displayCount']}", ' / '.join(str(r[k]) for k in ['firstStageRemoved','rootDedupRemoved','localRemoved','temporalRemoved']),r['reviewWindows'],f"{r['dense3Plus']} / {r['dense4Plus']}",r['pdfPages'],f"{r['fullPages']} / {r['melodyPages']}",f"{r['bareFullPages']} / {r['bareMelodyPages']}",f"{r['alternateFull']} / {r['alternateMelody']}" if r['alternateFull'] else 'Not selected',r['reviewPriority']]
 p.append('<tr>'+''.join('<td>'+esc(x)+'</td>' for x in vals)+'</tr>')
p+=['</table></div><h2>Validation and limitations</h2><p>All 29 sources had zero native harmony and zero chord-like direction text, checked with the production chord parser. All 29 passed positional Full/Melody harmony equivalence and +2 structural transposition checks. Existing 7,288 chord assertions cover spelling/transposition behavior. Source slash-harmony precedence remains supported.</p><p>58 original-key renders and 54 +2 renders at 820×1180 were inspected. +2 covered all flagged/chromatic songs and page-expansion cases; only #274 and #294 needed no alternate visual render. Symbols remained above the staff, with no observed chord/title or chord/lyric collision and no duplicate generated symbols. This does not mean every existing lyric spacing problem is resolved.</p><p>Harmony adds an original-key page in #229 (both views), #230 (Melody), #243 (Melody), #255 (Full), #260 (Melody), and #272 (Melody). #232/#264/#266/#273 Full lyric warnings and #244 Melody close lyric joins also occur without chords. #255 has newly tighter Full lyrics (collision metric 0→3) and remains a reported release-review outlier. No layout changes were made.</p><p>Analytical checks: every ending is tonic-root; all openings are tonic-root except #255’s D7 in G, a plausible dominant pickup retained for review. Seventh/chromatic/diminished symbols remain where the frozen algorithm emits them. Consecutive uncertain gaps in #239/#241/#243/#254/#255 are listed below; a preceding symbol is not proof of the harmony through those gaps. Retained dense spans are evidence for review, not silently approved.</p><ul>']
p.extend('<li>'+esc(t)+'</li>' for t in tests)
p+=['</ul><h2>Stable IDs, musical review windows and retained dense spans</h2><p>Measure labels are source labels; offsets are quarter-note units, not necessarily printed beats. Full detailed decisions are retained in the linked JSON.</p>']
for r in rows:
 p+=['<details><summary>'+esc(f"{r['number']} — {r['title']} — {r['reviewPriority']}")+'</summary><p>Stable ID: <code>'+esc(r['id'])+'</code></p><p>Source SHA-256: <code>'+r['sourceSha256']+'</code></p><p>'+esc('Opening '+r['opening']+'; ending '+r['ending']+'. '+('; '.join(r['reviewReasons']) or 'No automatic or visual outlier flag.'))+'</p><pre>'+esc(json.dumps({k:r[k] for k in ['qualities','uncertainGaps','remainingClusters','reviewDetails','events']},ensure_ascii=False,indent=2))+'</pre></details>']
p+=['<h2>Visual evidence</h2><p>Contact sheets contain every primary and alternate-key virtual page; auto means Full/Transpose, large means Melody. Extra sheets include additional +2 renders and no-overlay comparisons. Click an image to open its full contact sheet.</p>']
outdir=ROOT/'reports/harmony-batch3c-shots';outdir.mkdir(exist_ok=True)
for pattern,label in [('batch3c-contact-0-*.jpg','Original key'),('batch3c-contact-2-*.jpg','Alternate +2'),('extra-review-*.jpg','Additional keys / no-overlay controls')]:
 p.append('<details><summary>'+label+'</summary>')
 for f in sorted((ROOT/'test-results').glob(pattern)):
  shutil.copyfile(f,outdir/f.name);url='harmony-batch3c-shots/'+f.name;p.append(f'<a href="{url}"><img loading="lazy" src="{url}" alt="{esc(f.stem)}"></a>')
 p.append('</details>')
p+=['<h2>Files changed</h2><ul>'+''.join('<li><code>'+esc(f)+'</code></li>' for f in summary['filesChanged'])+'</ul>']
p+=['<h2>Release record</h2><p>Baseline 9ae1b6b. This report ships with the Phase 3C commit; the chat handoff records its SHA and verified deployment. Service worker shell v215 includes the new overlay data; score cache behavior is unchanged. No further hymns are authorized in this batch.</p><p><a href="harmony-batch3c-validation.json">Machine-readable validation</a> · <a href="harmony-batch3c.json">Detailed analysis and suppression decisions</a></p></html>']
(ROOT/'reports/harmony-batch3c-validation.html').write_text('\n'.join(p)+'\n',encoding='utf8')
print('Report:',len(rows),'songs;',summary['analysisEvents'],'analysis;',summary['displayEvents'],'display;',len(renders),'renders')
print('Dense4+',[(r['number'],r['dense4Plus']) for r in rows if r['dense4Plus']])
print('Alternate',summary['alternateNumbers'])
