"""Targeted Batch 2 rollout. Reuse the frozen engine; never regenerate other songs."""
import hashlib,json,pathlib,runpy,subprocess,sys
import xml.etree.ElementTree as ET
ROOT=pathlib.Path(__file__).resolve().parents[1]
NUMBERS=[72,83,95,116,129,130,169,198,214,280]
BASELINE='7248829dab38b806a00ca13909e082a7cbca669b4d9709f81d18b40e3b26c8a7'
HEADER='// Generated by tools/harmony-inference.py and tools/harmony-expansion-batch2.py. 119 inferred accompaniment overlays; not authoritative arrangements.\n'
def catalog():
 return json.loads(subprocess.check_output(['node','--input-type=module','-e',"import {songs} from './songs.js';console.log(JSON.stringify(songs))"],cwd=ROOT))
def parse(text):
 return json.loads(text.split('export const generatedHarmony = ')[1].strip().rstrip(';'))
def extend(overlays):
 assert len(overlays)==110 and hashlib.sha256(json.dumps(overlays,sort_keys=True,separators=(',',':')).encode()).hexdigest()==BASELINE,'STOP: accepted 110 overlays changed'
 h=runpy.run_path(str(ROOT/'tools/harmony-inference.py'));d=runpy.run_path(str(ROOT/'tools/harmony-display.py'));songs=catalog();rows=[]
 for number in NUMBERS:
  matches=[s for s in songs if s['collection']=='Hymns (1985)' and int(s['page'])==number];assert len(matches)==1
  song=matches[0];xml=h['source'](song);doc=ET.fromstring(xml)
  assert song['id'] not in overlays,'Duplicate overlay'
  assert not doc.findall('.//harmony'),'Source harmony takes precedence'
  ms=h['extract'](xml);analysis=h['infer'](xml)
  simplified=d['simplify'](analysis['events'],ms);root=d['root_only_display'](simplified['events'],ms,local_density=True);temporal=d['temporal_display'](root['events'],ms);events=temporal['events']
  assert events and all(0<=e['offset']<ms[e['measure']]['duration'] for e in events)
  keys=[dict(measure=m['number'],fifths=m['fifths'],mode=m['mode']) for i,m in enumerate(ms) if i==0 or (m['fifths'],m['mode'])!=(ms[i-1]['fifths'],ms[i-1]['mode'])]
  blocked=len(keys)>1
  assert blocked==(number==280),'STOP: unexpected source structure'
  tonic=(7*ms[0]['fifths']+(9 if ms[0]['mode']=='minor' else 0))%12;flags=[]
  if len(analysis['review'])>=10:flags.append('10+ uncertainty/review windows; omitted windows are not inferred as the preceding chord')
  if any(e['kind'] in ['augmented','major-seventh'] for e in events):flags.append('Augmented/major-seventh interpretation needs musical review')
  if events[0]['rootPC']!=tonic or events[-1]['rootPC']!=tonic:flags.append('Non-tonic opening or ending relative to declared source key')
  if temporal['remainingClusters']:flags.append('Retained close-spaced chord cluster')
  if number==198:flags.append('Source declares F major; opening and ending Dm, with A7 to Dm at X14-X15. Review relative-minor interpretation and Dbdim spelling at X10 offset 2 (existing flat-key convention); source metadata unchanged.')
  if blocked:flags.append('C to G at X10, back to C at X20. Current app intentionally disables transposition. Candidates are diagnostic only; no overlay deployed.')
  rows.append(dict(number=number,id=song['id'],title=song['title'],asset=song['asset'],sourceSha256=hashlib.sha256((ROOT/song['asset']).read_bytes()).hexdigest(),originalKey=(song['tonic']+' '+song['mode']).strip() or 'C major / G major / C major',keyChanges=keys,analysis=analysis,omittedWindows=sum(e.get('reason','').startswith('Omitted:') for e in analysis['review']),displayStages=dict(analysis=len(analysis['events']),simplified=len(simplified['events']),rootOnly=len(root['events']),temporal=len(events)),temporalDisplay=dict(events=events,remainingClusters=temporal['remainingClusters']),reviewFlags=flags,measureCount=len(ms),generatedSymbolCount=0 if blocked else len(events),outcome='D. Structurally blocked' if blocked else 'B. Generated - musical review recommended' if flags else 'A. Generated - no significant warning'))
  if not blocked:overlays[song['id']]=dict(provenance='generated',version=1,xmlSha256=hashlib.sha256(xml.encode()).hexdigest(),events=[{k:e[k] for k in ['measure','offset','root','kind','bass']} for e in events])
 return rows

def main():
 path=ROOT/'generated-harmony-data.js';data=parse(path.read_text(encoding='utf8'))
 ids={s['id'] for s in catalog() if s['collection']=='Hymns (1985)' and int(s['page']) in NUMBERS}
 data={k:v for k,v in data.items() if k not in ids};rows=extend(data)
 report=dict(scope=NUMBERS,baseline='fc78baebcfa467f7a0d30fd2779959362ba8dbb3',policy='Unchanged inference, simplify, root-only and temporal display; no thresholds tuned or manual chords',limitations=['Heuristic accompaniment suggestions, not human-approved arrangements.','Offsets are quarter-note units; source measure labels including X prefixes are preserved. Pitch coverage is not a confidence probability.','Omitted windows are not filled; the preceding symbol does not establish harmony through those gaps.','280 candidates are diagnostic only; no modulation/transposition rewrite.','198 source declares F major; D-minor cadence warrants review.'],coverage=dict(previousGenerated=110,generated=119,native=1,chorded=120,usableUnchorded=215,noUsableXML=6,remainingUnexaminedPriority=40,blockedThisBatch=1),rows=rows)
 for target,content in [(path,HEADER+'export const generatedHarmony = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n'),(ROOT/'reports/chord-expansion-batch2.json',json.dumps(report,ensure_ascii=False,indent=2)+'\n')]:
  if '--check' in sys.argv:assert target.read_text(encoding='utf8')==content,str(target)+' not reproducible'
  else:target.write_text(content,encoding='utf8')
 for r in rows:print(r['number'],r['generatedSymbolCount'],r['omittedWindows'],r['outcome'])
if __name__=='__main__':main()
