"""Nine deferred priority hymns: append-only rollout using the frozen SATB/display policy.
Run this file (optionally --check), not a full catalog regeneration.
"""
import hashlib,json,pathlib,runpy,subprocess,sys
import xml.etree.ElementTree as ET
ROOT=pathlib.Path(__file__).resolve().parents[1]
NUMBERS=[7,62,100,108,246,270,292,301,307]
BASELINE='b33ac944441c389f962c3edc0884a5062e263343ed248381221658cceb3fae7a'
HEADER='// Generated by tools/harmony-inference.py and tools/harmony-priority-nine.py. 110 inferred accompaniment overlays; not authoritative arrangements.\n'
def extend(overlays):
 assert len(overlays)==101 and hashlib.sha256(json.dumps(overlays,sort_keys=True,separators=(',',':')).encode()).hexdigest()==BASELINE,'STOP: accepted 101 overlays changed'
 h=runpy.run_path(str(ROOT/'tools/harmony-inference.py'));d=runpy.run_path(str(ROOT/'tools/harmony-display.py'))
 songs=json.loads(subprocess.check_output(['node','--input-type=module','-e',"import {songs} from './songs.js';console.log(JSON.stringify(songs))"],cwd=ROOT));rows=[]
 assert set(NUMBERS)==set(h['PRIORITY'])-set(h['PILOTS'])-set(h['CHRISTMAS']),'Historical rollout scope changed'
 for number in NUMBERS:
  song=next(s for s in songs if s['collection']=='Hymns (1985)' and int(s['page'])==number);xml=h['source'](song);doc=ET.fromstring(xml)
  assert not doc.findall('.//harmony'),'Source harmony takes precedence'
  ms=h['extract'](xml);analysis=h['infer'](xml);simplified=d['simplify'](analysis['events'],ms);root=d['root_only_display'](simplified['events'],ms,local_density=True);temporal=d['temporal_display'](root['events'],ms);events=temporal['events']
  assert events and all(0<=e['offset']<ms[e['measure']]['duration'] for e in events)
  tonic=(7*ms[0]['fifths']+(9 if ms[0]['mode']=='minor' else 0))%12;flags=[]
  if len(analysis['review'])>=10:flags.append('10+ uncertainty/review windows; omitted windows are not inferred as the preceding chord')
  if any(e['kind'] in ['augmented','major-seventh'] for e in events):flags.append('Augmented/major-seventh interpretation needs musical review')
  if events[0]['rootPC']!=tonic or events[-1]['rootPC']!=tonic:flags.append('Non-tonic opening or ending')
  if temporal['remainingClusters']:flags.append('Retained close-spaced chord cluster')
  rows.append(dict(number=number,id=song['id'],title=song['title'],asset=song['asset'],sourceSha256=hashlib.sha256((ROOT/song['asset']).read_bytes()).hexdigest(),originalKey=song['tonic']+' '+song['mode'],cause='Deferred rollout: in PRIORITY, outside PILOTS/CHRISTMAS and subsequent batch lists; current generator does not fail',analysis=analysis,displayStages=dict(analysis=len(analysis['events']),simplified=len(simplified['events']),rootOnly=len(root['events']),temporal=len(events)),temporalDisplay=dict(events=events,remainingClusters=temporal['remainingClusters']),reviewFlags=flags,measureCount=len(ms),outcome='Requiring musical review (overlay generated)' if flags else 'Generated successfully'))
  overlays[song['id']]=dict(provenance='generated',version=1,xmlSha256=hashlib.sha256(xml.encode()).hexdigest(),events=[{k:e[k] for k in ['measure','offset','root','kind','bass']} for e in events])
 return rows

def main():
 path=ROOT/'generated-harmony-data.js';data=json.loads(path.read_text(encoding='utf8').split('export const generatedHarmony = ')[1].strip().rstrip(';'))
 songs=json.loads(subprocess.check_output(['node','--input-type=module','-e',"import {songs} from './songs.js';console.log(JSON.stringify(songs))"],cwd=ROOT));ids={s['id'] for s in songs if s['collection']=='Hymns (1985)' and s['page'] in set(map(str,NUMBERS))}
 data={k:v for k,v in data.items() if k not in ids};rows=extend(data)
 report=dict(supersedes='Source-only classification at 27085ba; absence of native chord symbols is normal input for automatic generation.',scope=NUMBERS,baseline='27085ba',policy='Unchanged inference, simplify, root-only display and temporal display; no thresholds tuned and no manual chord substitutions',validation=dict(sourceIntegrity='All nine MXL hashes match the baseline; existing 101 overlay objects unchanged',structural='Injection before transpose/Melody; source precedence, fingerprint guards, idempotence, unchanged notes and timed Full/Melody harmony equivalence',transpositionCases=117,responsiveWidths=[390,820,1440],actualTransposedMusicXMLDownloads=18,sharedChordParserAssertions=7288,physicalDevicesTested=False),limitations=['Generated accompaniment is heuristic and not an authoritative or human-approved arrangement.','Omitted ambiguous windows are not filled with invented chords; the preceding symbol is not proof of harmony through those gaps.','Six overlays retain musical-review flags; review the exact windows and close-spaced clusters below.','Hymn 307 Full-score beaming/spacing also appears in a no-overlay control; no engraving changes were made.','Playback remains driven by source notes rather than synthesized chord accompaniment.'],coverage=dict(previousGenerated=101,generated=110,native=1,chorded=111,usableUnchorded=224,noUsableXML=6),rows=rows)
 for target,content in [(path,HEADER+'export const generatedHarmony = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n'),(ROOT/'reports/chord-priority-nine.json',json.dumps(report,ensure_ascii=False,indent=2)+'\n')]:
  if '--check' in sys.argv:assert target.read_text(encoding='utf8')==content,str(target)+' not reproducible'
  else:target.write_text(content,encoding='utf8')
 for r in rows:print(r['number'],len(r['analysis']['events']),'->',len(r['temporalDisplay']['events']),r['reviewFlags']);print('  '+' '.join(e['label']+'@'+str(e['sourceMeasure'])+':'+str(e['offset']) for e in r['temporalDisplay']['events']))
if __name__=='__main__':main()
