"""Targeted Batch 3 rollout. Reuse the frozen engine; never regenerate other songs."""
import hashlib,json,pathlib,runpy,subprocess,sys
import xml.etree.ElementTree as ET
ROOT=pathlib.Path(__file__).resolve().parents[1]
NUMBERS=[300,302,309,319,44,52,59,78,117,145]
BASELINE='d8b587e9ed19f65041a08763d92d52f9b8a4d421b8ecad6af713697c384a3ca9'
HEADER='// Generated by tools/harmony-inference.py and tools/harmony-expansion-batch3.py. 129 inferred accompaniment overlays; not authoritative arrangements.\n'
def catalog():
 return json.loads(subprocess.check_output(['node','--input-type=module','-e',"import {songs} from './songs.js';console.log(JSON.stringify(songs))"],cwd=ROOT))
def parse(text):
 return json.loads(text.split('export const generatedHarmony = ')[1].strip().rstrip(';'))
def extend(overlays):
 assert len(overlays)==119 and hashlib.sha256(json.dumps(overlays,sort_keys=True,separators=(',',':')).encode()).hexdigest()==BASELINE,'STOP: accepted 119 overlays changed'
 h=runpy.run_path(str(ROOT/'tools/harmony-inference.py'));d=runpy.run_path(str(ROOT/'tools/harmony-display.py'));songs=catalog();rows=[]
 for number in NUMBERS:
  matches=[s for s in songs if s['collection']=='Hymns (1985)' and int(s['page'])==number];assert len(matches)==1
  song=matches[0];xml=h['source'](song);doc=ET.fromstring(xml)
  assert song['id'] not in overlays,'Duplicate overlay'
  assert not doc.findall('.//harmony'),'Source harmony takes precedence'
  ms=h['extract'](xml);analysis=h['infer'](xml)
  simplified=d['simplify'](analysis['events'],ms);root=d['root_only_display'](simplified['events'],ms,local_density=True);temporal=d['temporal_display'](root['events'],ms);events=temporal['events']
  assert events and all(0<=e['offset']<ms[e['measure']]['duration'] for e in events)
  keys=[dict(measure=m['number'],fifths=m['fifths'],mode=m['mode']) for i,m in enumerate(ms) if i==0 or (m['fifths'],m['mode'])!=(ms[i-1]['fifths'],ms[i-1]['mode'])]
  blocked=len(keys)>1
  assert not blocked and song['transpositionAvailable'],'STOP: unsupported source structure'
  tonic=(7*ms[0]['fifths']+(9 if ms[0]['mode']=='minor' else 0))%12;flags=[]
  if len(analysis['review'])>=10:flags.append('10+ uncertainty/review windows; omitted windows are not inferred as the preceding chord')
  if any(e['kind'] in ['augmented','major-seventh'] for e in events):flags.append('Augmented/major-seventh interpretation needs musical review')
  if events[0]['rootPC']!=tonic or events[-1]['rootPC']!=tonic:flags.append('Non-tonic opening or ending relative to declared source key')
  if temporal['remainingClusters']:flags.append('Retained close-spaced chord cluster')
  rows.append(dict(number=number,id=song['id'],title=song['title'],asset=song['asset'],sourceSha256=hashlib.sha256((ROOT/song['asset']).read_bytes()).hexdigest(),originalKey=(song['tonic']+' '+song['mode']).strip(),keyChanges=keys,analysis=analysis,omittedWindows=sum(e.get('reason','').startswith('Omitted:') for e in analysis['review']),displayStages=dict(analysis=len(analysis['events']),simplified=len(simplified['events']),rootOnly=len(root['events']),temporal=len(events)),temporalDisplay=dict(events=events,remainingClusters=temporal['remainingClusters']),reviewFlags=flags,measureCount=len(ms),generatedSymbolCount=0 if blocked else len(events),outcome='D. Structurally blocked' if blocked else 'B. Generated - musical review recommended' if flags else 'A. Generated - no significant warning'))
  if not blocked:overlays[song['id']]=dict(provenance='generated',version=1,xmlSha256=hashlib.sha256(xml.encode()).hexdigest(),events=[{k:e[k] for k in ['measure','offset','root','kind','bass']} for e in events])
 return rows

def main():
 path=ROOT/'generated-harmony-data.js';data=parse(path.read_text(encoding='utf8'))
 ids={s['id'] for s in catalog() if s['collection']=='Hymns (1985)' and int(s['page']) in NUMBERS}
 data={k:v for k,v in data.items() if k not in ids};rows=extend(data)
 report=dict(scope=NUMBERS,baseline='6dd3259b60139ae5822e37aaa283816d76672e77',policy='Unchanged inference, simplify, root-only and temporal display; no thresholds tuned or manual chords',limitations=['Heuristic accompaniment suggestions, not human-approved arrangements.','Offsets are quarter-note units; source measure labels including X prefixes are preserved. Pitch coverage is not a confidence probability.','Omitted windows are not filled; the preceding symbol does not establish harmony through those gaps.'],coverage=dict(previousGenerated=119,generated=129,native=1,chorded=130,usableUnchorded=205,noUsableXML=6,remainingUnexaminedPriority=30,blockedThisBatch=0,previouslyDeferred=[280]),rows=rows)
 for target,content in [(path,HEADER+'export const generatedHarmony = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n'),(ROOT/'reports/chord-expansion-batch3.json',json.dumps(report,ensure_ascii=False,indent=2)+'\n')]:
  if '--check' in sys.argv:assert target.read_text(encoding='utf8')==content,str(target)+' not reproducible'
  else:target.write_text(content,encoding='utf8')
 for r in rows:print(r['number'],r['generatedSymbolCount'],r['omittedWindows'],r['outcome'])
if __name__=='__main__':main()
