"""Targeted Batch 8 rollout. Reuse the frozen engine; never regenerate other songs."""
import hashlib,json,pathlib,runpy,subprocess,sys
import xml.etree.ElementTree as ET
ROOT=pathlib.Path(__file__).resolve().parents[1]
NUMBERS=[176,177,182,183,190,216,235,285,293,338,339,340,341]
BASELINE='c35734cd0a5d06da7d96bc2433f880aba35e534946059ee30ae647ca6f34c510'
HEADER='// Generated by tools/harmony-inference.py and tools/harmony-expansion-batch8.py. 182 inferred accompaniment overlays; not authoritative arrangements.\n'
def catalog():
 return json.loads(subprocess.check_output(['node','--input-type=module','-e',"import {songs} from './songs.js';console.log(JSON.stringify(songs))"],cwd=ROOT))
def parse(text):
 return json.loads(text.split('export const generatedHarmony = ')[1].strip().rstrip(';'))
def extend(overlays):
 assert len(overlays)==169 and hashlib.sha256(json.dumps(overlays,sort_keys=True,separators=(',',':')).encode()).hexdigest()==BASELINE,'STOP: accepted 169 overlays changed'
 h=runpy.run_path(str(ROOT/'tools/harmony-inference.py'));d=runpy.run_path(str(ROOT/'tools/harmony-display.py'));songs=catalog();rows=[]
 for number in NUMBERS:
  matches=[s for s in songs if s['collection']=='Hymns (1985)' and int(s['page'])==number];assert len(matches)==1
  song=matches[0];assert song.get('availabilityReason')!='licensing' and song.get('asset') and song.get('pdfAsset'),'Unavailable source; defer without reconstruction'
  assert (ROOT/song['pdfAsset']).is_file(),'Missing original PDF'
  xml=h['source'](song);doc=ET.fromstring(xml)
  assert song['id'] not in overlays,'Duplicate overlay'
  assert not doc.findall('.//harmony'),'Source harmony takes precedence'
  ms=h['extract'](xml);analysis=h['infer'](xml)
  simplified=d['simplify'](analysis['events'],ms);root=d['root_only_display'](simplified['events'],ms,local_density=True);temporal=d['temporal_display'](root['events'],ms);events=temporal['events']
  assert events and all(0<=e['offset']<ms[e['measure']]['duration'] for e in events)
  keys=[dict(measure=m['number'],fifths=m['fifths'],mode=m['mode']) for i,m in enumerate(ms) if i==0 or (m['fifths'],m['mode'])!=(ms[i-1]['fifths'],ms[i-1]['mode'])]
  tails=[]
  for w in analysis['review']:
   matches=[m for m in ms if m['number']==w['measure']]
   if w['reason'].startswith('Omitted:') and len(matches)==1:
    remaining=matches[0]['duration']-w['offset']
    if 0<remaining<1e-7:tails.append(dict(w,remainingQuarterNotes=remaining))
  blocked=len(keys)>1
  assert not blocked and song['transpositionAvailable'],'STOP: unsupported source structure'
  # Review reference respects the existing registry mode override; inference stays untouched.
  tonic=(7*ms[0]['fifths']+(9 if (song.get('modeOverride') or ms[0]['mode'])=='minor' else 0))%12;flags=[]
  if len(analysis['review'])>=10:flags.append('10+ uncertainty/review windows; omitted windows are not inferred as the preceding chord')
  if tails:flags.append(str(len(tails))+' recorded omissions are sub-1e-7-quarter-note rounding tails, not substantive musical gaps; raw diagnostics and inference are unchanged')
  if any(e['kind'] in ['augmented','major-seventh'] for e in events):flags.append('Augmented/major-seventh interpretation needs musical review')
  if events[0]['rootPC']!=tonic or events[-1]['rootPC']!=tonic:flags.append('Non-tonic opening or ending relative to registered key')
  if temporal['remainingClusters']:flags.append('Retained close-spaced chord cluster')
  if any(e['kind']=='diminished' for e in events):flags.append('Diminished interpretations retained for consolidated review; not confirmed errors')
  rows.append(dict(number=number,id=song['id'],title=song['title'],asset=song['asset'],sourceSha256=hashlib.sha256((ROOT/song['asset']).read_bytes()).hexdigest(),originalKey=(song['tonic']+' '+song['mode']).strip(),modeOverride=song.get('modeOverride'),unusualQualities=[dict(measure=e['sourceMeasure'],offset=e['offset'],chord=e['label'],kind=e['kind']) for e in events if e['kind'] in ['major-seventh','augmented','diminished']],keyChanges=keys,analysis=analysis,boundaryRoundoffObservations=tails,omittedWindows=sum(e.get('reason','').startswith('Omitted:') for e in analysis['review']),displayStages=dict(analysis=len(analysis['events']),simplified=len(simplified['events']),rootOnly=len(root['events']),temporal=len(events)),temporalDisplay=dict(events=events,remainingClusters=temporal['remainingClusters']),reviewFlags=flags,measureCount=len(ms),generatedSymbolCount=0 if blocked else len(events),outcome='D. Structurally blocked' if blocked else 'B. Generated - musical review recommended' if flags else 'A. Generated - no significant warning'))
  if not blocked:overlays[song['id']]=dict(provenance='generated',version=1,xmlSha256=hashlib.sha256(xml.encode()).hexdigest(),events=[{k:e[k] for k in ['measure','offset','root','kind','bass']} for e in events])
 return rows

def main():
 path=ROOT/'generated-harmony-data.js';data=parse(path.read_text(encoding='utf8'))
 ids={s['id'] for s in catalog() if s['collection']=='Hymns (1985)' and int(s['page']) in NUMBERS}
 data={k:v for k,v in data.items() if k not in ids};rows=extend(data)
 report=dict(scope=NUMBERS,baseline='cdb48a2bd268125a7975ab356f41d99041df57e7',policy='Unchanged inference, simplify, root-only and temporal display; no thresholds tuned or manual chords',technicalObservations=[],reviewTiming='Consolidated musical review after selected batches; warnings are not confirmed errors',limitations=['Heuristic accompaniment suggestions, not human-approved arrangements.','Offsets are quarter-note units; source measure labels are preserved. Pitch coverage is not a confidence probability.','Omitted windows are not filled; preceding symbols do not establish harmony through those gaps.'],coverage=dict(previousGenerated=169,generated=182,native=1,chorded=183,usableUnchorded=152,noUsableXML=6,newSelectionTotal=22,newSelectionCompleted=22,newSelectionRemaining=0,blockedThisBatch=0),rows=rows)
 for target,content in [(path,HEADER+'export const generatedHarmony = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n'),(ROOT/'reports/chord-expansion-batch8.json',json.dumps(report,ensure_ascii=False,indent=2)+'\n')]:
  if '--check' in sys.argv:assert target.read_text(encoding='utf8')==content,str(target)+' not reproducible'
  else:target.write_text(content,encoding='utf8')
 for r in rows:print(r['number'],r['generatedSymbolCount'],r['omittedWindows'],r['outcome'])
if __name__=='__main__':main()
