"""Targeted #280 rollout using the unchanged local-key inference/display engine."""
import hashlib,json,pathlib,runpy,sys,xml.etree.ElementTree as ET
ROOT=pathlib.Path(__file__).resolve().parents[1]
BASELINE='09c62aa9312de370e7059f16cdaa57402462ad5ecc66185ff59cb568fabcd15d'
HEADER='// Generated by tools/harmony-inference.py and tools/harmony-280.py. 160 inferred accompaniment overlays; not authoritative arrangements.\n'
def extend(overlays):
 assert len(overlays)==159 and hashlib.sha256(json.dumps(overlays,sort_keys=True,separators=(',',':')).encode()).hexdigest()==BASELINE,'Accepted 159 overlays changed'
 h=runpy.run_path(str(ROOT/'tools/harmony-inference.py'));d=runpy.run_path(str(ROOT/'tools/harmony-display.py'));catalog=runpy.run_path(str(ROOT/'tools/harmony-expansion-batch6.py'))['catalog']()
 song=next(s for s in catalog if s['collection']=='Hymns (1985)' and s['page']=='280');xml=h['source'](song);doc=ET.fromstring(xml);assert not doc.findall('.//harmony') and song['id'] not in overlays
 # Validate the actual source positions independently of measure-level extraction.
 sourceKeys=[]
 for part in doc.findall('part'):
  keys=[];divisions=1
  for mi,m in enumerate(part.findall('measure')):
   at=0
   for n in m:
    if n.tag=='attributes':
     divisions=float(n.findtext('divisions',divisions))
     if n.find('key') is not None:keys.append(dict(measureIndex=mi,measure=m.get('number'),offset=at,fifths=int(n.findtext('key/fifths')),mode=n.findtext('key/mode','major')))
    duration=float(n.findtext('duration',0))/divisions
    if n.tag=='backup':at-=duration
    elif n.tag=='forward' or n.tag=='note' and n.find('chord') is None:at+=duration
  sourceKeys.append(keys)
 assert len(sourceKeys)==2 and sourceKeys[0]==sourceKeys[1]
 assert [(k['measureIndex'],k['offset'],k['fifths'],k['mode']) for k in sourceKeys[0]]==[(0,0,0,'major'),(10,0,1,'major'),(20,0,0,'major')]
 ms=h['extract'](xml);analysis=h['infer'](xml);simple=d['simplify'](analysis['events'],ms);root=d['root_only_display'](simple['events'],ms,local_density=True);temporal=d['temporal_display'](root['events'],ms);events=temporal['events']
 assert all(e['keyFifths']==(1 if 10<=e['measure']<20 else 0) and 0<=e['offset']<ms[e['measure']]['duration'] for e in events)
 assert len(events)==len({(e['measure'],e['offset']) for e in events})
 overlays[song['id']]=dict(provenance='generated',version=1,xmlSha256=hashlib.sha256(xml.encode()).hexdigest(),events=[{k:e[k] for k in ['measure','offset','root','kind','bass']} for e in events])
 # Report existing numerical tail diagnostics without changing frozen inference.
 tails=[dict(w,remainingQuarterNotes=ms[next(i for i,m in enumerate(ms) if m['number']==w['measure'])]['duration']-w['offset']) for w in analysis['review'] if w['reason'].startswith('Omitted:') and 0<ms[next(i for i,m in enumerate(ms) if m['number']==w['measure'])]['duration']-w['offset']<1e-7]
 row=dict(number=280,id=song['id'],title=song['title'],asset=song['asset'],sourceSha256=hashlib.sha256((ROOT/song['asset']).read_bytes()).hexdigest(),originalKey='C major / G major / C major',keyChanges=sourceKeys[0],analysis=analysis,omittedWindows=sum(w['reason'].startswith('Omitted:') for w in analysis['review']),boundaryRoundoffObservations=tails,temporalDisplay=temporal,generatedSymbolCount=len(events),reviewFlags=[f"17 recorded omission windows include {len(tails)} sub-1e-7-quarter-note triplet rounding tails; eight other windows remain uninferred. Frozen inference unchanged.",'Source-supported modulation at X10 and X20; generated accompaniment remains a suggestion pending musical review'],outcome='Generated - musical review pending')
 return dict(scope=[280],baseline='3946e857f09589feba83879cf28ee1d947595abd',diagnosis='Inference already tracks measure-local keys. Prior deferral protected against single-key runtime transposition flattening the modulation.',policy='Frozen infer/simplify/root-only/temporal rules; freshly recomputed candidates, not copied from prior report',limitations=['Generated accompaniment suggestions, not authoritative arrangements.','17 omission records are preserved: nine numerical triplet tails and eight other windows. No inference thresholds or omissions were changed; preceding labels do not establish harmony through real gaps.','Runtime modulation support is bounded to aligned measure-start conventional same-mode concert keys. Mid-bar, part-disagreeing, staff-specific or transposing-instrument modulation is rejected.'],coverage=dict(generated=160,native=1,chorded=161,priorityCompleted=59,selectedCompleted=50,deferred=0),rows=[row])
def main():
 p=ROOT/'generated-harmony-data.js';data=json.loads(p.read_text(encoding='utf8').split('export const generatedHarmony = ')[1].strip().rstrip(';'));data.pop('song-00c582e3-baa8-410b-940c-9fd52aa166a9',None);report=extend(data)
 for target,content in [(p,HEADER+'export const generatedHarmony = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n'),(ROOT/'reports/chord-hymn280.json',json.dumps(report,ensure_ascii=False,indent=2)+'\n')]:
  if '--check' in sys.argv:assert target.read_text(encoding='utf8')==content
  else:target.write_text(content,encoding='utf8')
 print('280:',report['rows'][0]['generatedSymbolCount'],'symbols;',report['rows'][0]['omittedWindows'],'omitted windows')
if __name__=='__main__':main()
